import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS} from '../js/core/cloud-full-record-shadow.js';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';
import {createBrowserStagingLiveExecutionStorage} from '../js/core/browser-staging-live-execution-storage.js';
import {createOperationJournal} from '../js/core/cloud-operation-journal.js';

const counts=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,0]));
const manifest=()=>{const body={schema:'danbridge-staging-execution-manifest-v1',environment:'staging',companyId:'danbridge',state:'ready',createdAt:'2026-08-15T04:00:00+08:00',backupId:'backup_123',backupSha256:'a'.repeat(64),restoreDrillId:'restore_123',legacyVersionHash:'legacy-v1',operationPlanHash:'b'.repeat(64),operationListHash:sha256Canonical([]),sourceRecordHash:'record-v1:'+'c'.repeat(64),targetRecordHash:'record-v1:'+'c'.repeat(64),sourceRecordCount:0,targetRecordCount:0,sourceCounts:counts(),targetCounts:counts(),targetDocumentCount:0,targetActiveCount:0,targetTombstoneCount:0,targetDocumentCounts:counts(),operationCount:0,maxOperationsPerRun:100,plannedExecutionPasses:1,activationAttemptAllowance:4,transactionRetryAllowance:3,estimatedReads:100,estimatedWrites:3,readBudget:100,writeBudget:100,requiredScenarios:['create','modify','tombstone','revive','refresh-readback','failure-resume','two-tab-race','role-matrix'],featureFlagOnly:true,uploadOwnerStateAttached:false,readTakeover:false,productionAllowed:false};return{...body,manifestHash:sha256Canonical(body)}};
const setup=()=>{let value=null,lock=Promise.resolve();const raw={load:async()=>structuredClone(value),save:async next=>{value=structuredClone(next)},exclusive:work=>{const result=lock.then(work,work);lock=result.then(()=>{},()=>{});return result}};return{raw,value:()=>structuredClone(value)}};

test('第一次保存操作列時把完整 manifest 與日誌放進同一原子封套',async()=>{const {raw,value}=setup(),expected=manifest(),execution=createBrowserStagingLiveExecutionStorage({storage:raw,manifestHash:expected.manifestHash,manifest:expected}),journal=createOperationJournal({storage:execution.journalStorage});await journal.appendMany([]);assert.equal(value().schema,'danbridge-staging-live-execution-journal-v1');assert.deepEqual(value().manifest,expected);assert.deepEqual(value().rows,[])});
test('雲端 manifest 尚未建立也能由本機封套讀回並續傳',async()=>{const {raw}=setup(),expected=manifest(),first=createBrowserStagingLiveExecutionStorage({storage:raw,manifestHash:expected.manifestHash,manifest:expected}),journal=createOperationJournal({storage:first.journalStorage});await journal.appendMany([]);const reopened=createBrowserStagingLiveExecutionStorage({storage:raw,manifestHash:expected.manifestHash});assert.deepEqual(await reopened.loadManifest(),expected);assert.deepEqual(await createOperationJournal({storage:reopened.journalStorage}).list(),[])});
test('舊陣列格式、缺 manifest、不同 hash 或遭竄改封套全部 fail closed',async()=>{const expected=manifest(),a=setup();await a.raw.save([]);await assert.rejects(()=>createBrowserStagingLiveExecutionStorage({storage:a.raw,manifestHash:expected.manifestHash}).loadManifest(),/封套格式/);const b=setup(),valid=createBrowserStagingLiveExecutionStorage({storage:b.raw,manifestHash:expected.manifestHash,manifest:expected});await createOperationJournal({storage:valid.journalStorage}).appendMany([]);await assert.rejects(()=>createBrowserStagingLiveExecutionStorage({storage:b.raw,manifestHash:'f'.repeat(64)}).loadManifest(),/identity/);const forged=b.value();forged.manifest.estimatedWrites=99;await b.raw.save(forged);await assert.rejects(()=>createBrowserStagingLiveExecutionStorage({storage:b.raw,manifestHash:expected.manifestHash}).loadManifest(),/manifest/)});
