import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,buildFullRecordShadowPlan,rebuildFullRecordShadowDb,verifyFullRecordShadowReadback,verifyFullRecordShadowCandidate} from '../js/core/cloud-full-record-shadow.js';
import {assertChangeRecordIdentity} from '../js/core/cloud-change-record-identity.js';

const db=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,key==='changes'?[{type:'one'},{type:'one'}]:[{id:`${key}-1`,value:1}]]));
const apply=(store,plan)=>{for(const op of plan.operations){const [,collection,id]=op.path.match(/collections\/([^/]+)\/records\/(.+)$/);store[collection]??=[];const index=store[collection].findIndex(row=>row.id===id),row={id,data:structuredClone(op.payload)};if(index<0)store[collection].push(row);else store[collection][index]=row}}

test('16 集合全部逐筆化，changes 保留順序與重複內容',()=>{const target=db(),store={};const plan=buildFullRecordShadowPlan(store,target,{sourceHash:'hash-1'});assert.equal(plan.collectionCount,16);assert.equal(plan.writes,17);for(const operation of plan.operations.filter(row=>row.payload.collection==='changes'))assert.equal(assertChangeRecordIdentity({recordIndex:operation.payload.recordIndex,recordId:operation.payload.recordId,record:operation.payload.record}),true);apply(store,plan);const rebuilt=verifyFullRecordShadowReadback(store,target);assert.equal(rebuilt.verified,true);assert.deepEqual(rebuilt.db.changes,[{type:'one'},{type:'one'}])});
test('legacy changes 新資料插在最前面時，逐筆層只在尾端追加且讀回仍維持畫面順序',()=>{const first=db();first.changes=[{type:'old'}];const store={};apply(store,buildFullRecordShadowPlan(store,first,{sourceHash:'h1'}));const second=db();second.changes=[{type:'new'},{type:'old'}];const plan=buildFullRecordShadowPlan(store,second,{sourceHash:'h2'}),changeOps=plan.operations.filter(row=>row.path.includes('/collections/changes/'));assert.equal(changeOps.length,1);assert.equal(changeOps[0].type,'create');assert.equal(changeOps[0].payload.recordIndex,1);assert.equal(changeOps[0].payload.record.type,'new');apply(store,plan);assert.deepEqual(verifyFullRecordShadowReadback(store,second).db.changes,second.changes)});
test('production 計畫使用隔離 namespace 與 production identity',()=>{const target=db(),store={},plan=buildFullRecordShadowPlan(store,target,{sourceHash:'production-hash',environment:'production'});assert.ok(plan.operations.every(row=>row.path.startsWith('productionFullRecordShadows/')));assert.ok(plan.operations.every(row=>row.payload.environment==='production'));apply(store,plan);assert.equal(verifyFullRecordShadowReadback(store,target,{environment:'production'}).verified,true);assert.throws(()=>verifyFullRecordShadowReadback(store,target),/格式無效/)});
test('唯讀候選保留未變文件的歷史來源版本，但內容、缺筆與空 sourceHash 仍拒絕',()=>{const target=db(),store={};apply(store,buildFullRecordShadowPlan(store,target,{sourceHash:'candidate-hash',environment:'production'}));const verified=verifyFullRecordShadowCandidate(store,target,{environment:'production',expectedSourceHash:'candidate-hash'});assert.equal(verified.candidateVerified,true);assert.equal(verified.collectionCount,16);assert.equal(verified.matchingSourceHashCount,verified.activeSourceHashCount);assert.equal(verified.historicalSourceHashCount,0);const historical=structuredClone(store);historical.lessons[0].data.sourceHash='older-valid-hash';const historicalVerified=verifyFullRecordShadowCandidate(historical,target,{environment:'production',expectedSourceHash:'candidate-hash'});assert.equal(historicalVerified.historicalSourceHashCount,1);const changed=structuredClone(historical);changed.lessons[0].data.record.value=99;assert.throws(()=>verifyFullRecordShadowCandidate(changed,target,{environment:'production',expectedSourceHash:'candidate-hash'}),/讀回與主資料不一致/);const missing=structuredClone(store);missing.lessons[0].data.sourceHash='';assert.throws(()=>verifyFullRecordShadowCandidate(missing,target,{environment:'production',expectedSourceHash:'candidate-hash'}),/缺少 sourceHash/);assert.throws(()=>verifyFullRecordShadowCandidate(store,target,{environment:'production'}),/缺少預期 sourceHash/)});
test('修改、墓碑與重建只作用於對應文件並增加 revision',()=>{const first=db(),store={};apply(store,buildFullRecordShadowPlan(store,first,{sourceHash:'h1'}));const second=db();second.lessons[0].value=2;second.students=[];let plan=buildFullRecordShadowPlan(store,second,{sourceHash:'h2'});assert.equal(plan.operations.filter(x=>['lessons','students'].some(key=>x.path.includes(`/collections/${key}/`))).length,2);apply(store,plan);assert.equal(store.lessons[0].data.revision,2);assert.equal(store.students[0].data.deleted,true);const third=db();third.lessons[0].value=2;plan=buildFullRecordShadowPlan(store,third,{sourceHash:'h3'});apply(store,plan);assert.equal(store.students[0].data.revision,3);assert.equal(store.students[0].data.deleted,false)});
test('缺筆、多筆、內容錯誤、changes 序序錯誤都拒絕 verified',()=>{const target=db(),store={};apply(store,buildFullRecordShadowPlan(store,target,{sourceHash:'h'}));for(const mutate of [copy=>copy.lessons.pop(),copy=>copy.lessons.push({...copy.lessons[0],id:'extra'}),copy=>copy.teachers[0].data.record.value=99,copy=>copy.changes[0].data.recordIndex=99]){const copy=structuredClone(store);mutate(copy);assert.throws(()=>verifyFullRecordShadowReadback(copy,target),/格式無效|不一致/)}});
test('非 changes 缺 ID、重複 ID 與超過安全批次都停止',()=>{const target=db();delete target.lessons[0].id;assert.throws(()=>buildFullRecordShadowPlan({},target,{sourceHash:'h'}),/無效或重複 ID/);const duplicate=db();duplicate.lessons.push(structuredClone(duplicate.lessons[0]));assert.throws(()=>buildFullRecordShadowPlan({},duplicate,{sourceHash:'h'}),/無效或重複 ID/);assert.throws(()=>buildFullRecordShadowPlan({},db(),{sourceHash:'h',batchSize:401}),/batchSize/) });
test('full shadow plan、rebuild 與 verify 對 malformed changes 全部 fail closed，accessor 不會被執行',()=>{const sparse=[];sparse[1]='x';let getterReads=0;const accessor={type:'unsafe'};Object.defineProperty(accessor,'danger',{enumerable:true,get(){getterReads++;return'x'}});for(const record of [{type:'unsafe',nested:undefined},{type:'unsafe',nested:new Date()},{type:'unsafe',nested:sparse},{type:'unsafe',nested:-0},accessor]){const target=db();target.changes=[record];assert.throws(()=>buildFullRecordShadowPlan({},target,{sourceHash:'h'}),/plain|lossless|sparse|accessor/)}assert.equal(getterReads,0);const target=db(),store={};apply(store,buildFullRecordShadowPlan(store,target,{sourceHash:'h'}));store.changes[0].data.record={type:'unsafe',nested:undefined};assert.throws(()=>rebuildFullRecordShadowDb(store),/格式無效/);assert.throws(()=>verifyFullRecordShadowReadback(store,target),/格式無效/)});
