import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,buildFullRecordShadowPlan} from '../js/core/cloud-full-record-shadow.js';
import {prepareActiveRecordSync,applyActiveRecordOperation} from '../js/core/cloud-active-record-sync.js';
import {rebuildFullRecordShadowDb} from '../js/core/cloud-full-record-shadow.js';
import {recordDataHash} from '../js/core/cloud-record-data-hash.js';

const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));
const db=()=>{const value=empty();value.students=[{id:'student-1',name:'A'}];value.teachers=[{id:'teacher-1',name:'T'}];value.lessons=[{id:'lesson-1',studentId:'student-1',teacherId:'teacher-1',date:'2026-08-15',room:'A'},{id:'lesson-2',studentId:'student-1',teacherId:'teacher-1',date:'2026-08-16',room:'A'}];value.changes=[{id:'change-1',type:'create'}];return value};
const documents=(value,environment='staging')=>{const result={};for(const key of FULL_RECORD_COLLECTIONS)result[key]=[];const plan=buildFullRecordShadowPlan(result,value,{sourceHash:'seed',environment});for(const operation of plan.operations){const [,collection,id]=operation.path.match(/collections\/([^/]+)\/records\/(.+)$/);result[collection].push({id,data:structuredClone(operation.payload)})}return result};
const apply=(store,operation)=>{const rows=store[operation.collection],index=rows.findIndex(row=>row.id===operation.recordId),current=index<0?null:rows[index].data,result=applyActiveRecordOperation(current,operation),row={id:operation.recordId,data:structuredClone(result.payload)};if(result.write){if(index<0)rows.push(row);else rows[index]=row}return result};
const plan=(store,baseline,local,overrides={})=>prepareActiveRecordSync({documentsByCollection:store,baselineDb:baseline,localDb:local,environment:'staging',deviceId:'device-a',activationEpoch:'epoch-12345678',...overrides});

test('大量資料只為真正變更的文件建立操作',()=>{const baseline=db();baseline.lessons=Array.from({length:10000},(_,index)=>({id:`lesson-${index}`,value:index}));const store=documents(baseline),local=structuredClone(baseline);local.lessons[4321].value='changed';const result=plan(store,baseline,local);assert.equal(result.operationCount,1);assert.equal(result.operations[0].recordId,'lesson-4321');assert.equal(result.operations[0].baseRevision,1);assert.equal(result.operations[0].nextRevision,2)});
test('多筆操作用連續增量 head 並逐步維護文件計數，最後仍等於完整資料雜湊',()=>{const baseline=db(),store=documents(baseline),local=structuredClone(baseline);local.lessons=local.lessons.filter(row=>row.id!=='lesson-1');local.lessons[0].room='B';local.students.push({id:'student-2',name:'B'});local.changes=[{id:'change-2',type:'batch'},...local.changes];const result=plan(store,baseline,local);assert.equal(result.operationCount,4);result.operations.slice(1).forEach((operation,index)=>assert.equal(operation.baseHash,result.operations[index].targetHash));for(const operation of result.operations)apply(store,operation);const rebuilt=rebuildFullRecordShadowDb(store,{environment:'staging'});assert.equal(recordDataHash(rebuilt.db),result.targetHash);assert.equal(result.operations.at(-1).targetHash,result.targetHash);assert.deepEqual({documentCount:result.operations.at(-1).targetDocumentCount,activeCount:result.operations.at(-1).targetActiveCount,tombstoneCount:result.operations.at(-1).targetTombstoneCount},{documentCount:rebuilt.documentCount,activeCount:rebuilt.activeCount,tombstoneCount:rebuilt.tombstoneCount})});
test('後端權威快照採線性 changes 尾段驗證，結果與一般完整合併一致且舊歷史不可改寫',()=>{const baseline=db(),store=documents(baseline),local=structuredClone(baseline);local.lessons[0].room='B';local.changes=[{id:'change-2',type:'scheduler'},...local.changes];const sourceHash=recordDataHash(baseline),regular=plan(store,baseline,local),trusted=plan(store,baseline,local,{authoritativeSourceHash:sourceHash});assert.equal(trusted.targetHash,regular.targetHash);assert.deepEqual(trusted.operations.map(row=>[row.collection,row.recordId,row.type,row.payload.record]),regular.operations.map(row=>[row.collection,row.recordId,row.type,row.payload.record]));assert.throws(()=>plan(store,baseline,local,{authoritativeSourceHash:`record-v1:${'0'.repeat(64)}`}),/來源雜湊/);const changedHistory=structuredClone(local);changedHistory.changes.at(-1).type='forged';assert.throws(()=>plan(store,baseline,changedHistory,{authoritativeSourceHash:sourceHash}),/舊歷史/)});
test('後端可注入等價的原生雜湊，但不接受格式不合的雜湊',()=>{const baseline=db(),store=documents(baseline),local=structuredClone(baseline);local.lessons[0].room='B';local.changes=[{id:'change-2',type:'scheduler'},...local.changes];let calls=0;const hashRecordDb=value=>{calls++;return recordDataHash(value)};const result=plan(store,baseline,local,{authoritativeSourceHash:recordDataHash(baseline),hashRecordDb});assert.equal(result.targetHash,recordDataHash(result.db));assert.equal(calls,2);assert.throws(()=>plan(store,baseline,local,{hashRecordDb:()=>`bad`}),/雜湊無效/)});
test('後端已驗證遠端快照不重建、不重算來源且精簡結果仍保持相同操作',()=>{const baseline=db(),store=documents(baseline),local=structuredClone(baseline);local.lessons[0].room='C';local.changes=[{id:'change-2',type:'scheduler'},...local.changes];const source=rebuildFullRecordShadowDb(store,{environment:'staging'}),sourceHash=recordDataHash(source.db),regular=plan(store,baseline,local,{authoritativeSourceHash:sourceHash});let calls=0;const trusted=plan(store,source.db,local,{authoritativeSourceHash:sourceHash,verifiedRemote:{...source,hash:sourceHash},compactResult:true,hashRecordDb:value=>{calls++;return recordDataHash(value)}});assert.equal(calls,1);assert.equal(trusted.db,local);assert.equal(trusted.remoteDb,source.db);assert.equal(trusted.targetHash,regular.targetHash);assert.deepEqual(trusted.operations.map(row=>[row.collection,row.recordId,row.type,row.payload.record]),regular.operations.map(row=>[row.collection,row.recordId,row.type,row.payload.record]));assert.throws(()=>plan(store,baseline,local,{authoritativeSourceHash:sourceHash,verifiedRemote:{...source,db:structuredClone(source.db),hash:sourceHash},compactResult:true}),/已驗證遠端快照/)});
test('後端受信集合範圍與完整計畫一致，範圍外任何修改都 fail closed',()=>{const baseline=db(),store=documents(baseline),local=structuredClone(baseline);local.lessons[0].room='Scoped';local.changes=[{id:'change-scoped',type:'scheduler'},...local.changes];const source=rebuildFullRecordShadowDb(store,{environment:'staging'}),sourceHash=recordDataHash(source.db),trusted={authoritativeSourceHash:sourceHash,verifiedRemote:{...source,hash:sourceHash},compactResult:true},full=plan(store,source.db,local,trusted),scoped=plan(store,source.db,local,{...trusted,changedCollections:['lessons','students','makeups','changes']});assert.equal(scoped.targetHash,full.targetHash);assert.deepEqual(scoped.operations.map(row=>[row.collection,row.recordId,row.type,row.payload.record]),full.operations.map(row=>[row.collection,row.recordId,row.type,row.payload.record]));const forged=structuredClone(local);forged.teachers[0].name='forged';assert.throws(()=>plan(store,source.db,forged,{...trusted,changedCollections:['lessons','students','makeups','changes']}),/未授權集合遭修改：teachers/);assert.throws(()=>plan(store,source.db,local,{...trusted,changedCollections:['lessons','lessons']}),/集合範圍/)});
test('兩位 Owner 修改不同課程可自然合併且不墓碑遠端新增資料',()=>{const baseline=db(),store=documents(baseline),daniel=structuredClone(baseline),catherine=structuredClone(baseline);daniel.lessons[0].room='Daniel';catherine.lessons[1].room='Catherine';const first=plan(store,baseline,daniel,{deviceId:'daniel'});apply(store,first.operations[0]);const second=plan(store,baseline,catherine,{deviceId:'catherine',startSequence:2});assert.equal(second.operationCount,1);assert.equal(second.operations[0].recordId,'lesson-2');apply(store,second.operations[0]);const final=plan(store,second.db,second.db,{deviceId:'verify'});assert.equal(final.operationCount,0);assert.equal(final.remoteDb.lessons.find(row=>row.id==='lesson-1').room,'Daniel');assert.equal(final.remoteDb.lessons.find(row=>row.id==='lesson-2').room,'Catherine')});
test('同一課程不同欄位在 revision 衝突後重讀可自動三方合併',()=>{const baseline=db(),store=documents(baseline),daniel=structuredClone(baseline),catherine=structuredClone(baseline);daniel.lessons[0].room='B';catherine.lessons[0].date='2026-09-01';const first=plan(store,baseline,daniel,{deviceId:'daniel'});const stale=plan(store,baseline,catherine,{deviceId:'catherine'});apply(store,first.operations[0]);assert.throws(()=>apply(store,stale.operations[0]),/revision 衝突/);const rebased=plan(store,baseline,catherine,{deviceId:'catherine',startSequence:2});assert.equal(rebased.conflicts.length,0);assert.equal(rebased.db.lessons[0].room,'B');assert.equal(rebased.db.lessons[0].date,'2026-09-01');assert.equal(rebased.operations[0].baseRevision,2);apply(store,rebased.operations[0])});
test('同一課程同一欄位衝突有完整證據且不靜默遺失遠端內容',()=>{const baseline=db(),store=documents(baseline),remote=structuredClone(baseline),local=structuredClone(baseline);remote.lessons[0].room='Remote';local.lessons[0].room='Local';apply(store,plan(store,baseline,remote,{deviceId:'remote'}).operations[0]);const rebased=plan(store,baseline,local,{deviceId:'local'});assert.equal(rebased.conflicts.length,1);assert.equal(rebased.conflicts[0].path,'lessons.lesson-1.room');assert.equal(rebased.conflicts[0].local,'Local');assert.equal(rebased.conflicts[0].remote,'Remote');assert.equal(rebased.db.lessons[0].room,'Local')});
test('墓碑、同 ID 重建與永久 changes 追加都保留 revision',()=>{const baseline=db(),store=documents(baseline),removed=structuredClone(baseline);removed.lessons=removed.lessons.filter(row=>row.id!=='lesson-1');removed.changes=[{id:'change-delete',type:'delete'},...removed.changes];const deletion=plan(store,baseline,removed),lessonDelete=deletion.operations.find(row=>row.recordId==='lesson-1');assert.equal(lessonDelete.type,'delete');apply(store,lessonDelete);for(const operation of deletion.operations.filter(row=>row!==lessonDelete))apply(store,operation);const revived=structuredClone(removed);revived.lessons.push({...baseline.lessons[0],room:'Revived'});revived.changes=[{id:'change-revive',type:'revive'},...revived.changes];const resurrection=plan(store,removed,revived,{startSequence:deletion.nextSequence}),lessonRevive=resurrection.operations.find(row=>row.recordId==='lesson-1');assert.equal(lessonRevive.type,'revive');assert.equal(lessonRevive.baseRevision,2);assert.equal(lessonRevive.nextRevision,3);apply(store,lessonRevive);assert.equal(store.lessons.find(row=>row.id==='lesson-1').data.deleted,false)});
test('changes 永久日誌禁止刪除與改寫舊紀錄，純重排不寫入',()=>{const baseline=db(),store=documents(baseline),removed=structuredClone(baseline);removed.changes=[];assert.throws(()=>plan(store,baseline,removed),/永久操作日誌|禁止刪除歷史/);const modified=structuredClone(baseline);modified.changes[0].type='forged';assert.throws(()=>plan(store,baseline,modified),/永久操作日誌/);const two=structuredClone(baseline);two.changes=[{id:'change-2',type:'update'},...two.changes];const appended=plan(store,baseline,two);for(const operation of appended.operations)apply(store,operation);const reordered=structuredClone(two);reordered.changes.reverse();assert.equal(plan(store,two,reordered,{startSequence:appended.nextSequence}).operationCount,0)});
test('相同操作重送冪等，內容或 epoch 改變立即阻止',()=>{const baseline=db(),store=documents(baseline),local=structuredClone(baseline);local.lessons[0].room='B';const operation=plan(store,baseline,local).operations[0],first=apply(store,operation),duplicate=apply(store,operation);assert.equal(first.kind,'update');assert.equal(duplicate.kind,'duplicate');assert.throws(()=>applyActiveRecordOperation(store.lessons[0].data,{...operation,activationEpoch:'other-epoch'}),/identity 衝突|格式無效/)});
