import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,materializeFullRecordDb} from '../js/core/cloud-full-record-shadow.js';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';
import {buildStagingLivePreflight} from '../js/core/cloud-staging-live-preflight.js';

const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,[]]));
const fixture=()=>{const sourceDb=empty(),targetDb=empty(),revisions=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{}]));targetDb.lessons=[{id:'test-lesson-1',name:'TEST'}];const legacyVersionHash='legacy-v1',sourceHash=sha256Canonical(targetDb),collections=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{count:collection==='lessons'?1:0,chunks:collection==='lessons'?1:0}])),backup={schema:'danbridge-immutable-migration-backup-v2',environment:'staging',state:'verified',backupId:'backup_123',sourceHash,verifiedHash:sourceHash,sourceVersionHash:legacyVersionHash,collectionOrder:[...FULL_RECORD_COLLECTIONS],chunkCount:1,recordCount:1,collections},restoreReceipt={persisted:true,drillId:'drill_123',sourceBackupId:backup.backupId,sourceHash,restoredHash:sourceHash,recordCount:1,mainVersionHash:legacyVersionHash,mainUnchanged:true};return{environment:'staging',role:'owner',projectId:'danbridge-d8877-staging',sourceState:{db:sourceDb,revisions},targetDb,backup,restoreReceipt,legacyVersionHash,deviceId:'staging-owner-device',startSequence:1,readBudget:500,writeBudget:100,createdAt:'2026-08-15T01:00:00+08:00'}};

test('staging Owner 首次灌入只建立零寫入預檢、完整計畫與安全 manifest',()=>{const result=buildStagingLivePreflight(fixture());assert.equal(result.state,'ready');assert.equal(result.plan.operationCount,1);assert.equal(result.manifest.sourceRecordCount,0);assert.equal(result.manifest.targetRecordCount,1);assert.equal(result.writes,0);assert.equal(result.featureFlagOnly,true);assert.equal(result.uploadOwnerStateAttached,false);assert.equal(result.readTakeover,false);assert.equal(result.productionAllowed,false)});
test('legacy changes 重排時 verified 備份仍核對原始主資料，但逐筆計畫只追加新紀錄',()=>{const input=fixture(),sourceDb=empty(),targetDb=empty();sourceDb.changes=[{id:'b',type:'B'},{id:'a',type:'A'},{id:'c',type:'C'}];targetDb.changes=[{id:'new',type:'NEW'},{id:'a',type:'A'},{id:'c',type:'C'},{id:'b',type:'B'}];const revisions=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{}]));for(const item of materializeFullRecordDb(sourceDb).changes)revisions.changes[item.recordId]=1;const sourceHash=sha256Canonical(targetDb),collections=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{count:collection==='changes'?4:0,chunks:collection==='changes'?1:0}])),backup={...input.backup,sourceHash,verifiedHash:sourceHash,recordCount:4,collections},restoreReceipt={...input.restoreReceipt,sourceHash,restoredHash:sourceHash,recordCount:4},result=buildStagingLivePreflight({...input,sourceState:{db:sourceDb,revisions},targetDb,backup,restoreReceipt});assert.equal(result.plan.operationCount,1);assert.equal(result.plan.operations[0].record.id,'new');assert.equal(result.manifest.backupSha256,sourceHash);assert.equal(result.manifest.targetDocumentCount,4)});
test('production、非 Owner 或錯誤 Firebase 專案全部在規劃前拒絕',()=>{const input=fixture();for(const changed of [{environment:'production'},{role:'teacher'},{projectId:'danbridge-d8877'}])assert.throws(()=>buildStagingLivePreflight({...input,...changed}),/只允許 staging Owner/)});
test('legacy 版本、verified 備份、復原 receipt 或配額任一不符都 fail closed',()=>{const input=fixture();assert.throws(()=>buildStagingLivePreflight({...input,legacyVersionHash:'changed'}),/版本/);assert.throws(()=>buildStagingLivePreflight({...input,backup:{...input.backup,recordCount:0}}),/備份/);assert.throws(()=>buildStagingLivePreflight({...input,restoreReceipt:{...input.restoreReceipt,persisted:false}}),/receipt/);assert.throws(()=>buildStagingLivePreflight({...input,writeBudget:1}),/配額/)});
