import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,buildFullRecordShadowPlan,rebuildFullRecordShadowDb} from '../js/core/cloud-full-record-shadow.js';
import {verifyRoleViewCandidateSourceBinding,buildRoleViewCandidateSourceAudit,buildRoleViewCandidateManifest,assertRoleViewCandidateManifest,buildRoleViewVerificationReceipt,assertRoleViewVerificationReceipt,verifyRoleViewReceiptSet} from '../js/core/cloud-role-view-verification.js';
import {recordDataHash} from '../js/core/cloud-record-data-hash.js';
import {buildOpenRecordSyncCandidateControl,sealRecordSyncCandidateControl} from '../js/core/cloud-record-sync-candidate-control.js';

const counts=count=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map((key,index)=>[key,index===2?count:0]));
const views=[{viewId:'scheduler--aa',email:'aa@example.com',kind:'scheduler',viewHash:'a'.repeat(64),documentCount:2,counts:counts(2)},{viewId:'teacher--one',email:'teacher@example.com',kind:'teacher',viewHash:'b'.repeat(64),documentCount:1,counts:counts(1)},{viewId:'manager--one',email:'manager@example.com',kind:'branch_manager',viewHash:'c'.repeat(64),documentCount:1,counts:counts(1)}];
const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));
function boundSource(){const sourceDb=empty();sourceDb.lessons=[{id:'lesson-1'}];const legacyVersionHash='legacy-source-1',documents=empty();for(const operation of buildFullRecordShadowPlan(documents,sourceDb,{sourceHash:legacyVersionHash}).operations){const match=operation.path.match(/collections\/([^/]+)\/records\/(.+)$/);documents[match[1]].push({id:match[2],data:operation.payload})}const full=rebuildFullRecordShadowDb(documents),open=buildOpenRecordSyncCandidateControl({candidateEpoch:'candidate-role-123',legacyVersionHash,createdAt:'2026-08-15T19:50:00+08:00'}),candidateControl=sealRecordSyncCandidateControl({control:open,currentLegacyVersionHash:legacyVersionHash,recordDataHash:recordDataHash(sourceDb),documentCount:full.documentCount,activeCount:full.activeCount,tombstoneCount:full.tombstoneCount,sealedAt:'2026-08-15T19:55:00+08:00'}),fullReadback={...full,candidateVerified:true,sourceHash:legacyVersionHash};return{sourceDb,legacyVersionHash,candidateControl,fullReadback,documents}}
const manifest=()=>buildRoleViewCandidateManifest({runId:'role-run-123',sourceHash:'d'.repeat(64),views,createdAt:'2026-08-15T20:00:00+08:00'});
const receipt=(row,overrides={})=>buildRoleViewVerificationReceipt({runId:'role-run-123',sourceHash:'d'.repeat(64),manifestHash:manifest().manifestHash,email:row.email,kind:row.kind,viewId:row.viewId,viewHash:row.viewHash,verifiedViewCount:1,documentCount:row.documentCount,realtimeObserved:true,directCoreDenied:true,crossRoleDenied:true,testedAt:'2026-08-15T20:05:00+08:00',...overrides});
const owner=(email,overrides={})=>{const value=manifest();return buildRoleViewVerificationReceipt({runId:value.runId,sourceHash:value.sourceHash,manifestHash:value.manifestHash,email,kind:'owner',viewHash:value.manifestHash,verifiedViewCount:value.viewCount,documentCount:value.documentCount,realtimeObserved:true,directCoreDenied:false,crossRoleDenied:false,testedAt:'2026-08-15T20:06:00+08:00',...overrides})};

test('候選 manifest 綁定全部 16 集合計數、角色與 hash',()=>{const value=manifest();assert.equal(assertRoleViewCandidateManifest(value),value);assert.equal(value.viewCount,3);assert.equal(value.documentCount,4)});
test('本人與 Owner 憑證分別保存拒絕證據及完整候選讀回',()=>{const own=receipt(views[0]),ownerReceipt=owner('daniel@example.com');assert.equal(assertRoleViewVerificationReceipt(own),own);assert.equal(assertRoleViewVerificationReceipt(ownerReceipt),ownerReceipt);assert.equal(own.directCoreDenied,true);assert.equal(ownerReceipt.verifiedViewCount,3)});
test('Daniel、Catherine、aa、老師與管理者全部到齊才形成 receipt set',()=>{const value=manifest(),receipts=[owner('daniel@example.com'),owner('catherine@example.com'),...views.map(row=>receipt(row))],set=verifyRoleViewReceiptSet({manifest:value,receipts,primaryOwnerEmail:'daniel@example.com',backupOwnerEmail:'catherine@example.com',schedulerEmail:'aa@example.com'});assert.equal(set.receiptCount,5);assert.deepEqual(set.teacherAccounts,['teacher@example.com']);assert.match(set.receiptSetHash,/^[a-f0-9]{64}$/)});
test('少一人、跨 run、錯 view 或遭竄改全部 fail closed',()=>{const value=manifest(),receipts=[owner('daniel@example.com'),owner('catherine@example.com'),...views.map(row=>receipt(row))];assert.throws(()=>verifyRoleViewReceiptSet({manifest:value,receipts:receipts.slice(1),primaryOwnerEmail:'daniel@example.com',backupOwnerEmail:'catherine@example.com',schedulerEmail:'aa@example.com'}),/尚未收齊/);for(const mutate of [row=>row.runId='other-run',row=>row.viewHash='f'.repeat(64),row=>row.receiptHash='e'.repeat(64)]){const changed=structuredClone(receipts);mutate(changed[2]);assert.throws(()=>verifyRoleViewReceiptSet({manifest:value,receipts:changed,primaryOwnerEmail:'daniel@example.com',backupOwnerEmail:'catherine@example.com',schedulerEmail:'aa@example.com'}),/格式無效|hash 不符|版本不一致|view 不符/)}});
test('角色候選寫入前必須綁定同一份 sealed 全資料候選與完整讀回',()=>{const input=boundSource(),verified=verifyRoleViewCandidateSourceBinding(input);assert.match(verified.sourceHash,/^[a-f0-9]{64}$/);assert.equal(verified.recordDataHash,recordDataHash(input.sourceDb));for(const mutate of [copy=>copy.candidateControl.state='open',copy=>copy.candidateControl.legacyVersionHash='changed',copy=>copy.candidateControl.recordDataHash='record-v1:'+'f'.repeat(64),copy=>copy.fullReadback.db.lessons=[],copy=>copy.fullReadback.documentCount++,copy=>copy.fullReadback.sourceHash='changed']){const changed=structuredClone(input);mutate(changed);assert.throws(()=>verifyRoleViewCandidateSourceBinding(changed),/格式無效|seal hash 不符|未綁定|讀回不一致/)}});
test('唯讀來源稽核精確定位缺筆、多筆、內容與格式，歷史來源版本只記錄不重寫',()=>{const input=boundSource(),valid=buildRoleViewCandidateSourceAudit({...input,legacyHashMatchesSource:true,documentsByCollection:input.documents});assert.equal(valid.state,'ready');assert.equal(valid.writes,0);for(const [mutate,field] of [[copy=>copy.documents.lessons.splice(0,1),'missing'],[copy=>{const row=structuredClone(copy.documents.lessons[0]);row.id='extra';row.data.recordId='extra';row.data.record.id='extra';copy.documents.lessons.push(row)},'extra'],[copy=>copy.documents.lessons[0].data.record.id='changed','changed'],[copy=>copy.documents.lessons[0].data.schema='wrong','formatErrors']]){const changed=structuredClone(input);mutate(changed);const audit=buildRoleViewCandidateSourceAudit({...changed,legacyHashMatchesSource:true,documentsByCollection:changed.documents});assert.equal(audit.state,'blocked');assert.ok(audit.totals[field]>0)}const historical=structuredClone(input);historical.documents.lessons[0].data.sourceHash='old';const audit=buildRoleViewCandidateSourceAudit({...historical,legacyHashMatchesSource:true,documentsByCollection:historical.documents});assert.equal(audit.state,'ready');assert.equal(audit.totals.historicalSourceVersions,1)});
