import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS} from '../js/core/cloud-full-record-shadow.js';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';
import {recordDataHash} from '../js/core/cloud-record-data-hash.js';
import {buildLiveOperationPlan} from '../js/core/cloud-live-operation-plan.js';
import {buildStagingExecutionManifest,verifyStagingExecutionManifest} from '../js/core/cloud-staging-execution-manifest.js';

const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,[]]));
const fixture=()=>{const sourceDb=empty(),targetDb=empty(),sourceRevisions=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{}]));targetDb.lessons=[{id:'l1'}];const plan=buildLiveOperationPlan({db:sourceDb,revisions:sourceRevisions},targetDb,{deviceId:'device'}),sourceHash=sha256Canonical(targetDb),legacyVersionHash='legacy-v1',collections=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{count:collection==='lessons'?1:0,chunks:collection==='lessons'?1:0}])),backup={schema:'danbridge-immutable-migration-backup-v2',environment:'staging',state:'verified',backupId:'backup_123',sourceHash,verifiedHash:sourceHash,sourceVersionHash:legacyVersionHash,collectionOrder:[...FULL_RECORD_COLLECTIONS],chunkCount:1,recordCount:1,collections},restoreReceipt={persisted:true,drillId:'drill_123',sourceBackupId:'backup_123',sourceHash,restoredHash:sourceHash,recordCount:1,mainVersionHash:legacyVersionHash,mainUnchanged:true};return{sourceDb,sourceRevisions,targetDb,plan,backup,restoreReceipt,legacyVersionHash,readBudget:500,writeBudget:100,createdAt:'2026-08-15T00:00:00+08:00'}};

test('verified 備份、持久化復原 receipt、16 集合、完整操作計畫與配額齊全才建立 ready manifest',()=>{const input=fixture(),manifest=buildStagingExecutionManifest(input);assert.equal(manifest.state,'ready');assert.equal(manifest.operationCount,1);assert.equal(manifest.targetDocumentCount,1);assert.equal(manifest.targetActiveCount,1);assert.equal(manifest.targetTombstoneCount,0);assert.equal(manifest.maxOperationsPerRun,100);assert.equal(manifest.plannedExecutionPasses,1);assert.equal(manifest.activationAttemptAllowance,4);assert.equal(manifest.estimatedReads,111);assert.equal(manifest.estimatedWrites,6);assert.equal(manifest.requiredScenarios.length,8);assert.equal(manifest.productionAllowed,false);assert.equal(manifest.operationPlanHash,sha256Canonical(input.plan));assert.equal(manifest.operationListHash,sha256Canonical(input.plan.operations));assert.match(manifest.manifestHash,/^[a-f0-9]{64}$/);assert.equal(verifyStagingExecutionManifest(manifest,{currentLegacyVersionHash:input.legacyVersionHash,currentRecordHash:recordDataHash(input.sourceDb),currentOperationPlan:input.plan}),true)});
test('Firestore 欄位順序改變不會被誤判成集合缺漏或內容不同',()=>{const input=fixture(),manifest=buildStagingExecutionManifest(input),reverse=value=>Object.fromEntries(Object.entries(value).reverse()),reordered={...manifest,sourceCounts:reverse(manifest.sourceCounts),targetCounts:reverse(manifest.targetCounts),targetDocumentCounts:reverse(manifest.targetDocumentCounts)},body={...reordered};delete body.manifestHash;reordered.manifestHash=sha256Canonical(body);assert.equal(verifyStagingExecutionManifest(reordered,{currentLegacyVersionHash:input.legacyVersionHash,currentRecordHash:recordDataHash(input.sourceDb),currentOperationPlan:input.plan}),true)});
test('超過單輪上限時把每輪證據核對與額外續傳完整算入配額',()=>{const input=fixture(),sourceDb=empty(),sourceRevisions=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{}])),targetDb=empty();targetDb.lessons=Array.from({length:205},(_,index)=>({id:`lesson-${index}`}));const plan=buildLiveOperationPlan({db:sourceDb,revisions:sourceRevisions},targetDb,{deviceId:'device'}),sourceHash=sha256Canonical(targetDb),collections=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{count:collection==='lessons'?205:0,chunks:collection==='lessons'?1:0}])),backup={...input.backup,sourceHash,verifiedHash:sourceHash,recordCount:205,collections},restoreReceipt={...input.restoreReceipt,sourceHash,restoredHash:sourceHash,recordCount:205},manifest=buildStagingExecutionManifest({...input,sourceDb,sourceRevisions,targetDb,plan,backup,restoreReceipt,readBudget:5000,writeBudget:1000,maxOperationsPerRun:100});assert.equal(manifest.plannedExecutionPasses,3);assert.equal(manifest.activationAttemptAllowance,6);assert.equal(manifest.estimatedReads,2385);assert.equal(manifest.estimatedWrites,618)});
test('缺備份、未持久化復原、版本改變與配額不足全部禁止 ready',()=>{const input=fixture();assert.throws(()=>buildStagingExecutionManifest({...input,backup:null}),/備份/);assert.throws(()=>buildStagingExecutionManifest({...input,restoreReceipt:{...input.restoreReceipt,persisted:false}}),/receipt/);assert.throws(()=>buildStagingExecutionManifest({...input,legacyVersionHash:'changed'}),/版本/);assert.throws(()=>buildStagingExecutionManifest({...input,writeBudget:1}),/配額/)});
test('首次灌入時備份保護 legacy 目標，不會錯拿空的 live 來源比對',()=>{const input=fixture(),manifest=buildStagingExecutionManifest(input);assert.equal(manifest.sourceRecordCount,0);assert.equal(manifest.targetRecordCount,1);assert.equal(manifest.backupSha256,sha256Canonical(input.targetDb));const wrongHash=sha256Canonical(input.sourceDb),wrongBackup={...input.backup,sourceHash:wrongHash,verifiedHash:wrongHash,recordCount:0,collections:Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{count:0,chunks:0}]))};assert.throws(()=>buildStagingExecutionManifest({...input,backup:wrongBackup}),/備份/)});
test('來源 revision、目標內容或計畫 hash 鏈任一不符都不能建立 manifest',()=>{const input=fixture();assert.throws(()=>buildStagingExecutionManifest({...input,sourceRevisions:{...input.sourceRevisions,lessons:{l1:1}}}),/revision\/hash 鏈/);const wrongTarget={...input.targetDb,lessons:[{id:'l2'}]};assert.throws(()=>buildStagingExecutionManifest({...input,targetDb:wrongTarget}),/來源或目標/);const badPlan={...input.plan,operations:input.plan.operations.map((operation,index)=>index?operation:{...operation,nextHash:operation.baseHash})};assert.throws(()=>buildStagingExecutionManifest({...input,plan:badPlan}),/revision\/hash 鏈/)});
test('manifest 任一安全旗標、內容 hash、來源版本、操作計畫或情境清單被改動都 fail closed',()=>{const input=fixture(),manifest=buildStagingExecutionManifest(input),verify=value=>verifyStagingExecutionManifest(value,{currentLegacyVersionHash:input.legacyVersionHash,currentRecordHash:recordDataHash(input.sourceDb),currentOperationPlan:input.plan});assert.throws(()=>verify({...manifest,productionAllowed:true}),/安全旗標/);assert.throws(()=>verify({...manifest,estimatedWrites:99}),/hash/);assert.throws(()=>verifyStagingExecutionManifest(manifest,{currentLegacyVersionHash:'changed',currentRecordHash:recordDataHash(input.sourceDb),currentOperationPlan:input.plan}),/來源版本/);assert.throws(()=>verifyStagingExecutionManifest(manifest,{currentLegacyVersionHash:input.legacyVersionHash,currentRecordHash:recordDataHash(input.sourceDb),currentOperationPlan:{...input.plan,nextSequence:99}}),/操作計畫/);const scenarios={...manifest,requiredScenarios:manifest.requiredScenarios.slice(1)},body={...scenarios};delete body.manifestHash;scenarios.manifestHash=sha256Canonical(body);assert.throws(()=>verify(scenarios),/情境/)});
test('即使攻擊者重算 manifest hash，畸形時間、集合、總數、完成筆數、輪次、估算與 ID 仍全部拒絕',()=>{const input=fixture(),manifest=buildStagingExecutionManifest(input),verify=value=>verifyStagingExecutionManifest(value,{currentLegacyVersionHash:input.legacyVersionHash,currentRecordHash:recordDataHash(input.sourceDb),currentOperationPlan:input.plan}),reseal=changes=>{const body={...manifest,...changes};delete body.manifestHash;return{...body,manifestHash:sha256Canonical(body)}};assert.throws(()=>verify(reseal({createdAt:'not-a-date'})),/建立時間/);assert.throws(()=>verify(reseal({restoreDrillId:'x'})),/identity/);const sourceCounts={...manifest.sourceCounts};delete sourceCounts.lessons;assert.throws(()=>verify(reseal({sourceCounts})),/16 集合/);assert.throws(()=>verify(reseal({targetRecordCount:99})),/總筆數/);assert.throws(()=>verify(reseal({targetDocumentCount:2})),/完成文件/);assert.throws(()=>verify(reseal({plannedExecutionPasses:2})),/配額估算/);assert.throws(()=>verify(reseal({estimatedReads:18})),/配額估算/)});
