import test from 'node:test';
import assert from 'node:assert/strict';
import {RECORD_SYNC_V2_FREEZE_CONTROL_SCOPE,RECORD_SYNC_V2_FREEZE_OPERATION_POLICY,RECORD_SYNC_V2_FREEZE_PREFLIGHT_AUTHORITY,assertRecordSyncV2FreezeRequest,assertRequestedRecordSyncV2FreezeControl,buildRecordSyncV2FreezeRequest,buildRequestedRecordSyncV2FreezeControl,stripRecordSyncV2FreezeControlAudit,stripRecordSyncV2FreezeRequestAudit} from '../js/core/cloud-record-sync-v2-freeze-control.js';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';

const requestInput=(extra={})=>({environment:'staging',companyId:'danbridge',freezeId:'freeze-12345678',activationEpoch:'active-epoch-12345',sourceWriterGeneration:7,targetWriterGeneration:8,targetV2Epoch:'v2-epoch-12345678',sourceWriterControlHash:'f'.repeat(64),minClientProtocolVersion:3,minClientReleaseId:'20.26.113',rulesetHash:'a'.repeat(64),preflightRecordDataHash:`record-v1:${'b'.repeat(64)}`,preflightRawDocumentRoot:'c'.repeat(64),preflightBackupId:'backup-12345678',preflightBackupManifestHash:'d'.repeat(64),createdAt:'2026-08-17T10:20:30.123456789+08:00',...extra});
const reorder=value=>Object.fromEntries(Object.entries(value).reverse());
const coreWithout=(value,field)=>{const core=structuredClone(value);delete core[field];return core};

test('immutable freeze request 與 requested control deterministic、deep frozen 且不 mutate input',()=>{const input=requestInput(),before=structuredClone(input),request=buildRecordSyncV2FreezeRequest(input),control=buildRequestedRecordSyncV2FreezeControl({request});assert.deepEqual(input,before);assert.equal(request.requestHash,sha256Canonical(coreWithout(request,'requestHash')));assert.equal(control.controlHash,sha256Canonical(coreWithout(control,'controlHash')));assert.deepEqual({phase:control.phase,revision:control.revision,acceptNewSessions:control.acceptNewSessions,acceptNewMutations:control.acceptNewMutations,allowDrainOperations:control.allowDrainOperations,writerProtocol:control.writerProtocol},{phase:'requested',revision:1,acceptNewSessions:false,acceptNewMutations:false,allowDrainOperations:false,writerProtocol:'v1'});assert.ok(Object.isFrozen(request)&&Object.isFrozen(control));assert.throws(()=>{control.phase='draining'},TypeError);assert.equal(RECORD_SYNC_V2_FREEZE_PREFLIGHT_AUTHORITY,'rollback-hint-only');assert.equal(RECORD_SYNC_V2_FREEZE_OPERATION_POLICY,'hard-pause-all-v1-no-drain')});

test('Firestore map key reorder 不影響 request/control canonical verifier',()=>{const request=buildRecordSyncV2FreezeRequest(reorder(requestInput())),control=buildRequestedRecordSyncV2FreezeControl({request});assert.deepEqual(assertRecordSyncV2FreezeRequest(reorder(request)),request);assert.deepEqual(assertRequestedRecordSyncV2FreezeControl(reorder(control),{request:reorder(request)}),control)});

test('request/control expected保留合法subset，但typo/extra/symbol/custom proto/accessor全部fail closed',()=>{const request=buildRecordSyncV2FreezeRequest(requestInput()),control=buildRequestedRecordSyncV2FreezeControl({request});assert.deepEqual(assertRecordSyncV2FreezeRequest(request,{activationEpoch:request.activationEpoch,sourceWriterControlHash:request.sourceWriterControlHash}),request);assert.deepEqual(assertRequestedRecordSyncV2FreezeControl(control,{request,targetV2Epoch:request.targetV2Epoch}),control);for(const expected of [{activationEpooch:request.activationEpoch},{extra:true},{[Symbol('unexpected')]:true},Object.assign(Object.create({unsafe:true}),{activationEpoch:request.activationEpoch})])assert.throws(()=>assertRecordSyncV2FreezeRequest(request,expected),/expected/);for(const expected of [{targetV2Epooch:request.targetV2Epoch},{extra:true},{[Symbol('unexpected')]:true},Object.assign(Object.create({unsafe:true}),{targetV2Epoch:request.targetV2Epoch})])assert.throws(()=>assertRequestedRecordSyncV2FreezeControl(control,expected),/expected/);let requestGetterCalls=0;const requestGetter={};Object.defineProperty(requestGetter,'sourceWriterControlHash',{enumerable:true,get(){requestGetterCalls++;return request.sourceWriterControlHash}});assert.throws(()=>assertRecordSyncV2FreezeRequest(request,requestGetter),/data field/);assert.equal(requestGetterCalls,0);let controlGetterCalls=0;const controlGetter={};Object.defineProperty(controlGetter,'request',{enumerable:true,get(){controlGetterCalls++;return request}});assert.throws(()=>assertRequestedRecordSyncV2FreezeControl(control,controlGetter),/data field/);assert.equal(controlGetterCalls,0);const hidden={};Object.defineProperty(hidden,'activationEpoch',{enumerable:false,value:request.activationEpoch});assert.throws(()=>assertRecordSyncV2FreezeRequest(request,hidden),/data field/)});

test('request/control audit 欄位只接受 0 或完整3欄且不改 immutable hash',()=>{const request=buildRecordSyncV2FreezeRequest(requestInput()),control=buildRequestedRecordSyncV2FreezeControl({request}),audit={persistedAt:{server:true},persistedBy:'owner-12345678',persistedByEmail:'owner@example.com'},requestDoc={...request,...audit},controlDoc={...control,...audit};assert.deepEqual(stripRecordSyncV2FreezeRequestAudit(requestDoc),request);assert.deepEqual(stripRecordSyncV2FreezeControlAudit(controlDoc),control);assert.deepEqual(assertRecordSyncV2FreezeRequest(requestDoc),request);assert.deepEqual(assertRequestedRecordSyncV2FreezeControl(controlDoc,{request:requestDoc}),control);for(const doc of [{...request,persistedAt:{server:true}},{...request,...audit,persistedByEmail:'Owner@Example.com'},{...control,persistedAt:{server:true},persistedBy:'owner-12345678'}])assert.throws(()=>doc.schema.includes('request')?assertRecordSyncV2FreezeRequest(doc):assertRequestedRecordSyncV2FreezeControl(doc),/audit/)});

test('request extra/getter/timestamp/hash/generation 與 cross epoch 全部 fail closed，getter/toJSON不執行',()=>{for(const changed of [{...requestInput(),extra:true},requestInput({environment:'production'}),requestInput({targetWriterGeneration:9}),requestInput({minClientProtocolVersion:0}),requestInput({minClientReleaseId:'bad\ud800'}),requestInput({createdAt:'2026-08-17 10:20:30'}),requestInput({sourceWriterControlHash:'bad'}),requestInput({rulesetHash:'bad'}),requestInput({preflightRecordDataHash:'bad'}),requestInput({preflightBackupId:'bad/id'})])assert.throws(()=>buildRecordSyncV2FreezeRequest(changed),/欄位|identity|generation|hash|timestamp/);let reads=0;const getter=requestInput();Object.defineProperty(getter,'rulesetHash',{enumerable:true,get(){reads++;return'a'.repeat(64)}});assert.throws(()=>buildRecordSyncV2FreezeRequest(getter),/data field/);assert.equal(reads,0);let toJSONCalls=0;const hostile={toJSON(){toJSONCalls++;return'a'.repeat(64)}};for(const field of ['sourceWriterControlHash','rulesetHash','createdAt'])assert.throws(()=>buildRecordSyncV2FreezeRequest(requestInput({[field]:hostile})),/identity|generation|hash|timestamp/);assert.equal(toJSONCalls,0);const request=buildRecordSyncV2FreezeRequest(requestInput());assert.throws(()=>assertRecordSyncV2FreezeRequest(request,{activationEpoch:'other-epoch-123',sourceWriterGeneration:8}),/epoch|generation/);assert.throws(()=>assertRecordSyncV2FreezeRequest(request,{sourceWriterControlHash:'e'.repeat(64)}),/writer control/);for(const tampered of [{...request,minClientReleaseId:'20.26.114'},{...request,sourceWriterControlHash:'e'.repeat(64)}])assert.throws(()=>assertRecordSyncV2FreezeRequest(tampered),/canonical hash/);const custom=Object.assign(Object.create({unsafe:true}),request);assert.throws(()=>assertRecordSyncV2FreezeRequest(custom),/plain object/)});

test('requested control 任一phase/revision/hash/flag/protocol/sentinel/extra或request mirror變造皆拒',()=>{const request=buildRecordSyncV2FreezeRequest(requestInput()),original=buildRequestedRecordSyncV2FreezeControl({request}),mutations=[value=>value.phase='draining',value=>value.revision=2,value=>value.requestHash='e'.repeat(64),value=>value.acceptNewSessions=true,value=>value.acceptNewMutations=true,value=>value.allowDrainOperations=true,value=>value.writerProtocol='v2',value=>value.targetWriterGeneration++,value=>value.sessionSnapshotHash='f'.repeat(64),value=>value.extra=true];for(const mutate of mutations){const changed=structuredClone(original);mutate(changed);assert.throws(()=>assertRequestedRecordSyncV2FreezeControl(changed,{request}),/格式|hash|欄位|request/)}const forgedDrain={...original,allowDrainOperations:true};forgedDrain.controlHash=sha256Canonical(coreWithout(forgedDrain,'controlHash'));assert.throws(()=>assertRequestedRecordSyncV2FreezeControl(forgedDrain,{request}),/格式/);const other=buildRecordSyncV2FreezeRequest(requestInput({freezeId:'freeze-87654321',targetV2Epoch:'v2-epoch-87654321'}));assert.throws(()=>assertRequestedRecordSyncV2FreezeControl(original,{request:other}),/request/);assert.throws(()=>assertRequestedRecordSyncV2FreezeControl(original,{targetV2Epoch:'v2-epoch-other123'}),/epoch|generation/)});

test('preflight/backup proofs 改變只會形成rollback hint；requested不授權任何V1 operation',()=>{const first=buildRecordSyncV2FreezeRequest(requestInput()),second=buildRecordSyncV2FreezeRequest(requestInput({preflightRawDocumentRoot:'e'.repeat(64)}));assert.notEqual(first.requestHash,second.requestHash);const control=buildRequestedRecordSyncV2FreezeControl({request:first});assert.equal(control.phase,'requested');assert.equal(control.acceptNewMutations,false);assert.equal(control.allowDrainOperations,false);assert.equal(RECORD_SYNC_V2_FREEZE_OPERATION_POLICY,'hard-pause-all-v1-no-drain');assert.equal(RECORD_SYNC_V2_FREEZE_CONTROL_SCOPE,'requested-intent-only-not-current-phase');assert.equal(control.sessionSnapshotHash,'0'.repeat(64));assert.equal(control.drainEvidenceHash,'0'.repeat(64));assert.equal(control.hardPauseEventHash,'0'.repeat(64))});

test('source writer generation 0 與 target overflow/非 source+1 單獨拒絕',()=>{assert.throws(()=>buildRecordSyncV2FreezeRequest(requestInput({sourceWriterGeneration:0,targetWriterGeneration:1})),/generation/);assert.throws(()=>buildRecordSyncV2FreezeRequest(requestInput({sourceWriterGeneration:Number.MAX_SAFE_INTEGER,targetWriterGeneration:Number.MAX_SAFE_INTEGER})),/generation/);assert.throws(()=>buildRecordSyncV2FreezeRequest(requestInput({sourceWriterGeneration:7,targetWriterGeneration:9})),/generation/)});

test('targetV2Epoch 不得等於 activationEpoch，freezeId 也不得冒充任一 epoch',()=>{assert.throws(()=>buildRecordSyncV2FreezeRequest(requestInput({targetV2Epoch:'active-epoch-12345'})),/identity/);assert.throws(()=>buildRecordSyncV2FreezeRequest(requestInput({freezeId:'active-epoch-12345'})),/identity/);assert.throws(()=>buildRecordSyncV2FreezeRequest(requestInput({freezeId:'v2-epoch-12345678'})),/identity/)});

test('writer control/ruleset/raw document/backup manifest 64-zero proof hashes 分別拒絕',()=>{for(const field of ['sourceWriterControlHash','rulesetHash','preflightRawDocumentRoot','preflightBackupManifestHash'])assert.throws(()=>buildRecordSyncV2FreezeRequest(requestInput({[field]:'0'.repeat(64)})),/hash/)});

test('preflightRecordDataHash 的 record-v1:64-zero payload 單獨拒絕',()=>{assert.throws(()=>buildRecordSyncV2FreezeRequest(requestInput({preflightRecordDataHash:`record-v1:${'0'.repeat(64)}`})),/hash/)});
