import test from 'node:test';
import assert from 'node:assert/strict';
import {buildRecordSyncRoleEvidence,assertRecordSyncRoleEvidence,RECORD_SYNC_ROLE_SCENARIOS} from '../js/core/cloud-record-sync-role-evidence.js';

const passed=()=>Object.fromEntries(RECORD_SYNC_ROLE_SCENARIOS.map(key=>[key,true]));
const input=()=>({environment:'staging',primaryOwnerEmail:'daniel@example.com',backupOwnerEmail:'catherine@example.com',schedulerEmail:'aa@example.com',teacherAccounts:['z@example.com','a@example.com','z@example.com'],roleViewCount:5,candidateRunId:'role-run-123',candidateSourceHash:'a'.repeat(64),candidateManifestHash:'b'.repeat(64),receiptCount:7,receiptSetHash:'c'.repeat(64),results:passed(),testedAt:'2026-08-15T18:00:00+08:00'});

test('Daniel、Catherine、aa 與全部老師情境形成不可變證據',()=>{const evidence=buildRecordSyncRoleEvidence(input());assert.equal(assertRecordSyncRoleEvidence(evidence),evidence);assert.equal(evidence.teacherAccountCount,2);assert.equal(Object.keys(evidence.results).length,RECORD_SYNC_ROLE_SCENARIOS.length);assert.ok(RECORD_SYNC_ROLE_SCENARIOS.every(key=>evidence.results[key]===true));assert.match(evidence.evidenceHash,/^[a-f0-9]{64}$/)});
test('老師清單順序與重複不影響帳號 hash',()=>{const first=buildRecordSyncRoleEvidence(input()),second=buildRecordSyncRoleEvidence({...input(),teacherAccounts:['a@example.com','z@example.com']});assert.equal(first.teacherAccountHash,second.teacherAccountHash);assert.equal(first.evidenceHash,second.evidenceHash)});
test('少任一角色、老師、憑證或通過情境都 fail closed',()=>{for(const mutate of [value=>value.backupOwnerEmail=value.primaryOwnerEmail,value=>value.teacherAccounts=[],value=>value.roleViewCount=1,value=>value.receiptCount--,value=>delete value.results['teacher-report-write']])assert.throws(()=>{const value=input();mutate(value);buildRecordSyncRoleEvidence(value)},/輸入無效/);const evidence=buildRecordSyncRoleEvidence(input());delete evidence.results['teacher-report-write'];assert.throws(()=>assertRecordSyncRoleEvidence(evidence),/格式無效/)});
test('計數、帳號 hash、receipt set、結果或 evidenceHash 遭修改均拒絕',()=>{const original=buildRecordSyncRoleEvidence(input());for(const mutate of [value=>value.teacherAccountCount++,value=>value.teacherAccountHash='a'.repeat(64),value=>value.receiptSetHash='d'.repeat(64),value=>value.results['scheduler-record-direct-denied']=false,value=>value.evidenceHash='b'.repeat(64)]){const changed=structuredClone(original);mutate(changed);assert.throws(()=>assertRecordSyncRoleEvidence(changed),/格式無效|hash 不符/)}});
