import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS} from '../js/core/cloud-full-record-shadow.js';
import {buildRecordSyncRoleEvidence,RECORD_SYNC_ROLE_SCENARIOS} from '../js/core/cloud-record-sync-role-evidence.js';
import {buildOpenRecordSyncCandidateControl,sealRecordSyncCandidateControl} from '../js/core/cloud-record-sync-candidate-control.js';
import {buildActiveRecordSyncControl,buildRecordSyncActivationManifest} from '../js/core/cloud-record-sync-control.js';
import {buildOpenRecordSyncV1WriterCurrent} from '../js/core/cloud-record-sync-v1-writer-current.js';
import {buildRecordSyncV2FreezeRequest,buildRequestedRecordSyncV2FreezeControl} from '../js/core/cloud-record-sync-v2-freeze-control.js';
import {buildRecordSyncV1V2HardPauseTransition} from '../js/core/cloud-record-sync-v1-v2-hard-pause-transition.js';
import {buildRecordSyncV1PostPauseScanExecution,buildRecordSyncV1PostPauseScanReceipt} from '../js/core/cloud-record-sync-v1-post-pause-scan-receipt.js';
import {buildRecordSyncV1PostPauseScanPair} from '../js/core/cloud-record-sync-v1-post-pause-scan-pair.js';
import {buildRecordSyncV1RawCutoverBackup,verifyRecordSyncV1RawCutoverBackupReadback} from '../js/core/cloud-record-sync-v1-raw-cutover-backup.js';
import {RECORD_SYNC_V1_RAW_TIMESTAMP_SCHEMA} from '../js/core/cloud-record-sync-v1-raw-document-leaf.js';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';
import {RECORD_SYNC_V1_FROZEN_SOURCE_COUNT_POLICY,RECORD_SYNC_V1_FROZEN_SOURCE_PROOF_INTEGRITY_SCOPE,RECORD_SYNC_V1_FROZEN_SOURCE_PROOF_MAX_CANONICAL_BYTES,RECORD_SYNC_V1_FROZEN_SOURCE_PROOF_SCOPE,assertRecordSyncV1FrozenSourceProof,assertRecordSyncV1FrozenSourceProofIntegrity,buildRecordSyncV1FrozenSourceProof} from '../js/core/cloud-record-sync-v1-frozen-source-proof.js';

const audit={persistedAt:'2026-08-17T11:20:00.123456789+08:00',persistedBy:'owner-12345678',persistedByEmail:'owner@example.com'};
const safetyAudit={persistedAt:audit.persistedAt,updatedBy:audit.persistedBy,updatedByEmail:audit.persistedByEmail};
const controlAudit={persistedAt:audit.persistedAt,activatedBy:audit.persistedBy,activatedByEmail:audit.persistedByEmail};
const rawTimestamp={schema:RECORD_SYNC_V1_RAW_TIMESTAMP_SCHEMA,type:'timestamp',seconds:'1786896000',nanoseconds:123456789};
const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));
const raw=(index,deleted=false)=>({documentId:'student-'+String(index).padStart(8,'0'),data:{schema:'danbridge-full-record-shadow-v1',companyId:'danbridge',collection:'students',recordId:'student-'+String(index).padStart(8,'0'),record:{id:'student-'+String(index).padStart(8,'0'),name:'學生'+index},recordIndex:null,sourceHash:'record-v1:'+'a'.repeat(64),revision:deleted?2:1,deleted,environment:'staging',updatedAt:{...rawTimestamp},updatedBy:'owner-12345678',updatedByEmail:'owner@example.com'}});
const documents=(count,tombstoneCount=0)=>{const value=empty();value.students=Array.from({length:count},(_,index)=>raw(index,index<tombstoneCount));return value};

function activation(baselineCount){const roleEvidence=buildRecordSyncRoleEvidence({environment:'staging',primaryOwnerEmail:'daniel@example.com',backupOwnerEmail:'catherine@example.com',schedulerEmail:'aa@example.com',teacherAccounts:['teacher@example.com'],roleViewCount:12,candidateRunId:'role-run-123',candidateSourceHash:'b'.repeat(64),candidateManifestHash:'c'.repeat(64),receiptCount:14,receiptSetHash:'d'.repeat(64),results:Object.fromEntries(RECORD_SYNC_ROLE_SCENARIOS.map(key=>[key,true])),testedAt:'2026-08-17T10:00:00+08:00'}),candidate=sealRecordSyncCandidateControl({control:buildOpenRecordSyncCandidateControl({candidateEpoch:'candidate-12345678',legacyVersionHash:'legacy-123',createdAt:'2026-08-17T10:01:00+08:00'}),currentLegacyVersionHash:'legacy-123',recordDataHash:'record-v1:'+'a'.repeat(64),documentCount:baselineCount,activeCount:baselineCount,tombstoneCount:0,sealedAt:'2026-08-17T10:02:00+08:00'}),manifest=buildRecordSyncActivationManifest({environment:'staging',activationEpoch:'active-epoch-12345',candidateControl:candidate,legacyVersionHash:'legacy-123',recordDataHash:'record-v1:'+'a'.repeat(64),roleEvidence,backupId:'backup-activation-123',restoreReceiptId:'restore-activation-123',documentCount:baselineCount,activeCount:baselineCount,tombstoneCount:0,createdAt:'2026-08-17T10:03:00+08:00'}),control=buildActiveRecordSyncControl({manifest,currentLegacyVersionHash:manifest.legacyVersionHash,currentRecordDataHash:manifest.recordDataHash,currentRoleEvidenceHash:manifest.roleEvidenceHash,activatedAt:'2026-08-17T10:04:00+08:00'});return{activationManifest:{...manifest,...audit},activeControl:{...control,...controlAudit}}}

function source({baselineCount=1,frozenCount=2,tombstoneCount=0}={}){const lineage=activation(baselineCount),activeSafety={schema:'danbridge-record-sync-safety-control-v1',environment:'staging',companyId:'danbridge',activationEpoch:'active-epoch-12345',state:'active',revision:3,lastEventId:'resume-event-12345',lastEventHash:'e'.repeat(64),readAllowed:true,writeAllowed:true,updatedAt:'2026-08-17T10:05:00+08:00',...safetyAudit},writer=buildOpenRecordSyncV1WriterCurrent({recordSyncControl:lineage.activeControl,safetyControl:activeSafety,writerGeneration:1,minClientProtocolVersion:3,minClientReleaseId:'20.26.113',createdAt:'2026-08-17T10:06:00+08:00'}),request=buildRecordSyncV2FreezeRequest({environment:'staging',companyId:'danbridge',freezeId:'freeze-12345678',activationEpoch:writer.activationEpoch,sourceWriterGeneration:1,targetWriterGeneration:2,targetV2Epoch:'v2-epoch-12345678',sourceWriterControlHash:writer.controlHash,minClientProtocolVersion:3,minClientReleaseId:'20.26.113',rulesetHash:'1'.repeat(64),preflightRecordDataHash:'record-v1:'+'2'.repeat(64),preflightRawDocumentRoot:'3'.repeat(64),preflightBackupId:'backup-freeze-123',preflightBackupManifestHash:'4'.repeat(64),createdAt:'2026-08-17T10:07:00+08:00'}),requestedControl=buildRequestedRecordSyncV2FreezeControl({request}),pause=buildRecordSyncV1V2HardPauseTransition({writerCurrent:writer,safetyControl:activeSafety,request,requestedControl,pausedAt:'2026-08-17T10:08:00+08:00'}),anchors={hardPauseReceipt:{...pause.transitionReceipt,...audit},hardPausedWriterCurrent:{...pause.nextWriterCurrent,...audit},pausedSafetyControl:{...pause.nextSafetyControl,...safetyAudit}},docs=documents(frozenCount,tombstoneCount),uCore=buildRecordSyncV1PostPauseScanReceipt({...anchors,ordinal:'U',startedAt:'2026-08-17T10:09:00+08:00',completedAt:'2026-08-17T10:10:00+08:00',documentsByCollection:docs}),vExecution=buildRecordSyncV1PostPauseScanExecution({...anchors,ordinal:'V',startedAt:'2026-08-17T10:10:00+08:00',completedAt:'2026-08-17T10:11:00+08:00',documentsByCollection:docs}),uScanReceipt={...uCore,...audit},vScanReceipt={...vExecution.receipt,...audit},pairCore=buildRecordSyncV1PostPauseScanPair({...anchors,uScanReceipt,vScanReceipt,matchedAt:'2026-08-17T10:12:00+08:00'}),scanPair={...pairCore,...audit},backupPlan=buildRecordSyncV1RawCutoverBackup({...anchors,uScanReceipt,vScanReceipt,scanPair,vScanExecution:vExecution}),persistedManifest={...backupPlan.manifest,...audit},persistedChunks=backupPlan.chunks.map(row=>({...row,...audit})),readbackCore=verifyRecordSyncV1RawCutoverBackupReadback({...anchors,uScanReceipt,vScanReceipt,scanPair,manifest:persistedManifest,chunks:persistedChunks}),rawBackupReadbackReceipt={...readbackCore,...audit};return{...lineage,...anchors,uScanReceipt,vScanReceipt,scanPair,rawBackupManifest:persistedManifest,rawBackupReadbackReceipt,sealedAt:'2026-08-17T11:21:00.123456789+08:00'}}
const reorder=value=>Object.fromEntries(Object.entries(value).reverse());

test('frozen source proof以單向compact DAG綁baseline與frozen source，供future parent但非seed/final authority',()=>{const input=source(),proof=buildRecordSyncV1FrozenSourceProof(input);assert.equal(proof.state,'verified-observation');assert.equal(proof.scope,RECORD_SYNC_V1_FROZEN_SOURCE_PROOF_SCOPE);assert.equal(proof.countPolicy,RECORD_SYNC_V1_FROZEN_SOURCE_COUNT_POLICY);assert.match(proof.scope,/not-v2-seed-or-final/);assert.equal(proof.proofId,'v1-frozen-source:'+input.hardPauseReceipt.receiptHash);assert.equal(proof.rawBackupId,'v1-cutover-raw:'+input.hardPauseReceipt.receiptHash);assert.equal(proof.activationBaselineDocumentCount,1);assert.equal(proof.frozenDocumentCount,2);assert.equal(proof.documentCountDeltaFromActivation,1);assert.match(proof.activationBaselineRecordDataHash,/^record-v1:/);assert.match(proof.activeLogicalDataHash,/^raw-active-v1:/);assert.equal('documents'in proof,false);assert.equal('chunks'in proof,false);assert.ok(new TextEncoder().encode(JSON.stringify(proof)).length<RECORD_SYNC_V1_FROZEN_SOURCE_PROOF_MAX_CANONICAL_BYTES);assert.equal(Object.isFrozen(proof),true)});

test('full expected接受audit/map reorder；Integrity明示self-hash only且自洽forge仍被full strict拒',()=>{const input=source(),proof=buildRecordSyncV1FrozenSourceProof(input),audited=reorder({...proof,...audit}),reordered=Object.fromEntries(Object.entries(input).reverse().map(([key,value])=>[key,value&&typeof value==='object'&&!Array.isArray(value)?reorder(value):value]));assert.deepEqual(assertRecordSyncV1FrozenSourceProof(audited,reordered),proof);assert.equal(assertRecordSyncV1FrozenSourceProofIntegrity(proof).proofHash,proof.proofHash);assert.match(RECORD_SYNC_V1_FROZEN_SOURCE_PROOF_INTEGRITY_SCOPE,/self-hash-only/);const forged={...proof,activeLogicalDataHash:'raw-active-v1:'+'f'.repeat(64)};delete forged.proofHash;forged.proofHash=sha256Canonical(forged);assert.equal(assertRecordSyncV1FrozenSourceProofIntegrity(forged).proofHash,forged.proofHash);assert.throws(()=>assertRecordSyncV1FrozenSourceProof(forged,input),/full expected/)});

test('V1 tombstone保留政策要求document total不降低；active轉tombstone合法，empty只接受baseline empty',()=>{assert.throws(()=>buildRecordSyncV1FrozenSourceProof(source({baselineCount:1,frozenCount:0})),/低於 activation baseline/);const deleted=buildRecordSyncV1FrozenSourceProof(source({baselineCount:1,frozenCount:1,tombstoneCount:1}));assert.equal(deleted.frozenActiveCount,0);assert.equal(deleted.frozenTombstoneCount,1);assert.equal(deleted.documentCountDeltaFromActivation,0);const emptyProof=buildRecordSyncV1FrozenSourceProof(source({baselineCount:0,frozenCount:0}));assert.equal(emptyProof.frozenDocumentCount,0);assert.equal(emptyProof.chunkCount,0)});

test('activation/HWS/pair/backup hash swap、foreign H backupId或count tamper一律fail closed',()=>{const first=source(),second=source({baselineCount:0,frozenCount:1});assert.throws(()=>buildRecordSyncV1FrozenSourceProof({...first,activeControl:second.activeControl}),/lineage|mirror|manifest/);assert.throws(()=>buildRecordSyncV1FrozenSourceProof({...first,scanPair:second.scanPair}),/expected|linkage|DAG/);assert.throws(()=>buildRecordSyncV1FrozenSourceProof({...first,rawBackupReadbackReceipt:second.rawBackupReadbackReceipt}),/mirror/);const manifest={...first.rawBackupManifest,documentCount:first.rawBackupManifest.documentCount+1};delete manifest.manifestHash;manifest.manifestHash=sha256Canonical(manifest);assert.throws(()=>buildRecordSyncV1FrozenSourceProof({...first,rawBackupManifest:{...manifest,...audit}}),/manifest|mirror/);const wrongId='v1-cutover-raw:'+'f'.repeat(64),manifestCore=Object.fromEntries(Object.entries(first.rawBackupManifest).filter(([key])=>!['persistedAt','persistedBy','persistedByEmail','manifestHash'].includes(key)));manifestCore.backupId=wrongId;const wrongManifest={...manifestCore,manifestHash:sha256Canonical(manifestCore),...audit},receiptCore=Object.fromEntries(Object.entries(first.rawBackupReadbackReceipt).filter(([key])=>!['persistedAt','persistedBy','persistedByEmail','receiptHash'].includes(key)));receiptCore.backupId=wrongId;receiptCore.manifestHash=wrongManifest.manifestHash;const wrongReceipt={...receiptCore,receiptHash:sha256Canonical(receiptCore),...audit};assert.throws(()=>buildRecordSyncV1FrozenSourceProof({...first,rawBackupManifest:wrongManifest,rawBackupReadbackReceipt:wrongReceipt}),/manifest|DAG linkage/)});

test('所有source durable artifact必須full strict audit；getter/extra不執行且proof audit 0/all3',()=>{const input=source();for(const key of ['activationManifest','activeControl','hardPauseReceipt','hardPausedWriterCurrent','pausedSafetyControl','uScanReceipt','vScanReceipt','scanPair','rawBackupManifest','rawBackupReadbackReceipt']){const changed={...input,[key]:Object.fromEntries(Object.entries(input[key]).filter(([field])=>field!=='persistedAt'))};assert.throws(()=>buildRecordSyncV1FrozenSourceProof(changed),/audit/)}let calls=0;const hostile={...input.hardPauseReceipt};Object.defineProperty(hostile,'persistedAt',{enumerable:true,get(){calls++;return audit.persistedAt}});assert.throws(()=>buildRecordSyncV1FrozenSourceProof({...input,hardPauseReceipt:hostile}),/audit/);assert.equal(calls,0);const proof=buildRecordSyncV1FrozenSourceProof(input);assert.throws(()=>assertRecordSyncV1FrozenSourceProofIntegrity({...proof,persistedAt:audit.persistedAt}),/all-or-none/);assert.throws(()=>assertRecordSyncV1FrozenSourceProofIntegrity({...proof,extra:true}),/欄位無效/)});

test('sealedAt與每個durable persistedAt使用nanosecond/offset chronology，早1ns拒',()=>{const input=source(),earlyByArtifact={activationManifest:'2026-08-17T10:02:59.999999999+08:00',activeControl:'2026-08-17T10:03:59.999999999+08:00',hardPauseReceipt:'2026-08-17T10:07:59.999999999+08:00',hardPausedWriterCurrent:'2026-08-17T10:07:59.999999999+08:00',pausedSafetyControl:'2026-08-17T10:07:59.999999999+08:00',uScanReceipt:'2026-08-17T10:09:59.999999999+08:00',vScanReceipt:'2026-08-17T10:10:59.999999999+08:00',scanPair:'2026-08-17T10:11:59.999999999+08:00',rawBackupManifest:'2026-08-17T10:11:59.999999999+08:00'};for(const [key,persistedAt] of Object.entries(earlyByArtifact))assert.throws(()=>buildRecordSyncV1FrozenSourceProof({...input,[key]:{...input[key],persistedAt}}),/chronology/);assert.throws(()=>buildRecordSyncV1FrozenSourceProof({...input,rawBackupReadbackReceipt:{...input.rawBackupReadbackReceipt,persistedAt:'2026-08-17T11:19:59.999999999+08:00'}}),/chronology/);assert.throws(()=>buildRecordSyncV1FrozenSourceProof({...input,sealedAt:'2026-08-17T11:20:00.123456788+08:00'}),/chronology/);const equal=buildRecordSyncV1FrozenSourceProof({...input,sealedAt:'2026-08-17T03:20:00.123456789Z'});assert.equal(equal.sealedAt,'2026-08-17T03:20:00.123456789Z')});
