import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS} from '../js/core/cloud-full-record-shadow.js';
import {buildChangeRecordId} from '../js/core/cloud-change-record-identity.js';
import {RECORD_SYNC_V1_RAW_TIMESTAMP_SCHEMA} from '../js/core/cloud-record-sync-v1-raw-document-leaf.js';
import {buildRecordSyncV1PostPauseScanExecution,buildRecordSyncV1PostPauseScanReceipt,consumeRecordSyncV1PostPauseScanExecution} from '../js/core/cloud-record-sync-v1-post-pause-scan-receipt.js';
import {buildRecordSyncV1PostPauseScanPair} from '../js/core/cloud-record-sync-v1-post-pause-scan-pair.js';
import {buildRecordSyncV1V2HardPauseTransition} from '../js/core/cloud-record-sync-v1-v2-hard-pause-transition.js';
import {buildOpenRecordSyncV1WriterCurrent} from '../js/core/cloud-record-sync-v1-writer-current.js';
import {buildRecordSyncV2FreezeRequest,buildRequestedRecordSyncV2FreezeControl} from '../js/core/cloud-record-sync-v2-freeze-control.js';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';
import {
 RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_MAX_CHUNK_DOCUMENTS,
 RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_MAX_CORE_CANONICAL_BYTES,
 RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_OPERATIONAL_CANONICAL_BUDGET_BYTES,
 RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_AUDIT_TIMESTAMP_POLICY,
 RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_COMPACT_LINK_SCOPE,
 RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_RECEIPT_INTEGRITY_SCOPE,
 RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_SCOPE,
 RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_SERVER_AUDIT_MARGIN_BYTES,
 assertRecordSyncV1RawCutoverBackupReadbackReceipt,
 assertRecordSyncV1RawCutoverBackupReadbackReceiptIntegrity,
 assertRecordSyncV1RawCutoverBackupManifestMetadata,
 assertRecordSyncV1RawCutoverBackupReadbackReceiptMetadata,
 assertRecordSyncV1RawCutoverBackupCompactMetadataLink,
 buildRecordSyncV1RawCutoverBackup,
 planRecordSyncV1RawCutoverBackupResume,
 verifyRecordSyncV1RawCutoverBackupReadback
} from '../js/core/cloud-record-sync-v1-raw-cutover-backup.js';
import {
 RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_MAX_BATCH_OPERATIONAL_BYTES,
 RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_MAX_BATCH_WRITES,
 RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_OPAQUE_CHUNK_SCHEMA,
 buildRecordSyncV1RawCutoverBackupOpaquePersistenceExecution,
 assertRecordSyncV1RawCutoverBackupOpaqueChunkReadback,
 consumeRecordSyncV1RawCutoverBackupOpaquePersistenceExecution,
 createFirebaseRecordSyncV1RawCutoverBackupAdapter
} from '../js/core/firebase-record-sync-v1-raw-cutover-backup-adapter.js';

const sourceControl=()=>({schema:'danbridge-record-sync-control-v1',environment:'staging',companyId:'danbridge',state:'active',activationEpoch:'active-epoch-12345',manifestHash:'a'.repeat(64),candidateEpoch:'candidate-epoch-123',candidateRevision:2,candidateSealHash:'b'.repeat(64),legacyVersionHash:'legacy-version-123',recordDataHash:'record-v1:'+'c'.repeat(64),roleEvidenceHash:'d'.repeat(64),backupId:'backup-source-123',restoreReceiptId:'restore-1234567',collectionCount:16,documentCount:1739,activeCount:19,tombstoneCount:1720,roleViewCount:4,readTakeover:true,writeTakeover:true,activatedAt:'2026-08-16T12:00:00+08:00'});
const activeSafety=()=>({schema:'danbridge-record-sync-safety-control-v1',environment:'staging',companyId:'danbridge',activationEpoch:'active-epoch-12345',state:'active',revision:3,lastEventId:'resume-event-12345',lastEventHash:'e'.repeat(64),readAllowed:true,writeAllowed:true,updatedAt:'2026-08-16T12:05:00+08:00'});
const anchors=()=>{const writerCurrent=buildOpenRecordSyncV1WriterCurrent({recordSyncControl:sourceControl(),safetyControl:activeSafety(),writerGeneration:1,minClientProtocolVersion:3,minClientReleaseId:'20.26.113',createdAt:'2026-08-17T11:00:00.123456789+08:00'}),request=buildRecordSyncV2FreezeRequest({environment:'staging',companyId:'danbridge',freezeId:'freeze-12345678',activationEpoch:writerCurrent.activationEpoch,sourceWriterGeneration:1,targetWriterGeneration:2,targetV2Epoch:'v2-epoch-12345678',sourceWriterControlHash:writerCurrent.controlHash,minClientProtocolVersion:3,minClientReleaseId:'20.26.113',rulesetHash:'1'.repeat(64),preflightRecordDataHash:'record-v1:'+'2'.repeat(64),preflightRawDocumentRoot:'3'.repeat(64),preflightBackupId:'backup-freeze-123',preflightBackupManifestHash:'4'.repeat(64),createdAt:'2026-08-17T11:05:00.123456789+08:00'}),requestedControl=buildRequestedRecordSyncV2FreezeControl({request}),plan=buildRecordSyncV1V2HardPauseTransition({writerCurrent,safetyControl:activeSafety(),request,requestedControl,pausedAt:'2026-08-17T11:06:00.123456789+08:00'});return{hardPauseReceipt:plan.transitionReceipt,hardPausedWriterCurrent:plan.nextWriterCurrent,pausedSafetyControl:plan.nextSafetyControl}};
const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));
const timestamp={schema:RECORD_SYNC_V1_RAW_TIMESTAMP_SCHEMA,type:'timestamp',seconds:'1786896000',nanoseconds:123456789};
const raw=(collection,record,{recordId=record.id,recordIndex=null,revision=1,deleted=false,note,updatedBy='owner-12345678',updatedByEmail='owner@example.com'}={})=>({documentId:recordId,data:{schema:'danbridge-full-record-shadow-v1',companyId:'danbridge',collection,recordId,record:note===undefined?record:{...record,note},recordIndex,sourceHash:'record-v1:'+'a'.repeat(64),revision,deleted,environment:'staging',updatedAt:{...timestamp},updatedBy,updatedByEmail}});
const change=(recordIndex,record,options={})=>raw('changes',record,{...options,recordIndex,recordId:buildChangeRecordId(recordIndex,record)});
const fixture=()=>{const docs=empty();docs.students=[raw('students',{id:'學生-é-active',name:'甲'}),raw('students',{id:'student-deleted',name:'刪除'},{revision:4,deleted:true})];docs.changes=[change(0,{type:'old'}),change(3,{type:'deleted'},{revision:2,deleted:true})];return docs};
const source=(documentsByCollection=fixture())=>{const link=anchors(),uScanReceipt=buildRecordSyncV1PostPauseScanReceipt({...link,ordinal:'U',startedAt:'2026-08-17T11:07:00+08:00',completedAt:'2026-08-17T11:08:00+08:00',documentsByCollection}),vScanExecution=buildRecordSyncV1PostPauseScanExecution({...link,ordinal:'V',startedAt:'2026-08-17T11:08:00+08:00',completedAt:'2026-08-17T11:09:00+08:00',documentsByCollection}),vScanReceipt=vScanExecution.receipt,scanPair=buildRecordSyncV1PostPauseScanPair({...link,uScanReceipt,vScanReceipt,matchedAt:'2026-08-17T11:10:00+08:00'});return{...link,uScanReceipt,vScanReceipt,scanPair,vScanExecution}};
const readback=(value,plan)=>({hardPauseReceipt:value.hardPauseReceipt,hardPausedWriterCurrent:value.hardPausedWriterCurrent,pausedSafetyControl:value.pausedSafetyControl,uScanReceipt:value.uScanReceipt,vScanReceipt:value.vScanReceipt,scanPair:value.scanPair,manifest:plan.manifest,chunks:plan.chunks});
const reorder=value=>Object.fromEntries(Object.entries(value).reverse());
const audit={persistedAt:'2026-08-17T11:11:00.123456789+08:00',persistedBy:'owner-12345678',persistedByEmail:'owner@example.com'};
const persistedReadback=(value,plan)=>({...readback(value,plan),manifest:{...plan.manifest,...audit},chunks:plan.chunks.map(row=>({...row,...audit}))});

test('branded V execution建立唯一per-H完整raw backup，保留tombstone/changes gap/timestamp/Unicode且非final authority',()=>{const value=source(),plan=buildRecordSyncV1RawCutoverBackup(value),payload=consumeRecordSyncV1PostPauseScanExecution(value.vScanExecution,{expectedScanHash:value.vScanReceipt.scanHash,expectedRawDocumentRootHash:value.vScanReceipt.rawDocumentRootHash});assert.equal(plan.context.backupId,'v1-cutover-raw:'+value.hardPauseReceipt.receiptHash);assert.equal(plan.scope,RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_SCOPE);assert.match(plan.scope,/not-final-cutover-authority/);assert.deepEqual({documents:plan.manifest.documentCount,active:plan.manifest.activeCount,tombstones:plan.manifest.tombstoneCount},{documents:4,active:2,tombstones:2});const rows=plan.chunks.flatMap(row=>row.documents);assert.deepEqual(rows.filter(row=>row.collection==='changes').map(row=>row.recordIndex),[0,3]);assert.equal(rows.find(row=>row.recordId==='student-deleted').deleted,true);assert.deepEqual(rows[0].audit.updatedAt,timestamp);assert.strictEqual(rows[0],payload.normalizedDocumentsByCollection.students[0]);assert.ok(plan.chunks.every(row=>row.documentCount<=400));assert.equal('documents'in plan.manifest,false)});

test('strict readback重建pair raw root；artifact map/chunk順序與server audit不影響hash',()=>{const value=source(),plan=buildRecordSyncV1RawCutoverBackup(value),persisted={...readback(value,plan),manifest:reorder({...plan.manifest,...audit}),chunks:[...plan.chunks].reverse().map(row=>reorder({...row,...audit,documents:row.documents.map(reorder)}))},receipt=verifyRecordSyncV1RawCutoverBackupReadback(persisted),auditedReceipt=reorder({...receipt,...audit});assert.equal(receipt.state,'complete-observation');assert.equal(receipt.rawDocumentRootHash,value.scanPair.rawDocumentRootHash);assert.deepEqual(assertRecordSyncV1RawCutoverBackupReadbackReceipt(auditedReceipt,persisted),receipt);assert.equal(receipt.receiptHash,assertRecordSyncV1RawCutoverBackupReadbackReceiptIntegrity(receipt).receiptHash);assert.match(RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_RECEIPT_INTEGRITY_SCOPE,/self-hash-only/)});

test('V capability只能使用原brand與匹配durable V；同capability replay deterministic',()=>{const value=source(),first=buildRecordSyncV1RawCutoverBackup(value),second=buildRecordSyncV1RawCutoverBackup(value);assert.deepEqual(first,second);assert.throws(()=>buildRecordSyncV1RawCutoverBackup({...value,vScanExecution:structuredClone(value.vScanExecution)}),/capability/);assert.throws(()=>buildRecordSyncV1RawCutoverBackup({...value,vScanExecution:new Proxy(value.vScanExecution,{})}),/capability/);const foreign=source(empty());assert.throws(()=>buildRecordSyncV1RawCutoverBackup({...value,vScanExecution:foreign.vScanExecution}),/expected hash|capability/);assert.throws(()=>buildRecordSyncV1RawCutoverBackup({...value,vScanReceipt:{...value.vScanReceipt,scanHash:'f'.repeat(64)}}),/canonical|pair/)});

test('固定400 documents雙切分，401筆線性打包且不會塞進同一chunk',(context)=>{const docs=empty();docs.students=Array.from({length:401},(_,index)=>raw('students',{id:'s-'+String(index).padStart(6,'0')},{updatedBy:'u',updatedByEmail:'a@b'}));const started=performance.now(),plan=buildRecordSyncV1RawCutoverBackup(source(docs)),elapsed=performance.now()-started;context.diagnostic(`401 build+root+pack ms=${elapsed.toFixed(1)}`);assert.equal(RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_MAX_CHUNK_DOCUMENTS,400);assert.deepEqual(plan.chunks.map(row=>row.documentCount),[400,1])});

test('sealed core固定<224KiB並保留16KiB operational audit margin；byte edge會拆片或單筆fail closed',()=>{assert.equal(RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_MAX_CORE_CANONICAL_BYTES,224*1024);assert.equal(RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_SERVER_AUDIT_MARGIN_BYTES,16*1024);assert.equal(RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_OPERATIONAL_CANONICAL_BUDGET_BYTES,240*1024);assert.equal(RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_AUDIT_TIMESTAMP_POLICY,'adapter-normalized-rfc3339-nanosecond-string-from-server-timestamp');const docs=empty();docs.students=[raw('students',{id:'large-a'},{note:'x'.repeat(120*1024)}),raw('students',{id:'large-b'},{note:'y'.repeat(120*1024)})];const plan=buildRecordSyncV1RawCutoverBackup(source(docs));assert.equal(plan.chunks.length,2);assert.ok(plan.chunkSummaries.every(row=>row.coreCanonicalBytes<224*1024));const tooLarge=empty();tooLarge.students=[raw('students',{id:'too-large'},{note:'z'.repeat(230*1024)})];assert.throws(()=>buildRecordSyncV1RawCutoverBackup(source(tooLarge)),/canonical 上限/)});

test('readback必須是full audited persisted artifacts；tamper fail closed且integrity自洽偽造仍非strict authority',()=>{const value=source(),plan=buildRecordSyncV1RawCutoverBackup(value),base=persistedReadback(value,plan);assert.throws(()=>verifyRecordSyncV1RawCutoverBackupReadback(readback(value,plan)),/server audit/);assert.throws(()=>verifyRecordSyncV1RawCutoverBackupReadback({...base,chunks:[]}),/缺漏/);assert.throws(()=>verifyRecordSyncV1RawCutoverBackupReadback({...base,chunks:[base.chunks[0],base.chunks[0]]}),/重複|缺漏/);const changed=structuredClone(base.chunks);changed[0].documents[0].record.name='改';assert.throws(()=>verifyRecordSyncV1RawCutoverBackupReadback({...base,chunks:changed}),/hash|canonical/);assert.throws(()=>verifyRecordSyncV1RawCutoverBackupReadback({...base,manifest:{...base.manifest,rawDocumentRootHash:'f'.repeat(64)}}),/manifest/);const receipt=verifyRecordSyncV1RawCutoverBackupReadback(base),forged={...receipt,activeLogicalDataHash:'raw-active-v1:'+'f'.repeat(64)};forged.receiptHash=sha256Canonical(Object.fromEntries(Object.entries(forged).filter(([key])=>key!=='receiptHash')));assert.equal(assertRecordSyncV1RawCutoverBackupReadbackReceiptIntegrity(forged).receiptHash,forged.receiptHash);assert.throws(()=>assertRecordSyncV1RawCutoverBackupReadbackReceipt({...forged,...audit},base),/strict expected/);assert.throws(()=>assertRecordSyncV1RawCutoverBackupReadbackReceipt({...receipt,persistedAt:audit.persistedAt},base),/all-or-none/);assert.throws(()=>assertRecordSyncV1RawCutoverBackupReadbackReceipt({...receipt,...audit,persistedAt:'x'.repeat(20000)},base),/audit/)});

test('untrusted persisted chunk nested accessor在hash前fail closed且getter0',()=>{const value=source(),plan=buildRecordSyncV1RawCutoverBackup(value),base=persistedReadback(value,plan),chunks=structuredClone(base.chunks);let calls=0;Object.defineProperty(chunks[0].documents[0].record,'name',{enumerable:true,get(){calls++;return'X'}});assert.throws(()=>verifyRecordSyncV1RawCutoverBackupReadback({...base,chunks}),/accessor|data field/);assert.equal(calls,0)});

test('pure resume只create missing；local plan不可冒充existing，exact audited skip且衝突blocked',()=>{const value=source(),plan=buildRecordSyncV1RawCutoverBackup(value),none=planRecordSyncV1RawCutoverBackupResume(structuredClone(plan),{});assert.equal(none.complete,false);assert.equal(none.missingManifest.manifestHash,plan.manifest.manifestHash);assert.equal(none.missingChunks.length,plan.chunks.length);assert.throws(()=>planRecordSyncV1RawCutoverBackupResume(plan,{manifest:plan.manifest,chunks:plan.chunks}),/server audit/);assert.throws(()=>planRecordSyncV1RawCutoverBackupResume(plan,{manifest:{...plan.manifest,...audit},chunks:plan.chunks}),/server audit/);const manifestOnly=planRecordSyncV1RawCutoverBackupResume(plan,{manifest:{...plan.manifest,...audit},chunks:[]});assert.equal(manifestOnly.missingManifest,null);assert.equal(manifestOnly.complete,false);const auditedChunks=plan.chunks.map(row=>({...row,...audit})),complete=planRecordSyncV1RawCutoverBackupResume(plan,{manifest:{...plan.manifest,...audit},chunks:auditedChunks});assert.equal(complete.complete,true);assert.deepEqual(complete.missingChunks,[]);assert.throws(()=>planRecordSyncV1RawCutoverBackupResume(plan,{manifest:{...plan.manifest,persistedAt:audit.persistedAt},chunks:[]}),/all-or-none/);assert.throws(()=>planRecordSyncV1RawCutoverBackupResume(plan,{chunks:[auditedChunks[0],auditedChunks[0]]}),/重複/);const extra={...plan.chunks[0],index:99,chunkId:'chunk-000099'};delete extra.chunkHash;extra.chunkHash=sha256Canonical(extra);assert.throws(()=>planRecordSyncV1RawCutoverBackupResume(plan,{chunks:[{...extra,...audit}]}),/衝突/);const different={...plan.manifest,rawDocumentRootHash:'f'.repeat(64)};delete different.manifestHash;different.manifestHash=sha256Canonical(different);assert.throws(()=>planRecordSyncV1RawCutoverBackupResume(plan,{manifest:{...different,...audit}}),/衝突/);const forged=structuredClone(plan);forged.chunks[0].documents[0].record.name='forge';assert.throws(()=>planRecordSyncV1RawCutoverBackupResume(forged,{}),/canonical|hash|rebuild/)});

test('empty backup仍要求audited manifest；無chunks時readback與resume可complete',()=>{const value=source(empty()),plan=buildRecordSyncV1RawCutoverBackup(value);assert.equal(plan.chunks.length,0);assert.throws(()=>verifyRecordSyncV1RawCutoverBackupReadback(readback(value,plan)),/server audit/);const persisted=persistedReadback(value,plan),receipt=verifyRecordSyncV1RawCutoverBackupReadback(persisted),resume=planRecordSyncV1RawCutoverBackupResume(plan,{manifest:persisted.manifest,chunks:[]});assert.equal(receipt.documentCount,0);assert.equal(resume.complete,true);assert.throws(()=>assertRecordSyncV1RawCutoverBackupReadbackReceipt(receipt,persisted),/server audit/);assert.equal(assertRecordSyncV1RawCutoverBackupReadbackReceipt({...receipt,...audit},persisted).receiptHash,receipt.receiptHash)});

test('O(1) compact metadata link只接受audited manifest/readback exact mirrors且不讀chunks',()=>{const value=source(),plan=buildRecordSyncV1RawCutoverBackup(value),persisted=persistedReadback(value,plan),receipt={...verifyRecordSyncV1RawCutoverBackupReadback(persisted),...audit},link=assertRecordSyncV1RawCutoverBackupCompactMetadataLink({manifest:persisted.manifest,readbackReceipt:receipt});assert.equal(assertRecordSyncV1RawCutoverBackupManifestMetadata(persisted.manifest).manifestHash,plan.manifest.manifestHash);assert.equal(assertRecordSyncV1RawCutoverBackupReadbackReceiptMetadata(receipt).receiptHash,receipt.receiptHash);assert.equal(link.scope,RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_COMPACT_LINK_SCOPE);assert.equal('chunks'in link,false);assert.throws(()=>assertRecordSyncV1RawCutoverBackupManifestMetadata(plan.manifest),/server audit/);assert.throws(()=>assertRecordSyncV1RawCutoverBackupReadbackReceiptMetadata({...receipt,persistedAt:undefined}),/audit/);const foreignValue=source(empty()),foreignPlan=buildRecordSyncV1RawCutoverBackup(foreignValue),foreignPersisted=persistedReadback(foreignValue,foreignPlan),foreignReceipt={...verifyRecordSyncV1RawCutoverBackupReadback(foreignPersisted),...audit};assert.throws(()=>assertRecordSyncV1RawCutoverBackupCompactMetadataLink({manifest:persisted.manifest,readbackReceipt:foreignReceipt}),/mirror/);const slashCore=Object.fromEntries(Object.entries(persisted.manifest).filter(([key])=>!['persistedAt','persistedBy','persistedByEmail','manifestHash'].includes(key)));slashCore.backupId='v1-cutover-raw/bad';assert.throws(()=>assertRecordSyncV1RawCutoverBackupManifestMetadata({...slashCore,manifestHash:sha256Canonical(slashCore),...audit}),/manifest/);let calls=0;const hostile={...persisted.manifest};Object.defineProperty(hostile,'manifestHash',{enumerable:true,get(){calls++;return plan.manifest.manifestHash}});assert.throws(()=>assertRecordSyncV1RawCutoverBackupCompactMetadataLink({manifest:hostile,readbackReceipt:receipt}),/data field/);assert.equal(calls,0)});

test('opaque persistence execution隱藏payload並以string隔離Firestore map depth/index，clone/manual拒絕',()=>{const plan=buildRecordSyncV1RawCutoverBackup(source()),execution=buildRecordSyncV1RawCutoverBackupOpaquePersistenceExecution(plan),hidden=consumeRecordSyncV1RawCutoverBackupOpaquePersistenceExecution(execution,{expectedManifestHash:plan.manifest.manifestHash});assert.equal(execution.chunkCount,plan.chunks.length);assert.equal('groups'in execution,false);assert.equal(JSON.stringify(execution).includes('學生'),false);assert.ok(hidden.groups.flat().every(row=>row.opaque.schema===RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_OPAQUE_CHUNK_SCHEMA&&typeof row.opaque.payloadJson==='string'&&!('documents'in row.opaque)));assert.throws(()=>consumeRecordSyncV1RawCutoverBackupOpaquePersistenceExecution(structuredClone(execution)),/capability/);assert.throws(()=>consumeRecordSyncV1RawCutoverBackupOpaquePersistenceExecution({...execution}),/capability/);assert.throws(()=>consumeRecordSyncV1RawCutoverBackupOpaquePersistenceExecution(execution,{expectedManifestHash:'f'.repeat(64)}),/capability/)});

test('opaque chunk batches固定雙cap <=20 writes且worst operational <=4MiB',()=>{const docs=empty();docs.students=Array.from({length:21},(_,index)=>raw('students',{id:'large-'+String(index).padStart(3,'0')},{note:'x'.repeat(120*1024),updatedBy:'u',updatedByEmail:'a@b'}));const plan=buildRecordSyncV1RawCutoverBackup(source(docs)),execution=buildRecordSyncV1RawCutoverBackupOpaquePersistenceExecution(plan),hidden=consumeRecordSyncV1RawCutoverBackupOpaquePersistenceExecution(execution);assert.equal(RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_MAX_BATCH_WRITES,20);assert.equal(RECORD_SYNC_V1_RAW_CUTOVER_BACKUP_MAX_BATCH_OPERATIONAL_BYTES,4*1024*1024);assert.ok(hidden.groups.length>=2);assert.ok(hidden.groups.every(group=>group.length<=20&&group.reduce((sum,row)=>sum+row.operationalBytes,0)<=4*1024*1024));assert.equal(hidden.groups.flat().length,plan.chunks.length)});

test('existing opaque group audit即使三欄一致也必須先通過strict timestamp/actor/email語意',()=>{const plan=buildRecordSyncV1RawCutoverBackup(source()),execution=buildRecordSyncV1RawCutoverBackupOpaquePersistenceExecution(plan),hidden=consumeRecordSyncV1RawCutoverBackupOpaquePersistenceExecution(execution),invalidAudit={persistedAt:'garbage',persistedBy:'x',persistedByEmail:'NOT-EMAIL'};assert.throws(()=>planRecordSyncV1RawCutoverBackupResume(plan,{chunks:[{...hidden.groups[0][0].chunk,...invalidAudit}]}),/audit/)});

test('generic adapter不能用manual/clone completion觸發任何server I/O或mint authority',async()=>{let io=0;const adapter=createFirebaseRecordSyncV1RawCutoverBackupAdapter({environment:'staging',role:'owner',actor:{uid:'owner-12345678',email:'owner@example.com',claims:{recordSyncV2CutoverOperator:true}},serverTimestamp:()=>{io++;return{}},getDocumentFromServer:async()=>{io++;return null},getChunkCollectionFromServer:async()=>{io++;return[]},runTransaction:async()=>{io++}});await assert.rejects(()=>adapter.execute({scope:'fake-v'},{scope:'fake-pair'}),/capability/);assert.equal(io,0)});

test('opaque durable audit與pure domain逐字一致，slash/DEL email在任何resume/write前拒絕',()=>{const plan=buildRecordSyncV1RawCutoverBackup(source()),execution=buildRecordSyncV1RawCutoverBackupOpaquePersistenceExecution(plan),hidden=consumeRecordSyncV1RawCutoverBackupOpaquePersistenceExecution(execution),base=hidden.rows[0].opaque,at='2026-08-17T11:11:00.123456789+08:00';assert.equal(assertRecordSyncV1RawCutoverBackupOpaqueChunkReadback({...base,persistedAt:at,persistedBy:'owner-12345678',persistedByEmail:'owner@example.com'},execution,0).decoded.chunkHash,hidden.chunks[0].chunkHash);for(const persistedByEmail of ['a/b@example.com','a\u007fb@example.com'])assert.throws(()=>assertRecordSyncV1RawCutoverBackupOpaqueChunkReadback({...base,persistedAt:at,persistedBy:'owner-12345678',persistedByEmail},execution,0),/audit invalid/)});
