import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,buildFullRecordShadowPlan,rebuildFullRecordShadowDb} from '../js/core/cloud-full-record-shadow.js';
import {recordDataHash} from '../js/core/cloud-record-data-hash.js';
import {applyActiveRecordOperation} from '../js/core/cloud-active-record-sync.js';
import {createOperationJournal} from '../js/core/cloud-operation-journal.js';
import {createActiveRecordPageController} from '../js/core/cloud-active-record-page-controller.js';

const epoch='epoch-12345678';
const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));
const baseDb=()=>{const db=empty();db.lessons=[{id:'lesson-1',room:'A'},{id:'lesson-2',room:'A'}];return db};
const memoryJournal=(source={rows:null,time:1000})=>createOperationJournal({storage:{load:async()=>structuredClone(source.rows),save:async rows=>{source.rows=structuredClone(rows)}},now:()=>source.time});
function cloudSource(environment='staging',initialDb=baseDb()){const documents=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));for(const operation of buildFullRecordShadowPlan(documents,initialDb,{sourceHash:'seed',environment}).operations){const match=operation.path.match(/collections\/([^/]+)\/records\/(.+)$/);documents[match[1]].push({id:match[2],data:structuredClone(operation.payload)})}return{documents,read:async()=>structuredClone(documents),send:async operation=>{const rows=documents[operation.collection],index=rows.findIndex(row=>row.id===operation.recordId),current=index<0?null:rows[index].data,result=applyActiveRecordOperation(current,operation);if(result.write){const next={id:operation.recordId,data:structuredClone(result.payload)};if(index<0)rows.push(next);else rows[index]=next}return result},db:()=>rebuildFullRecordShadowDb(documents,{environment}).db}}
const snapshot=source=>({db:source.db(),hash:recordDataHash(source.db()),activationEpoch:epoch,writeAllowed:true});
function makeController({source=cloudSource(),journal=memoryJournal(),local=baseDb(),deviceId='device-123',publish=[],backups=[],statuses=[],send,sendBatch,applyHook,publishHook,ensureBackup=async()=>true,strictConvergence=false,environment='staging',trustCommittedPlan=false,maxOperations=1000}={}){let ui=structuredClone(local),controller;const api=createActiveRecordPageController({environment,role:'owner',deviceId,journal,readDocuments:source.read,send:send||source.send,sendBatch,persistConflicts:async(conflicts,context)=>{backups.push({conflicts:structuredClone(conflicts),context});return{backupId:`backup-${backups.length}`}},getLocalDb:()=>structuredClone(ui),applyCloudDb:async db=>{ui=structuredClone(db);await applyHook?.(ui,controller)},ensureCloudBackup:ensureBackup,publishRoleViews:async db=>{publish.push(structuredClone(db));await publishHook?.(db,controller)},onStatus:status=>statuses.push(structuredClone(status)),setTimer:()=>1,clearTimer:()=>{},saveDelay:0,strictConvergence,trustCommittedPlan,maxOperations});controller=api;return{controller,source,journal,statuses,get ui(){return structuredClone(ui)},setUi(value){ui=structuredClone(value)}}}

test('production 八堂課同批移動會以單一可信批次送出並立即全部確認',async()=>{
 const initial=empty();initial.lessons=Array.from({length:8},(_,index)=>({id:`lesson-${index+1}`,room:'A'}));
 const source=cloudSource('production',initial),batches=[];
 const app=makeController({source,local:initial,environment:'production',trustCommittedPlan:true,sendBatch:async operations=>{
  batches.push(structuredClone(operations));for(const operation of operations)await source.send(operation);
  return{kind:'batch',write:true,operationCount:operations.length,targetHash:operations.at(-1).targetHash};
 }});
 await app.controller.acceptCloudSnapshot(snapshot(source));const moved=app.ui;moved.lessons.forEach(row=>{row.room='B'});app.setUi(moved);app.controller.queueLocalSave();
 const result=await app.controller.flush();assert.equal(result.state,'complete');assert.equal(batches.length,1);assert.equal(batches[0].length,8);
 assert.deepEqual(source.db().lessons.map(row=>row.room),Array(8).fill('B'));assert.equal(result.counts.confirmed,8);assert.equal(result.counts.quarantined,0);
});

test('production 舊格式隔離的八堂批次只恢復一次，依原操作送出後以雲端資料解鎖',async()=>{
 const initial=empty();initial.lessons=Array.from({length:8},(_,index)=>({id:`lesson-${index+1}`,room:'A'}));
 const target=structuredClone(initial);target.lessons.forEach(row=>{row.room='C'});const source=cloudSource('production',initial),journal=memoryJournal();
 const {prepareActiveRecordSync}=await import('../js/core/cloud-active-record-sync.js');
 const plan=prepareActiveRecordSync({documentsByCollection:source.documents,baselineDb:initial,localDb:target,environment:'production',deviceId:'device-123',activationEpoch:epoch});
 await journal.appendMany(plan.operations);const claimed=await journal.claimNextMany({causal:true,max:8});await journal.failMany(claimed.map(row=>row.operationId),new Error('trusted batch 格式無效'),{retryable:false});
 let batches=0;const app=makeController({source,journal,local:target,environment:'production',trustCommittedPlan:true,sendBatch:async operations=>{
  batches++;for(const operation of operations)await source.send(operation);return{kind:'batch',write:true,operationCount:operations.length,targetHash:operations.at(-1).targetHash};
 }});
 await app.controller.acceptCloudSnapshot(snapshot(source));const resumed=await app.controller.resume();assert.equal(resumed.counts.pending,8);
 const result=await app.controller.flush();assert.equal(result.state,'complete');assert.equal(result.plan,null);assert.equal(batches,1);
 assert.deepEqual(result.readbackDb.lessons.map(row=>row.room),Array(8).fill('C'));assert.equal(result.counts.confirmed,8);assert.equal(result.counts.quarantined,0);
 assert.equal((await journal.retryProductionTrustedBatchFormatOnce()).recovered,0);
});

test('完整逐筆快照先成為基準，單堂修改只送一筆並以全量讀回確認',async()=>{const app=makeController(),applied=await app.controller.acceptCloudSnapshot(snapshot(app.source));assert.equal(applied.state,'ready');const local=app.ui;local.lessons[0].room='B';app.setUi(local);app.controller.queueLocalSave();const result=await app.controller.flush();assert.equal(result.state,'complete');assert.equal(result.plan.operationCount,1);assert.equal(app.source.db().lessons[0].room,'B');assert.equal(app.controller.diagnostics().dirty,false);assert.equal(app.statuses.at(-1).state,'complete');assert.equal(app.statuses.at(-1).inFlight,false)});
test('課表命令只複製與規劃 lessons、makeups、changes，範圍外資料仍取自完整權威快照',async()=>{const source=cloudSource('staging'),app=makeController({source,environment:'staging',trustCommittedPlan:true});await app.controller.acceptCloudSnapshot({...snapshot(source),documents:structuredClone(source.documents)});const local=app.ui;local.lessons[0].room='Scoped UI';app.setUi(local);app.controller.queueLocalSave({changedCollections:['lessons','makeups','changes']});assert.deepEqual(app.controller.diagnostics().pendingCollections,['lessons','makeups','changes']);const result=await app.controller.flush();assert.equal(result.state,'complete');assert.deepEqual(result.plan.operations.map(row=>row.collection),['lessons']);assert.equal(source.db().lessons[0].room,'Scoped UI');assert.equal(app.controller.diagnostics().pendingCollections,null)});
test('課表批次追加 changes 時沿用已驗證歷史，舊歷史遭改動則不會誤走追加快路',async()=>{const initial=baseDb();initial.changes=Array.from({length:240},(_,index)=>({id:`old-${index}`,type:'old'}));const source=cloudSource('staging',initial),app=makeController({source,local:initial,environment:'staging',trustCommittedPlan:true});await app.controller.acceptCloudSnapshot({...snapshot(source),documents:structuredClone(source.documents)});const local=app.ui;local.lessons[0].room='Batch';local.changes.unshift({id:'new-change',type:'scheduler'});app.setUi(local);app.controller.queueLocalSave({changedCollections:['lessons','makeups','changes']});const result=await app.controller.flush();assert.equal(result.state,'complete');assert.deepEqual(result.plan.operations.map(row=>row.collection),['lessons','changes']);assert.equal(source.db().changes[0].id,'new-change');const forged=app.ui;forged.changes.unshift({id:'newer-change',type:'scheduler'});forged.changes[1].type='forged';app.setUi(forged);app.controller.queueLocalSave({changedCollections:['lessons','makeups','changes']});assert.equal((await app.controller.flush()).state,'blocked')});
test('後端已提交但瀏覽器串流仍短暫保留舊版本時，等待權威版本收斂後才發布角色檢視',async()=>{const authority=cloudSource(),stale=structuredClone(authority.documents);let staleReads=0;const source={...authority,read:async()=>staleReads-->0?structuredClone(stale):authority.read(),send:async operation=>{const result=await authority.send(operation);staleReads=2;return result}},published=[];const app=makeController({source,publish:published,strictConvergence:true});await app.controller.acceptCloudSnapshot(snapshot(authority));const local=app.ui;local.lessons[0].room='Converged';app.setUi(local);app.controller.queueLocalSave();const result=await app.controller.flush();assert.equal(result.state,'complete');assert.equal(result.readbackDb.lessons[0].room,'Converged');assert.equal(published.at(-1).lessons[0].room,'Converged');assert.equal(app.controller.diagnostics().dirty,false)});
test('production 可信交易回條可直接套用已提交計畫，不等待串流重複收斂才解除操作鎖',async()=>{const source=cloudSource('production');let reads=0;const productionSource={...source,read:async()=>{reads++;return source.read()}};const app=makeController({source:productionSource,environment:'production',strictConvergence:true,trustCommittedPlan:true});await app.controller.acceptCloudSnapshot({...snapshot(source),activationEpoch:epoch});const local=app.ui;local.lessons[0].room='Trusted';app.setUi(local);app.controller.queueLocalSave();reads=0;const result=await app.controller.flush();assert.equal(result.state,'complete');assert.equal(result.readbackDb.lessons[0].room,'Trusted');assert.equal(reads,1);assert.equal(app.controller.diagnostics().dirty,false)});
test('staging V2 可信後端回條可直接套用已提交 revision，不會因短暫舊讀回建立假衝突',async()=>{const source=cloudSource('staging'),stale=structuredClone(source.documents);let reads=0;const delayed={...source,read:async()=>{reads++;return reads===1?structuredClone(stale):source.read()}};const backups=[];const app=makeController({source:delayed,environment:'staging',trustCommittedPlan:true,backups});await app.controller.acceptCloudSnapshot(snapshot(source));const local=app.ui;local.lessons[0].room='V2 Trusted';app.setUi(local);app.controller.queueLocalSave();reads=0;const result=await app.controller.flush();assert.equal(result.state,'complete');assert.equal(result.readbackDb.lessons[0].room,'V2 Trusted');assert.equal(app.controller.diagnostics().dirty,false);assert.equal(backups.length,0)});
test('staging V2 以同次啟動已驗證文件規劃，不在每筆操作前重讀完整權威集合',async()=>{const source=cloudSource('staging');let reads=0;const cached={...source,read:async()=>{reads++;return source.read()}};const app=makeController({source:cached,environment:'staging',trustCommittedPlan:true});await app.controller.acceptCloudSnapshot({...snapshot(source),documents:structuredClone(source.documents)});const local=app.ui;local.lessons[0].room='Cached';app.setUi(local);app.controller.queueLocalSave();const result=await app.controller.flush();assert.equal(result.state,'complete');assert.equal(result.readbackDb.lessons[0].room,'Cached');assert.equal(reads,0);assert.equal(app.controller.diagnostics().hasTrustedDocuments,true)});
test('staging V2 快取若遇到後端 revision 衝突，會強制重讀權威文件後安全重排',async()=>{const source=cloudSource('staging');let reads=0,injected=false;const cached={...source,read:async()=>{reads++;return source.read()},send:async operation=>{if(!injected){injected=true;const row=source.documents.lessons.find(item=>item.id===operation.recordId);row.data={...row.data,record:{...row.data.record,note:'Remote'},revision:row.data.revision+1,lastOperationId:'other:1',deviceId:'other',activationEpoch:epoch}}return source.send(operation)}};const app=makeController({source:cached,environment:'staging',trustCommittedPlan:true});await app.controller.acceptCloudSnapshot({...snapshot(source),documents:structuredClone(source.documents)});const local=app.ui;local.lessons[0].room='Cached conflict';app.setUi(local);app.controller.queueLocalSave();const result=await app.controller.flush();assert.equal(result.state,'complete');assert.equal(result.rebases,1);assert.equal(reads,1);assert.equal(result.readbackDb.lessons[0].note,'Remote');assert.equal(result.readbackDb.lessons[0].room,'Cached conflict')});
test('重新整理前已有未入日誌的本機修改時，第一個雲端快照只建基準不覆蓋，後續可精確送出',async()=>{const source=cloudSource(),local=baseDb();local.lessons[0].room='Recovered local';const app=makeController({source,local});app.controller.queueLocalSave();await app.controller.acceptCloudSnapshot(snapshot(source));assert.equal(app.ui.lessons[0].room,'Recovered local');assert.equal(app.controller.diagnostics().hasBaseline,true);assert.equal((await app.controller.flush()).state,'complete');assert.equal(source.db().lessons[0].room,'Recovered local')});
test('中央暫停仍可套用雲端讀取，但任何本機修改都不會送出',async()=>{const source=cloudSource();let sends=0;const app=makeController({source,send:async operation=>{sends++;return source.send(operation)}});await app.controller.acceptCloudSnapshot({...snapshot(source),writeAllowed:false});const local=app.ui;local.lessons[0].room='Paused';app.setUi(local);app.controller.queueLocalSave();assert.equal((await app.controller.flush()).state,'paused');assert.equal(sends,0);app.controller.setWriteAllowed(true);assert.equal((await app.controller.flush()).state,'complete');assert.equal(sends,1)});
test('同步途中新增的第二筆本機修改不會被第一次讀回覆蓋，下一輪精確續傳',async()=>{const source=cloudSource();let app,sends=0;app=makeController({source,send:async operation=>{const result=await source.send(operation);sends++;if(sends===1){const newer=app.ui;newer.lessons[1].room='Newer';app.setUi(newer);app.controller.queueLocalSave()}return result}});await app.controller.acceptCloudSnapshot(snapshot(source));const local=app.ui;local.lessons[0].room='First';app.setUi(local);app.controller.queueLocalSave();const first=await app.controller.flush();assert.equal(first.state,'pending');assert.equal(app.ui.lessons[0].room,'First');assert.equal(app.ui.lessons[1].room,'Newer');const second=await app.controller.flush();assert.equal(second.state,'complete');assert.equal(source.db().lessons[0].room,'First');assert.equal(source.db().lessons[1].room,'Newer')});
test('production A→B→A：第一筆提交途中拖回原位仍是新意圖，不能被 B 回條蓋掉',async()=>{
 const source=cloudSource('production');let app,sends=0;
 app=makeController({source,environment:'production',trustCommittedPlan:true,send:async operation=>{
  const result=await source.send(operation);if(++sends===1){const next=app.ui;next.lessons[0].room='A';app.setUi(next);app.controller.queueLocalSave()}return result;
 }});
 await app.controller.acceptCloudSnapshot(snapshot(source));const next=app.ui;next.lessons[0].room='B';app.setUi(next);app.controller.queueLocalSave();
 assert.equal((await app.controller.flush()).state,'pending');assert.equal(app.ui.lessons[0].room,'A');
 assert.equal((await app.controller.flush()).state,'complete');assert.equal(source.db().lessons[0].room,'A');assert.equal(sends,2);
});
test('production 新增後立即刪除：新增回條不能把已刪除的本機課程復活',async()=>{
 const source=cloudSource('production');let app,sends=0;
 app=makeController({source,environment:'production',trustCommittedPlan:true,send:async operation=>{
  const result=await source.send(operation);if(++sends===1){const next=app.ui;next.lessons=next.lessons.filter(row=>row.id!=='rapid-new');app.setUi(next);app.controller.queueLocalSave()}return result;
 }});
 await app.controller.acceptCloudSnapshot(snapshot(source));const next=app.ui;next.lessons.push({id:'rapid-new',room:'A'});app.setUi(next);app.controller.queueLocalSave();
 assert.equal((await app.controller.flush()).state,'pending');assert.equal(app.ui.lessons.some(row=>row.id==='rapid-new'),false);
 assert.equal((await app.controller.flush()).state,'complete');assert.equal(source.db().lessons.some(row=>row.id==='rapid-new'),false);assert.equal(sends,2);
});
test('production 新增回條已確認但串流仍舊：立即刪除仍必須真正送出墓碑',async()=>{
 const authority=cloudSource('production'),stale=structuredClone(authority.documents);let sends=0;
 const source={...authority,read:async()=>structuredClone(stale),send:async operation=>{sends++;return authority.send(operation)}};
 const app=makeController({source,environment:'production',trustCommittedPlan:true});await app.controller.acceptCloudSnapshot(snapshot(authority));
 const created=app.ui;created.lessons.push({id:'new-stale',room:'A'});app.setUi(created);app.controller.queueLocalSave();
 assert.equal((await app.controller.flush()).state,'complete');
 const removed=app.ui;removed.lessons=removed.lessons.filter(row=>row.id!=='new-stale');app.setUi(removed);app.controller.queueLocalSave();
 assert.equal((await app.controller.flush()).state,'complete');assert.equal(sends,2);
 assert.equal(authority.db().lessons.some(row=>row.id==='new-stale'),false);
});
test('production 延遲到達的舊版完整快照不得蓋掉已確認的新版本',async()=>{
 const source=cloudSource('production'),app=makeController({source,environment:'production',trustCommittedPlan:true});
 const old={...snapshot(source),revisions:rebuildFullRecordShadowDb(source.documents,{environment:'production'}).revisions};
 await app.controller.acceptCloudSnapshot(old);const moved=app.ui;moved.lessons[0].room='B';app.setUi(moved);app.controller.queueLocalSave();await app.controller.flush();
 assert.equal((await app.controller.acceptCloudSnapshot(old)).accepted,false);assert.equal(app.ui.lessons[0].room,'B');
 const fresh={...snapshot(source),revisions:rebuildFullRecordShadowDb(source.documents,{environment:'production'}).revisions};
 await app.controller.acceptCloudSnapshot(fresh);assert.equal(app.ui.lessons[0].room,'B');
});
test('production 已提交回條不覆蓋更高版雲端資料，且失敗回條不會進入權威讀取',async()=>{
 const source=cloudSource('production'),app=makeController({source,environment:'production',trustCommittedPlan:true});await app.controller.acceptCloudSnapshot(snapshot(source));
 const moved=app.ui;moved.lessons[0].room='B';app.setUi(moved);app.controller.queueLocalSave();await app.controller.flush();
 const row=source.documents.lessons[0];row.data={...row.data,revision:row.data.revision+1,record:{...row.data.record,room:'Newer remote'}};
 assert.equal(rebuildFullRecordShadowDb(await app.controller.readConfirmedDocuments(),{environment:'production'}).db.lessons[0].room,'Newer remote');
 const failed=makeController({source:cloudSource('production'),environment:'production',trustCommittedPlan:true,send:async()=>({kind:'update',write:true,revision:999})});await failed.controller.acceptCloudSnapshot(snapshot(failed.source));const wrong=failed.ui;wrong.lessons[0].room='Unconfirmed';failed.setUi(wrong);failed.controller.queueLocalSave();
 assert.equal((await failed.controller.flush()).state,'blocked');assert.equal(rebuildFullRecordShadowDb(await failed.controller.readConfirmedDocuments(),{environment:'production'}).db.lessons[0].room,'A');
});
test('production 批次回條須精確吻合才可接入下一次讀取',async()=>{
 const source=cloudSource('production'),app=makeController({source,environment:'production',trustCommittedPlan:true});await app.controller.acceptCloudSnapshot(snapshot(source));
 const {prepareActiveRecordSync}=await import('../js/core/cloud-active-record-sync.js');const target=app.ui;target.lessons=[];
 const plan=prepareActiveRecordSync({documentsByCollection:source.documents,baselineDb:app.ui,localDb:target,environment:'production',deviceId:'batch-test',activationEpoch:epoch});
 const batch={activationEpoch:epoch,operations:plan.operations},receipt={kind:'batch',write:true,operationCount:plan.operations.length,targetHash:plan.targetHash};
 assert.throws(()=>app.controller.acceptCommittedBatch(batch,{...receipt,targetHash:'wrong'}),/回條/);
 assert.throws(()=>app.controller.acceptCommittedBatch(batch,{...receipt,write:false}),/回條/);
 assert.throws(()=>app.controller.acceptCommittedBatch(batch,{...receipt,kind:'duplicate-batch',write:true}),/回條/);
 assert.equal(rebuildFullRecordShadowDb(await app.controller.readConfirmedDocuments(),{environment:'production'}).db.lessons.length,2);
 app.controller.acceptCommittedBatch(batch,receipt);assert.equal(rebuildFullRecordShadowDb(await app.controller.readConfirmedDocuments(),{environment:'production'}).db.lessons.length,0);
});
test('連續移回仍保留另一位使用者同堂課的不同欄位修改',async()=>{
 const source=cloudSource();let app,sends=0;
 app=makeController({source,send:async operation=>{
  const result=await source.send(operation);if(++sends===1){
   const row=source.documents.lessons.find(value=>value.id==='lesson-1');
   row.data={...row.data,record:{...row.data.record,note:'Remote note'},revision:row.data.revision+1,lastOperationId:'other-owner:9',deviceId:'other-owner',activationEpoch:epoch};
   const next=app.ui;next.lessons[0].room='A';app.setUi(next);app.controller.queueLocalSave();
  }return result;
 }});
 await app.controller.acceptCloudSnapshot(snapshot(source));const next=app.ui;next.lessons[0].room='B';app.setUi(next);app.controller.queueLocalSave();
 assert.equal((await app.controller.flush()).state,'pending');assert.deepEqual(app.ui.lessons[0],{id:'lesson-1',room:'A',note:'Remote note'});
 assert.equal((await app.controller.flush()).state,'complete');assert.deepEqual(source.db().lessons[0],{id:'lesson-1',room:'A',note:'Remote note'});
});
test('失敗操作留在永久日誌，重開控制器後由同一 operationId 繼續而不重複 revision',async()=>{const source=cloudSource(),storage={rows:null,time:1000},journal=memoryJournal(storage);let firstAttempt=true,ui=baseDb(),first=makeController({source,journal,local:ui,send:async operation=>{if(firstAttempt){firstAttempt=false;throw Object.assign(new Error('offline'),{code:'unavailable'})}return source.send(operation)}});await first.controller.acceptCloudSnapshot(snapshot(source));ui=first.ui;ui.lessons[0].room='Retry';first.setUi(ui);first.controller.queueLocalSave();assert.equal((await first.controller.flush()).state,'waiting');assert.equal((await journal.counts()).failed,1);storage.time+=2000;const second=makeController({source,journal,local:first.ui});await second.controller.acceptCloudSnapshot(snapshot(source));await second.controller.resume();assert.equal((await second.controller.flush()).state,'complete');assert.equal(source.db().lessons[0].room,'Retry');assert.equal(source.documents.lessons[0].data.revision,2);assert.equal((await journal.counts()).confirmed,1)});
test('Daniel 與 Catherine 從相同基準改不同課程，兩邊資料自然合併且角色檢視拿到完整結果',async()=>{const source=cloudSource(),danielPublish=[],catherinePublish=[],daniel=makeController({source,deviceId:'daniel-123',publish:danielPublish}),catherine=makeController({source,deviceId:'catherine-123',publish:catherinePublish});await Promise.all([daniel.controller.acceptCloudSnapshot(snapshot(source)),catherine.controller.acceptCloudSnapshot(snapshot(source))]);const d=daniel.ui,c=catherine.ui;d.lessons[0].room='Daniel';c.lessons[1].room='Catherine';daniel.setUi(d);catherine.setUi(c);daniel.controller.queueLocalSave();catherine.controller.queueLocalSave();assert.equal((await daniel.controller.flush()).state,'complete');assert.equal((await catherine.controller.flush()).state,'complete');assert.deepEqual(source.db().lessons.map(row=>row.room),['Daniel','Catherine']);assert.deepEqual(catherinePublish.at(-1).lessons.map(row=>row.room),['Daniel','Catherine'])});
test('同步後偵測同欄位較晚遠端變更時先備份，再保留本機意圖排入下一輪',async()=>{const source=cloudSource(),backups=[];let app,injected=false;app=makeController({source,backups,send:async operation=>{const result=await source.send(operation);if(!injected){injected=true;const row=source.documents.lessons.find(value=>value.id==='lesson-1');row.data={...row.data,record:{...row.data.record,room:'Later remote'},revision:row.data.revision+1,lastOperationId:'other-owner:9',deviceId:'other-owner',activationEpoch:epoch}}return result}});await app.controller.acceptCloudSnapshot(snapshot(source));const local=app.ui;local.lessons[0].room='Mine';app.setUi(local);app.controller.queueLocalSave();const result=await app.controller.flush();assert.equal(result.state,'pending');assert.equal(backups.length,1);assert.equal(backups[0].conflicts[0].path,'lessons.lesson-1.room');assert.equal(app.ui.lessons[0].room,'Mine')});
test('核心逐筆已確認但角色發布中斷時，手動重試會重新發布且不重送已確認操作',async()=>{const source=cloudSource();let publishAttempts=0,sends=0;const app=makeController({source,send:async operation=>{sends++;return source.send(operation)},publishHook:async()=>{publishAttempts++;if(publishAttempts===1)throw new Error('role publish interrupted')}});await app.controller.acceptCloudSnapshot(snapshot(source));const local=app.ui;local.lessons[0].room='Confirmed core';app.setUi(local);app.controller.queueLocalSave();const first=await app.controller.flush();assert.equal(first.state,'blocked');assert.equal(source.db().lessons[0].room,'Confirmed core');assert.equal(app.controller.diagnostics().retryPending,true);assert.equal(sends,1);const second=await app.controller.flush();assert.equal(second.state,'complete');assert.equal(app.controller.diagnostics().retryPending,false);assert.equal(publishAttempts,2);assert.equal(sends,1)});
test('每日第一次寫入必須先完成雲端分片備份，失敗時零寫入且可安全重試',async()=>{const source=cloudSource(),order=[];let backupReady=false,sends=0;const app=makeController({source,ensureBackup:async db=>{order.push(`backup:${db.lessons[0].room}`);return backupReady},send:async operation=>{order.push('send');sends++;return source.send(operation)}});await app.controller.acceptCloudSnapshot(snapshot(source));const local=app.ui;local.lessons[0].room='After';app.setUi(local);app.controller.queueLocalSave();const first=await app.controller.flush();assert.equal(first.state,'blocked');assert.equal(sends,0);assert.equal(source.db().lessons[0].room,'A');backupReady=true;const second=await app.controller.flush();assert.equal(second.state,'complete');assert.equal(sends,1);assert.deepEqual(order,['backup:A','backup:A','send']);assert.equal(source.db().lessons[0].room,'After')});
test('Owner 大批次碰到單輪上限會保留 queued 並自動接續，不停在 paused',async()=>{
 const initial=empty();initial.lessons=Array.from({length:12},(_,index)=>({id:`capacity-${index}`,room:'A'}));const source=cloudSource('production',initial),app=makeController({source,local:initial,environment:'production',trustCommittedPlan:true,maxOperations:8});
 await app.controller.acceptCloudSnapshot(snapshot(source));const changed=app.ui;changed.lessons.forEach(row=>{row.room='B'});app.setUi(changed);app.controller.queueLocalSave();
 const first=await app.controller.flush();assert.equal(first.state,'paused');assert.equal(app.controller.diagnostics().queued,true);assert.equal(first.worker.counts.pending,4);
 const second=await app.controller.flush();assert.equal(second.state,'complete');assert.equal(app.controller.diagnostics().queued,false);assert.deepEqual(source.db().lessons.map(row=>row.room),Array(12).fill('B'));
});
