import test from 'node:test';
import assert from 'node:assert/strict';
import {buildOpenRecordSyncCandidateControl,reopenRecordSyncCandidateControl,sealRecordSyncCandidateControl,assertRecordSyncCandidateControl} from '../js/core/cloud-record-sync-candidate-control.js';

const opened=()=>buildOpenRecordSyncCandidateControl({candidateEpoch:'candidate-epoch-1',legacyVersionHash:'legacy-v1',createdAt:'2026-08-15T01:00:00+08:00'});
const sealed=()=>sealRecordSyncCandidateControl({control:opened(),currentLegacyVersionHash:'legacy-v1',recordDataHash:'record-v1:'+'a'.repeat(64),documentCount:3,activeCount:2,tombstoneCount:1,sealedAt:'2026-08-15T01:05:00+08:00'});

test('候選先 open，封存後固定逐筆 hash、計數與 revision',()=>{const open=opened(),seal=sealed();assert.equal(assertRecordSyncCandidateControl(open).state,'open');assert.equal(seal.state,'sealed');assert.equal(seal.revision,2);assert.equal(seal.documentCount,3);assert.equal(seal.activeCount,2);assert.equal(seal.tombstoneCount,1);assert.match(seal.sealHash,/^[a-f0-9]{64}$/);assert.equal(assertRecordSyncCandidateControl(seal).sealHash,seal.sealHash)});
test('legacy 版本、計數、hash 或 sealHash 不符都拒絕封存',()=>{assert.throws(()=>sealRecordSyncCandidateControl({control:opened(),currentLegacyVersionHash:'changed',recordDataHash:'record-v1:'+'a'.repeat(64),documentCount:1,activeCount:1,tombstoneCount:0,sealedAt:'2026-08-15T01:05:00+08:00'}),/封存證據無效/);assert.throws(()=>sealRecordSyncCandidateControl({control:opened(),currentLegacyVersionHash:'legacy-v1',recordDataHash:'wrong',documentCount:1,activeCount:1,tombstoneCount:0,sealedAt:'2026-08-15T01:05:00+08:00'}),/封存證據無效/);assert.throws(()=>sealRecordSyncCandidateControl({control:opened(),currentLegacyVersionHash:'legacy-v1',recordDataHash:'record-v1:'+'a'.repeat(64),documentCount:2,activeCount:1,tombstoneCount:0,sealedAt:'2026-08-15T01:05:00+08:00'}),/封存證據無效/);const changed=sealed();changed.documentCount++;assert.throws(()=>assertRecordSyncCandidateControl(changed),/格式無效|seal hash 不符/)});
test('失敗候選只能換新 epoch 重新 open，不能沿用封存 identity',()=>{const current=sealed(),reopened=reopenRecordSyncCandidateControl({control:current,candidateEpoch:'candidate-epoch-2',legacyVersionHash:'legacy-v1',createdAt:'2026-08-15T01:10:00+08:00'});assert.equal(reopened.state,'open');assert.equal(reopened.revision,3);assert.equal(reopened.recordDataHash,'');assert.throws(()=>reopenRecordSyncCandidateControl({control:current,candidateEpoch:current.candidateEpoch,legacyVersionHash:'legacy-v1',createdAt:'2026-08-15T01:10:00+08:00'}),/重新開啟證據無效/)});
test('封存後主資料換版時只能以新 epoch 與目前 legacy 重新 open',()=>{const current=sealed(),reopened=reopenRecordSyncCandidateControl({control:current,candidateEpoch:'candidate-epoch-v2',legacyVersionHash:'legacy-v2',createdAt:'2026-08-15T01:11:00+08:00'});assert.equal(reopened.state,'open');assert.equal(reopened.candidateEpoch,'candidate-epoch-v2');assert.equal(reopened.legacyVersionHash,'legacy-v2');assert.equal(reopened.revision,3);assert.equal(reopened.recordDataHash,'');assert.equal(reopened.sealHash,'')});
test('落地稽核欄位只能三個一起存在，且不影響 seal hash',()=>{const core=sealed(),persisted={...core,persistedAt:{seconds:1},updatedBy:'owner-1',updatedByEmail:'owner@example.com'};assert.equal(assertRecordSyncCandidateControl(persisted).sealHash,core.sealHash);assert.throws(()=>assertRecordSyncCandidateControl({...core,persistedAt:{seconds:1}}),/稽核欄位不完整/);assert.throws(()=>assertRecordSyncCandidateControl({...persisted,extra:true}),/格式無效/)});
