import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS} from '../js/core/cloud-full-record-shadow.js';
import {buildRoleViewCandidatePlan,verifyRoleViewCandidateDocuments,verifyOwnRoleViewCandidateReadback} from '../js/core/cloud-role-view-candidate.js';
import {recordDataDigest} from '../js/core/cloud-record-data-hash.js';

const hashDb=recordDataDigest;
const sourceHash='f'.repeat(64);
const db=(prefix,lessons=2)=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,key==='changes'?[{type:`${prefix}-change`}]:key==='lessons'?Array.from({length:lessons},(_,i)=>({id:`${prefix}-lesson-${i}`})):[]]));
const view=(viewId,kind,lessons=2)=>{const value=db(viewId,lessons);return{viewId,email:`${viewId}@example.com`,kind,db:value,viewHash:hashDb(value)}};

test('aa、老師與管理者候選全部拆成隔離逐筆文件',()=>{const plan=buildRoleViewCandidatePlan({runId:'run-12345678',sourceHash,environment:'production',views:[view('aa','scheduler',3),view('teacher','teacher',2),view('manager','branch_manager',1)]});assert.equal(plan.viewCount,3);assert.equal(plan.documentCount,9);assert.ok(plan.documents.every(row=>row.path.startsWith('productionRoleViewCandidates/danbridge/runs/run-12345678/')));assert.ok(plan.documents.every(row=>row.payload.environment==='production'));assert.equal(verifyRoleViewCandidateDocuments(plan,plan.documents.map(row=>structuredClone(row)),{hashDb}).verified,true)});
test('缺筆、多筆、重複、內容或 viewHash 不符全部拒絕',()=>{const plan=buildRoleViewCandidatePlan({runId:'run-12345678',sourceHash,views:[view('aa','scheduler',3)]}),rows=plan.documents.map(row=>structuredClone(row));for(const mutate of [copy=>copy.pop(),copy=>copy.push(structuredClone(copy[0])),copy=>copy[0].payload.record={id:'wrong'},copy=>copy[0].path+='-wrong']){const changed=structuredClone(rows);mutate(changed);assert.throws(()=>verifyRoleViewCandidateDocuments(plan,changed,{hashDb}),/筆數不符|文件不符/)}const badPlan=structuredClone(plan);badPlan.views[0].viewHash='wrong-hash';assert.throws(()=>verifyRoleViewCandidateDocuments(badPlan,rows,{hashDb}),/viewHash 不符/)});
test('無效 view、重複 view、錯誤環境與超過批次上限立即停止',()=>{assert.throws(()=>buildRoleViewCandidatePlan({runId:'run-12345678',sourceHash,views:[{...view('bad','teacher'),viewId:'bad/view'}]}),/view 無效/);assert.throws(()=>buildRoleViewCandidatePlan({runId:'run-12345678',sourceHash,views:[view('same','teacher'),view('same','teacher')]}),/view 無效/);assert.throws(()=>buildRoleViewCandidatePlan({runId:'run-12345678',sourceHash,environment:'other',views:[view('aa','scheduler')]}),/identity 無效/);assert.throws(()=>buildRoleViewCandidatePlan({runId:'run-12345678',sourceHash,batchSize:401,views:[view('aa','scheduler')]}),/輸入無效/)});
test('sourceHash 與 viewHash 只接受精確 64 位小寫 SHA-256',()=>{const validView=view('aa','scheduler');for(const invalid of ['a'.repeat(62),'a'.repeat(65),'A'.repeat(64),'g'.repeat(64),'legacy:123'])assert.throws(()=>buildRoleViewCandidatePlan({runId:'run-12345678',sourceHash:invalid,views:[validView]}),/identity 無效/);for(const invalid of ['b'.repeat(62),'b'.repeat(65),'B'.repeat(64),'z'.repeat(64),'legacy:123'])assert.throws(()=>buildRoleViewCandidatePlan({runId:'run-12345678',sourceHash,views:[{...validView,viewHash:invalid}]}),/view 無效/)});
test('Firestore 改變物件或文件回傳順序不會誤判，原始陣列位置改變仍拒絕',()=>{const plan=buildRoleViewCandidatePlan({runId:'run-12345678',sourceHash,views:[view('aa','scheduler',3)]}),rows=plan.documents.map(row=>structuredClone(row)).reverse();rows.forEach(row=>{row.payload=Object.fromEntries(Object.entries(row.payload).reverse());row.payload.record=Object.fromEntries(Object.entries(row.payload.record).reverse())});assert.equal(verifyRoleViewCandidateDocuments(plan,rows,{hashDb}).verified,true);const lessons=rows.filter(row=>row.payload.collection==='lessons');[lessons[0].payload.recordIndex,lessons[1].payload.recordIndex]=[lessons[1].payload.recordIndex,lessons[0].payload.recordIndex];assert.throws(()=>verifyRoleViewCandidateDocuments(plan,rows,{hashDb}),/文件不符/)});
test('多筆 changes 由舊到新儲存後必須反轉回畫面順序，Owner 與本人讀回 hash 都一致',()=>{const value=db('aa',2);value.changes=[{type:'newest'},{type:'middle'},{type:'oldest'}];const candidate={viewId:'aa',email:'aa@example.com',kind:'scheduler',db:value,viewHash:hashDb(value)},plan=buildRoleViewCandidatePlan({runId:'run-12345678',sourceHash,views:[candidate]});assert.equal(verifyRoleViewCandidateDocuments(plan,plan.documents.map(row=>structuredClone(row)),{hashDb}).verified,true);const documentsByCollection=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,plan.documents.filter(row=>row.payload.collection===collection).map(row=>({id:row.payload.recordId,data:{...structuredClone(row.payload),createdAt:{seconds:1},createdBy:'owner',createdByEmail:'owner@example.com'}}))]));const own=verifyOwnRoleViewCandidateReadback({documentsByCollection,runId:plan.runId,sourceHash:plan.sourceHash,viewId:candidate.viewId,email:candidate.email,kind:candidate.kind,viewHash:candidate.viewHash},{hashDb});assert.deepEqual(own.db.changes,value.changes);assert.equal(own.documentCount,plan.documentCount);documentsByCollection.changes[0].data.recordIndex=9;assert.throws(()=>verifyOwnRoleViewCandidateReadback({documentsByCollection,runId:plan.runId,sourceHash:plan.sourceHash,viewId:candidate.viewId,email:candidate.email,kind:candidate.kind,viewHash:candidate.viewHash},{hashDb}),/內容不符|順序不連續/)});
