import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,materializeFullRecordDb} from '../js/core/cloud-full-record-shadow.js';
import {recordDataHash} from '../js/core/cloud-record-data-hash.js';
import {buildLiveOperationPlan,verifyLiveOperationPlan} from '../js/core/cloud-live-operation-plan.js';

const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,[]]));
const state=db=>{const materialized=materializeFullRecordDb(db),revisions=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,Object.fromEntries(materialized[collection].map(item=>[item.recordId,1]))]));return{db:structuredClone(db),revisions}};

test('16 集合的新增都建立連續 hash、revision 與配額估算',()=>{const before=empty(),after=empty();for(const collection of FULL_RECORD_COLLECTIONS)after[collection]=collection==='changes'?[{type:'新增'}]:[{id:`${collection}-1`,name:collection}];const plan=buildLiveOperationPlan(state(before),after,{deviceId:'daniel-device',startSequence:7,expectedBaseHash:recordDataHash(before)});assert.equal(plan.collectionCount,16);assert.equal(plan.operationCount,16);assert.equal(plan.estimatedFirestoreReads,48);assert.equal(plan.estimatedFirestoreWrites,48);assert.equal(plan.operations[0].operationId,'daniel-device:7');assert.equal(plan.operations.at(-1).nextHash,plan.finalHash);plan.operations.slice(1).forEach((operation,index)=>assert.equal(operation.baseHash,plan.operations[index].nextHash));assert.equal(verifyLiveOperationPlan(plan,before,after,{revisions:state(before).revisions}).verified,true)});
test('修改、墓碑、墓碑重建精確分類且沿用 revision',()=>{const before=empty(),after=empty();before.lessons=[{id:'update',name:'old'},{id:'delete',name:'gone'}];after.lessons=[{id:'update',name:'new'},{id:'revive',name:'back'}];const current=state(before);current.revisions.lessons.update=4;current.revisions.lessons.delete=2;current.revisions.lessons.revive=8;const plan=buildLiveOperationPlan(current,after,{deviceId:'catherine'});assert.deepEqual(plan.counts.lessons,{creates:0,updates:1,tombstones:1,revives:1,writes:3});const byId=Object.fromEntries(plan.operations.map(operation=>[operation.recordId,operation]));assert.equal(byId.delete.deleted,true);assert.equal(byId.delete.nextRevision,3);assert.equal(byId.update.nextRevision,5);assert.equal(byId.revive.nextRevision,9)});
test('非 changes 純排序不寫入，legacy changes 前插只形成一筆永久追加',()=>{const before=empty(),after=empty();before.students=[{id:'b'},{id:'a'}];after.students=[...before.students].reverse();before.changes=[{type:'old'}];after.changes=[{type:'new'},{type:'old'}];const plan=buildLiveOperationPlan(state(before),after,{deviceId:'aa-device'});assert.equal(plan.operationCount,1);assert.equal(plan.operations[0].collection,'changes');assert.equal(plan.operations[0].recordIndex,1);assert.equal(plan.operations[0].record.type,'new');assert.deepEqual(verifyLiveOperationPlan(plan,before,after,{revisions:state(before).revisions}).db.changes,after.changes)});
test('changes 刪除、修改或重排全部 fail closed',()=>{const before=empty();before.changes=[{type:'new'},{type:'old'}];for(const changes of [[{type:'new'}],[{type:'X'},{type:'old'}],[{type:'old'},{type:'new'}]])assert.throws(()=>buildLiveOperationPlan(state(before),{...empty(),changes},{deviceId:'device'}),/永久操作日誌/)});
test('缺 revision、來源 hash 改變、無效 device 與遭竄改 hash 鏈全部拒絕',()=>{const before=empty(),after=empty();before.teachers=[{id:'t1',name:'A'}];after.teachers=[{id:'t1',name:'B'}];const current=state(before);delete current.revisions.teachers.t1;assert.throws(()=>buildLiveOperationPlan(current,after,{deviceId:'device'}),/缺少目前 revision/);assert.throws(()=>buildLiveOperationPlan(state(before),after,{deviceId:'device',expectedBaseHash:'old'}),/來源 hash/);assert.throws(()=>buildLiveOperationPlan(state(before),after,{deviceId:'bad/id'}),/deviceId/);const plan=buildLiveOperationPlan(state(before),after,{deviceId:'device'}),forged=structuredClone(plan);forged.operations[0].nextHash='forged';assert.throws(()=>verifyLiveOperationPlan(forged,before,after,{revisions:state(before).revisions}),/nextHash/)});
test('一萬堂只修改一堂仍只有一個逐筆操作',()=>{const before=empty(),after=empty();before.lessons=Array.from({length:10000},(_,index)=>({id:`lesson-${String(index).padStart(5,'0')}`,name:`L${index}`}));after.lessons=structuredClone(before.lessons);after.lessons[4321].name='changed';const plan=buildLiveOperationPlan(state(before),after,{deviceId:'stress'});assert.equal(plan.operationCount,1);assert.equal(plan.operations[0].recordId,'lesson-04321');assert.equal(plan.estimatedFirestoreWrites,3)});
test('一萬堂首次逐筆建立使用線性小型 hash 鏈且可完整重建',()=>{const before=empty(),after=empty();after.lessons=Array.from({length:10000},(_,index)=>({id:`year-lesson-${String(index).padStart(5,'0')}`,name:`Y${index}`}));const plan=buildLiveOperationPlan(state(before),after,{deviceId:'year-capacity'}),verified=verifyLiveOperationPlan(plan,before,after,{revisions:state(before).revisions});assert.equal(plan.operationCount,10000);assert.equal(new Set(plan.operations.map(operation=>operation.operationId)).size,10000);assert.equal(new Set(plan.operations.map(operation=>operation.nextHash)).size,10000);assert.equal(plan.operations.at(-1).nextHash,plan.finalHash);assert.equal(verified.verified,true);assert.equal(verified.db.lessons.length,10000)});
test('兩次規劃延續 device 序號、hash 與 revision',()=>{const firstDb=empty(),secondDb=empty(),thirdDb=empty();secondDb.students=[{id:'s1',name:'A'}];thirdDb.students=[{id:'s1',name:'B'}];const first=buildLiveOperationPlan(state(firstDb),secondDb,{deviceId:'device',startSequence:41}),applied=verifyLiveOperationPlan(first,firstDb,secondDb,{revisions:state(firstDb).revisions}),second=buildLiveOperationPlan({db:applied.db,revisions:applied.revisions},thirdDb,{deviceId:'device',startSequence:first.nextSequence,expectedBaseHash:first.finalHash});assert.equal(first.operations[0].operationId,'device:41');assert.equal(second.operations[0].operationId,'device:42');assert.equal(second.operations[0].baseHash,first.finalHash);assert.equal(second.operations[0].baseRevision,1);assert.equal(second.operations[0].nextRevision,2)});
test('不完整 state、無效墓碑 revision 與被加入額外欄位的操作全部拒絕',()=>{assert.throws(()=>buildLiveOperationPlan({},empty(),{deviceId:'device'}));const current=state(empty());current.revisions.lessons['bad/id']=1;assert.throws(()=>buildLiveOperationPlan(current,empty(),{deviceId:'device'}),/revision 無效/);const before=empty(),after=empty();after.lessons=[{id:'l1'}];const plan=buildLiveOperationPlan(state(before),after,{deviceId:'device'}),forged=structuredClone(plan);forged.operations[0].unexpected=true;assert.throws(()=>verifyLiveOperationPlan(forged,before,after,{revisions:state(before).revisions}),/格式遭到改動/)});
