import test from 'node:test';
import assert from 'node:assert/strict';
import {buildInitialRecordSyncSafetyControl,buildRecordSyncSafetyPause,buildRecordSyncRecoveryReceipt,buildRecordSyncSafetyResume,evaluateRecordSyncSafety} from '../js/core/cloud-record-sync-safety-control.js';

const manifest=()=>({schema:'danbridge-record-sync-activation-manifest-v1',environment:'staging',activationEpoch:'epoch-12345678',manifestHash:'a'.repeat(64)});
const initial=()=>buildInitialRecordSyncSafetyControl({manifest:manifest(),createdAt:'2026-08-15T12:00:00+08:00'});
const paused=()=>buildRecordSyncSafetyPause({control:initial(),eventId:'pause-12345678',reason:'串流 revision 異常',safeRecordDataHash:'record-v1:'+'b'.repeat(64),cloudBackupId:'backup-12345678',createdAt:'2026-08-15T12:05:00+08:00'});

test('啟用時安全控制必須同時允許讀寫且 revision 從 1 開始',()=>{const control=initial(),state=evaluateRecordSyncSafety({control,environment:'staging',activationEpoch:'epoch-12345678'});assert.equal(control.state,'active');assert.equal(control.revision,1);assert.equal(state.readAllowed,true);assert.equal(state.writeAllowed,true)});
test('暫停一次只關閉寫入、保留讀取並留下不可變事件 hash',()=>{const result=paused();assert.equal(result.event.type,'pause');assert.match(result.event.eventHash,/^[a-f0-9]{64}$/);assert.equal(result.nextControl.state,'paused');assert.equal(result.nextControl.revision,2);assert.equal(evaluateRecordSyncSafety({control:result.nextControl,environment:'staging',activationEpoch:'epoch-12345678'}).writeAllowed,false)});
test('只有 verified 復原 receipt 與重新讀回 hash 一致才能恢復',()=>{const pause=paused(),receipt=buildRecordSyncRecoveryReceipt({environment:'staging',activationEpoch:'epoch-12345678',pauseEventId:pause.event.eventId,sourceBackupId:'backup-12345678',restoredRecordDataHash:'record-v1:'+'c'.repeat(64),operationLogHash:'d'.repeat(64),confirmedOperationCount:12,createdAt:'2026-08-15T12:10:00+08:00'}),resume=buildRecordSyncSafetyResume({control:pause.nextControl,eventId:'resume-1234567',recoveryReceipt:receipt,readbackRecordDataHash:receipt.restoredRecordDataHash,createdAt:'2026-08-15T12:15:00+08:00'});assert.equal(resume.event.type,'resume');assert.equal(resume.nextControl.state,'active');assert.equal(resume.nextControl.revision,3);assert.equal(resume.nextControl.writeAllowed,true)});
test('缺備份、receipt 被改、hash 未讀回一致或重播暫停全部 fail closed',()=>{const pause=paused(),receipt=buildRecordSyncRecoveryReceipt({environment:'staging',activationEpoch:'epoch-12345678',pauseEventId:pause.event.eventId,sourceBackupId:'backup-12345678',restoredRecordDataHash:'record-v1:'+'c'.repeat(64),operationLogHash:'d'.repeat(64),confirmedOperationCount:12,createdAt:'2026-08-15T12:10:00+08:00'});assert.throws(()=>buildRecordSyncSafetyPause({control:pause.nextControl,eventId:'pause-again-123',reason:'again',safeRecordDataHash:'record-v1:'+'b'.repeat(64),cloudBackupId:'backup-12345678',createdAt:'2026-08-15T12:20:00+08:00'}),/暫停證據無效/);assert.throws(()=>buildRecordSyncSafetyResume({control:pause.nextControl,eventId:'resume-1234567',recoveryReceipt:receipt,readbackRecordDataHash:'record-v1:'+'e'.repeat(64),createdAt:'2026-08-15T12:15:00+08:00'}),/恢復寫入證據無效/);const tampered=structuredClone(receipt);tampered.confirmedOperationCount++;assert.throws(()=>buildRecordSyncSafetyResume({control:pause.nextControl,eventId:'resume-1234567',recoveryReceipt:tampered,readbackRecordDataHash:tampered.restoredRecordDataHash,createdAt:'2026-08-15T12:15:00+08:00'}),/receipt hash 不符/)});
test('控制版本、epoch、旗標或事件 hash 不一致時讀寫都 fail closed',()=>{const original=initial();for(const mutate of [value=>value.revision=0,value=>value.activationEpoch='wrong',value=>value.writeAllowed=false,value=>value.lastEventHash='bad']){const control=structuredClone(original);mutate(control);const state=evaluateRecordSyncSafety({control,environment:'staging',activationEpoch:'epoch-12345678'});assert.equal(state.valid,false);assert.equal(state.readAllowed,false);assert.equal(state.writeAllowed,false)}});
