import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,buildFullRecordShadowPlan} from '../js/core/cloud-full-record-shadow.js';
import {createOperationJournal} from '../js/core/cloud-operation-journal.js';
import {applyActiveRecordOperation} from '../js/core/cloud-active-record-sync.js';
import {runActiveRecordSync} from '../js/core/cloud-active-record-runtime.js';

const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));
const db=()=>{const value=empty();value.lessons=[{id:'lesson-1',room:'A',date:'2026-08-15'},{id:'lesson-2',room:'A',date:'2026-08-16'}];return value};
function setup(){let journalRows=null,time=1000;const documents=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]])),seed=buildFullRecordShadowPlan(documents,db(),{sourceHash:'seed'});for(const operation of seed.operations){const [,collection,id]=operation.path.match(/collections\/([^/]+)\/records\/(.+)$/);documents[collection].push({id,data:structuredClone(operation.payload)})}const storage={load:async()=>structuredClone(journalRows),save:async value=>{journalRows=structuredClone(value)}},journal=createOperationJournal({storage,now:()=>time}),readDocuments=async()=>structuredClone(documents),send=async operation=>{const rows=documents[operation.collection],index=rows.findIndex(row=>row.id===operation.recordId),current=index<0?null:rows[index].data,result=applyActiveRecordOperation(current,operation);if(result.write){const row={id:operation.recordId,data:structuredClone(result.payload)};if(index<0)rows.push(row);else rows[index]=row}return result};return{documents,journal,readDocuments,send,advance:value=>time+=value}};
const run=(source,local,overrides={})=>runActiveRecordSync({journal:source.journal,readDocuments:source.readDocuments,send:source.send,baselineDb:db(),localDb:local,environment:'staging',deviceId:'device-a',activationEpoch:'epoch-12345678',...overrides});

test('日常同步先永久落地再只送真正變更文件',async()=>{const source=setup(),local=db();local.lessons[1].room='B';const result=await run(source,local);assert.equal(result.state,'complete');assert.equal(result.plan.operationCount,1);assert.equal(result.worker.counts.confirmed,1);assert.equal(source.documents.lessons.find(row=>row.id==='lesson-2').data.record.room,'B')});
test('revision 競態會原子取代舊計畫、重讀合併並續傳',async()=>{const source=setup(),local=db();local.lessons[0].date='2026-09-01';let injected=false;const send=async operation=>{if(!injected){injected=true;const row=source.documents.lessons.find(item=>item.id==='lesson-1');row.data={...row.data,record:{...row.data.record,room:'Remote'},revision:2,lastOperationId:'other:1',deviceId:'other',activationEpoch:'epoch-12345678'}}return source.send(operation)},result=await run(source,local,{send});assert.equal(result.state,'complete');assert.equal(result.rebases,1);assert.equal(result.plan.db.lessons[0].room,'Remote');assert.equal(result.plan.db.lessons[0].date,'2026-09-01');const counts=await source.journal.counts();assert.equal(counts.superseded,1);assert.equal(counts.confirmed,1)});
test('同欄位衝突必須先保存不可變證據才允許替代操作',async()=>{const source=setup(),local=db();local.lessons[0].room='Local';let injected=false,backups=0;const send=async operation=>{if(!injected){injected=true;const row=source.documents.lessons.find(item=>item.id==='lesson-1');row.data={...row.data,record:{...row.data.record,room:'Remote'},revision:2,lastOperationId:'other:1',deviceId:'other',activationEpoch:'epoch-12345678'}}return source.send(operation)},result=await run(source,local,{send,persistConflicts:async conflicts=>{backups++;assert.equal(conflicts[0].path,'lessons.lesson-1.room');return{id:'backup-1'}}});assert.equal(result.state,'complete');assert.equal(backups,1);assert.equal(result.conflictBackups[0].id,'backup-1');assert.equal(source.documents.lessons.find(row=>row.id==='lesson-1').data.record.room,'Local')});
test('衝突備份失敗時保留隔離操作且絕不繼續覆蓋',async()=>{const source=setup(),local=db();local.lessons[0].room='Local';let injected=false;const send=async operation=>{if(!injected){injected=true;const row=source.documents.lessons.find(item=>item.id==='lesson-1');row.data={...row.data,record:{...row.data.record,room:'Remote'},revision:2,lastOperationId:'other:1',deviceId:'other',activationEpoch:'epoch-12345678'}}return source.send(operation)};await assert.rejects(run(source,local,{send,persistConflicts:async()=>{throw new Error('backup offline')}}),/backup offline/);const counts=await source.journal.counts();assert.equal(counts.quarantined,1);assert.equal(counts.confirmed,0);assert.equal(source.documents.lessons.find(row=>row.id==='lesson-1').data.record.room,'Remote')});
test('網路失敗只等待退避，不會誤判成版本重排',async()=>{const source=setup(),local=db();local.lessons[0].room='B';const result=await run(source,local,{send:async()=>{throw Object.assign(new Error('offline'),{code:'unavailable'})}});assert.equal(result.state,'waiting');assert.equal(result.rebases,0);assert.equal((await source.journal.counts()).failed,1)});
