import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,buildFullRecordShadowPlan,rebuildFullRecordShadowDb,verifyFullRecordShadowReadback} from '../js/core/cloud-full-record-shadow.js';

const db=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,key==='changes'?[{type:'one'},{type:'one'}]:[{id:`${key}-1`,value:1}]]));
const apply=(store,plan)=>{for(const op of plan.operations){const [,collection,id]=op.path.match(/collections\/([^/]+)\/records\/(.+)$/);store[collection]??=[];const index=store[collection].findIndex(row=>row.id===id),row={id,data:structuredClone(op.payload)};if(index<0)store[collection].push(row);else store[collection][index]=row}}

test('16 集合全部逐筆化，changes 保留順序與重複內容',()=>{const target=db(),store={};const plan=buildFullRecordShadowPlan(store,target,{sourceHash:'hash-1'});assert.equal(plan.collectionCount,16);assert.equal(plan.writes,17);apply(store,plan);const rebuilt=verifyFullRecordShadowReadback(store,target);assert.equal(rebuilt.verified,true);assert.deepEqual(rebuilt.db.changes,[{type:'one'},{type:'one'}])});
test('production 計畫使用隔離 namespace 與 production identity',()=>{const target=db(),store={},plan=buildFullRecordShadowPlan(store,target,{sourceHash:'production-hash',environment:'production'});assert.ok(plan.operations.every(row=>row.path.startsWith('productionFullRecordShadows/')));assert.ok(plan.operations.every(row=>row.payload.environment==='production'));apply(store,plan);assert.equal(verifyFullRecordShadowReadback(store,target,{environment:'production'}).verified,true);assert.throws(()=>verifyFullRecordShadowReadback(store,target),/格式無效/)});
test('修改、墓碑與重建只作用於對應文件並增加 revision',()=>{const first=db(),store={};apply(store,buildFullRecordShadowPlan(store,first,{sourceHash:'h1'}));const second=db();second.lessons[0].value=2;second.students=[];let plan=buildFullRecordShadowPlan(store,second,{sourceHash:'h2'});assert.equal(plan.operations.filter(x=>['lessons','students'].some(key=>x.path.includes(`/collections/${key}/`))).length,2);apply(store,plan);assert.equal(store.lessons[0].data.revision,2);assert.equal(store.students[0].data.deleted,true);const third=db();third.lessons[0].value=2;plan=buildFullRecordShadowPlan(store,third,{sourceHash:'h3'});apply(store,plan);assert.equal(store.students[0].data.revision,3);assert.equal(store.students[0].data.deleted,false)});
test('缺筆、多筆、內容錯誤、changes 序序錯誤都拒絕 verified',()=>{const target=db(),store={};apply(store,buildFullRecordShadowPlan(store,target,{sourceHash:'h'}));for(const mutate of [copy=>copy.lessons.pop(),copy=>copy.lessons.push({...copy.lessons[0],id:'extra'}),copy=>copy.teachers[0].data.record.value=99,copy=>copy.changes[0].data.recordIndex=99]){const copy=structuredClone(store);mutate(copy);assert.throws(()=>verifyFullRecordShadowReadback(copy,target),/格式無效|不一致/)}});
test('非 changes 缺 ID、重複 ID 與超過安全批次都停止',()=>{const target=db();delete target.lessons[0].id;assert.throws(()=>buildFullRecordShadowPlan({},target,{sourceHash:'h'}),/無效或重複 ID/);const duplicate=db();duplicate.lessons.push(structuredClone(duplicate.lessons[0]));assert.throws(()=>buildFullRecordShadowPlan({},duplicate,{sourceHash:'h'}),/無效或重複 ID/);assert.throws(()=>buildFullRecordShadowPlan({},db(),{sourceHash:'h',batchSize:401}),/batchSize/) });
