import test from 'node:test';
import assert from 'node:assert/strict';
import {createOperationJournal} from '../js/core/cloud-operation-journal.js';
import {classifyOperationError,enqueueOperationPlan,runOperationWorker} from '../js/core/cloud-operation-worker.js';

const operation=(id,revision=1)=>({schema:'danbridge-live-record-operation-v1',operationId:id,collection:'lessons',recordId:`lesson-${revision}`,nextRevision:revision});
const plan=operations=>({schema:'danbridge-live-operation-plan-v1',operations,operationCount:operations.length});
const setup=()=>{let value=null,time=1000;const storage={load:async()=>structuredClone(value),save:async next=>{value=structuredClone(next)}};return{journal:createOperationJournal({storage,now:()=>time}),advance:ms=>time+=ms}};
const receipt=op=>({kind:'create',write:true,revision:op.nextRevision});

test('完整計畫先原子加入，再嚴格依序確認',async()=>{const {journal}=setup(),sent=[];await enqueueOperationPlan(journal,plan([operation('d:1'),operation('d:2',2)]));const result=await runOperationWorker({journal,send:async op=>{sent.push(op.operationId);return receipt(op)}});assert.equal(result.state,'complete');assert.equal(result.processed,2);assert.deepEqual(sent,['d:1','d:2']);assert.equal(result.counts.confirmed,2)});
test('相同計畫的多筆操作以單一後端批次確認',async()=>{const {journal}=setup(),sent=[],send=async op=>receipt(op);send.batch=async operations=>{sent.push(operations.map(row=>row.operationId));return{kind:'batch',write:true,operationCount:operations.length,targetHash:operations.at(-1).targetHash}};const rows=[{...operation('d:1'),environment:'staging',activationEpoch:'epoch-batch',deviceId:'device-batch',createdAt:'2026-09-04T00:00:00.000Z',baseHash:'h0',targetHash:'h1',type:'create'},{...operation('d:2',2),environment:'staging',activationEpoch:'epoch-batch',deviceId:'device-batch',createdAt:'2026-09-04T00:00:00.000Z',baseHash:'h1',targetHash:'h2',type:'update'}];await enqueueOperationPlan(journal,plan(rows));const result=await runOperationWorker({journal,send});assert.equal(result.state,'complete');assert.equal(result.processed,2);assert.deepEqual(sent,[['d:1','d:2']]);assert.equal(result.counts.confirmed,2)});
test('批次回應遺失會讓整批共同等待且不留下半確認',async()=>{const {journal}=setup(),send=async op=>receipt(op);send.batch=async()=>{throw Object.assign(new Error('network timeout'),{code:'unavailable'})};const rows=[{...operation('d:1'),environment:'staging',activationEpoch:'epoch-batch',deviceId:'device-batch',createdAt:'2026-09-04T00:00:00.000Z',baseHash:'h0',targetHash:'h1',type:'create'},{...operation('d:2',2),environment:'staging',activationEpoch:'epoch-batch',deviceId:'device-batch',createdAt:'2026-09-04T00:00:00.000Z',baseHash:'h1',targetHash:'h2',type:'update'}];await enqueueOperationPlan(journal,plan(rows));const result=await runOperationWorker({journal,send});assert.equal(result.state,'waiting');assert.equal(result.counts.failed,2);assert.equal(result.counts.confirmed,0)});
test('一般資料與其 immutable changes 審計同一批送達，審計單獨留隊時仍必須單筆',async()=>{const {journal}=setup(),batches=[],singles=[],send=async op=>{singles.push(op.collection);return receipt(op)};send.batch=async operations=>{batches.push(operations.map(row=>row.collection));return{kind:'batch',write:true,operationCount:operations.length,targetHash:operations.at(-1).targetHash}};const common={environment:'staging',activationEpoch:'epoch-batch',deviceId:'device-batch',createdAt:'2026-09-04T00:00:00.000Z'},rows=[{...operation('lesson:1'),...common,collection:'lessons',recordId:'lesson-1',baseHash:'h0',targetHash:'h1',type:'create'},{...operation('lesson:2',2),...common,collection:'lessons',recordId:'lesson-2',baseHash:'h1',targetHash:'h2',type:'create'},{...operation('audit:1',3),...common,collection:'changes',recordId:'seq_00000001_12345678',baseHash:'h2',targetHash:'h3',type:'create'},{...operation('audit:2',4),...common,collection:'changes',recordId:'seq_00000002_12345678',baseHash:'h3',targetHash:'h4',type:'create'}];await enqueueOperationPlan(journal,plan(rows));const result=await runOperationWorker({journal,send});assert.equal(result.state,'complete');assert.equal(result.processed,4);assert.deepEqual(batches,[['lessons','lessons','changes','changes']]);assert.deepEqual(singles,[]);assert.equal(result.counts.confirmed,4);const second=setup(),auditRows=rows.slice(2);await enqueueOperationPlan(second.journal,plan(auditRows));const auditResult=await runOperationWorker({journal:second.journal,send});assert.equal(auditResult.state,'complete');assert.deepEqual(singles,['changes','changes'])});
test('首筆網路失敗時停止且不越過，時間到後依序續傳',async()=>{const {journal,advance}=setup(),sent=[];await enqueueOperationPlan(journal,plan([operation('d:1'),operation('d:2',2)]));let fail=true;const send=async op=>{sent.push(op.operationId);if(fail){fail=false;throw Object.assign(new Error('offline'),{code:'unavailable'})}return receipt(op)};const first=await runOperationWorker({journal,send});assert.equal(first.state,'waiting');assert.deepEqual(sent,['d:1']);advance(1000);const second=await runOperationWorker({journal,send,recoverInterrupted:false});assert.equal(second.state,'complete');assert.deepEqual(sent,['d:1','d:1','d:2'])});
test('不可重試或錯誤回應會隔離首筆並阻擋後續',async()=>{for(const send of [async()=>{throw Object.assign(new Error('hash 衝突'),{code:'failed-precondition'})},async()=>({kind:'create',write:true,revision:99})]){const {journal}=setup();await enqueueOperationPlan(journal,plan([operation('d:1'),operation('d:2',2)]));const result=await runOperationWorker({journal,send});assert.equal(result.state,'blocked');assert.equal(result.counts.quarantined,1);assert.equal(result.counts.pending,1)}});
test('雲端成功但回應遺失後，以 duplicate 冪等確認',async()=>{const {journal,advance}=setup();await enqueueOperationPlan(journal,plan([operation('d:1')]));let calls=0;const send=async op=>{calls++;if(calls===1)throw Object.assign(new Error('response lost'),{code:'unavailable'});return{kind:'duplicate',write:false,revision:op.nextRevision}};assert.equal((await runOperationWorker({journal,send})).state,'waiting');advance(1000);const resumed=await runOperationWorker({journal,send,recoverInterrupted:false});assert.equal(resumed.state,'complete');assert.equal(calls,2)});
test('配額錯誤至少延後十五分鐘且工作程序不忙迴圈',async()=>{const {journal}=setup();await enqueueOperationPlan(journal,plan([operation('d:1'),operation('d:2',2)]));const result=await runOperationWorker({journal,send:async()=>{throw Object.assign(new Error('Quota exceeded'),{code:'resource-exhausted'})}});assert.equal(result.state,'waiting');assert.equal(result.head.nextRetryAt-result.head.updatedAt,900000);assert.equal(result.head.attempts,1)});
test('每輪上限會安全暫停並保留剩餘操作',async()=>{const {journal}=setup();await enqueueOperationPlan(journal,plan([operation('d:1'),operation('d:2',2)]));const result=await runOperationWorker({journal,send:async op=>receipt(op),maxOperations:1});assert.equal(result.state,'paused');assert.equal(result.counts.confirmed,1);assert.equal(result.counts.pending,1)});
test('錯誤分類區分網路、配額與權限／版本問題',()=>{assert.equal(classifyOperationError({code:'unavailable'}).retryable,true);assert.equal(classifyOperationError({code:'resource-exhausted'}).retryAfterMs,900000);assert.equal(classifyOperationError({code:'permission-denied'}).retryable,false);assert.equal(classifyOperationError(new Error('revision 衝突')).retryable,false)});
test('進度顯示失敗不會污染已確認的雲端狀態',async()=>{const {journal}=setup();await enqueueOperationPlan(journal,plan([operation('d:1')]));const result=await runOperationWorker({journal,send:async op=>receipt(op),onProgress:async()=>{throw new Error('UI unavailable')}});assert.equal(result.state,'complete');assert.equal(result.counts.confirmed,1);assert.equal(result.counts.failed,0)});
test('兩個工作程序同時啟動也只傳送每筆一次',async()=>{let value=null,shared=Promise.resolve(),calls=0;const storage={load:async()=>structuredClone(value),save:async next=>{value=structuredClone(next)},exclusive:work=>{const result=shared.then(work,work);shared=result.then(()=>{},()=>{});return result}},first=createOperationJournal({storage}),second=createOperationJournal({storage});await enqueueOperationPlan(first,plan([operation('d:1'),operation('d:2',2)]));await Promise.all([runOperationWorker({journal:first,send:async op=>{calls++;return receipt(op)}}),runOperationWorker({journal:second,send:async op=>{calls++;return receipt(op)}})]);assert.equal(calls,2);assert.equal((await first.counts()).confirmed,2)});
test('已由新版取代的舊操作不阻擋工作程序且永久留在日誌',async()=>{const {journal}=setup();await journal.append(operation('d:old'));await journal.claimNext({causal:true});await journal.fail('d:old','revision 衝突',{retryable:false});await journal.append(operation('d:new',2));await journal.supersede('d:old',{replacementOperationIds:['d:new']});const result=await runOperationWorker({journal,send:async op=>receipt(op),recoverInterrupted:false});assert.equal(result.state,'complete');assert.equal(result.counts.superseded,1);assert.equal(result.counts.confirmed,1);assert.equal(result.head,null)});
