import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,buildFullRecordShadowPlan} from '../js/core/cloud-full-record-shadow.js';
import {buildRecordSyncActivationManifest,buildActiveRecordSyncControl} from '../js/core/cloud-record-sync-control.js';
import {buildRecordSyncRoleEvidence,RECORD_SYNC_ROLE_SCENARIOS} from '../js/core/cloud-record-sync-role-evidence.js';
import {buildOpenRecordSyncCandidateControl,sealRecordSyncCandidateControl} from '../js/core/cloud-record-sync-candidate-control.js';
import {buildInitialRecordSyncSafetyControl,buildRecordSyncSafetyPause} from '../js/core/cloud-record-sync-safety-control.js';
import {createActiveRecordStream} from '../js/core/cloud-active-record-stream.js';

const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));
const db=()=>{const value=empty();value.lessons=[{id:'lesson-1',room:'A'}];value.students=[{id:'student-1',name:'A'}];return value};
const documents=value=>{const result=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));for(const operation of buildFullRecordShadowPlan(result,value,{sourceHash:'seed'}).operations){const [,collection,id]=operation.path.match(/collections\/([^/]+)\/records\/(.+)$/);result[collection].push({id,data:structuredClone(operation.payload)})}return result};
const activation=()=>{const roleEvidence=buildRecordSyncRoleEvidence({environment:'staging',primaryOwnerEmail:'daniel@example.com',backupOwnerEmail:'catherine@example.com',schedulerEmail:'aa@example.com',teacherAccounts:['teacher@example.com'],roleViewCount:4,candidateRunId:'role-run-123',candidateSourceHash:'b'.repeat(64),candidateManifestHash:'c'.repeat(64),receiptCount:6,receiptSetHash:'d'.repeat(64),results:Object.fromEntries(RECORD_SYNC_ROLE_SCENARIOS.map(key=>[key,true])),testedAt:'2026-08-15T11:55:00+08:00'}),candidateControl=sealRecordSyncCandidateControl({control:buildOpenRecordSyncCandidateControl({candidateEpoch:'candidate-12345678',legacyVersionHash:'legacy',createdAt:'2026-08-15T11:50:00+08:00'}),currentLegacyVersionHash:'legacy',recordDataHash:'record-v1:'+'a'.repeat(64),documentCount:2,activeCount:2,tombstoneCount:0,sealedAt:'2026-08-15T11:58:00+08:00'}),manifest=buildRecordSyncActivationManifest({environment:'staging',activationEpoch:'epoch-12345678',candidateControl,legacyVersionHash:'legacy',recordDataHash:'record-v1:'+'a'.repeat(64),roleEvidence,backupId:'backup-123',restoreReceiptId:'restore-123',documentCount:2,activeCount:2,tombstoneCount:0,createdAt:'2026-08-15T12:00:00+08:00'}),control=buildActiveRecordSyncControl({manifest,currentLegacyVersionHash:'legacy',currentRecordDataHash:manifest.recordDataHash,currentRoleEvidenceHash:manifest.roleEvidenceHash,activatedAt:'2026-08-15T12:05:00+08:00'}),safetyControl=buildInitialRecordSyncSafetyControl({manifest,createdAt:control.activatedAt});return{manifest,control,safetyControl}};
async function ready(overrides={}){const applied=[],stream=createActiveRecordStream({environment:'staging',onApply:snapshot=>applied.push(snapshot),...overrides}),{manifest,control,safetyControl}=activation(),source=documents(db());stream.setActivation(control,manifest);await stream.setSafetyControl(safetyControl);for(const collection of FULL_RECORD_COLLECTIONS)await stream.replaceCollection(collection,source[collection]);return{stream,source,applied,manifest,control,safetyControl}}

test('16 集合完整到齊後才一次套用，缺集合時不產生半份畫面',async()=>{const applied=[],stream=createActiveRecordStream({environment:'staging',onApply:value=>applied.push(value)}),{manifest,control,safetyControl}=activation(),source=documents(db());stream.setActivation(control,manifest);await stream.setSafetyControl(safetyControl);for(const collection of FULL_RECORD_COLLECTIONS.slice(0,-1))await stream.replaceCollection(collection,source[collection]);assert.equal(applied.length,0);await stream.replaceCollection(FULL_RECORD_COLLECTIONS.at(-1),source[FULL_RECORD_COLLECTIONS.at(-1)]);assert.equal(applied.length,1);assert.equal(applied[0].db.lessons[0].room,'A')});
test('新增、修改、墓碑與同 ID 重建皆由單一文件串流即時更新',async()=>{const {stream,source,applied}=await ready(),current=source.lessons[0].data,update={...current,record:{...current.record,room:'B'},revision:2,sourceHash:'h2',activationEpoch:'epoch-12345678',lastOperationId:'device:1',deviceId:'device'};await stream.applyChanges('lessons',[{type:'modified',id:'lesson-1',data:update}]);assert.equal(applied.at(-1).db.lessons[0].room,'B');const tombstone={...update,revision:3,deleted:true,sourceHash:'h3',lastOperationId:'device:2'};await stream.applyChanges('lessons',[{type:'modified',id:'lesson-1',data:tombstone}]);assert.equal(applied.at(-1).db.lessons.length,0);const revive={...tombstone,revision:4,deleted:false,record:{...tombstone.record,room:'C'},sourceHash:'h4',lastOperationId:'device:3'};await stream.applyChanges('lessons',[{type:'modified',id:'lesson-1',data:revive}]);assert.equal(applied.at(-1).db.lessons[0].room,'C')});
test('實體刪除、revision 倒退、同版變造與缺操作證據全部阻止',async()=>{for(const mutate of [current=>({type:'removed',id:'lesson-1'}),current=>({type:'modified',id:'lesson-1',data:{...current,revision:0,activationEpoch:'epoch-12345678',lastOperationId:'x',deviceId:'x'}}),current=>({type:'modified',id:'lesson-1',data:{...current,record:{...current.record,room:'forged'},activationEpoch:'epoch-12345678',lastOperationId:'x',deviceId:'x'}}),current=>({type:'modified',id:'lesson-1',data:{...current,revision:2}})]){const {stream,source}=await ready();await assert.rejects(stream.applyChanges('lessons',[mutate(source.lessons[0].data)]),/實體刪除|revision|identity|證據缺失/)}});
test('停用或被篡改的控制永遠不套用逐筆資料',async()=>{const applied=[],stream=createActiveRecordStream({environment:'staging',onApply:value=>applied.push(value)}),{manifest,control}=activation(),source=documents(db());assert.equal(stream.setActivation({...control,writeTakeover:false},manifest).eligible,false);for(const collection of FULL_RECORD_COLLECTIONS)await stream.replaceCollection(collection,source[collection]);assert.equal(applied.length,0);assert.equal((await stream.snapshot()).ready,false)});
test('中央安全暫停後串流仍可讀，但所有畫面會立即收到 writeAllowed=false',async()=>{const {stream,safetyControl,applied}=await ready(),pause=buildRecordSyncSafetyPause({control:safetyControl,eventId:'pause-12345678',reason:'測試異常',safeRecordDataHash:'record-v1:'+'b'.repeat(64),cloudBackupId:'backup-12345678',createdAt:'2026-08-15T12:10:00+08:00'});assert.equal((await stream.setSafetyControl(pause.nextControl)).writeAllowed,false);const result=await stream.snapshot();assert.equal(result.ready,true);assert.equal(stream.diagnostics().writeTakeover,false);assert.equal(stream.diagnostics().readTakeover,true);assert.equal(applied.at(-1).writeAllowed,false);assert.equal(applied.at(-1).safetyState,'paused')});
test('重新整理重新載入 16 集合可讀回完全相同 hash 與內容',async()=>{const first=await ready(),firstSnapshot=(await first.stream.snapshot()).snapshot,second=await ready(),secondSnapshot=(await second.stream.snapshot()).snapshot;assert.equal(firstSnapshot.hash,secondSnapshot.hash);assert.deepEqual(firstSnapshot.db,secondSnapshot.db);assert.equal(second.stream.diagnostics().ready,true);assert.equal(second.stream.diagnostics().readTakeover,true)});
test('pending 後完整重新對齊只接受不缺筆且 revision 單調增加的已確認集合',async()=>{const first=await ready(),current=first.source.lessons[0],valid={...current,data:{...current.data,record:{...current.data.record,room:'B'},revision:2,lastOperationId:'device:1',deviceId:'device',activationEpoch:'epoch-12345678'}};await first.stream.refreshCollection('lessons',[valid]);assert.equal(first.applied.at(-1).db.lessons[0].room,'B');await assert.rejects(first.stream.refreshCollection('lessons',[]),/實體刪除/);await assert.rejects(first.stream.refreshCollection('lessons',[current]),/revision 倒退/);await assert.rejects(first.stream.refreshCollection('lessons',[{...valid,data:{...valid.data,record:{...valid.data.record,room:'forged'}}}]),/同版變造/)});
