import test from 'node:test';
import assert from 'node:assert/strict';
import {buildRecordSyncActivationManifest,assertRecordSyncActivationManifest,assertRecordSyncActivationSourceLineage,buildActiveRecordSyncControl,evaluateActiveRecordSyncControl} from '../js/core/cloud-record-sync-control.js';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';
import {buildRecordSyncRoleEvidence,RECORD_SYNC_ROLE_SCENARIOS} from '../js/core/cloud-record-sync-role-evidence.js';
import {buildOpenRecordSyncCandidateControl,sealRecordSyncCandidateControl} from '../js/core/cloud-record-sync-candidate-control.js';

const roleEvidence=()=>buildRecordSyncRoleEvidence({environment:'staging',primaryOwnerEmail:'daniel@example.com',backupOwnerEmail:'catherine@example.com',schedulerEmail:'aa@example.com',teacherAccounts:['teacher@example.com'],roleViewCount:12,candidateRunId:'role-run-123',candidateSourceHash:'b'.repeat(64),candidateManifestHash:'c'.repeat(64),receiptCount:14,receiptSetHash:'d'.repeat(64),results:Object.fromEntries(RECORD_SYNC_ROLE_SCENARIOS.map(key=>[key,true])),testedAt:'2026-08-15T11:55:00+08:00'});
const candidateControl=()=>sealRecordSyncCandidateControl({control:buildOpenRecordSyncCandidateControl({candidateEpoch:'candidate-12345678',legacyVersionHash:'legacy-123',createdAt:'2026-08-15T11:50:00+08:00'}),currentLegacyVersionHash:'legacy-123',recordDataHash:'record-v1:'+'a'.repeat(64),documentCount:1050,activeCount:1049,tombstoneCount:1,sealedAt:'2026-08-15T11:58:00+08:00'});
const input=()=>({environment:'staging',activationEpoch:'epoch-12345678',candidateControl:candidateControl(),legacyVersionHash:'legacy-123',recordDataHash:'record-v1:'+'a'.repeat(64),roleEvidence:roleEvidence(),backupId:'backup-123',restoreReceiptId:'restore-123',documentCount:1050,activeCount:1049,tombstoneCount:1,createdAt:'2026-08-15T12:00:00+08:00'});
const activate=manifest=>buildActiveRecordSyncControl({manifest,currentLegacyVersionHash:manifest.legacyVersionHash,currentRecordDataHash:manifest.recordDataHash,currentRoleEvidenceHash:manifest.roleEvidenceHash,activatedAt:'2026-08-15T12:05:00+08:00'});

test('完整備份、復原、逐筆與角色證據才能建立不可變 manifest',()=>{const manifest=buildRecordSyncActivationManifest(input());assert.equal(assertRecordSyncActivationManifest(manifest),manifest);assert.equal(manifest.collectionCount,16);assert.equal(manifest.readTakeover,false);assert.equal(manifest.writeTakeover,false);assert.match(manifest.manifestHash,/^[a-f0-9]{64}$/)});
test('啟用必須一次同時打開讀寫，沒有半套接管狀態',()=>{const manifest=buildRecordSyncActivationManifest(input()),control=activate(manifest),result=evaluateActiveRecordSyncControl({control,manifest,environment:'staging',currentRecordDataHash:manifest.recordDataHash,currentRoleEvidenceHash:manifest.roleEvidenceHash});assert.equal(control.readTakeover,true);assert.equal(control.writeTakeover,true);assert.deepEqual(result,{eligible:true,reason:'',readTakeover:true,writeTakeover:true,activationEpoch:'epoch-12345678'})});
test('版本、逐筆 hash 或角色證據在啟用前改變都立即阻止',()=>{const manifest=buildRecordSyncActivationManifest(input());for(const overrides of [{currentLegacyVersionHash:'changed'},{currentRecordDataHash:'record-v1:'+'c'.repeat(64)},{currentRoleEvidenceHash:'d'.repeat(64)}])assert.throws(()=>buildActiveRecordSyncControl({manifest,currentLegacyVersionHash:manifest.legacyVersionHash,currentRecordDataHash:manifest.recordDataHash,currentRoleEvidenceHash:manifest.roleEvidenceHash,activatedAt:'2026-08-15T12:05:00+08:00',...overrides}),/來源版本已改變/)});
test('manifest 任一封存、計數、情境、hash 或旗標被修改均 fail closed',()=>{const original=buildRecordSyncActivationManifest(input());for(const mutate of [value=>value.candidateRevision++,value=>value.candidateSealHash='f'.repeat(64),value=>value.documentCount++,value=>value.activeCount--,value=>value.requiredScenarios.pop(),value=>value.roleEvidenceHash='c'.repeat(64),value=>value.readTakeover=true]){const changed=structuredClone(original);mutate(changed);assert.throws(()=>assertRecordSyncActivationManifest(changed),/格式無效|hash 不符/)}});
test('重新整理讀回不符或環境錯誤時自動回到 legacy 而非套用候選',()=>{const manifest=buildRecordSyncActivationManifest(input()),control=activate(manifest);for(const overrides of [{environment:'production'},{currentRecordDataHash:'record-v1:'+'c'.repeat(64)},{currentRoleEvidenceHash:'d'.repeat(64)},{control:{...control,writeTakeover:false}}]){const result=evaluateActiveRecordSyncControl({control,manifest,environment:'staging',currentRecordDataHash:manifest.recordDataHash,currentRoleEvidenceHash:manifest.roleEvidenceHash,...overrides});assert.equal(result.eligible,false);assert.equal(result.readTakeover,false);assert.equal(result.writeTakeover,false)}});
test('Firestore 讀回只允許固定三個落地稽核欄位，且不污染核心 manifest hash',()=>{const manifest=buildRecordSyncActivationManifest(input()),persisted={...manifest,persistedAt:{seconds:123,nanoseconds:0},persistedBy:'owner-123',persistedByEmail:'owner@example.com'};assert.equal(assertRecordSyncActivationManifest(persisted),persisted);assert.throws(()=>assertRecordSyncActivationManifest({...persisted,unexpected:true}),/格式無效/);assert.throws(()=>assertRecordSyncActivationManifest({...manifest,persistedBy:'owner-123'}),/稽核欄位不完整/)});
test('descriptor-safe source lineage逐欄綁activation manifest/control且回canonical control hash',()=>{const manifest=buildRecordSyncActivationManifest(input()),control=activate(manifest),persistedManifest={...manifest,persistedAt:'2026-08-15T12:01:00.123456789+08:00',persistedBy:'owner-123',persistedByEmail:'owner@example.com'},persistedControl={...control,persistedAt:'2026-08-15T12:06:00.123456789+08:00',activatedBy:'owner-123',activatedByEmail:'owner@example.com'},result=assertRecordSyncActivationSourceLineage({manifest:persistedManifest,control:persistedControl,expectedManifestHash:manifest.manifestHash});assert.equal(result.controlCoreHash,sha256Canonical(control));assert.equal(result.manifestAuditPresent,true);assert.equal(result.controlAuditPresent,true);assert.deepEqual(result.controlCore,control);assert.throws(()=>assertRecordSyncActivationSourceLineage({manifest:persistedManifest,control:{...persistedControl,activeCount:1048},expectedManifestHash:manifest.manifestHash}),/mirror/);assert.throws(()=>assertRecordSyncActivationSourceLineage({manifest:{...manifest,persistedBy:'owner-123'},control:persistedControl,expectedManifestHash:manifest.manifestHash}),/all-or-none/)});
test('source lineage拒extra/accessor/custom prototype且getter0；Firestore map key reorder仍一致',()=>{const manifest=buildRecordSyncActivationManifest(input()),control=activate(manifest),persistedManifest={...manifest,persistedAt:'2026-08-15T12:01:00Z',persistedBy:'owner-123',persistedByEmail:'owner@example.com'},persistedControl={...control,persistedAt:'2026-08-15T12:06:00Z',activatedBy:'owner-123',activatedByEmail:'owner@example.com'},reorder=value=>Object.fromEntries(Object.entries(value).reverse()),expected=assertRecordSyncActivationSourceLineage({manifest:persistedManifest,control:persistedControl,expectedManifestHash:manifest.manifestHash});assert.deepEqual(assertRecordSyncActivationSourceLineage(reorder({control:reorder(persistedControl),expectedManifestHash:manifest.manifestHash,manifest:reorder(persistedManifest)})),expected);let calls=0;const hostile={...persistedControl};Object.defineProperty(hostile,'manifestHash',{enumerable:true,get(){calls++;return manifest.manifestHash}});assert.throws(()=>assertRecordSyncActivationSourceLineage({manifest:persistedManifest,control:hostile,expectedManifestHash:manifest.manifestHash}),/data field/);assert.equal(calls,0);assert.throws(()=>assertRecordSyncActivationSourceLineage({manifest:{...persistedManifest,extra:true},control:persistedControl,expectedManifestHash:manifest.manifestHash}),/欄位無效/);assert.throws(()=>assertRecordSyncActivationSourceLineage({manifest:persistedManifest,control:Object.assign(Object.create({}),persistedControl),expectedManifestHash:manifest.manifestHash}),/plain object/)});
