import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,buildFullRecordShadowPlan,rebuildFullRecordShadowDb} from '../js/core/cloud-full-record-shadow.js';
import {recordDataHash} from '../js/core/cloud-record-data-hash.js';
import {applyActiveRecordOperation} from '../js/core/cloud-active-record-sync.js';
import {createOperationJournal} from '../js/core/cloud-operation-journal.js';
import {createActiveRecordPageController} from '../js/core/cloud-active-record-page-controller.js';

const epoch='epoch-12345678';
const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));
const baseDb=()=>{const db=empty();db.lessons=[{id:'lesson-1',room:'A'},{id:'lesson-2',room:'A'}];return db};
const memoryJournal=(source={rows:null,time:1000})=>createOperationJournal({storage:{load:async()=>structuredClone(source.rows),save:async rows=>{source.rows=structuredClone(rows)}},now:()=>source.time});
function cloudSource(){const documents=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));for(const operation of buildFullRecordShadowPlan(documents,baseDb(),{sourceHash:'seed',environment:'staging'}).operations){const match=operation.path.match(/collections\/([^/]+)\/records\/(.+)$/);documents[match[1]].push({id:match[2],data:structuredClone(operation.payload)})}return{documents,read:async()=>structuredClone(documents),send:async operation=>{const rows=documents[operation.collection],index=rows.findIndex(row=>row.id===operation.recordId),current=index<0?null:rows[index].data,result=applyActiveRecordOperation(current,operation);if(result.write){const next={id:operation.recordId,data:structuredClone(result.payload)};if(index<0)rows.push(next);else rows[index]=next}return result},db:()=>rebuildFullRecordShadowDb(documents,{environment:'staging'}).db}}
const snapshot=source=>({db:source.db(),hash:recordDataHash(source.db()),activationEpoch:epoch,writeAllowed:true});
function makeController({source=cloudSource(),journal=memoryJournal(),local=baseDb(),deviceId='device-123',publish=[],backups=[],send,applyHook,publishHook,ensureBackup=async()=>true,strictConvergence=false}={}){let ui=structuredClone(local),controller;const api=createActiveRecordPageController({environment:'staging',role:'owner',deviceId,journal,readDocuments:source.read,send:send||source.send,persistConflicts:async(conflicts,context)=>{backups.push({conflicts:structuredClone(conflicts),context});return{backupId:`backup-${backups.length}`}},getLocalDb:()=>structuredClone(ui),applyCloudDb:async db=>{ui=structuredClone(db);await applyHook?.(ui,controller)},ensureCloudBackup:ensureBackup,publishRoleViews:async db=>{publish.push(structuredClone(db));await publishHook?.(db,controller)},setTimer:()=>1,clearTimer:()=>{},saveDelay:0,strictConvergence});controller=api;return{controller,source,journal,get ui(){return structuredClone(ui)},setUi(value){ui=structuredClone(value)}}}

test('完整逐筆快照先成為基準，單堂修改只送一筆並以全量讀回確認',async()=>{const app=makeController(),applied=await app.controller.acceptCloudSnapshot(snapshot(app.source));assert.equal(applied.state,'ready');const local=app.ui;local.lessons[0].room='B';app.setUi(local);app.controller.queueLocalSave();const result=await app.controller.flush();assert.equal(result.state,'complete');assert.equal(result.plan.operationCount,1);assert.equal(app.source.db().lessons[0].room,'B');assert.equal(app.controller.diagnostics().dirty,false)});
test('後端已提交但瀏覽器串流仍短暫保留舊版本時，等待權威版本收斂後才發布角色檢視',async()=>{const authority=cloudSource(),stale=structuredClone(authority.documents);let staleReads=0;const source={...authority,read:async()=>staleReads-->0?structuredClone(stale):authority.read(),send:async operation=>{const result=await authority.send(operation);staleReads=2;return result}},published=[];const app=makeController({source,publish:published,strictConvergence:true});await app.controller.acceptCloudSnapshot(snapshot(authority));const local=app.ui;local.lessons[0].room='Converged';app.setUi(local);app.controller.queueLocalSave();const result=await app.controller.flush();assert.equal(result.state,'complete');assert.equal(result.readbackDb.lessons[0].room,'Converged');assert.equal(published.at(-1).lessons[0].room,'Converged');assert.equal(app.controller.diagnostics().dirty,false)});
test('重新整理前已有未入日誌的本機修改時，第一個雲端快照只建基準不覆蓋，後續可精確送出',async()=>{const source=cloudSource(),local=baseDb();local.lessons[0].room='Recovered local';const app=makeController({source,local});app.controller.queueLocalSave();await app.controller.acceptCloudSnapshot(snapshot(source));assert.equal(app.ui.lessons[0].room,'Recovered local');assert.equal(app.controller.diagnostics().hasBaseline,true);assert.equal((await app.controller.flush()).state,'complete');assert.equal(source.db().lessons[0].room,'Recovered local')});
test('中央暫停仍可套用雲端讀取，但任何本機修改都不會送出',async()=>{const source=cloudSource();let sends=0;const app=makeController({source,send:async operation=>{sends++;return source.send(operation)}});await app.controller.acceptCloudSnapshot({...snapshot(source),writeAllowed:false});const local=app.ui;local.lessons[0].room='Paused';app.setUi(local);app.controller.queueLocalSave();assert.equal((await app.controller.flush()).state,'paused');assert.equal(sends,0);app.controller.setWriteAllowed(true);assert.equal((await app.controller.flush()).state,'complete');assert.equal(sends,1)});
test('同步途中新增的第二筆本機修改不會被第一次讀回覆蓋，下一輪精確續傳',async()=>{const source=cloudSource();let app,sends=0;app=makeController({source,send:async operation=>{const result=await source.send(operation);sends++;if(sends===1){const newer=app.ui;newer.lessons[1].room='Newer';app.setUi(newer);app.controller.queueLocalSave()}return result}});await app.controller.acceptCloudSnapshot(snapshot(source));const local=app.ui;local.lessons[0].room='First';app.setUi(local);app.controller.queueLocalSave();const first=await app.controller.flush();assert.equal(first.state,'pending');assert.equal(app.ui.lessons[0].room,'First');assert.equal(app.ui.lessons[1].room,'Newer');const second=await app.controller.flush();assert.equal(second.state,'complete');assert.equal(source.db().lessons[0].room,'First');assert.equal(source.db().lessons[1].room,'Newer')});
test('失敗操作留在永久日誌，重開控制器後由同一 operationId 繼續而不重複 revision',async()=>{const source=cloudSource(),storage={rows:null,time:1000},journal=memoryJournal(storage);let firstAttempt=true,ui=baseDb(),first=makeController({source,journal,local:ui,send:async operation=>{if(firstAttempt){firstAttempt=false;throw Object.assign(new Error('offline'),{code:'unavailable'})}return source.send(operation)}});await first.controller.acceptCloudSnapshot(snapshot(source));ui=first.ui;ui.lessons[0].room='Retry';first.setUi(ui);first.controller.queueLocalSave();assert.equal((await first.controller.flush()).state,'waiting');assert.equal((await journal.counts()).failed,1);storage.time+=2000;const second=makeController({source,journal,local:first.ui});await second.controller.acceptCloudSnapshot(snapshot(source));await second.controller.resume();assert.equal((await second.controller.flush()).state,'complete');assert.equal(source.db().lessons[0].room,'Retry');assert.equal(source.documents.lessons[0].data.revision,2);assert.equal((await journal.counts()).confirmed,1)});
test('Daniel 與 Catherine 從相同基準改不同課程，兩邊資料自然合併且角色檢視拿到完整結果',async()=>{const source=cloudSource(),danielPublish=[],catherinePublish=[],daniel=makeController({source,deviceId:'daniel-123',publish:danielPublish}),catherine=makeController({source,deviceId:'catherine-123',publish:catherinePublish});await Promise.all([daniel.controller.acceptCloudSnapshot(snapshot(source)),catherine.controller.acceptCloudSnapshot(snapshot(source))]);const d=daniel.ui,c=catherine.ui;d.lessons[0].room='Daniel';c.lessons[1].room='Catherine';daniel.setUi(d);catherine.setUi(c);daniel.controller.queueLocalSave();catherine.controller.queueLocalSave();assert.equal((await daniel.controller.flush()).state,'complete');assert.equal((await catherine.controller.flush()).state,'complete');assert.deepEqual(source.db().lessons.map(row=>row.room),['Daniel','Catherine']);assert.deepEqual(catherinePublish.at(-1).lessons.map(row=>row.room),['Daniel','Catherine'])});
test('同步後偵測同欄位較晚遠端變更時先備份，再保留本機意圖排入下一輪',async()=>{const source=cloudSource(),backups=[];let app,injected=false;app=makeController({source,backups,send:async operation=>{const result=await source.send(operation);if(!injected){injected=true;const row=source.documents.lessons.find(value=>value.id==='lesson-1');row.data={...row.data,record:{...row.data.record,room:'Later remote'},revision:row.data.revision+1,lastOperationId:'other-owner:9',deviceId:'other-owner',activationEpoch:epoch}}return result}});await app.controller.acceptCloudSnapshot(snapshot(source));const local=app.ui;local.lessons[0].room='Mine';app.setUi(local);app.controller.queueLocalSave();const result=await app.controller.flush();assert.equal(result.state,'pending');assert.equal(backups.length,1);assert.equal(backups[0].conflicts[0].path,'lessons.lesson-1.room');assert.equal(app.ui.lessons[0].room,'Mine')});
test('核心逐筆已確認但角色發布中斷時，手動重試會重新發布且不重送已確認操作',async()=>{const source=cloudSource();let publishAttempts=0,sends=0;const app=makeController({source,send:async operation=>{sends++;return source.send(operation)},publishHook:async()=>{publishAttempts++;if(publishAttempts===1)throw new Error('role publish interrupted')}});await app.controller.acceptCloudSnapshot(snapshot(source));const local=app.ui;local.lessons[0].room='Confirmed core';app.setUi(local);app.controller.queueLocalSave();const first=await app.controller.flush();assert.equal(first.state,'blocked');assert.equal(source.db().lessons[0].room,'Confirmed core');assert.equal(app.controller.diagnostics().retryPending,true);assert.equal(sends,1);const second=await app.controller.flush();assert.equal(second.state,'complete');assert.equal(app.controller.diagnostics().retryPending,false);assert.equal(publishAttempts,2);assert.equal(sends,1)});
test('每日第一次寫入必須先完成雲端分片備份，失敗時零寫入且可安全重試',async()=>{const source=cloudSource(),order=[];let backupReady=false,sends=0;const app=makeController({source,ensureBackup:async db=>{order.push(`backup:${db.lessons[0].room}`);return backupReady},send:async operation=>{order.push('send');sends++;return source.send(operation)}});await app.controller.acceptCloudSnapshot(snapshot(source));const local=app.ui;local.lessons[0].room='After';app.setUi(local);app.controller.queueLocalSave();const first=await app.controller.flush();assert.equal(first.state,'blocked');assert.equal(sends,0);assert.equal(source.db().lessons[0].room,'A');backupReady=true;const second=await app.controller.flush();assert.equal(second.state,'complete');assert.equal(sends,1);assert.deepEqual(order,['backup:A','backup:A','send']);assert.equal(source.db().lessons[0].room,'After')});
