import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS} from '../js/core/cloud-full-record-shadow.js';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';
import {buildStagingLivePreflight} from '../js/core/cloud-staging-live-preflight.js';
import {buildStagingLiveActivationControl,buildStagingLiveFinalControl,verifyStagingLiveJournalRows} from '../js/core/cloud-staging-live-activation.js';
import {createFirebaseStagingLiveActivationAdapter} from '../js/core/firebase-staging-live-activation-adapter.js';

const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,[]]));
function fixture(){const sourceDb=empty(),targetDb=empty(),revisions=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{}]));targetDb.lessons=[{id:'lesson-1',name:'safe'}];const legacyVersionHash='legacy-v1',sourceHash=sha256Canonical(targetDb),collections=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{count:collection==='lessons'?1:0,chunks:collection==='lessons'?1:0}])),backup={schema:'danbridge-immutable-migration-backup-v2',environment:'staging',state:'verified',backupId:'backup_123',sourceHash,verifiedHash:sourceHash,sourceVersionHash:legacyVersionHash,collectionOrder:[...FULL_RECORD_COLLECTIONS],chunkCount:1,recordCount:1,collections},restoreReceipt={schema:'danbridge-migration-restore-drill-v1',environment:'staging',state:'verified',persisted:true,drillId:'drill_123',sourceBackupId:backup.backupId,sourceHash,restoredHash:sourceHash,recordCount:1,mainVersionHash:legacyVersionHash,mainUnchanged:true},preflight=buildStagingLivePreflight({environment:'staging',role:'owner',projectId:'danbridge-d8877-staging',sourceState:{db:sourceDb,revisions},targetDb,backup,restoreReceipt,legacyVersionHash,deviceId:'device',readBudget:500,writeBudget:100,createdAt:'2026-08-15T01:00:00+08:00'});return{...preflight,targetDb,backup,restoreReceipt,legacyVersionHash}}
const snapshot=(store,path)=>({exists:store.has(path),data:store.get(path)});
function setup(input=fixture()){const {manifest,backup,restoreReceipt,legacyVersionHash}=input,store=new Map([['companies/danbridge/data/main',{db:input.targetDb,clientHash:legacyVersionHash}],['stagingMigrationBackups/danbridge/runs/backup_123',backup],['stagingMigrationRestoreDrills/danbridge/runs/drill_123',{...restoreReceipt}]]),writes=[];const adapter=createFirebaseStagingLiveActivationAdapter({actor:{uid:'owner',email:'OWNER@EXAMPLE.COM'},serverTimestamp:()=> 'SERVER_TIME',runTransaction:async callback=>callback({get:async path=>snapshot(store,path),set:(path,value)=>{writes.push(path);store.set(path,value)}})});return{manifest,store,writes,adapter,input}}

test('控制文件完整綁定 manifest、備份、復原與預期完成筆數',()=>{const {manifest}=fixture(),control=buildStagingLiveActivationControl(manifest);assert.equal(control.schema,'danbridge-live-record-control-v2');assert.equal(control.executionManifestHash,manifest.manifestHash);assert.equal(control.dataHash,manifest.sourceRecordHash);assert.equal(control.targetDataHash,manifest.targetRecordHash);assert.equal(control.operationCount,1);assert.equal(control.state,'migrating')});
test('永久日誌逐筆內容、順序 hash 與 manifest 三重綁定',()=>{const {manifest,plan}=fixture(),rows=plan.operations.map(operation=>({operation:{...operation,executionManifestHash:manifest.manifestHash,operationPlanHash:manifest.operationPlanHash,operationListHash:manifest.operationListHash}}));assert.equal(verifyStagingLiveJournalRows(manifest,rows).verified,true);assert.throws(()=>verifyStagingLiveJournalRows(manifest,[]),/manifest/);assert.throws(()=>verifyStagingLiveJournalRows(manifest,[{operation:{...rows[0].operation,operationPlanHash:'0'.repeat(64)}}]),/manifest/);assert.throws(()=>verifyStagingLiveJournalRows(manifest,[{operation:{...rows[0].operation,record:{...rows[0].operation.record,forged:true}}}]),/內容 hash/)});
test('續傳端獨立拒絕缺集合、負筆數、總數、輪次與配額公式遭竄改的 manifest',()=>{const {manifest}=fixture(),reseal=changes=>{const body={...manifest,...changes};delete body.manifestHash;return{...body,manifestHash:sha256Canonical(body)}};const missing={...manifest.sourceCounts};delete missing.lessons;for(const changed of [{sourceCounts:missing},{targetDocumentCounts:{...manifest.targetDocumentCounts,lessons:-1}},{sourceRecordCount:1},{maxOperationsPerRun:0},{plannedExecutionPasses:2},{activationAttemptAllowance:9},{estimatedWrites:99},{readBudget:0}])assert.throws(()=>buildStagingLiveActivationControl(reseal(changed)),/manifest 啟用格式/)});
test('同一交易不可覆寫地建立 manifest 與控制，重送保持冪等',async()=>{const {adapter,manifest,store,writes}=setup(),first=await adapter.activate(manifest);assert.equal(first.kind,'activated');assert.deepEqual(writes,[`stagingLiveExecutionManifests/danbridge/runs/${manifest.manifestHash}`,'stagingLiveRecordControls/danbridge']);assert.equal(store.get('stagingLiveRecordControls/danbridge').updatedByEmail,'owner@example.com');const replay=await adapter.activate(manifest);assert.equal(replay.kind,'duplicate');assert.equal(writes.length,2)});
test('Firestore 重排 manifest 欄位後仍辨識為同一份，不會誤報衝突或覆寫',async()=>{const {adapter,manifest,store,writes}=setup();await adapter.activate(manifest);const path=`stagingLiveExecutionManifests/danbridge/runs/${manifest.manifestHash}`,stored=store.get(path);store.set(path,Object.fromEntries(Object.entries(stored).reverse()));const replay=await adapter.activate(manifest);assert.equal(replay.kind,'duplicate');assert.equal(writes.length,2)});
test('中斷後同一 manifest 控制可安全續跑，不會嘗試重建或覆寫',async()=>{const {adapter,manifest,store,writes}=setup();await adapter.activate(manifest);store.set('stagingLiveRecordControls/danbridge',{...store.get('stagingLiveRecordControls/danbridge'),dataHash:'record-v1:'+'1'.repeat(64),rootRevision:1,confirmedOperationCount:1,state:'verifying',lastOperationId:'device:1',lastCollection:'lessons',lastRecordId:'lesson-1',verifiedHash:'',verifiedDocumentCount:0,verifiedActiveCount:0,verifiedTombstoneCount:0,targetDataHash:manifest.targetRecordHash});const control=store.get('stagingLiveRecordControls/danbridge');store.set('stagingLiveRecordControls/danbridge',{...control,dataHash:manifest.targetRecordHash});assert.equal((await adapter.activate(manifest)).kind,'resume');assert.equal(writes.length,2)});
test('legacy、備份、receipt、既有 manifest 或控制任一改變都拒絕啟用',async()=>{for(const mutate of [store=>store.set('companies/danbridge/data/main',{db:{},clientHash:'changed'}),store=>store.set('companies/danbridge/data/main',{...store.get('companies/danbridge/data/main'),db:{forged:true}}),store=>store.set('stagingMigrationBackups/danbridge/runs/backup_123',{...store.get('stagingMigrationBackups/danbridge/runs/backup_123'),sourceHash:'0'.repeat(64)}),store=>store.set('stagingMigrationRestoreDrills/danbridge/runs/drill_123',{...store.get('stagingMigrationRestoreDrills/danbridge/runs/drill_123'),mainUnchanged:false})]){const {adapter,manifest,store}=setup();mutate(store);await assert.rejects(()=>adapter.activate(manifest),/證據已改變/)}const a=setup();a.store.set(`stagingLiveExecutionManifests/danbridge/runs/${a.manifest.manifestHash}`,{...a.manifest,operationCount:99});await assert.rejects(()=>a.adapter.activate(a.manifest),/manifest identity/);const b=setup();b.store.set('stagingLiveRecordControls/danbridge',{...buildStagingLiveActivationControl(b.manifest),targetDataHash:'wrong'});await assert.rejects(()=>b.adapter.activate(b.manifest),/控制 identity/)});
test('只有完成全部操作且全量讀回 hash／文件／有效／墓碑全符才可啟用',async()=>{const {adapter,manifest,store,input}=setup();await adapter.activate(manifest);const initial=store.get('stagingLiveRecordControls/danbridge'),verifying={...initial,state:'verifying',dataHash:manifest.targetRecordHash,rootRevision:1,confirmedOperationCount:1,lastOperationId:'device:1',lastCollection:'lessons',lastRecordId:'lesson-1'};store.set('stagingLiveRecordControls/danbridge',verifying);const readback={db:input.targetDb,documentCount:1,activeCount:1,tombstoneCount:0},final=buildStagingLiveFinalControl({manifest,control:verifying,readback});assert.equal(final.state,'active');assert.equal((await adapter.finalize(manifest,readback)).kind,'finalized');assert.equal(store.get('stagingLiveRecordControls/danbridge').verifiedHash,manifest.targetRecordHash);assert.equal((await adapter.finalize(manifest,readback)).kind,'duplicate')});
test('缺筆、多筆、hash 不符與未完成控制全部 fail closed',()=>{const {manifest,targetDb}=fixture(),base={...buildStagingLiveActivationControl(manifest),state:'verifying',dataHash:manifest.targetRecordHash,rootRevision:1,confirmedOperationCount:1,lastOperationId:'device:1',lastCollection:'lessons',lastRecordId:'lesson-1'},readback={db:targetDb,documentCount:1,activeCount:1,tombstoneCount:0};for(const changed of [{documentCount:0,activeCount:0},{documentCount:2,activeCount:2},{db:{...targetDb,lessons:[{id:'lesson-1',name:'forged'}]}}])assert.throws(()=>buildStagingLiveFinalControl({manifest,control:base,readback:{...readback,...changed}}),/讀回不一致/);assert.throws(()=>buildStagingLiveFinalControl({manifest,control:{...base,confirmedOperationCount:0},readback}),/控制不一致/)});
test('前一輪 active 後可原子換綁下一份 manifest，全域 revision 延續且本輪計數歸零',async()=>{const first=setup(),{adapter,manifest,store,input}=first;await adapter.activate(manifest);store.set('stagingLiveRecordControls/danbridge',{...buildStagingLiveActivationControl(manifest),state:'active',dataHash:manifest.targetRecordHash,rootRevision:1,confirmedOperationCount:1,lastOperationId:'device:1',lastCollection:'lessons',lastRecordId:'lesson-1',verifiedHash:manifest.targetRecordHash,verifiedDocumentCount:1,verifiedActiveCount:1,verifiedTombstoneCount:0});const sourceDb=structuredClone(input.targetDb),targetDb=structuredClone(sourceDb);targetDb.lessons[0].name='updated';const revisions=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{}]));revisions.lessons['lesson-1']=1;const legacyVersionHash='legacy-v2',backupId='backup_456',drillId='drill_456',sourceHash=sha256Canonical(targetDb),collections=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(collection=>[collection,{count:collection==='lessons'?1:0,chunks:collection==='lessons'?1:0}])),backup={schema:'danbridge-immutable-migration-backup-v2',environment:'staging',state:'verified',backupId,sourceHash,verifiedHash:sourceHash,sourceVersionHash:legacyVersionHash,collectionOrder:[...FULL_RECORD_COLLECTIONS],chunkCount:1,recordCount:1,collections},restoreReceipt={schema:'danbridge-migration-restore-drill-v1',environment:'staging',state:'verified',persisted:true,drillId,sourceBackupId:backupId,sourceHash,restoredHash:sourceHash,recordCount:1,mainVersionHash:legacyVersionHash,mainUnchanged:true},next=buildStagingLivePreflight({environment:'staging',role:'owner',projectId:'danbridge-d8877-staging',sourceState:{db:sourceDb,revisions},targetDb,backup,restoreReceipt,legacyVersionHash,deviceId:'device',startSequence:2,readBudget:500,writeBudget:100,createdAt:'2026-08-15T02:00:00+08:00'});store.set('companies/danbridge/data/main',{db:targetDb,clientHash:legacyVersionHash});store.set(`stagingMigrationBackups/danbridge/runs/${backupId}`,backup);store.set(`stagingMigrationRestoreDrills/danbridge/runs/${drillId}`,restoreReceipt);const result=await adapter.activate(next.manifest),control=store.get('stagingLiveRecordControls/danbridge');assert.equal(result.kind,'rearmed');assert.equal(control.executionManifestHash,next.manifest.manifestHash);assert.equal(control.rootRevision,1);assert.equal(control.executionBaseRootRevision,1);assert.equal(control.confirmedOperationCount,0);assert.equal(control.state,'migrating')});
