import test from 'node:test';
import assert from 'node:assert/strict';
import {buildDurableOpenRecordSyncV1WriterCurrent} from '../js/core/cloud-record-sync-v1-writer-current.js';
import {buildRecordSyncV2FreezeRequest,buildRequestedRecordSyncV2FreezeControl} from '../js/core/cloud-record-sync-v2-freeze-control.js';
import {buildRecordSyncV1V2HardPauseTransition} from '../js/core/cloud-record-sync-v1-v2-hard-pause-transition.js';
import {
 RECORD_SYNC_V1_V2_HARD_PAUSE_DURABLE_TIME_POLICY,
 RECORD_SYNC_V1_V2_HARD_PAUSE_CHRONOLOGY_SCOPE,
 buildRecordSyncV1V2HardPausePersistencePlan,
 consumeRecordSyncV1V2HardPausePersistencePlan
} from '../js/core/cloud-record-sync-v1-v2-hard-pause-persistence.js';
import {
 RECORD_SYNC_V1_SAFETY_CONTROL_PATH,
 RECORD_SYNC_V1_RECORD_SYNC_CONTROL_PATH,
 RECORD_SYNC_V1_WRITER_CURRENT_PATH,
 RECORD_SYNC_V1_SAFETY_EVENT_PATH,
 RECORD_SYNC_V1_V2_HARD_PAUSE_RECEIPT_PATH,
 RECORD_SYNC_V2_FREEZE_CONTROL_PATH,
 RECORD_SYNC_V2_FREEZE_REQUEST_PATH,
 consumeFirebaseRecordSyncV1V2HardPauseCompletion,
 createFirebaseRecordSyncV1V2HardPauseBinder,
 createFirebaseRecordSyncV1V2HardPauseAdapter
} from '../js/core/firebase-record-sync-v1-v2-hard-pause-adapter.js';

const auditAt='2026-08-17T04:00:00.123456789Z',semantic={seconds:1786939200,nanoseconds:123456789},actor={uid:'owner-12345678',email:'owner@example.com',claims:{recordSyncV2CutoverOperator:true}};
const sourceControl=()=>({schema:'danbridge-record-sync-control-v1',environment:'staging',companyId:'danbridge',state:'active',activationEpoch:'active-epoch-12345',manifestHash:'a'.repeat(64),candidateEpoch:'candidate-epoch-123',candidateRevision:2,candidateSealHash:'b'.repeat(64),legacyVersionHash:'legacy-version-123',recordDataHash:'record-v1:'+'c'.repeat(64),roleEvidenceHash:'d'.repeat(64),backupId:'backup-source-123',restoreReceiptId:'restore-1234567',collectionCount:16,documentCount:1739,activeCount:19,tombstoneCount:1720,roleViewCount:4,readTakeover:true,writeTakeover:true,activatedAt:'2026-08-16T12:00:00+08:00'});
const safetyControl=()=>({schema:'danbridge-record-sync-safety-control-v1',environment:'staging',companyId:'danbridge',activationEpoch:'active-epoch-12345',state:'active',revision:3,lastEventId:'resume-event-12345',lastEventHash:'e'.repeat(64),readAllowed:true,writeAllowed:true,updatedAt:'2026-08-16T12:05:00+08:00'});
function fixture(){const safety=safetyControl(),recordSyncControl=sourceControl(),sourceExpected={recordSyncControl,safetyControl:safety,writerGeneration:1,minClientProtocolVersion:4,minClientReleaseId:'20.26.114',createdAt:safety.updatedAt},writerCurrent=buildDurableOpenRecordSyncV1WriterCurrent(sourceExpected),request=buildRecordSyncV2FreezeRequest({environment:'staging',companyId:'danbridge',freezeId:'freeze-12345678',activationEpoch:writerCurrent.activationEpoch,sourceWriterGeneration:1,targetWriterGeneration:2,targetV2Epoch:'v2-epoch-12345678',sourceWriterControlHash:writerCurrent.controlHash,minClientProtocolVersion:4,minClientReleaseId:'20.26.114',rulesetHash:'1'.repeat(64),preflightRecordDataHash:'record-v1:'+'2'.repeat(64),preflightRawDocumentRoot:'3'.repeat(64),preflightBackupId:'backup-freeze-123',preflightBackupManifestHash:'4'.repeat(64),createdAt:safety.updatedAt}),requestedControl=buildRequestedRecordSyncV2FreezeControl({request}),transitionPlan=buildRecordSyncV1V2HardPauseTransition({writerCurrent,safetyControl:safety,request,requestedControl,pausedAt:safety.updatedAt});return{transitionPlan,expected:{recordSyncControl,writerCurrent,safetyControl:safety}}}
const audit=(value,kind='normal',at=auditAt)=>kind==='event'?{...value,persistedAt:at,createdBy:actor.uid,createdByEmail:actor.email}:kind==='safety'?{...value,persistedAt:at,updatedBy:actor.uid,updatedByEmail:actor.email}:kind==='control'?{...value,persistedAt:at,activatedBy:actor.uid,activatedByEmail:actor.email}:{...value,persistedAt:at,persistedBy:actor.uid,persistedByEmail:actor.email};
const missingPersisted=({expected})=>({recordSyncControl:audit(expected.recordSyncControl,'control'),freezeRequest:null,freezeControl:null,pauseEvent:null,transitionReceipt:null,writerCurrent:audit(expected.writerCurrent),safetyControl:audit(expected.safetyControl,'safety')});
const replayPersisted=({expected,transitionPlan})=>({recordSyncControl:audit(expected.recordSyncControl,'control'),freezeRequest:audit(transitionPlan.request),freezeControl:audit(transitionPlan.requestedControl),pauseEvent:audit(transitionPlan.pauseEvent,'event'),transitionReceipt:audit(transitionPlan.transitionReceipt),writerCurrent:audit(transitionPlan.nextWriterCurrent),safetyControl:audit(transitionPlan.nextSafetyControl,'safety')});
const consumeExpected=plan=>({expectedState:plan.state,expectedPlanHash:plan.planHash,expectedFreezeId:plan.freezeId,expectedActivationEpoch:plan.activationEpoch,expectedTransitionPlanHash:plan.transitionPlanHash});

test('pure persistence只允許全missing create或六artifact exact audited replay',()=>{const input=fixture(),create=buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted:missingPersisted(input)}),createPayload=consumeRecordSyncV1V2HardPausePersistencePlan(create,consumeExpected(create));assert.equal(create.state,'create-required');assert.equal(create.writeCount,6);assert.equal(createPayload.writes.writerCurrent.state,'hard-paused');const replay=buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted:replayPersisted(input)});assert.equal(replay.state,'replayed');assert.equal(replay.writeCount,0);assert.deepEqual(consumeRecordSyncV1V2HardPausePersistencePlan(replay,consumeExpected(replay)).serverAudit,{persistedAt:auditAt,persistedBy:actor.uid,persistedByEmail:actor.email});assert.equal(RECORD_SYNC_V1_V2_HARD_PAUSE_DURABLE_TIME_POLICY,'immutable-core-time-equals-authoritative-w0-and-s0-time-server-audit-is-commit-time');assert.equal(RECORD_SYNC_V1_V2_HARD_PAUSE_CHRONOLOGY_SCOPE,'six-artifact-server-persistedAt-is-post-pause-minimum-not-legacy-core-createdAt');assert.equal(replay.chronologyScope,RECORD_SYNC_V1_V2_HARD_PAUSE_CHRONOLOGY_SCOPE);assert.throws(()=>consumeRecordSyncV1V2HardPausePersistencePlan(structuredClone(create),consumeExpected(create)),/capability/)});

test('partial、split audit、source race與future immutable time全部fail closed',()=>{const input=fixture(),partial=missingPersisted(input);partial.freezeRequest=audit(input.transitionPlan.request);assert.throws(()=>buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted:partial}),/partial/);const split=replayPersisted(input);split.pauseEvent={...split.pauseEvent,createdBy:'other-owner'};assert.throws(()=>buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted:split}),/split/);const race=missingPersisted(input);race.safetyControl={...race.safetyControl,revision:99};assert.throws(()=>buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted:race}),/safety/);const bad={...input.transitionPlan,request:{...input.transitionPlan.request,createdAt:'2026-08-17T12:05:00+08:00'}};assert.throws(()=>buildRecordSyncV1V2HardPausePersistencePlan({transitionPlan:bad,expected:input.expected,persisted:missingPersisted(input)}),/canonical|time policy/)});

test('F/K/P/H 16 bitmap與W/S mixed狀態只有全source或全target可接受',()=>{
 const input=fixture(),names=['freezeRequest','freezeControl','pauseEvent','transitionReceipt'],full=replayPersisted(input);
 for(let mask=0;mask<16;mask++){
  const persisted=missingPersisted(input);for(let index=0;index<4;index++)if(mask&(1<<index))persisted[names[index]]=full[names[index]];
  if(mask===0)assert.equal(buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted}).state,'create-required');
  else assert.throws(()=>buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted}),/partial|mismatch|無效/);
 }
 assert.equal(buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted:full}).state,'replayed');
 for(const persisted of [
  {...missingPersisted(input),writerCurrent:full.writerCurrent},
  {...missingPersisted(input),safetyControl:full.safetyControl},
  {...full,writerCurrent:missingPersisted(input).writerCurrent},
  {...full,safetyControl:missingPersisted(input).safetyControl}
 ])assert.throws(()=>buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted}),/mismatch|hard pause|safety|無效/);
});

test('durable hard pause只接受W0 revision1且K保持requested/zero sentinel',()=>{
 const input=fixture(),wrongRevision=missingPersisted(input);wrongRevision.writerCurrent={...wrongRevision.writerCurrent,revision:3};
 assert.throws(()=>buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted:wrongRevision}),/revision 1|genesis|canonical|無效/);
 const forged=replayPersisted(input);forged.freezeControl={...forged.freezeControl,phase:'paused'};
 assert.throws(()=>buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted:forged}),/requested|canonical|mismatch/);
 const forgedZero=replayPersisted(input);forgedZero.freezeControl={...forgedZero.freezeControl,hardPauseEventHash:'f'.repeat(64)};
 assert.throws(()=>buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted:forgedZero}),/canonical|requested|mismatch/);
});

function fake({throwAfterCommit=false,trusted=true}={}){const input=fixture(),store=new Map([[RECORD_SYNC_V1_RECORD_SYNC_CONTROL_PATH,{...input.expected.recordSyncControl,persistedAt:semantic,activatedBy:'seed-owner',activatedByEmail:actor.email}],[RECORD_SYNC_V1_WRITER_CURRENT_PATH,{...input.expected.writerCurrent,persistedAt:semantic,persistedBy:'seed-owner',persistedByEmail:actor.email}],[RECORD_SYNC_V1_SAFETY_CONTROL_PATH,{...input.expected.safetyControl,persistedAt:semantic,updatedBy:'seed-owner',updatedByEmail:actor.email}]]),transactions=[],fresh=[];let throws=throwAfterCommit;const adapter=createFirebaseRecordSyncV1V2HardPauseAdapter({environment:'staging',role:'owner',actor:{...actor,claims:{recordSyncV2CutoverOperator:trusted}},serverTimestamp:()=>semantic,getDocumentFromServer:async path=>{fresh.push(path);return store.get(path)??null},runTransaction:async callback=>{const events=[],pending=[];transactions.push(events);const result=await callback({get:async path=>{events.push(['get',path]);return store.get(path)??null},set:(path,value)=>{events.push(['set',path]);pending.push([path,value])}});for(const row of pending)store.set(...row);if(throws){throws=false;throw new Error('response loss')}return result}});return{input,adapter,store,transactions,fresh}}

test('adapter固定7 reads後原子6 writes；fresh readback與response-loss exact replay 0 writes',async()=>{const value=fake(),first=await value.adapter.execute(value.input);assert.equal(first.transactionState,'created');assert.equal(first.writeCount,6);assert.equal(first.hardPausePersistedAt,auditAt);assert.equal(first.chronologyScope,RECORD_SYNC_V1_V2_HARD_PAUSE_CHRONOLOGY_SCOPE);assert.deepEqual(value.transactions[0].map(row=>row[0]),[...Array(7).fill('get'),...Array(6).fill('set')]);assert.equal(value.fresh.length,7);assert.throws(()=>consumeFirebaseRecordSyncV1V2HardPauseCompletion(first),/capability/);assert.equal(value.adapter.consumeLocalCompletion(first).hardPausePersistedAt,auditAt);const replay=await value.adapter.execute(value.input);assert.equal(replay.transactionState,'replayed');assert.equal(replay.writeCount,0);assert.deepEqual(value.transactions[1].map(row=>row[0]),Array(7).fill('get'));const lost=fake({throwAfterCommit:true});await assert.rejects(()=>lost.adapter.execute(lost.input),/response loss/);const recovered=await lost.adapter.execute(lost.input);assert.equal(recovered.writeCount,0)});

test('adapter partial/tamper/非trusted/caller time欄在任何write前fail closed',async()=>{const partial=fake();partial.store.set('stagingRecordSyncV2FreezeRequests/danbridge/epochs/active-epoch-12345/freezes/freeze-12345678',{forged:true});await assert.rejects(()=>partial.adapter.execute(partial.input),/partial|exact core/);assert.equal(partial.transactions[0].some(row=>row[0]==='set'),false);const untrusted=fake({trusted:false});await assert.rejects(()=>untrusted.adapter.execute(untrusted.input),/trusted staging Owner/);assert.equal(untrusted.transactions.length,0);const extra=fake();await assert.rejects(()=>extra.adapter.execute({...extra.input,pausedAt:'9999-12-31T23:59:59Z'}),/fields invalid/);assert.equal(extra.transactions.length,0);let calls=0;const hostile={transitionPlan:untrusted.input.transitionPlan};Object.defineProperty(hostile,'expected',{enumerable:true,get(){calls++;return untrusted.input.expected}});await assert.rejects(()=>fake().adapter.execute(hostile),/data field/);assert.equal(calls,0)});

const emulatorHosts=Boolean(process.env.FIRESTORE_EMULATOR_HOST&&process.env.FIREBASE_AUTH_EMULATOR_HOST),emulatorRequired=process.env.DANBRIDGE_REQUIRE_V2_BINDER_EMULATOR==='1';
test('hard-pause binder真Auth/Firestore原子六寫：primary與backup可用，普通Owner/teacher/partial/claim revoke拒絕',{skip:!emulatorHosts&&!emulatorRequired},async()=>{
 assert.equal(emulatorHosts,true,'hard-pause integration requires Auth and Firestore emulators');
 const [{initializeTestEnvironment},{initializeApp:initializeAdminApp,deleteApp:deleteAdminApp},{getAuth:getAdminAuth},{initializeApp:initializeWebApp,deleteApp:deleteWebApp},{getAuth,connectAuthEmulator,signInWithEmailAndPassword,signOut},{connectFirestoreEmulator,doc,getDocFromServer,getFirestore,runTransaction,serverTimestamp,setDoc,Timestamp}]=await Promise.all([import('@firebase/rules-unit-testing'),import('firebase-admin/app'),import('firebase-admin/auth'),import('firebase/app'),import('firebase/auth'),import('firebase/firestore')]);
 const projectId='danbridge-rules-test',suffix=Date.now().toString(36),password='Hard-pause-12345!',primary={uid:`hard-primary-${suffix}`,email:'a0965487920@gmail.com'},backup={uid:`hard-backup-${suffix}`,email:'catherine890202@gmail.com'},teacher={uid:`hard-teacher-${suffix}`,email:`hard-teacher-${suffix}@example.com`},adminApp=initializeAdminApp({projectId},`hard-pause-admin-${suffix}`),adminAuth=getAdminAuth(adminApp),webApp=initializeWebApp({apiKey:'demo-key',authDomain:'localhost',projectId},`hard-pause-web-${suffix}`),auth=getAuth(webApp),firestore=getFirestore(webApp),environment=await initializeTestEnvironment({projectId});
 connectAuthEmulator(auth,'http://127.0.0.1:9099',{disableWarnings:true});connectFirestoreEmulator(firestore,'127.0.0.1',8080);
 const input=fixture(),binder=createFirebaseRecordSyncV1V2HardPauseBinder({firestore,auth,expectedProjectId:projectId}),seed=async({activationEpoch=input.transitionPlan.activationEpoch}={})=>{await environment.clearFirestore();await environment.withSecurityRulesDisabled(async context=>{const db=context.firestore(),at=Timestamp.now();await setDoc(doc(db,RECORD_SYNC_V1_RECORD_SYNC_CONTROL_PATH),{...input.expected.recordSyncControl,activationEpoch,persistedAt:at,activatedBy:'seed-admin',activatedByEmail:primary.email});await setDoc(doc(db,RECORD_SYNC_V1_WRITER_CURRENT_PATH),{...input.expected.writerCurrent,activationEpoch,persistedAt:at,persistedBy:'seed-admin',persistedByEmail:primary.email});await setDoc(doc(db,RECORD_SYNC_V1_SAFETY_CONTROL_PATH),{...input.expected.safetyControl,activationEpoch,persistedAt:at,updatedBy:'seed-admin',updatedByEmail:primary.email});await setDoc(doc(db,`companyAccess/${backup.email}`),{companyId:'danbridge',role:'owner',active:true});await setDoc(doc(db,`companyAccess/${teacher.email}`),{companyId:'danbridge',role:'teacher',active:true,teacherId:'teacher-hard-pause'})})};
 const directHardPause=async({activationEpoch=input.transitionPlan.activationEpoch,mutate})=>{await seed({activationEpoch});const plan=buildRecordSyncV1V2HardPausePersistencePlan({...input,persisted:missingPersisted(input)}),hidden=consumeRecordSyncV1V2HardPausePersistencePlan(plan,consumeExpected(plan)),writes=structuredClone(hidden.writes);for(const key of ['freezeRequest','freezeControl','pauseEvent','transitionReceipt','writerCurrent','safetyControl'])writes[key].activationEpoch=activationEpoch;mutate(writes);const epoch=writes.freezeRequest.activationEpoch,freezeId=writes.freezeRequest.freezeId,paths={freezeRequest:RECORD_SYNC_V2_FREEZE_REQUEST_PATH(epoch,freezeId),freezeControl:RECORD_SYNC_V2_FREEZE_CONTROL_PATH(epoch,freezeId),pauseEvent:RECORD_SYNC_V1_SAFETY_EVENT_PATH(epoch,writes.pauseEvent.eventId),transitionReceipt:RECORD_SYNC_V1_V2_HARD_PAUSE_RECEIPT_PATH(epoch,freezeId),writerCurrent:RECORD_SYNC_V1_WRITER_CURRENT_PATH,safetyControl:RECORD_SYNC_V1_SAFETY_CONTROL_PATH};return runTransaction(firestore,async tx=>{const stamp=serverTimestamp();for(const key of Object.keys(paths)){const identity=key==='pauseEvent'?{createdBy:primary.uid,createdByEmail:primary.email}:key==='safetyControl'?{updatedBy:primary.uid,updatedByEmail:primary.email}:{persistedBy:primary.uid,persistedByEmail:primary.email};tx.set(doc(firestore,paths[key]),{...writes[key],persistedAt:stamp,...identity},{merge:false})}})};
 try{
  for(const user of [primary,backup,teacher])await adminAuth.createUser({uid:user.uid,email:user.email,password,emailVerified:true});
  await seed();await adminAuth.setCustomUserClaims(primary.uid,{recordSyncV2CutoverOperator:true});await signInWithEmailAndPassword(auth,primary.email,password);const first=await binder.execute(input);assert.equal(first.transactionState,'created');assert.equal(first.writeCount,6);assert.equal(first.transactionReadCount,7);assert.equal((await getDocFromServer(doc(firestore,RECORD_SYNC_V2_FREEZE_REQUEST_PATH(input.transitionPlan.activationEpoch,input.transitionPlan.request.freezeId)))).data().persistedAt instanceof Timestamp,true);const replay=await binder.execute(input);assert.equal(replay.writeCount,0);
  await seed();await signOut(auth);await adminAuth.setCustomUserClaims(backup.uid,{recordSyncV2CutoverOperator:true});await signInWithEmailAndPassword(auth,backup.email,password);assert.equal((await binder.execute(input)).writeCount,6);
  await seed();await signOut(auth);await adminAuth.setCustomUserClaims(primary.uid,{recordSyncV2CutoverOperator:false});await signInWithEmailAndPassword(auth,primary.email,password);await assert.rejects(()=>binder.execute(input),/fresh trusted operator token/);
  await signOut(auth);await adminAuth.setCustomUserClaims(teacher.uid,{recordSyncV2CutoverOperator:true});await signInWithEmailAndPassword(auth,teacher.email,password);await assert.rejects(()=>binder.execute(input));
  await seed();await signOut(auth);await adminAuth.setCustomUserClaims(primary.uid,{recordSyncV2CutoverOperator:true});await signInWithEmailAndPassword(auth,primary.email,password);await environment.withSecurityRulesDisabled(async context=>{const db=context.firestore(),at=Timestamp.now();await setDoc(doc(db,RECORD_SYNC_V2_FREEZE_REQUEST_PATH(input.transitionPlan.activationEpoch,input.transitionPlan.request.freezeId)),{...input.transitionPlan.request,persistedAt:at,persistedBy:primary.uid,persistedByEmail:primary.email})});await assert.rejects(()=>binder.execute(input),/partial/);
  const denied=promise=>assert.rejects(promise,error=>error?.code==='permission-denied');
  await denied(directHardPause({mutate:writes=>{const value=writes.freezeRequest.activationEpoch;writes.freezeRequest.freezeId=value;writes.freezeControl.freezeId=value;writes.transitionReceipt.freezeId=value;writes.writerCurrent.currentFreezeId=value}}));
  await denied(directHardPause({mutate:writes=>{const value='short-1';writes.freezeRequest.freezeId=value;writes.freezeControl.freezeId=value;writes.transitionReceipt.freezeId=value;writes.writerCurrent.currentFreezeId=value}}));
  await denied(directHardPause({activationEpoch:'bad epoch',mutate:()=>{}}));
  await denied(directHardPause({mutate:writes=>{writes.freezeRequest.targetV2Epoch='short';writes.freezeControl.targetV2Epoch='short';writes.transitionReceipt.targetV2Epoch='short'}}));
  await denied(directHardPause({mutate:writes=>{const zero='record-v1:'+'0'.repeat(64);writes.freezeRequest.preflightRecordDataHash=zero;writes.pauseEvent.safeRecordDataHash=zero}}));
 }finally{await signOut(auth).catch(()=>{});await Promise.allSettled([primary,backup,teacher].map(user=>adminAuth.deleteUser(user.uid)));await environment.cleanup();await deleteWebApp(webApp);await deleteAdminApp(adminApp)}
});
