import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';
import {FIREBASE_ADMIN_PRODUCTION_PROJECT_ID,FIREBASE_ADMIN_RULES_TEST_PROJECT_ID,FIREBASE_ADMIN_STAGING_IAM_ALLOWLIST,FIREBASE_ADMIN_STAGING_IAM_RECEIPT_SCHEMA,FIREBASE_ADMIN_STAGING_PROJECT_ID,assertFirebaseAdminStagingIdentityBoundary,verifyFirebaseAdminStagingIamReceiptShape} from '../js/core/firebase-admin-staging-identity-boundary.js';

const app=projectId=>({options:{projectId}}),firestore=owner=>({app:owner});
const body=()=>({schema:FIREBASE_ADMIN_STAGING_IAM_RECEIPT_SCHEMA,state:'reviewed-immutable',environment:'staging',projectId:FIREBASE_ADMIN_STAGING_PROJECT_ID,projectNumber:'123456789012',serviceAccountEmail:'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com',serviceAccountUniqueId:'123456789012345678901',credentialSource:'explicit-service-account-metadata',principalType:'serviceAccount',iamPolicyEtag:'BwYReviewed123',requiredPermissions:['datastore.entities.create','datastore.entities.get','datastore.entities.list','datastore.entities.update'],condition:{title:'staging-v2-only',expression:"resource.name.startsWith('projects/danbridge-d8877-staging/')"},reviewedAt:'2026-08-19T12:00:00Z',reviewer:{id:'spark-review-20260819',method:'spark-reviewed-read-only-iam-inventory'}});
const receipt=()=>{const value=body();return{...value,receiptHash:sha256Canonical(value)}};
const deepFreeze=value=>{for(const item of Object.values(value))if(item&&typeof item==='object')deepFreeze(item);return Object.freeze(value)};
function emulator(overrides={}){const owner=app(FIREBASE_ADMIN_RULES_TEST_PROJECT_ID),db=firestore(owner);return{mode:'emulator',app:owner,firestore:db,nativeFirestore:db,expectedProjectId:FIREBASE_ADMIN_RULES_TEST_PROJECT_ID,emulatorHost:'127.0.0.1:8080',credential:null,iamReceipt:null,...overrides}}
function staging(overrides={}){const owner=app(FIREBASE_ADMIN_STAGING_PROJECT_ID),db=firestore(owner);return{mode:'staging',app:owner,firestore:db,nativeFirestore:db,expectedProjectId:FIREBASE_ADMIN_STAGING_PROJECT_ID,emulatorHost:null,credential:{clientEmail:'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com',projectId:FIREBASE_ADMIN_STAGING_PROJECT_ID,source:'explicit-service-account-metadata'},iamReceipt:deepFreeze(receipt()),...overrides}}

test('constants與初始staging allowlist固定為空且不可修改',()=>{assert.equal(FIREBASE_ADMIN_PRODUCTION_PROJECT_ID,'danbridge-d8877');assert.equal(FIREBASE_ADMIN_RULES_TEST_PROJECT_ID,'danbridge-rules-test');assert.equal(FIREBASE_ADMIN_STAGING_PROJECT_ID,'danbridge-d8877-staging');assert.deepEqual(FIREBASE_ADMIN_STAGING_IAM_ALLOWLIST,[]);assert.equal(Object.isFrozen(FIREBASE_ADMIN_STAGING_IAM_ALLOWLIST),true);assert.throws(()=>FIREBASE_ADMIN_STAGING_IAM_ALLOWLIST.push('a'.repeat(64)),TypeError)});
test('現有rules-test emulator exact identity通過且不接受credential/receipt',()=>{assert.deepEqual(assertFirebaseAdminStagingIdentityBoundary(emulator()),{mode:'emulator',projectId:FIREBASE_ADMIN_RULES_TEST_PROJECT_ID});for(const row of [emulator({emulatorHost:''}),emulator({emulatorHost:null}),emulator({expectedProjectId:FIREBASE_ADMIN_STAGING_PROJECT_ID}),emulator({credential:{}}),emulator({iamReceipt:{}})])assert.throws(()=>assertFirebaseAdminStagingIdentityBoundary(row),/blocked/)});
test('production default unknown與錯誤mode全部拒絕',()=>{for(const projectId of [FIREBASE_ADMIN_PRODUCTION_PROJECT_ID,'production','default','foreign-project']){const owner=app(projectId),db=firestore(owner);assert.throws(()=>assertFirebaseAdminStagingIdentityBoundary({...emulator(),app:owner,firestore:db,nativeFirestore:db,expectedProjectId:projectId}),/blocked|project identity invalid/)}for(const mode of ['production','default','unknown',''])assert.throws(()=>assertFirebaseAdminStagingIdentityBoundary({...emulator(),mode}),/mode blocked/)});
test('same native App/Firestore identity、own data descriptor、symbol與extra fail closed getter0',()=>{const base=emulator(),other=firestore(base.app);assert.throws(()=>assertFirebaseAdminStagingIdentityBoundary({...base,nativeFirestore:other}),/native identity/);const foreignApp=app(FIREBASE_ADMIN_RULES_TEST_PROJECT_ID),foreignDb=firestore(foreignApp);assert.throws(()=>assertFirebaseAdminStagingIdentityBoundary({...base,firestore:foreignDb,nativeFirestore:foreignDb}),/app identity/);for(const hostile of [{...base,extra:true},Object.assign({...base},{[Symbol('x')]:true})])assert.throws(()=>assertFirebaseAdminStagingIdentityBoundary(hostile),/fields/);let calls=0;const accessor={...base};Object.defineProperty(accessor,'mode',{enumerable:true,get(){calls++;return'emulator'}});assert.throws(()=>assertFirebaseAdminStagingIdentityBoundary(accessor),/data field/);assert.equal(calls,0)});
test('IAM receipt canonical hash、exact descriptors與deep frozen output',()=>{const value=receipt(),verified=verifyFirebaseAdminStagingIamReceiptShape(value);assert.equal(verified.receiptHash,value.receiptHash);assert.equal(Object.isFrozen(verified),true);assert.equal(Object.isFrozen(verified.requiredPermissions),true);assert.equal(Object.isFrozen(verified.condition),true);for(const bad of [{...value,receiptHash:'a'.repeat(64)},{...value,projectId:FIREBASE_ADMIN_PRODUCTION_PROJECT_ID},{...value,requiredPermissions:['*']},{...value,extra:true}])assert.throws(()=>verifyFirebaseAdminStagingIamReceiptShape(bad),/integrity|fields|item/)});
test('staging allowlist空時synthetic完整receipt永遠fail closed',()=>{assert.throws(()=>assertFirebaseAdminStagingIdentityBoundary(staging()),/allowlist blocked/)});
test('staging拒絕emulator、ADC/env/key/privateKey與模糊principal',()=>{const attempts=[staging({emulatorHost:'127.0.0.1:8080'}),staging({credential:{clientEmail:'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com',projectId:FIREBASE_ADMIN_STAGING_PROJECT_ID,source:'application-default-credentials'}}),staging({credential:{clientEmail:'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com',projectId:FIREBASE_ADMIN_STAGING_PROJECT_ID,source:'env'}}),staging({credential:{clientEmail:'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com',projectId:FIREBASE_ADMIN_STAGING_PROJECT_ID,source:'key-file',privateKey:'secret'}}),staging({credential:{clientEmail:'owner@example.com',projectId:FIREBASE_ADMIN_STAGING_PROJECT_ID,source:'explicit-service-account-metadata'}})];for(const row of attempts)assert.throws(()=>assertFirebaseAdminStagingIdentityBoundary(row),/blocked|fields/)});
test('IAM receipt clone、wildcard、wrong principal/hash拒絕',()=>{assert.throws(()=>assertFirebaseAdminStagingIdentityBoundary(staging({iamReceipt:structuredClone(staging().iamReceipt)})),/immutable original/);const wildcard=receipt();wildcard.requiredPermissions=['*'];wildcard.receiptHash=sha256Canonical(Object.fromEntries(Object.entries(wildcard).filter(([key])=>key!=='receiptHash')));assert.throws(()=>assertFirebaseAdminStagingIdentityBoundary(staging({iamReceipt:deepFreeze(wildcard)})),/item invalid/);const wrong=receipt();wrong.serviceAccountEmail='other@danbridge-d8877-staging.iam.gserviceaccount.com';wrong.receiptHash=sha256Canonical(Object.fromEntries(Object.entries(wrong).filter(([key])=>key!=='receiptHash')));assert.throws(()=>assertFirebaseAdminStagingIdentityBoundary(staging({iamReceipt:deepFreeze(wrong)})),/allowlist blocked/)});
test('module純本機且不含SDK、fs、env、auth、network、subprocess或write能力',async()=>{const source=await readFile(new URL('../js/core/firebase-admin-staging-identity-boundary.js',import.meta.url),'utf8');assert.doesNotMatch(source,/firebase-admin|node:fs|node:crypto|child_process|process\s*\.|import\.meta\.env|fetch\s*\(|https?\s*[:.(]|applicationDefault|privateKey|keyFile|writeFile|appendFile|runTransaction|\.set\s*\(|\.delete\s*\(/)});
