import test from 'node:test';
import assert from 'node:assert/strict';
import {createFirebaseRecordSyncCandidateAdapter} from '../js/core/firebase-record-sync-candidate-adapter.js';

function source(legacy='legacy-v1'){const store=new Map([['companies/danbridge/data/main',{clientHash:legacy}]]),events=[];return{store,events,getDocument:async path=>snapshot(store.get(path)),runTransaction:async callback=>{const writes=[],transaction={get:async path=>{events.push(`get:${path}`);return snapshot(store.get(path))},set:(path,value)=>{events.push(`set:${path}`);writes.push([path,structuredClone(value)])}};const result=await callback(transaction);for(const [path,value] of writes)store.set(path,value);return result}}}
const snapshot=data=>({exists:()=>data!==undefined,data:()=>structuredClone(data)});
const adapter=(db,overrides={})=>createFirebaseRecordSyncCandidateAdapter({getDocument:db.getDocument,runTransaction:db.runTransaction,serverTimestamp:()=>({server:true}),actor:{uid:'owner-1',email:'OWNER@EXAMPLE.COM'},environment:'staging',role:'owner',...overrides});
const openInput={candidateEpoch:'candidate-epoch-1',legacyVersionHash:'legacy-v1',createdAt:'2026-08-15T01:00:00+08:00'};
const sealInput={candidateEpoch:'candidate-epoch-1',legacyVersionHash:'legacy-v1',recordDataHash:'record-v1:'+'a'.repeat(64),documentCount:3,activeCount:2,tombstoneCount:1,sealedAt:'2026-08-15T01:05:00+08:00'};

test('Owner 先原子開啟候選，再原子封存且完整保留 actor 稽核',async()=>{const db=source(),first=await adapter(db).open(openInput),sealed=await adapter(db).seal(sealInput),readback=await adapter(db).read();assert.equal(first.kind,'opened');assert.equal(sealed.kind,'sealed');assert.equal(readback.state,'sealed');assert.equal(readback.sealHash,sealed.control.sealHash);assert.equal(db.store.get(sealed.path).updatedByEmail,'owner@example.com');assert.deepEqual(db.store.get(sealed.path).persistedAt,{server:true})});
test('回應遺失重送 open 或 seal 都是 duplicate，沒有第二次寫入',async()=>{const db=source();await adapter(db).open(openInput);const openWrites=db.events.filter(row=>row.startsWith('set:')).length;assert.equal((await adapter(db).open(openInput)).kind,'duplicate');assert.equal(db.events.filter(row=>row.startsWith('set:')).length,openWrites);await adapter(db).seal(sealInput);const sealedWrites=db.events.filter(row=>row.startsWith('set:')).length;assert.equal((await adapter(db).seal(sealInput)).kind,'duplicate');assert.equal(db.events.filter(row=>row.startsWith('set:')).length,sealedWrites)});
test('sealed 候選換新 epoch 才可重新 open，重開後重新整理可冪等續傳',async()=>{const db=source();await adapter(db).open(openInput);await adapter(db).seal(sealInput);await assert.rejects(adapter(db).open(openInput),/重新開啟證據無效/);const next={...openInput,candidateEpoch:'candidate-epoch-2',createdAt:'2026-08-15T01:10:00+08:00'},reopened=await adapter(db).open(next);assert.equal(reopened.kind,'reopened');assert.equal(reopened.control.revision,3);assert.equal((await adapter(db).open(next)).kind,'duplicate');await assert.rejects(adapter(db).seal({...sealInput,candidateEpoch:'candidate-epoch-1'}),/identity 已改變/)});
test('封存後 legacy 換版會用新版本重開，舊版本與舊 epoch 都不能再封存',async()=>{const db=source();await adapter(db).open(openInput);await adapter(db).seal(sealInput);db.store.set('companies/danbridge/data/main',{clientHash:'legacy-v2'});const next={candidateEpoch:'candidate-epoch-v2',legacyVersionHash:'legacy-v2',createdAt:'2026-08-15T01:11:00+08:00'},reopened=await adapter(db).open(next);assert.equal(reopened.kind,'reopened');assert.equal(reopened.control.legacyVersionHash,'legacy-v2');assert.equal(reopened.control.revision,3);assert.equal((await adapter(db).open(next)).kind,'duplicate');await assert.rejects(adapter(db).seal({...sealInput,candidateEpoch:'candidate-epoch-v2'}),/版本已改變|identity 已改變/);await assert.rejects(adapter(db).seal({...sealInput,legacyVersionHash:'legacy-v2'}),/identity 已改變/)});
test('legacy 版本改變、已啟用、非 Owner 或 production 全部零候選寫入',async()=>{for(const db of [source('changed'),source()]){if(db.store.get('companies/danbridge/data/main').clientHash==='legacy-v1')db.store.set('stagingRecordSyncControls/danbridge',{state:'active'});await assert.rejects(adapter(db).open(openInput),/版本已改變|已啟用/);assert.equal(db.store.has('stagingRecordSyncCandidateControls/danbridge'),false)}const db=source();await assert.rejects(adapter(db,{role:'teacher'}).open(openInput),/只允許 staging Owner/);await assert.rejects(adapter(db,{environment:'production'}).open(openInput),/只允許 staging Owner/)});
