import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {
 RECORD_SYNC_V2_TAKEOVER_CANDIDATE_V2_ADAPTER_SCOPE,
 RECORD_SYNC_V2_TAKEOVER_CANDIDATE_V2_CI_ACTOR,
 RECORD_SYNC_V2_TAKEOVER_CANDIDATE_V2_CONTROL_PATH,
 RECORD_SYNC_V2_TAKEOVER_CANDIDATE_V2_HEAD_PATH,
 RECORD_SYNC_V2_TAKEOVER_CANDIDATE_V2_PRODUCTION_BLOCKER,
 consumeFirebaseRecordSyncV2TakeoverCandidateV2Completion,
 createFirebaseRecordSyncV2TakeoverCandidateV2Adapter,
 createFirebaseRecordSyncV2TakeoverCandidateV2AdminBinder,
 normalizeFirebaseRecordSyncV2TakeoverCandidateV2Snapshot
} from '../js/core/firebase-record-sync-v2-takeover-candidate-v2-adapter.js';

const manualG=()=>({state:'complete-confirmed',transactionState:'replayed',scope:'manual',environment:'staging',companyId:'danbridge',sourceV1ActivationEpoch:'epoch-v1-12345678',sourceFreezeId:'freeze-12345678',targetV2Epoch:'epoch-v2-12345678',seedId:'v2-genesis:'+'a'.repeat(64),parentFrozenSourceProofHash:'b'.repeat(64),seedManifestHash:'c'.repeat(64),durableManifestHash:'d'.repeat(64),readbackReceiptHash:'e'.repeat(64),authorityHash:'f'.repeat(64),authorityAuditHash:'1'.repeat(64),persistedAt:'2026-08-17T03:24:00.123456789Z',writeCount:0});
const manualR=()=>({state:'complete-confirmed',transactionState:'replayed',scope:'manual',environment:'staging',companyId:'danbridge',sourceV1ActivationEpoch:'epoch-v1-12345678',sourceFreezeId:'freeze-12345678',targetV2Epoch:'epoch-v2-12345678',seedId:'v2-genesis:'+'a'.repeat(64),reservationAuthorityHash:'2'.repeat(64),reservationAuthorityAuditHash:'3'.repeat(64),registrationHash:'4'.repeat(64),registrationAuditHash:'5'.repeat(64),batchSetSealHash:'6'.repeat(64),batchSetSealAuditHash:'7'.repeat(64),strictReadbackReceiptHash:'8'.repeat(64),strictReadbackReceiptAuditHash:'9'.repeat(64),receiptHash:'a'.repeat(64),receiptAuditHash:'b'.repeat(64),persistedAt:'2026-08-17T03:29:00.123456789Z',writeCount:0});

test('candidate-v2 adapter只接受global G3+R3.5 capabilities，manual/clone在任何I/O前拒',async()=>{let reads=0,transactions=0,writes=0;const adapter=createFirebaseRecordSyncV2TakeoverCandidateV2Adapter({getDocumentFromServer:async()=>{reads++;return null},runTransaction:async callback=>{transactions++;return callback({get:async()=>null,set(){writes++}})},serverTimestamp:()=>({seconds:1,nanoseconds:2})});await assert.rejects(adapter.execute(manualG(),manualR()),/native G3 completion invalid/);assert.deepEqual({reads,transactions,writes},{reads:0,transactions:0,writes:0});assert.throws(()=>consumeFirebaseRecordSyncV2TakeoverCandidateV2Completion({}),/native candidate-v2 completion invalid/);assert.match(adapter.scope,/admin-ci-emulator/);assert.equal(typeof adapter.consumeLocalCompletion,'function');assert.deepEqual(RECORD_SYNC_V2_TAKEOVER_CANDIDATE_V2_CI_ACTOR,{uid:'record-sync-v2-ci-emulator',email:'record-sync-v2-ci-emulator@danbridge.invalid'});assert.equal(Object.isFrozen(RECORD_SYNC_V2_TAKEOVER_CANDIDATE_V2_CI_ACTOR),true);assert.match(RECORD_SYNC_V2_TAKEOVER_CANDIDATE_V2_PRODUCTION_BLOCKER,/allowlist-not-yet-wired/)});

test('candidate-v2 fixed paths與Admin-only constructor/app-project guard fail closed',async()=>{assert.equal(RECORD_SYNC_V2_TAKEOVER_CANDIDATE_V2_CONTROL_PATH('epoch-v2-12345678'),'stagingRecordSyncV2TakeoverCandidateControls/danbridge/epochs/epoch-v2-12345678');assert.equal(RECORD_SYNC_V2_TAKEOVER_CANDIDATE_V2_HEAD_PATH('epoch-v2-12345678'),'stagingActiveRecordV2Heads/danbridge/epochs/epoch-v2-12345678');assert.match(RECORD_SYNC_V2_TAKEOVER_CANDIDATE_V2_ADAPTER_SCOPE,/six-fixed-document/);const base={getDocumentFromServer:async()=>null,runTransaction:async()=>{},serverTimestamp:()=>null};assert.throws(()=>createFirebaseRecordSyncV2TakeoverCandidateV2Adapter({...base,getDocument:base.getDocumentFromServer,getDocumentFromServer:undefined}),/config fields invalid/);assert.equal('createFirebaseRecordSyncV2TakeoverCandidateV2Binder' in await import('../js/core/firebase-record-sync-v2-takeover-candidate-v2-adapter.js'),false);const app={options:{projectId:'danbridge-rules-test'}},firestore={};assert.throws(()=>createFirebaseRecordSyncV2TakeoverCandidateV2AdminBinder({app,firestore,expectedProjectId:'danbridge-rules-test'}),/Admin App\/Firestore identity/);let calls=0,hostile={app,firestore,expectedProjectId:'danbridge-rules-test'};Object.defineProperty(hostile,'firestore',{enumerable:true,get(){calls++;return firestore}});assert.throws(()=>createFirebaseRecordSyncV2TakeoverCandidateV2AdminBinder(hostile),/data field/);assert.equal(calls,0)});

test('candidate-v2 generic config與snapshot normalization全程descriptor-safe getter0',()=>{const base={getDocumentFromServer:async()=>null,runTransaction:async()=>{},serverTimestamp:()=>null};let configCalls=0;const hostileConfig={...base};Object.defineProperty(hostileConfig,'getDocumentFromServer',{enumerable:true,get(){configCalls++;return base.getDocumentFromServer}});assert.throws(()=>createFirebaseRecordSyncV2TakeoverCandidateV2Adapter(hostileConfig),/own enumerable data field/);assert.equal(configCalls,0);assert.throws(()=>createFirebaseRecordSyncV2TakeoverCandidateV2Adapter({...base,cachedGet:async()=>null}),/config fields invalid/);assert.throws(()=>createFirebaseRecordSyncV2TakeoverCandidateV2Adapter({...base,beforePersistence:null}),/fixed Admin I\/O/);let existsCalls=0;const snapshot={data(){return{state:'durable'}}};Object.defineProperty(snapshot,'exists',{enumerable:true,get(){existsCalls++;throw new Error('must not read exists')}});assert.deepEqual(normalizeFirebaseRecordSyncV2TakeoverCandidateV2Snapshot(snapshot),{state:'durable'});assert.equal(existsCalls,0);let dataCalls=0;const hostileSnapshot={};Object.defineProperty(hostileSnapshot,'data',{enumerable:true,get(){dataCalls++;return()=>({})}});assert.throws(()=>normalizeFirebaseRecordSyncV2TakeoverCandidateV2Snapshot(hostileSnapshot),/data method unsafe/);assert.equal(dataCalls,0);assert.equal(normalizeFirebaseRecordSyncV2TakeoverCandidateV2Snapshot({data(){return undefined}}),null)});

test('candidate-v2 dependency graph不匯入Web Auth/Firestore、old candidate/replayPlan/raw R/D0/intent/active/runtime',async()=>{const pure=await readFile(new URL('../js/core/cloud-record-sync-v2-takeover-candidate-v2.js',import.meta.url),'utf8'),adapter=await readFile(new URL('../js/core/firebase-record-sync-v2-takeover-candidate-v2-adapter.js',import.meta.url),'utf8'),combined=pure+'\n'+adapter;for(const forbidden of ["from 'firebase/firestore'",'firebase-record-sync-v2-trusted-cutover-operator.js','cloud-record-sync-v2-takeover-candidate.js','firebase-record-sync-v2-takeover-candidate-adapter.js','cloud-record-sync-v2-change-reservation-authority.js','cloud-record-sync-v2-deployment-gate-source-attestation.js','cloud-record-sync-v2-activation-cutover-intent.js','cloud-record-sync-control.js','cloud-active-record-save-plan.js'])assert.equal(combined.includes(forbidden),false,forbidden);assert.equal(combined.includes('replayPlan'),false);assert.equal(combined.includes('onAuthStateChanged'),false);assert.match(adapter,/firebase-admin\/firestore/);assert.match(adapter,/createFirebaseRecordSyncV2TakeoverCandidateV2AdminBinder/)});
