import test from 'node:test';
import assert from 'node:assert/strict';
import {createFirebaseCallableHttpClient} from '../js/core/firebase-callable-http-client.js';

const user={uid:'scheduler-user-12345',email:'aa0966626336@gmail.com',emailVerified:true};
function fixture(overrides={}){let current=user,sent=null,force=null;const client=createFirebaseCallableHttpClient({projectId:'danbridge-d8877-staging',functionName:'stagingSchedulerOperation',getCurrentUser:()=>current,getIdToken:async(_user,value)=>{force=value;return'id-token-12345'},getLimitedUseAppCheckToken:async()=>'limited-app-check-12345',fetch:async(url,options)=>{sent={url,options};return{status:200,text:async()=>JSON.stringify({data:{state:'committed'}})}},timeoutMs:60000,...overrides});return{client,sent:()=>sent,force:()=>force,setUser:value=>current=value}}

test('預取 limited-use token 以官方 callable 格式直送同一受保護 Function',async()=>{const f=fixture(),result=await f.client.call({requestId:'request-12345'}),sent=f.sent();assert.equal(result.data.state,'committed');assert.equal(f.force(),false);assert.equal(f.client.endpoint,'https://asia-east1-danbridge-d8877-staging.cloudfunctions.net/stagingSchedulerOperation');assert.equal(sent.options.method,'POST');assert.equal(sent.options.headers.authorization,'Bearer id-token-12345');assert.equal(sent.options.headers['x-firebase-appcheck'],'limited-app-check-12345');assert.deepEqual(JSON.parse(sent.options.body),{data:{requestId:'request-12345'}});assert.equal(sent.options.credentials,'omit');assert.equal(sent.options.cache,'no-store')});
test('只允許精確 staging/production 排課 Function 配對',()=>{for(const [projectId,functionName] of [['other','stagingSchedulerOperation'],['danbridge-d8877','stagingSchedulerOperation'],['danbridge-d8877-staging','productionSchedulerOperation']])assert.throws(()=>createFirebaseCallableHttpClient({projectId,functionName,getCurrentUser:()=>user,getIdToken:async()=>'',getLimitedUseAppCheckToken:async()=>'',fetch:async()=>{},timeoutMs:60000}),/設定無效/)});
test('token 前後身分變更與 callable 錯誤都 fail closed',async()=>{let current=user;const changed=fixture({getCurrentUser:()=>current,getIdToken:async()=>{current={...user,uid:'other-user-12345'};return'id-token-12345'}});await assert.rejects(()=>changed.client.call({}),/身分已變更/);const blocked=fixture({fetch:async()=>({status:400,text:async()=>JSON.stringify({error:{status:'FAILED_PRECONDITION',message:'blocked'}})})});await assert.rejects(()=>blocked.client.call({}),error=>error.code==='functions/failed-precondition'&&error.message==='blocked')});
test('網路中斷與逾時保留 queue 可重試錯誤碼',async()=>{const unavailable=fixture({fetch:async()=>{throw new TypeError('offline')}});await assert.rejects(()=>unavailable.client.call({}),error=>error.code==='functions/unavailable');const timeout=fixture({fetch:async()=>{const error=new Error('aborted');error.name='AbortError';throw error}});await assert.rejects(()=>timeout.client.call({}),error=>error.code==='functions/deadline-exceeded')});
