import test from 'node:test';
import assert from 'node:assert/strict';
import {deleteApp,initializeApp} from 'firebase-admin/app';
import {getFirestore} from 'firebase-admin/firestore';
import {createFirebaseStagingV2SupervisorJournal} from '../js/core/firebase-staging-v2-supervisor-journal.js';

let fixtureSequence=0;
function fake(){const app=initializeApp({projectId:'danbridge-rules-test'},`supervisor-journal-test-${++fixtureSequence}`),firestore=getFirestore(app),rows=new Map(),calls=[];const collectionPath='stagingRecordSyncV2SupervisorJournals/danbridge/runs/run_12345678/entries';firestore.collection=function(path){calls.push(['collection',path]);return{doc(id){return{async create(value){calls.push(['create',id]);if(rows.has(id))throw new Error('already exists');rows.set(id,structuredClone(value))},async get(){calls.push(['get',id]);return{exists:rows.has(id),data:()=>structuredClone(rows.get(id))}}}},orderBy(field,direction){calls.push(['orderBy',field,direction]);return{async get(){return{docs:[...rows.entries()].sort().map(([id,value])=>({id,data:()=>structuredClone(value)}))}}}}}};return{app,firestore,rows,calls,collectionPath}}
const row=sequence=>({schema:'journal-test',runId:'run_12345678',sequence,value:`row-${sequence}`});

test('固定 project/app/firestore 與 create-only sequence path，逐筆 durable readback',async()=>{const value=fake(),saved=process.env.FIRESTORE_EMULATOR_HOST;process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';try{const journal=createFirebaseStagingV2SupervisorJournal({app:value.app,firestore:value.firestore,expectedProjectId:'danbridge-rules-test',runId:'run_12345678'});assert.equal(journal.collectionPath,value.collectionPath);await journal.append(row(0));await journal.append(row(1));assert.deepEqual(await journal.readAll(),[row(0),row(1)]);await assert.rejects(()=>journal.append(row(1)),/already exists/);assert.ok(value.calls.some(call=>call[0]==='orderBy'&&call[1]==='sequence'&&call[2]==='asc'))}finally{await deleteApp(value.app);if(saved===undefined)delete process.env.FIRESTORE_EMULATOR_HOST;else process.env.FIRESTORE_EMULATOR_HOST=saved}});

test('錯 project、不同 App/Firestore、跳號 inventory 與環境變動全部 fail closed',async()=>{const value=fake(),other=fake(),saved=process.env.FIRESTORE_EMULATOR_HOST;process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';try{assert.throws(()=>createFirebaseStagingV2SupervisorJournal({app:value.app,firestore:value.firestore,expectedProjectId:'wrong-project',runId:'run_12345678'}),/identity|service-account/);assert.throws(()=>createFirebaseStagingV2SupervisorJournal({app:value.app,firestore:other.firestore,expectedProjectId:'danbridge-rules-test',runId:'run_12345678'}),/identity/);const journal=createFirebaseStagingV2SupervisorJournal({app:value.app,firestore:value.firestore,expectedProjectId:'danbridge-rules-test',runId:'run_12345678'});value.rows.set('00000001',row(1));await assert.rejects(()=>journal.readAll(),/inventory/);value.rows.clear();process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8081';await assert.rejects(()=>journal.append(row(0)),/service-account/);assert.equal(value.calls.filter(call=>call[0]==='create').length,0)}finally{await Promise.all([deleteApp(value.app),deleteApp(other.app)]);if(saved===undefined)delete process.env.FIRESTORE_EMULATOR_HOST;else process.env.FIRESTORE_EMULATOR_HOST=saved}});
