import test from 'node:test';
import assert from 'node:assert/strict';
import {
 buildInitialRecordSyncSafetyControl,
 buildRecordSyncRecoveryReceipt,
 buildRecordSyncSafetyPause,
 buildRecordSyncSafetyResume
} from '../js/core/cloud-record-sync-safety-control.js';
import {createFirebaseRecordSyncSafetyAdapter} from '../js/core/firebase-record-sync-safety-adapter.js';

const activationEpoch='epoch-12345678',backupId='backup-12345678',serverValue={server:true};
const initial=()=>buildInitialRecordSyncSafetyControl({manifest:{schema:'danbridge-record-sync-activation-manifest-v1',environment:'staging',activationEpoch,manifestHash:'a'.repeat(64)},createdAt:'2026-08-15T15:00:00+08:00'});
const pauseFor=control=>buildRecordSyncSafetyPause({control,eventId:'pause-12345678',reason:'本機串流異常演練',safeRecordDataHash:'record-v1:'+'b'.repeat(64),cloudBackupId:backupId,createdAt:'2026-08-15T15:05:00+08:00'});
const recoveryFor=control=>buildRecordSyncRecoveryReceipt({environment:'staging',activationEpoch,pauseEventId:control.lastEventId,sourceBackupId:backupId,restoredRecordDataHash:'record-v1:'+'c'.repeat(64),operationLogHash:'d'.repeat(64),confirmedOperationCount:12,createdAt:'2026-08-15T15:10:00+08:00'});
const resumeFor=(control,recovery)=>buildRecordSyncSafetyResume({control,eventId:'resume-1234567',recoveryReceipt:recovery,readbackRecordDataHash:recovery.restoredRecordDataHash,createdAt:'2026-08-15T15:15:00+08:00'});

function fake({validBackup=true}={}){
 const store=new Map(),events=[];store.set('stagingRecordSyncSafetyControls/danbridge',{...initial(),persistedAt:serverValue,updatedBy:'owner-1',updatedByEmail:'owner@example.com'});store.set(`stagingMigrationBackups/danbridge/runs/${backupId}`,{state:'verified',backupId,sourceHash:'e'.repeat(64),verifiedHash:validBackup?'e'.repeat(64):'f'.repeat(64)});
 return{store,events,async runTransaction(callback){const writes=[],transaction={get:async path=>{events.push(`get:${path}`);const data=store.get(path);return{exists:()=>data!==undefined,data:()=>structuredClone(data)}},set:(path,data)=>{events.push(`set:${path}`);writes.push([path,structuredClone(data)])}};const result=await callback(transaction);for(const write of writes)store.set(...write);return result}};
}
const adapter=(source,overrides={})=>createFirebaseRecordSyncSafetyAdapter({runTransaction:source.runTransaction,serverTimestamp:()=>serverValue,actor:{uid:'owner-123',email:'OWNER@EXAMPLE.COM'},environment:'staging',role:'owner',...overrides});

test('暫停事件與中央控制原子落地，hash 證據時間不被伺服器時間覆蓋',async()=>{const source=fake(),pause=pauseFor(initial()),result=await adapter(source).pause(pause),savedEvent=source.store.get(result.eventPath),savedControl=source.store.get(result.controlPath);assert.equal(result.kind,'paused');assert.equal(savedEvent.createdAt,pause.event.createdAt);assert.deepEqual(savedEvent.persistedAt,serverValue);assert.equal(savedControl.updatedAt,pause.nextControl.updatedAt);assert.deepEqual(savedControl.persistedAt,serverValue);assert.equal(savedControl.writeAllowed,false)});
test('兩位 Owner 重送相同暫停只回 duplicate，不改寫 actor、時間或 revision',async()=>{const source=fake(),pause=pauseFor(initial()),first=await adapter(source).pause(pause),beforeEvent=structuredClone(source.store.get(first.eventPath)),beforeControl=structuredClone(source.store.get(first.controlPath)),retry=await adapter(source,{actor:{uid:'owner-456',email:'catherine@example.com'}}).pause(pause);assert.equal(retry.kind,'duplicate');assert.equal(retry.write,false);assert.deepEqual(source.store.get(first.eventPath),beforeEvent);assert.deepEqual(source.store.get(first.controlPath),beforeControl)});
test('復原 receipt 必須屬於目前暫停、綁定 verified 備份且不可變',async()=>{const source=fake(),pause=pauseFor(initial());await adapter(source).pause(pause);const recovery=recoveryFor(pause.nextControl),saved=await adapter(source).persistRecovery(recovery),before=structuredClone(source.store.get(saved.receiptPath)),retry=await adapter(source,{actor:{uid:'owner-456',email:'catherine@example.com'}}).persistRecovery(recovery);assert.equal(saved.kind,'persisted');assert.equal(retry.kind,'duplicate');assert.deepEqual(source.store.get(saved.receiptPath),before);const tampered={...recovery,confirmedOperationCount:13};await assert.rejects(adapter(source).persistRecovery(tampered),/receipt hash 不符/)});
test('重新讀回 hash 相同後才能原子恢復，重送不增加 revision',async()=>{const source=fake(),pause=pauseFor(initial());await adapter(source).pause(pause);const recovery=recoveryFor(pause.nextControl);await adapter(source).persistRecovery(recovery);const resume=resumeFor(pause.nextControl,recovery),result=await adapter(source).resume({...resume,recoveryReceipt:recovery,readbackRecordDataHash:recovery.restoredRecordDataHash}),revision=source.store.get(result.controlPath).revision,retry=await adapter(source).resume({...resume,recoveryReceipt:recovery,readbackRecordDataHash:recovery.restoredRecordDataHash});assert.equal(result.kind,'resumed');assert.equal(source.store.get(result.controlPath).state,'active');assert.equal(retry.kind,'duplicate');assert.equal(source.store.get(result.controlPath).revision,revision)});
test('缺 receipt、錯誤備份、舊控制、hash 篡改、非 Owner 與 production 全部零寫入',async()=>{const badBackup=fake({validBackup:false}),pause=pauseFor(initial());await adapter(badBackup).pause(pause);const recovery=recoveryFor(pause.nextControl),beforeBackup=badBackup.store.size;await assert.rejects(adapter(badBackup).persistRecovery(recovery),/來源備份無效/);assert.equal(badBackup.store.size,beforeBackup);const missing=fake();await adapter(missing).pause(pause);const resume=resumeFor(pause.nextControl,recovery),beforeMissing=missing.store.size;await assert.rejects(adapter(missing).resume({...resume,recoveryReceipt:recovery,readbackRecordDataHash:recovery.restoredRecordDataHash}),/尚未完整落地/);assert.equal(missing.store.size,beforeMissing);const stale=fake(),changed={...initial(),revision:2,lastEventId:'other-event-123',lastEventHash:'f'.repeat(64),updatedAt:'2026-08-15T15:01:00+08:00'};stale.store.set('stagingRecordSyncSafetyControls/danbridge',changed);await assert.rejects(adapter(stale).pause(pause),/基準版本已改變/);const tamperedPause=structuredClone(pause);tamperedPause.event.reason='被改寫';await assert.rejects(adapter(fake()).pause(tamperedPause),/hash 不符/);await assert.rejects(adapter(fake(),{role:'teacher'}).pause(pause),/只允許 staging Owner/);await assert.rejects(adapter(fake(),{environment:'production'}).pause(pause),/只允許 staging Owner/)});
test('事件或控制只落一半時禁止自動補寫，留待人工診斷',async()=>{const source=fake(),pause=pauseFor(initial()),eventPath=`stagingRecordSyncSafetyEvents/danbridge/epochs/${activationEpoch}/events/${pause.event.eventId}`;source.store.set(eventPath,{...pause.event,persistedAt:serverValue,createdBy:'owner-123',createdByEmail:'owner@example.com'});const before=source.store.size;await assert.rejects(adapter(source).pause(pause),/immutable 衝突/);assert.equal(source.store.size,before);source.store.set('stagingRecordSyncSafetyControls/danbridge',{...pause.nextControl,persistedAt:serverValue,updatedBy:'owner-123',updatedByEmail:'owner@example.com'});source.store.delete(eventPath);await assert.rejects(adapter(source).pause(pause),/半套狀態/)});
