import test from 'node:test';
import assert from 'node:assert/strict';
import {buildRecordSyncRoleEvidence,RECORD_SYNC_ROLE_SCENARIOS} from '../js/core/cloud-record-sync-role-evidence.js';
import {buildRecordSyncActivationManifest,buildActiveRecordSyncControl} from '../js/core/cloud-record-sync-control.js';
import {createFirebaseRecordSyncActivationAdapter} from '../js/core/firebase-record-sync-activation-adapter.js';
import {buildOpenRecordSyncCandidateControl,sealRecordSyncCandidateControl} from '../js/core/cloud-record-sync-candidate-control.js';

function fixture(){const legacyVersionHash='legacy-123',recordDataHash='record-v1:'+'a'.repeat(64),candidateControl=sealRecordSyncCandidateControl({control:buildOpenRecordSyncCandidateControl({candidateEpoch:'candidate-12345678',legacyVersionHash,createdAt:'2026-08-15T11:50:00+08:00'}),currentLegacyVersionHash:legacyVersionHash,recordDataHash,documentCount:2,activeCount:2,tombstoneCount:0,sealedAt:'2026-08-15T12:03:00+08:00'}),roleEvidence=buildRecordSyncRoleEvidence({environment:'staging',primaryOwnerEmail:'daniel@example.com',backupOwnerEmail:'catherine@example.com',schedulerEmail:'aa@example.com',teacherAccounts:['teacher@example.com'],roleViewCount:4,candidateRunId:'role-run-123',candidateSourceHash:'b'.repeat(64),candidateManifestHash:'c'.repeat(64),receiptCount:6,receiptSetHash:'d'.repeat(64),results:Object.fromEntries(RECORD_SYNC_ROLE_SCENARIOS.map(key=>[key,true])),testedAt:'2026-08-15T12:00:00+08:00'}),manifest=buildRecordSyncActivationManifest({environment:'staging',activationEpoch:'epoch-12345678',candidateControl,legacyVersionHash,recordDataHash,roleEvidence,backupId:'backup-123',restoreReceiptId:'restore-123',documentCount:2,activeCount:2,tombstoneCount:0,createdAt:'2026-08-15T12:05:00+08:00'}),control=buildActiveRecordSyncControl({manifest,currentLegacyVersionHash:legacyVersionHash,currentRecordDataHash:manifest.recordDataHash,currentRoleEvidenceHash:roleEvidence.evidenceHash,activatedAt:'2026-08-15T12:10:00+08:00'});return{roleEvidence,candidateControl,manifest,control}}
function fake({brokenBackup=false,brokenRestore=false,brokenCandidate=false,legacy='legacy-123'}={}){const store=new Map(),events=[],candidate=fixture().candidateControl;store.set('companies/danbridge/data/main',{clientHash:legacy});store.set('stagingRecordSyncCandidateControls/danbridge',brokenCandidate?{...candidate,recordDataHash:'record-v1:'+'b'.repeat(64)}:candidate);store.set('stagingMigrationBackups/danbridge/runs/backup-123',{state:'verified',backupId:'backup-123',sourceVersionHash:'legacy-123',sourceHash:'a'.repeat(64),verifiedHash:brokenBackup?'b'.repeat(64):'a'.repeat(64)});store.set('stagingMigrationRestoreDrills/danbridge/runs/restore-123',{state:'verified',drillId:'restore-123',sourceBackupId:'backup-123',sourceHash:'a'.repeat(64),restoredHash:brokenRestore?'b'.repeat(64):'a'.repeat(64),mainVersionHash:'legacy-123',mainUnchanged:true});return{store,events,async runTransaction(callback){const writes=[],transaction={get:async path=>{events.push(`get:${path}`);const data=store.get(path);return{exists:()=>data!==undefined,data:()=>structuredClone(data)}},set:(path,data)=>{events.push(`set:${path}`);writes.push([path,structuredClone(data)])}};const result=await callback(transaction);for(const write of writes)store.set(...write);return result}}}
const adapter=(source,overrides={})=>createFirebaseRecordSyncActivationAdapter({runTransaction:source.runTransaction,serverTimestamp:()=>({server:true}),actor:{uid:'owner-1',email:'OWNER@EXAMPLE.COM'},environment:'staging',role:'owner',...overrides});

test('角色證據、manifest、讀寫控制與安全控制在同一交易一次啟用',async()=>{const source=fake(),evidence=fixture(),result=await adapter(source).activate(evidence);assert.equal(result.kind,'activated');assert.equal(result.write,true);assert.equal(source.store.get(result.roleEvidencePath).persistedByEmail,'owner@example.com');assert.equal(source.store.get(result.manifestPath).manifestHash,evidence.manifest.manifestHash);assert.equal(source.store.get(result.controlPath).readTakeover,true);assert.equal(source.store.get(result.controlPath).activatedAt,evidence.control.activatedAt);assert.deepEqual(source.store.get(result.controlPath).persistedAt,{server:true});assert.equal(source.store.get(result.safetyPath).writeAllowed,true);assert.equal(source.store.get(result.safetyPath).revision,1);assert.equal(source.store.get(result.safetyPath).updatedAt,evidence.control.activatedAt);assert.deepEqual(source.store.get(result.safetyPath).persistedAt,{server:true});assert.equal(source.events.filter(value=>value.startsWith('set:')).length,4)});
test('回應遺失後相同啟用重送為 duplicate，不重寫時間與 actor',async()=>{const source=fake(),evidence=fixture(),first=await adapter(source).activate(evidence),before=structuredClone(source.store.get(first.controlPath)),second=await adapter(source,{actor:{uid:'owner-2',email:'catherine@example.com'}}).activate(evidence);assert.equal(second.kind,'duplicate');assert.equal(second.write,false);assert.deepEqual(source.store.get(first.controlPath),before)});
test('任一既有文件缺少或 identity 不符都不補寫半套狀態',async()=>{for(const mutate of [source=>source.store.set(`stagingRecordSyncRoleEvidence/danbridge/runs/${fixture().roleEvidence.evidenceHash}`,{partial:true}),source=>{const evidence=fixture();source.store.set(`stagingRecordSyncRoleEvidence/danbridge/runs/${evidence.roleEvidence.evidenceHash}`,evidence.roleEvidence);source.store.set(`stagingRecordSyncActivationManifests/danbridge/manifests/${evidence.manifest.manifestHash}`,{...evidence.manifest,documentCount:99})}]){const source=fake(),before=source.store.size;mutate(source);const afterSeed=source.store.size;await assert.rejects(adapter(source).activate(fixture()),/既有證據或控制 identity 衝突/);assert.equal(source.store.size,afterSeed);assert.ok(source.store.size>=before)}});
test('legacy 版本、候選封存、備份或復原演練不符全部零啟用寫入',async()=>{for(const source of [fake({legacy:'changed'}),fake({brokenCandidate:true}),fake({brokenBackup:true}),fake({brokenRestore:true})]){const before=source.store.size;await assert.rejects(adapter(source).activate(fixture()),/版本已改變|封存|seal hash|備份無效|復原演練無效/);assert.equal(source.store.size,before)}});
test('任意角色證據篡改、非 Owner 或 production 都拒絕',async()=>{const source=fake(),tampered=fixture();tampered.roleEvidence.results['teacher-report-write']=false;await assert.rejects(adapter(source).activate(tampered),/證據格式無效/);await assert.rejects(adapter(source,{role:'teacher'}).activate(fixture()),/只允許 staging Owner/);await assert.rejects(adapter(source,{environment:'production'}).activate(fixture()),/只允許 staging Owner/)});
