import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {deleteApp,initializeApp} from 'firebase-admin/app';
import {getFirestore} from 'firebase-admin/firestore';
import {RECORD_SYNC_V2_GENESIS_ALL_BATCHES_SCOPE} from '../js/core/firebase-record-sync-v2-genesis-all-batches-capability.js';
import {
 RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_ADAPTER_SCOPE,
 RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_BUCKET_PATH,
 RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_BUCKET_SEAL_PATH,
 RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_CI_ACTOR,
 RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_COMPLETION_SCOPE,
 RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_PRODUCTION_BLOCKER,
 RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_ROOT_PATH,
 consumeFirebaseRecordSyncV2GenesisIdentityIndexCompletion,
 createFirebaseRecordSyncV2GenesisIdentityIndexAdapter,
 createFirebaseRecordSyncV2GenesisIdentityIndexAdminBinder,
 normalizeFirebaseRecordSyncV2GenesisIdentityIndexSnapshot
} from '../js/core/firebase-record-sync-v2-genesis-identity-index-adapter.js';

const seed='v2-genesis:'+'a'.repeat(64),epoch='epoch-v2-12345678';
const fakeAll=()=>Object.freeze({state:'all-batches-dense-confirmed',scope:RECORD_SYNC_V2_GENESIS_ALL_BATCHES_SCOPE,environment:'staging',companyId:'danbridge',targetV2Epoch:epoch,seedId:seed,parentFrozenSourceProofHash:'b'.repeat(64),seedManifestHash:'c'.repeat(64),recordCount:0,batchCount:0});
const base=()=>({expectedProjectId:'danbridge-rules-test',getDocumentFromServer:async()=>null,runTransaction:async()=>{throw new Error('must not transact')},serverTimestamp:()=>({seconds:1787097600,nanoseconds:123456789})});

test('G1.5 native adapter只接受global all-batches capability，manual/clone在任何I/O前拒',async()=>{let reads=0,transactions=0,writes=0;const adapter=createFirebaseRecordSyncV2GenesisIdentityIndexAdapter({...base(),getDocumentFromServer:async()=>{reads++;return null},runTransaction:async callback=>{transactions++;return callback({get:async()=>null,set(){writes++}})}});await assert.rejects(()=>adapter.execute(fakeAll()),/native G2 all-batches completion invalid/);assert.deepEqual({reads,transactions,writes},{reads:0,transactions:0,writes:0});assert.throws(()=>consumeFirebaseRecordSyncV2GenesisIdentityIndexCompletion(Object.freeze({}),Object.freeze({})),/native identity index completion invalid/);assert.equal(adapter.scope,RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_ADAPTER_SCOPE);assert.equal(typeof adapter.consumeLocalCompletion,'function');assert.match(RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_COMPLETION_SCOPE,/future-g2-g3-only/);assert.match(RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_PRODUCTION_BLOCKER,/staging-service-account/);assert.deepEqual(RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_CI_ACTOR,{uid:'service-account:danbridge-staging-v2',email:'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com'});assert.equal(Object.isFrozen(RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_CI_ACTOR),true)});

test('G1.5 fixed 513 paths與generic config descriptor-safe getter0',()=>{assert.equal(RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_BUCKET_PATH(epoch,seed,0),`stagingRecordSyncV2GenesisIdentityIndexes/danbridge/epochs/${epoch}/seeds/${seed}/buckets/000`);assert.equal(RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_BUCKET_PATH(epoch,seed,255),`stagingRecordSyncV2GenesisIdentityIndexes/danbridge/epochs/${epoch}/seeds/${seed}/buckets/255`);assert.equal(RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_BUCKET_SEAL_PATH(epoch,seed,7),`stagingRecordSyncV2GenesisIdentityIndexes/danbridge/epochs/${epoch}/seeds/${seed}/bucketSeals/007`);assert.equal(RECORD_SYNC_V2_GENESIS_IDENTITY_INDEX_ROOT_PATH(epoch,seed),`stagingRecordSyncV2GenesisIdentityIndexes/danbridge/epochs/${epoch}/seeds/${seed}/artifacts/root`);let calls=0;const hostile=base();Object.defineProperty(hostile,'beforePersistence',{enumerable:true,get(){calls++;return async()=>{}}});assert.throws(()=>createFirebaseRecordSyncV2GenesisIdentityIndexAdapter(hostile),/own enumerable data field/);assert.equal(calls,0);assert.throws(()=>createFirebaseRecordSyncV2GenesisIdentityIndexAdapter({...base(),cachedGet:async()=>null}),/config fields invalid/);assert.throws(()=>createFirebaseRecordSyncV2GenesisIdentityIndexAdapter({...base(),beforePersistence:null}),/fixed Admin I\/O/);assert.throws(()=>createFirebaseRecordSyncV2GenesisIdentityIndexAdapter(null),/plain object/)});

test('G1.5 snapshot normalization不讀exists/accessor並保留Admin Timestamp nanos',()=>{const timestamp={seconds:1787097600,nanoseconds:123456789},snapshot={data(){return{persistedAt:timestamp,persistedBy:'service-account:danbridge-staging-v2',persistedByEmail:'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com'}}};let existsCalls=0;Object.defineProperty(snapshot,'exists',{enumerable:true,get(){existsCalls++;throw new Error('must not read exists')}});assert.equal(normalizeFirebaseRecordSyncV2GenesisIdentityIndexSnapshot(snapshot).persistedAt,'2026-08-19T00:00:00.123456789Z');assert.equal(existsCalls,0);assert.equal(Object.isFrozen(timestamp),false);let dataCalls=0;const hostile={};Object.defineProperty(hostile,'data',{enumerable:true,get(){dataCalls++;return()=>({})}});assert.throws(()=>normalizeFirebaseRecordSyncV2GenesisIdentityIndexSnapshot(hostile),/data method unsafe/);assert.equal(dataCalls,0);assert.equal(normalizeFirebaseRecordSyncV2GenesisIdentityIndexSnapshot({data(){return undefined}}),null);for(const value of [{seconds:1787097600,nanoseconds:1000000000},{_seconds:1787097600,_nanoseconds:-1},{seconds:1787097600,nanoseconds:1,extra:true}])assert.throws(()=>normalizeFirebaseRecordSyncV2GenesisIdentityIndexSnapshot({persistedAt:value}),/Timestamp/)});

test('G1.5 Admin binder固定App/Firestore/project/emulator且production預設關閉',async()=>{const name='g15-index-focused-'+Date.now(),app=initializeApp({projectId:'danbridge-rules-test'},name),other=initializeApp({projectId:'wrong-project-12345'},name+'-other'),firestore=getFirestore(app),otherFirestore=getFirestore(other),saved=process.env.FIRESTORE_EMULATOR_HOST;try{delete process.env.FIRESTORE_EMULATOR_HOST;assert.throws(()=>createFirebaseRecordSyncV2GenesisIdentityIndexAdminBinder({app,firestore,expectedProjectId:'danbridge-rules-test'}),/staging-service-account/);process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:1';assert.throws(()=>createFirebaseRecordSyncV2GenesisIdentityIndexAdminBinder({app,firestore,expectedProjectId:'wrong-project-12345'}),/staging-service-account/);assert.throws(()=>createFirebaseRecordSyncV2GenesisIdentityIndexAdminBinder({app,firestore:otherFirestore,expectedProjectId:'danbridge-rules-test'}),/App\/Firestore identity/);let calls=0,hostile={app,firestore,expectedProjectId:'danbridge-rules-test'};Object.defineProperty(hostile,'firestore',{enumerable:true,get(){calls++;return firestore}});assert.throws(()=>createFirebaseRecordSyncV2GenesisIdentityIndexAdminBinder(hostile),/own enumerable data field/);assert.equal(calls,0)}finally{if(saved===undefined)delete process.env.FIRESTORE_EMULATOR_HOST;else process.env.FIRESTORE_EMULATOR_HOST=saved;await Promise.all([deleteApp(app),deleteApp(other)])}});

test('G1.5 native dependency graph透過neutral capability不靜態載入Web SDK、G2/G3 runtime或browser',async()=>{const source=await readFile(new URL('../js/core/firebase-record-sync-v2-genesis-identity-index-adapter.js',import.meta.url),'utf8'),capability=await readFile(new URL('../js/core/firebase-record-sync-v2-genesis-all-batches-capability.js',import.meta.url),'utf8'),combined=source+'\n'+capability;for(const forbidden of ["from 'firebase/firestore'",'firebase/auth','firebase-auth-and-cloud-sync','cloud-active-record','cloud-record-sync-v2-genesis-authority.js','cloud-record-sync-v2-takeover-candidate','cloud-record-sync-v2-activation-cutover-intent','cloud-record-sync-v2-trusted-deployment-evidence'])assert.equal(combined.includes(forbidden),false,forbidden);assert.match(source,/firebase-admin\/firestore/);assert.match(source,/firebase-record-sync-v2-genesis-all-batches-capability\.js/);assert.doesNotMatch(source,/firebase-record-sync-v2-genesis-seed-readback-adapter\.js/);assert.match(capability,/await Promise\.all\(\[import\('\.\/firebase-record-sync-v2-genesis-seed-plan-adapter\.js'\),import\('\.\/firebase-record-sync-v2-genesis-seed-batch-adapter\.js'\),import\('\.\/firebase-record-sync-v1-frozen-source-proof-adapter\.js'\)\]\)/);assert.equal((source.match(/tx\.set\(/g)??[]).length,3);assert.match(source,/durableRead\(input\.getDocumentFromServer,p\)/)});
