import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS} from '../js/core/cloud-full-record-shadow.js';
import {createFirebaseFullRecordShadowAdapter} from '../js/core/firebase-full-record-shadow-adapter.js';

const target=count=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,key==='changes'?[{type:'same'},{type:'same'}]:Array.from({length:key==='lessons'?count:1},(_,i)=>({id:`${key}-${i}`,value:i}))]));
function fake({failBatch=0}={}){const store=new Map(),events=[];let calls=0;return{store,events,async getCollectionDocuments(path){const collection=path.split('/')[3];events.push(`list:${collection}`);return[...store].filter(([key])=>key.startsWith(`${collection}/`)).map(([key,data])=>({id:key.slice(collection.length+1),data:structuredClone(data)}))},async runBatchTransaction(callback){calls++;const writes=[],transaction={async get(path){const [,collection,id]=path.match(/collections\/([^/]+)\/records\/(.+)$/)||[];events.push(`get:${collection}/${id}`);const data=store.get(`${collection}/${id}`);return{exists:()=>data!==undefined,data:()=>structuredClone(data)}},set(path,data){const [,collection,id]=path.match(/collections\/([^/]+)\/records\/(.+)$/)||[];events.push(`set:${collection}/${id}`);writes.push([`${collection}/${id}`,structuredClone(data)])}};await callback(transaction);if(calls===failBatch)throw new Error('injected');for(const row of writes)store.set(...row)}}}
const adapter=(source,overrides={})=>createFirebaseFullRecordShadowAdapter({getCollectionDocuments:source.getCollectionDocuments,runBatchTransaction:source.runBatchTransaction,serverTimestamp:()=>({server:true}),actor:{uid:'owner',email:'OWNER@EXAMPLE.COM'},environment:'staging',role:'owner',...overrides});

test('staging Owner 寫入並讀回驗證完整 16 集合',async()=>{const source=fake(),result=await adapter(source).synchronize(target(2),{sourceHash:'hash'});assert.equal(result.verified,true);assert.equal(result.activeCount,18);assert.ok(source.events.findIndex(x=>x.startsWith('set:'))>source.events.findLastIndex(x=>x.startsWith('get:')));for(const data of source.store.values()){assert.deepEqual(data.updatedAt,{server:true});assert.equal(data.updatedByEmail,'owner@example.com')}});
test('production Owner 只寫入獨立 production namespace 並完整讀回',async()=>{const source=fake(),result=await adapter(source,{environment:'production'}).synchronize(target(2),{sourceHash:'production-hash'});assert.equal(result.verified,true);assert.equal(result.activeCount,18);for(const data of source.store.values())assert.equal(data.environment,'production')});
test('production 唯讀候選驗證不呼叫 transaction 或 set',async()=>{const source=fake(),production=adapter(source,{environment:'production'}),db=target(2);await production.synchronize(db,{sourceHash:'production-hash'});source.events.length=0;const result=await production.verifyCandidate(db,{sourceHash:'production-hash'});assert.equal(result.candidateVerified,true);assert.equal(result.activeCount,18);assert.ok(source.events.every(event=>event.startsWith('list:')))});
test('分批失敗後重新讀取只補剩餘文件',async()=>{const source=fake({failBatch:2}),db=target(10);await assert.rejects(adapter(source).synchronize(db,{sourceHash:'fail',batchSize:10}),error=>error.completedBatches===1);const resumed=await adapter(source).synchronize(db,{sourceHash:'resume',batchSize:10});assert.equal(resumed.verified,true);assert.ok(resumed.writes>0)});
test('未知環境與任何非 Owner 角色完全禁止',async()=>{for(const overrides of [{environment:'unknown'},{role:'teacher'},{role:'aa'}]){const source=fake();await assert.rejects(adapter(source,overrides).synchronize(target(1),{sourceHash:'x'}),/只允許指定環境 Owner/);assert.equal(source.events.length,0)}});
