import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,buildFullRecordShadowPlan} from '../js/core/cloud-full-record-shadow.js';
import {buildRecordSyncRoleEvidence,RECORD_SYNC_ROLE_SCENARIOS} from '../js/core/cloud-record-sync-role-evidence.js';
import {buildActiveRecordSyncControl,buildRecordSyncActivationManifest} from '../js/core/cloud-record-sync-control.js';
import {buildOpenRecordSyncCandidateControl,sealRecordSyncCandidateControl} from '../js/core/cloud-record-sync-candidate-control.js';
import {buildInitialRecordSyncSafetyControl,buildRecordSyncSafetyPause} from '../js/core/cloud-record-sync-safety-control.js';
import {createFirebaseActiveRecordStreamAdapter} from '../js/core/firebase-active-record-stream-adapter.js';

const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));
function fixture(){const db=empty();db.lessons=[{id:'lesson-1',room:'A'}];const roleEvidence=buildRecordSyncRoleEvidence({environment:'staging',primaryOwnerEmail:'daniel@example.com',backupOwnerEmail:'catherine@example.com',schedulerEmail:'aa@example.com',teacherAccounts:['teacher@example.com'],roleViewCount:2,candidateRunId:'role-run-123',candidateSourceHash:'b'.repeat(64),candidateManifestHash:'c'.repeat(64),receiptCount:4,receiptSetHash:'d'.repeat(64),results:Object.fromEntries(RECORD_SYNC_ROLE_SCENARIOS.map(key=>[key,true])),testedAt:'2026-08-15T16:00:00+08:00'}),candidateControl=sealRecordSyncCandidateControl({control:buildOpenRecordSyncCandidateControl({candidateEpoch:'candidate-12345678',legacyVersionHash:'legacy-123',createdAt:'2026-08-15T15:55:00+08:00'}),currentLegacyVersionHash:'legacy-123',recordDataHash:'record-v1:'+'a'.repeat(64),documentCount:1,activeCount:1,tombstoneCount:0,sealedAt:'2026-08-15T16:03:00+08:00'}),manifest=buildRecordSyncActivationManifest({environment:'staging',activationEpoch:'epoch-12345678',candidateControl,legacyVersionHash:'legacy-123',recordDataHash:'record-v1:'+'a'.repeat(64),roleEvidence,backupId:'backup-123',restoreReceiptId:'restore-123',documentCount:1,activeCount:1,tombstoneCount:0,createdAt:'2026-08-15T16:05:00+08:00'}),control=buildActiveRecordSyncControl({manifest,currentLegacyVersionHash:manifest.legacyVersionHash,currentRecordDataHash:manifest.recordDataHash,currentRoleEvidenceHash:manifest.roleEvidenceHash,activatedAt:'2026-08-15T16:10:00+08:00'}),safety=buildInitialRecordSyncSafetyControl({manifest,createdAt:control.activatedAt}),documents=Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));for(const operation of buildFullRecordShadowPlan(documents,db,{sourceHash:'seed',environment:'staging'}).operations){const match=operation.path.match(/collections\/([^/]+)\/records\/(.+)$/);documents[match[1]].push({id:match[2],data:operation.payload})}return{db,manifest:{...manifest,persistedAt:{seconds:1},persistedBy:'owner-123',persistedByEmail:'owner@example.com'},control:{...control,persistedAt:{seconds:1},activatedBy:'owner-123',activatedByEmail:'owner@example.com'},safety:{...safety,persistedAt:{seconds:1},updatedBy:'owner-123',updatedByEmail:'owner@example.com'},documents}}
function bus(){const documents=new Map(),collections=new Map(),unsubscribed=[];const subscribe=(target,path,next,error)=>{target.set(path,{next,error});return()=>{unsubscribed.push(path);target.delete(path)}};return{documents,collections,unsubscribed,subscribeDocument:(path,next,error)=>subscribe(documents,path,next,error),subscribeCollection:(path,next,error)=>subscribe(collections,path,next,error),emitDocument(path,value){documents.get(path)?.next(value)},emitCollection(path,value){collections.get(path)?.next(value)},failCollection(path,error){collections.get(path)?.error(error)}}}
async function loadAll(source,bus){bus.emitDocument('stagingRecordSyncControls/danbridge',{exists:true,data:source.control});await tick();bus.emitDocument(`stagingRecordSyncActivationManifests/danbridge/manifests/${source.control.manifestHash}`,{exists:true,data:source.manifest});bus.emitDocument('stagingRecordSyncSafetyControls/danbridge',{exists:true,data:source.safety});for(const collectionName of FULL_RECORD_COLLECTIONS){const path=`stagingFullRecordShadows/danbridge/collections/${collectionName}/records`,documents=source.documents[collectionName];bus.emitCollection(path,{documents,changes:documents.map(row=>({type:'added',...row}))})}await tick();await tick()}

test('控制、帶稽核 manifest、安全控制與 16 集合可亂序到達，完整後只套用一次',async()=>{const source=fixture(),events=[],states=[],network=bus(),adapter=createFirebaseActiveRecordStreamAdapter({environment:'staging',subscribeDocument:network.subscribeDocument,subscribeCollection:network.subscribeCollection,onApply:snapshot=>events.push(snapshot),onState:state=>states.push(state)});adapter.start();await loadAll(source,network);assert.equal(events.length,1);assert.equal(events[0].db.lessons[0].room,'A');assert.equal(events[0].writeAllowed,true);assert.equal(adapter.diagnostics().state,'ready');assert.equal(adapter.diagnostics().activeSubscriptionCount,18);assert.ok(states.some(row=>row.state==='loading'))});
test('單一文件 modified 立即更新；中央暫停在資料不變時也立即通知 writeAllowed=false',async()=>{const source=fixture(),events=[],network=bus(),adapter=createFirebaseActiveRecordStreamAdapter({environment:'staging',subscribeDocument:network.subscribeDocument,subscribeCollection:network.subscribeCollection,onApply:snapshot=>events.push(snapshot)});adapter.start();await loadAll(source,network);const old=source.documents.lessons[0],modified={...old,data:{...old.data,record:{...old.data.record,room:'B'},revision:2,lastOperationId:'device-123:1',deviceId:'device-123',activationEpoch:'epoch-12345678'}},path='stagingFullRecordShadows/danbridge/collections/lessons/records';network.emitCollection(path,{documents:[modified],changes:[{type:'modified',...modified}]});await tick();assert.equal(events.at(-1).db.lessons[0].room,'B');const pause=buildRecordSyncSafetyPause({control:source.safety,eventId:'pause-12345678',reason:'串流演練',safeRecordDataHash:events.at(-1).hash,cloudBackupId:'backup-123',createdAt:'2026-08-15T16:15:00+08:00'});network.emitDocument('stagingRecordSyncSafetyControls/danbridge',{exists:true,data:{...pause.nextControl,persistedAt:{seconds:2},updatedBy:'owner-123',updatedByEmail:'owner@example.com'}});await tick();assert.equal(events.at(-1).db.lessons[0].room,'B');assert.equal(events.at(-1).writeAllowed,false);assert.equal(adapter.diagnostics().state,'paused')});
test('略過 pending writes 後以完整集合重新對齊，不依賴 Firestore 是否重播 docChanges',async()=>{const source=fixture(),events=[],network=bus(),adapter=createFirebaseActiveRecordStreamAdapter({environment:'staging',subscribeDocument:network.subscribeDocument,subscribeCollection:network.subscribeCollection,onApply:snapshot=>events.push(snapshot)});adapter.start();await loadAll(source,network);const old=source.documents.lessons[0],modified={...old,data:{...old.data,record:{...old.data.record,room:'B'},revision:2,lastOperationId:'device-123:1',deviceId:'device-123',activationEpoch:'epoch-12345678'}},added={id:'lesson-2',data:{...old.data,recordId:'lesson-2',record:{...old.data.record,id:'lesson-2',room:'C'},revision:1,lastOperationId:'catherine-123:1',deviceId:'catherine-123',activationEpoch:'epoch-12345678'}},path='stagingFullRecordShadows/danbridge/collections/lessons/records';network.emitCollection(path,{hasPendingWrites:true,documents:[modified,added],changes:[{type:'modified',...modified},{type:'added',...added}]});await tick();assert.equal(events.at(-1).db.lessons[0].room,'A');network.emitCollection(path,{hasPendingWrites:false,documents:[modified,added],changes:[]});await tick();assert.deepEqual(events.at(-1).db.lessons.map(row=>row.room),['B','C']);assert.equal(adapter.diagnostics().state,'ready')});
test('實體刪除、manifest 多餘欄位或集合監聽錯誤都 fail closed 並保留最後畫面',async()=>{for(const scenario of ['removed','manifest','listener']){const source=fixture(),events=[],network=bus(),adapter=createFirebaseActiveRecordStreamAdapter({environment:'staging',subscribeDocument:network.subscribeDocument,subscribeCollection:network.subscribeCollection,onApply:snapshot=>events.push(snapshot)});adapter.start();if(scenario==='manifest'){network.emitDocument('stagingRecordSyncControls/danbridge',{exists:true,data:source.control});await tick();network.emitDocument(`stagingRecordSyncActivationManifests/danbridge/manifests/${source.control.manifestHash}`,{exists:true,data:{...source.manifest,unexpected:true}});await tick()}else{await loadAll(source,network);const path='stagingFullRecordShadows/danbridge/collections/lessons/records';if(scenario==='removed')network.emitCollection(path,{documents:[],changes:[{type:'removed',...source.documents.lessons[0]}]});else network.failCollection(path,new Error('listener offline'));await tick()}assert.equal(adapter.diagnostics().state,'blocked');assert.equal(adapter.diagnostics().activeSubscriptionCount,0);if(scenario!=='manifest')assert.equal(events.at(-1).db.lessons[0].room,'A')}});
test('控制不存在時保持 legacy 且不訂閱 16 集合；停止後解除所有監聽',async()=>{const network=bus(),adapter=createFirebaseActiveRecordStreamAdapter({environment:'staging',subscribeDocument:network.subscribeDocument,subscribeCollection:network.subscribeCollection,onApply:()=>{}});adapter.start();network.emitDocument('stagingRecordSyncControls/danbridge',{exists:false,data:null});await tick();assert.equal(adapter.diagnostics().state,'legacy');assert.equal(network.collections.size,0);adapter.stop();assert.equal(adapter.diagnostics().state,'stopped');assert.equal(network.documents.size,0)});
