import test from 'node:test';
import assert from 'node:assert/strict';
import {RECORD_SYNC_V2_TRUSTED_DEPLOYMENT_GATE_TYPES,RECORD_SYNC_V2_TRUSTED_DEPLOYMENT_REQUIRED_GATE_IDS} from '../js/core/cloud-record-sync-v2-deployment-gate-contract.js';
import {
 RECORD_SYNC_V2_DEPLOYMENT_ATTESTATION_ADAPTER_SCOPE,
 RECORD_SYNC_V2_DEPLOYMENT_ATTESTATION_PATH,
 RECORD_SYNC_V2_DEPLOYMENT_ATTESTATION_PRODUCTION_BLOCKER,
 consumeFirebaseRecordSyncV2DeploymentGateSourceAttestationCompletion,
 createFirebaseRecordSyncV2DeploymentGateSourceAttestationAdapter,
 createFirebaseRecordSyncV2DeploymentGateSourceAttestationAdminBinder
} from '../js/core/firebase-record-sync-v2-deployment-gate-source-attestation-adapter.js';

const h=n=>n.toString(16).repeat(64),source=()=>({environment:'staging',companyId:'danbridge',projectId:'danbridge-rules-test',sourceV1ActivationEpoch:'source-v1-epoch-12345',targetV2Epoch:'target-v2-epoch-12345',rulesetHash:h(10),runtimePolicyHash:h(11),gateSourceHashes:Object.fromEntries(RECORD_SYNC_V2_TRUSTED_DEPLOYMENT_REQUIRED_GATE_IDS.map((id,index)=>[id,RECORD_SYNC_V2_TRUSTED_DEPLOYMENT_GATE_TYPES[id]+':'+h(index+1)]))});
const timestamp=()=>({seconds:1787011200,nanoseconds:123456789});
function fake(beforePersistence=async()=>{}){const docs=new Map(),counts={reads:0,tx:0,sets:0,stamps:0};const adapter=createFirebaseRecordSyncV2DeploymentGateSourceAttestationAdapter({beforePersistence,getDocumentFromServer:async path=>{counts.reads++;return docs.get(path)??null},serverTimestamp:()=>{counts.stamps++;return timestamp()},runTransaction:async callback=>{counts.tx++;const writes=[];const result=await callback({get:async path=>docs.get(path)??null,set:(path,value)=>writes.push([path,value])});for(const [path,value] of writes){counts.sets++;docs.set(path,value)}return result}});return{adapter,docs,counts}}

test('D0 fixed path與Admin-only scope不冒充ready/active/runtime；production principal allowlist failclosed',()=>{assert.equal(RECORD_SYNC_V2_DEPLOYMENT_ATTESTATION_PATH('target-v2-epoch-12345',h(12)),`stagingRecordSyncV2DeploymentAttestations/danbridge/epochs/target-v2-epoch-12345/attestations/${h(12)}`);assert.match(RECORD_SYNC_V2_DEPLOYMENT_ATTESTATION_ADAPTER_SCOPE,/admin-ci-emulator-fixed/);assert.match(RECORD_SYNC_V2_DEPLOYMENT_ATTESTATION_PRODUCTION_BLOCKER,/principal.*allowlist/);assert.throws(()=>createFirebaseRecordSyncV2DeploymentGateSourceAttestationAdminBinder({app:{options:{projectId:'prod'}},firestore:{},expectedProjectId:'prod'}),/Admin App\/Firestore identity|principal.*allowlist/)});

test('generic D0 adapter create1/replay0且只能mint local；global consumer拒local/clone/manual',async()=>{const io=fake(),created=await io.adapter.execute(source()),replayed=await io.adapter.execute(source());assert.equal(created.transactionState,'created');assert.equal(created.writeCount,1);assert.equal(replayed.transactionState,'replayed');assert.equal(replayed.writeCount,0);assert.equal(io.counts.sets,1);assert.equal(io.adapter.consumeLocalCompletion(created).attestation.attestationHash,created.attestationHash);for(const value of [created,replayed,structuredClone(created),{...created}])assert.throws(()=>consumeFirebaseRecordSyncV2DeploymentGateSourceAttestationCompletion(value,{}),/native deployment attestation completion/)});

test('caller time/extra、top-level與nested accessor在任何I/O前getter0拒',async()=>{const io=fake();for(const hostile of [{...source(),evidenceAt:'2026-08-18T00:00:00.000000000Z'},{...source(),ready:true}])await assert.rejects(()=>io.adapter.execute(hostile),/fields/);let calls=0;const top=source();Object.defineProperty(top,'rulesetHash',{enumerable:true,get(){calls++;return h(10)}});await assert.rejects(()=>io.adapter.execute(top),/data field/);const nested=source();Object.defineProperty(nested.gateSourceHashes,RECORD_SYNC_V2_TRUSTED_DEPLOYMENT_REQUIRED_GATE_IDS[0],{enumerable:true,get(){calls++;return'bad'}});await assert.rejects(()=>io.adapter.execute(nested),/data field/);assert.equal(calls,0);assert.equal(io.counts.reads,0);assert.equal(io.counts.tx,0)});

test('fresh durable audit必為native Timestamp exact own fields；response-loss durable後重送0寫',async()=>{const io=fake(),first=await io.adapter.execute(source()),path=RECORD_SYNC_V2_DEPLOYMENT_ATTESTATION_PATH(first.targetV2Epoch,first.attestationHash),durable=io.docs.get(path);io.docs.set(path,{...durable,persistedAt:{seconds:1787011200,nanoseconds:123456789,extra:1}});await assert.rejects(()=>io.adapter.execute(source()),/Timestamp fields/);io.docs.set(path,durable);const replay=await io.adapter.execute(source());assert.equal(replay.writeCount,0);assert.equal(replay.persistedAt,'2026-08-18T00:00:00.123456789Z')});

test('任何await前固定六gate map snapshot；hook改caller不會造成path/core/hash split',async()=>{const caller=source(),original=structuredClone(caller),gateId=RECORD_SYNC_V2_TRUSTED_DEPLOYMENT_REQUIRED_GATE_IDS[0],type=RECORD_SYNC_V2_TRUSTED_DEPLOYMENT_GATE_TYPES[gateId],io=fake(async()=>{caller.gateSourceHashes[gateId]=type+':'+h(12)}),completion=await io.adapter.execute(caller),entries=[...io.docs.entries()];assert.equal(entries.length,1);const [path,stored]=entries[0];assert.equal(path.split('/').at(-1),completion.attestationHash);assert.equal(stored.attestationHash,completion.attestationHash);assert.equal(stored.gateSources[0].sourceEvidenceHash,original.gateSourceHashes[gateId]);assert.equal(Object.isFrozen(caller),false);assert.equal(Object.isFrozen(caller.gateSourceHashes),false);assert.notDeepEqual(caller,original)});

const emulatorHosts=Boolean(process.env.FIRESTORE_EMULATOR_HOST&&process.env.FIREBASE_AUTH_EMULATOR_HOST),emulatorRequired=process.env.DANBRIDGE_REQUIRE_V2_BINDER_EMULATOR==='1';
test('真Admin D0 create/replay/loss/restart；client immutable且只trusted Owner可讀',{skip:!emulatorHosts&&!emulatorRequired},async()=>{
 assert.equal(emulatorHosts,true,'D0 integration requires dual emulators');
 const [{initializeTestEnvironment,assertFails,assertSucceeds},{initializeApp,deleteApp},{getFirestore,FieldValue},{doc,getDoc,setDoc,updateDoc,deleteDoc,serverTimestamp}]=await Promise.all([import('@firebase/rules-unit-testing'),import('firebase-admin/app'),import('firebase-admin/firestore'),import('firebase/firestore')]);
 const projectId='danbridge-rules-test',suffix=Date.now().toString(36),app=initializeApp({projectId},`d0-admin-${suffix}`),firestore=getFirestore(app),environment=await initializeTestEnvironment({projectId}),expected=source();
 try{
  await environment.clearFirestore();
  const binder=createFirebaseRecordSyncV2DeploymentGateSourceAttestationAdminBinder({app,firestore,expectedProjectId:projectId}),created=await binder.execute(expected),path=RECORD_SYNC_V2_DEPLOYMENT_ATTESTATION_PATH(created.targetV2Epoch,created.attestationHash),saved=(await firestore.doc(path).get()).data();
  assert.equal(created.writeCount,1);assert.equal(saved.persistedAt.constructor.name,'Timestamp');
  const replayed=await createFirebaseRecordSyncV2DeploymentGateSourceAttestationAdminBinder({app,firestore,expectedProjectId:projectId}).execute(expected);assert.equal(replayed.writeCount,0);assert.equal(replayed.persistedAt,created.persistedAt);
  const trusted=environment.authenticatedContext(`d0-owner-${suffix}`,{email:'a0965487920@gmail.com',recordSyncV2CutoverOperator:true}).firestore(),ordinary=environment.authenticatedContext(`d0-ordinary-${suffix}`,{email:'a0965487920@gmail.com'}).firestore(),ref=db=>doc(db,...path.split('/'));
  await assertSucceeds(getDoc(ref(trusted)));await assertFails(getDoc(ref(ordinary)));await assertFails(setDoc(ref(trusted),{...saved,persistedAt:serverTimestamp()}));await assertFails(updateDoc(ref(trusted),{state:'forged'}));await assertFails(deleteDoc(ref(trusted)));
  await firestore.doc(path).set({...saved,runtimePolicyHash:h(13)},{merge:false});await assert.rejects(()=>binder.execute(expected),/full expected|mismatch|hash/);await firestore.doc(path).delete();
  let committed=false,lose=true;const local=createFirebaseRecordSyncV2DeploymentGateSourceAttestationAdapter({serverTimestamp:()=>FieldValue.serverTimestamp(),getDocumentFromServer:async value=>{if(committed&&lose&&value===path){lose=false;throw new Error('D0 postcommit response loss')}return firestore.doc(value).get()},runTransaction:callback=>firestore.runTransaction(async transaction=>{const result=await callback({get:value=>transaction.get(firestore.doc(value)),set:(value,payload)=>transaction.set(firestore.doc(value),payload,{merge:false})});committed=true;return result})});
  await assert.rejects(()=>local.execute(expected),/postcommit response loss/);assert.equal((await firestore.doc(path).get()).exists,true);
  const restarted=await createFirebaseRecordSyncV2DeploymentGateSourceAttestationAdminBinder({app,firestore,expectedProjectId:projectId}).execute(structuredClone(expected));assert.equal(restarted.writeCount,0);assert.throws(()=>consumeFirebaseRecordSyncV2DeploymentGateSourceAttestationCompletion(structuredClone(restarted),{}),/native deployment attestation completion/);
  await assert.rejects(()=>binder.execute({...expected,projectId:'danbridge-d8877-staging'}),/expected project mismatch/);
 }finally{await environment.cleanup();await deleteApp(app)}
});
