import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS} from '../js/core/cloud-full-record-shadow.js';
import {createFirebaseRoleViewCandidateAdapter} from '../js/core/firebase-role-view-candidate-adapter.js';

const stable=value=>Array.isArray(value)?value.map(stable):(value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])])):value);
const hashDb=value=>JSON.stringify(stable(value));
const db=(prefix,count=2)=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,key==='lessons'?Array.from({length:count},(_,i)=>({id:`${prefix}-${i}`,paymentStatus:undefined})):[]]));
const views=()=>['scheduler','teacher','branch_manager'].map((kind,index)=>{const value=db(kind,index+1);return{viewId:kind,email:`${kind}@example.com`,kind,db:value,viewHash:hashDb(value)}});
function fake({failBatch=0}={}){const store=new Map(),events=[];let calls=0;return{store,events,async getCollectionDocuments(path){events.push(`list:${path}`);return[...store].filter(([key])=>key.startsWith(`${path}/`)&&!key.slice(path.length+1).includes('/')).map(([key,data])=>({id:key.slice(path.length+1),data:structuredClone(data)}))},async runBatchTransaction(callback){calls++;const writes=[],transaction={async get(path){events.push(`get:${path}`);const data=store.get(path);return{exists:()=>data!==undefined,data:()=>structuredClone(data)}},set(path,data){events.push(`set:${path}`);writes.push([path,structuredClone(data)])}};const result=await callback(transaction);if(calls===failBatch)throw new Error('injected');for(const row of writes)store.set(...row);return result}}}
const adapter=(source,overrides={})=>createFirebaseRoleViewCandidateAdapter({getCollectionDocuments:source.getCollectionDocuments,runBatchTransaction:source.runBatchTransaction,serverTimestamp:()=>({server:true}),actor:{uid:'owner',email:'OWNER@EXAMPLE.COM'},environment:'staging',role:'owner',hashDb,...overrides});

test('aa、老師、管理者逐筆候選寫入隔離路徑並逐筆讀回',async()=>{const source=fake(),result=await adapter(source).writeAndVerify({runId:'run-12345678',sourceHash:'source-hash-123',views:views(),batchSize:2});assert.equal(result.verified,true);assert.equal(result.viewCount,3);assert.equal(result.writes,6);assert.equal(result.readTakeover,false);for(const [path,data] of source.store){assert.match(path,/^stagingRoleViewCandidates\/danbridge\/runs\/run-12345678\/views\//);assert.deepEqual(data.createdAt,{server:true});assert.equal(data.createdByEmail,'owner@example.com')}});
test('相同 run 重跑為零寫入，內容衝突立即停止',async()=>{const source=fake(),input={runId:'run-12345678',sourceHash:'source-hash-123',views:views()};await adapter(source).writeAndVerify(input);source.events.length=0;const rerun=await adapter(source).writeAndVerify(input);assert.equal(rerun.writes,0);assert.equal(rerun.skippedWrites,6);const first=source.store.keys().next().value;source.store.get(first).record={id:'tampered'};await assert.rejects(adapter(source).writeAndVerify(input),/immutable 衝突/)});
test('批次中斷後以同一 run 只補缺筆並完成驗證',async()=>{const source=fake({failBatch:2}),input={runId:'run-12345678',sourceHash:'source-hash-123',views:views(),batchSize:1};await assert.rejects(adapter(source).writeAndVerify(input),error=>error.completedBatches===1&&error.completedWrites===1);const resumed=await adapter(source).writeAndVerify(input);assert.equal(resumed.verified,true);assert.equal(resumed.skippedWrites,1);assert.equal(resumed.writes,5)});
test('production namespace 可隔離寫入；非 Owner 與錯誤環境零讀寫',async()=>{const production=fake(),result=await adapter(production,{environment:'production'}).writeAndVerify({runId:'run-12345678',sourceHash:'source-hash-123',views:views()});assert.equal(result.verified,true);assert.ok([...production.store.keys()].every(path=>path.startsWith('productionRoleViewCandidates/')));for(const overrides of [{role:'teacher'},{role:'aa'},{environment:'wrong'}]){const source=fake();await assert.rejects(adapter(source,overrides).writeAndVerify({runId:'run-12345678',sourceHash:'source-hash-123',views:views()}),/只允許指定環境 Owner/);assert.equal(source.events.length,0)}});
