import test from 'node:test';
import assert from 'node:assert/strict';
import {deleteApp,initializeApp} from 'firebase-admin/app';
import {getFirestore,Timestamp as AdminTimestamp} from 'firebase-admin/firestore';
import {
  RECORD_SYNC_V2_CHANGE_RESERVATION_REGISTRATION_ADAPTER_SCOPE,
  RECORD_SYNC_V2_CHANGE_RESERVATION_REGISTRATION_PATH,
  consumeFirebaseRecordSyncV2ChangeReservationRegistrationCompletion,
  createFirebaseRecordSyncV2ChangeReservationRegistrationAdapter,
  createFirebaseRecordSyncV2ChangeReservationRegistrationBinder,
  normalizeFirebaseRecordSyncV2ChangeReservationRegistrationAdminSnapshot
} from '../js/core/firebase-record-sync-v2-change-reservation-registration-adapter.js';

const fakeG35=()=>({state:'complete-confirmed',transactionState:'replayed',scope:'native-admin-ci-fixed-g3-audit-receipt-capability-for-future-r0-only',environment:'staging',companyId:'danbridge',sourceV1ActivationEpoch:'active-epoch-12345',sourceFreezeId:'freeze-12345678',targetV2Epoch:'v2-epoch-12345678',seedId:'v2-genesis:'+'1'.repeat(64),parentFrozenSourceProofHash:'2'.repeat(64),identityIndexRootHash:'a'.repeat(64),identityIndexRootAuditHash:'b'.repeat(64),identityIndexRootPersistedAt:'2026-08-17T03:23:59.123456789Z',genesisAuthorityHash:'6'.repeat(64),genesisAuthorityAuditHash:'7'.repeat(64),receiptHash:'8'.repeat(64),receiptAuditHash:'9'.repeat(64),persistedAt:'2026-08-17T03:24:30.123456789Z',writeCount:0});
const projectId='danbridge-rules-test';
const config=()=>({expectedProjectId:projectId,getDocumentFromServer:async()=>null,runTransaction:async()=>{throw new Error('must not transact')},serverTimestamp:()=>({seconds:1787097600,nanoseconds:123456789})});

test('R0 fixed path與scope不接受caller alias',()=>{assert.equal(RECORD_SYNC_V2_CHANGE_RESERVATION_REGISTRATION_PATH('v2-epoch-12345678','v2-genesis:'+'a'.repeat(64)),'stagingRecordSyncV2Reservations/danbridge/epochs/v2-epoch-12345678/seeds/v2-genesis:'+'a'.repeat(64));assert.match(RECORD_SYNC_V2_CHANGE_RESERVATION_REGISTRATION_ADAPTER_SCOPE,/fixed-g35-r0-registration/)});

test('generic adapter對manual/clone G3.5在任何I/O前拒，且不能mint global R0 completion',async()=>{let reads=0,tx=0,stamps=0;const adapter=createFirebaseRecordSyncV2ChangeReservationRegistrationAdapter({...config(),getDocumentFromServer:async()=>{reads++;return null},runTransaction:async callback=>{tx++;return callback({get:async()=>null,set(){}})},serverTimestamp:()=>{stamps++;return{}}});for(const completion of [fakeG35(),structuredClone(fakeG35())])await assert.rejects(()=>adapter.execute(completion),/native G3.5 completion/);assert.equal(reads,0);assert.equal(tx,0);assert.equal(stamps,0);assert.throws(()=>consumeFirebaseRecordSyncV2ChangeReservationRegistrationCompletion(fakeG35(),{}),/native R0 completion/)});

test('R0 public input/config descriptor getter fail closed getter0/0I/O',async()=>{let calls=0,reads=0;const completion=Object.defineProperty(fakeG35(),'genesisAuthorityHash',{enumerable:true,get(){calls++;return'6'.repeat(64)}}),adapter=createFirebaseRecordSyncV2ChangeReservationRegistrationAdapter({...config(),getDocumentFromServer:async()=>{reads++;return null}});await assert.rejects(()=>adapter.execute(completion),/data field/);assert.equal(calls,0);assert.equal(reads,0);const hostile={...config()};Object.defineProperty(hostile,'beforePersistence',{enumerable:true,get(){calls++;return async()=>{}}});assert.throws(()=>createFirebaseRecordSyncV2ChangeReservationRegistrationAdapter(hostile),/own enumerable data field/);assert.throws(()=>createFirebaseRecordSyncV2ChangeReservationRegistrationAdapter({...config(),cachedGet:async()=>null}),/config fields invalid/);assert.equal(calls,0)});

test('R0 Admin snapshot不讀exists/data accessor且只接受真正Admin Timestamp',()=>{const snapshot={data(){return{persistedAt:new AdminTimestamp(1787097600,123456789),persistedBy:'fixed-ci',persistedByEmail:'fixed-ci@example.invalid'}}};let exists=0;Object.defineProperty(snapshot,'exists',{enumerable:true,get(){exists++;throw new Error('must not read')}});assert.equal(normalizeFirebaseRecordSyncV2ChangeReservationRegistrationAdminSnapshot(snapshot,AdminTimestamp).persistedAt,'2026-08-19T00:00:00.123456789Z');assert.equal(exists,0);let data=0;const hostile={};Object.defineProperty(hostile,'data',{enumerable:true,get(){data++;return()=>({})}});assert.throws(()=>normalizeFirebaseRecordSyncV2ChangeReservationRegistrationAdminSnapshot(hostile,AdminTimestamp),/data method unsafe/);assert.equal(data,0);assert.throws(()=>normalizeFirebaseRecordSyncV2ChangeReservationRegistrationAdminSnapshot({persistedAt:'2026-08-19T00:00:00.123456789Z'},AdminTimestamp),/native Admin Timestamp/);assert.throws(()=>normalizeFirebaseRecordSyncV2ChangeReservationRegistrationAdminSnapshot({persistedAt:{seconds:1787097600,nanoseconds:123456789},persistedBy:'fixed-ci',persistedByEmail:'fixed-ci@example.invalid'},AdminTimestamp),/native Admin Timestamp/)});

test('R0 Admin binder固定App、Firestore、rules-test project與Emulator host',async()=>{const name='r0-admin-focused-'+Date.now(),app=initializeApp({projectId},name),wrong=initializeApp({projectId:'wrong-project-12345'},name+'-wrong'),firestore=getFirestore(app),wrongFirestore=getFirestore(wrong),saved=process.env.FIRESTORE_EMULATOR_HOST;try{delete process.env.FIRESTORE_EMULATOR_HOST;assert.throws(()=>createFirebaseRecordSyncV2ChangeReservationRegistrationBinder({app,firestore,expectedProjectId:projectId}),/allowlist-not-yet-wired/);process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:1';assert.throws(()=>createFirebaseRecordSyncV2ChangeReservationRegistrationBinder({app,firestore,expectedProjectId:'wrong-project-12345'}),/allowlist-not-yet-wired/);await assert.rejects(()=>createFirebaseRecordSyncV2ChangeReservationRegistrationBinder({app,firestore:wrongFirestore,expectedProjectId:projectId}).execute(fakeG35()),/App\/Firestore identity/);const fixed=createFirebaseRecordSyncV2ChangeReservationRegistrationBinder({app,firestore,expectedProjectId:projectId});process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:2';await assert.rejects(()=>fixed.execute(fakeG35()),/allowlist-not-yet-wired/);process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:1';let calls=0,hostile={app,firestore,expectedProjectId:projectId};Object.defineProperty(hostile,'firestore',{enumerable:true,get(){calls++;return firestore}});assert.throws(()=>createFirebaseRecordSyncV2ChangeReservationRegistrationBinder(hostile),/own enumerable data field/);assert.equal(calls,0)}finally{if(saved===undefined)delete process.env.FIRESTORE_EMULATOR_HOST;else process.env.FIRESTORE_EMULATOR_HOST=saved;await Promise.all([deleteApp(app),deleteApp(wrong)])}});

test('R0 static dependency closure不載Admin/Web SDK且downstream只在執行Admin binder時動態載入',async()=>{const {readFile}=await import('node:fs/promises'),entry=new URL('../js/core/firebase-record-sync-v2-change-reservation-registration-adapter.js',import.meta.url),seen=new Set(),walk=async url=>{if(seen.has(url.href))return;seen.add(url.href);const source=await readFile(url,'utf8'),specs=[...source.matchAll(/\bfrom\s+['"]([^'"]+)['"]/g)].map(match=>match[1]);for(const spec of specs){assert.equal(spec.startsWith('firebase-admin'),false,url.pathname+' -> '+spec);assert.equal(spec==='firebase/firestore'||spec==='firebase/auth',false,url.pathname+' -> '+spec);if(spec.startsWith('.'))await walk(new URL(spec,url))}};await walk(entry);const source=await readFile(entry,'utf8');assert.match(source,/import\('firebase-admin\/firestore'\)/);assert.match(source,/import\('\.\/firebase-record-sync-v2-genesis-authority-audit-receipt-adapter\.js'\)/);for(const file of ['firebase-record-sync-v2-change-reservation-batch-adapter.js','firebase-record-sync-v2-change-reservation-seal-adapter.js','firebase-record-sync-v2-change-reservation-authority-v2-adapter.js']){const downstream=await readFile(new URL('../js/core/'+file,import.meta.url),'utf8');assert.equal(downstream.includes('firebase-admin'),false,file)}});
