import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {deleteApp,initializeApp} from 'firebase-admin/app';
import {getFirestore} from 'firebase-admin/firestore';
import {createFirebaseRecordSyncV2GenesisSeedReadbackBinder} from '../js/core/firebase-record-sync-v2-genesis-seed-readback-adapter.js';
import {createFirebaseRecordSyncV2GenesisAuthorityBinder} from '../js/core/firebase-record-sync-v2-genesis-authority-adapter.js';
import {
 createFirebaseRecordSyncV2GenesisSeedReadbackAdminAdapter,
 createFirebaseRecordSyncV2GenesisSeedReadbackAdminBinder,
 normalizeFirebaseRecordSyncV2GenesisSeedReadbackAdminSnapshot
} from '../js/core/firebase-record-sync-v2-genesis-seed-readback-admin-adapter.js';
import {
 createFirebaseRecordSyncV2GenesisAuthorityAdminAdapter,
 createFirebaseRecordSyncV2GenesisAuthorityAdminBinder,
 normalizeFirebaseRecordSyncV2GenesisAuthorityAdminSnapshot
} from '../js/core/firebase-record-sync-v2-genesis-authority-admin-adapter.js';

const projectId='danbridge-rules-test';
const g2Config=()=>({expectedProjectId:projectId,getDocumentFromServer:async()=>null,getCollectionPageFromServer:async()=>[],runTransaction:async()=>{throw new Error('must not transact')},serverTimestamp:()=>({seconds:1787097600,nanoseconds:123456789})});
const g3Config=()=>({expectedProjectId:projectId,getDocumentFromServer:async()=>null,runTransaction:async()=>{throw new Error('must not transact')},serverTimestamp:()=>({seconds:1787097600,nanoseconds:123456789})});

test('legacy Web G2/G3 binders在讀config或I/O前永久拒絕',()=>{let calls=0;const hostile={};Object.defineProperty(hostile,'firestore',{enumerable:true,get(){calls++;throw new Error('must not read')}});assert.throws(()=>createFirebaseRecordSyncV2GenesisSeedReadbackBinder(hostile),/disabled before I\/O; Admin\/CI-only/);assert.throws(()=>createFirebaseRecordSyncV2GenesisAuthorityBinder(hostile),/disabled before I\/O; Admin\/CI-only/);assert.equal(calls,0)});

test('Admin G2/G3 generic seam拒manual/clone source且0 I/O，config accessor getter0',async()=>{let reads=0,pages=0,transactions=0;const g2=createFirebaseRecordSyncV2GenesisSeedReadbackAdminAdapter({...g2Config(),getDocumentFromServer:async()=>{reads++;return null},getCollectionPageFromServer:async()=>{pages++;return[]},runTransaction:async()=>{transactions++}}),g3=createFirebaseRecordSyncV2GenesisAuthorityAdminAdapter({...g3Config(),getDocumentFromServer:async()=>{reads++;return null},runTransaction:async()=>{transactions++}});await assert.rejects(()=>g2.executeManifest(Object.freeze({}),Object.freeze({})),/fields|all-batches/);await assert.rejects(()=>g3.execute(Object.freeze({})),/native Admin G2 completion|fields/);assert.deepEqual({reads,pages,transactions},{reads:0,pages:0,transactions:0});let getters=0;for(const [factory,base] of [[createFirebaseRecordSyncV2GenesisSeedReadbackAdminAdapter,g2Config()],[createFirebaseRecordSyncV2GenesisAuthorityAdminAdapter,g3Config()]]){const hostile={...base};Object.defineProperty(hostile,'beforePersistence',{enumerable:true,get(){getters++;return async()=>{}}});assert.throws(()=>factory(hostile),/own enumerable data field/);assert.throws(()=>factory({...base,cachedGet:async()=>null}),/config fields invalid/)}assert.equal(getters,0)});

test('Admin G2/G3 snapshot normalization不讀exists/data accessor並保留9位Timestamp',()=>{for(const normalize of [normalizeFirebaseRecordSyncV2GenesisSeedReadbackAdminSnapshot,normalizeFirebaseRecordSyncV2GenesisAuthorityAdminSnapshot]){const stamp={seconds:1787097600,nanoseconds:123456789},snapshot={data(){return{persistedAt:stamp,persistedBy:'fixed-ci-actor',persistedByEmail:'fixed-ci@example.invalid'}}};let exists=0;Object.defineProperty(snapshot,'exists',{enumerable:true,get(){exists++;throw new Error('must not read')}});assert.equal(normalize(snapshot).persistedAt,'2026-08-19T00:00:00.123456789Z');assert.equal(exists,0);let data=0;const hostile={};Object.defineProperty(hostile,'data',{enumerable:true,get(){data++;return()=>({})}});assert.throws(()=>normalize(hostile),/data method unsafe/);assert.equal(data,0);assert.equal(normalize({data(){return undefined}}),null);assert.throws(()=>normalize({persistedAt:{seconds:1787097600,nanoseconds:1000000000}}),/Timestamp/)}});

test('Admin G2/G3 binder固定App、Firestore、rules-test project與Emulator host',async()=>{const name='g23-admin-focused-'+Date.now(),app=initializeApp({projectId},name),wrong=initializeApp({projectId:'wrong-project-12345'},name+'-wrong'),firestore=getFirestore(app),wrongFirestore=getFirestore(wrong),saved=process.env.FIRESTORE_EMULATOR_HOST;try{delete process.env.FIRESTORE_EMULATOR_HOST;for(const factory of [createFirebaseRecordSyncV2GenesisSeedReadbackAdminBinder,createFirebaseRecordSyncV2GenesisAuthorityAdminBinder])assert.throws(()=>factory({app,firestore,expectedProjectId:projectId}),/allowlist-not-yet-wired/);process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:1';for(const factory of [createFirebaseRecordSyncV2GenesisSeedReadbackAdminBinder,createFirebaseRecordSyncV2GenesisAuthorityAdminBinder]){assert.throws(()=>factory({app,firestore,expectedProjectId:'wrong-project-12345'}),/allowlist-not-yet-wired/);assert.throws(()=>factory({app,firestore:wrongFirestore,expectedProjectId:projectId}),/App\/Firestore identity/);let calls=0,hostile={app,firestore,expectedProjectId:projectId};Object.defineProperty(hostile,'firestore',{enumerable:true,get(){calls++;return firestore}});assert.throws(()=>factory(hostile),/own enumerable data field/);assert.equal(calls,0)}}finally{if(saved===undefined)delete process.env.FIRESTORE_EMULATOR_HOST;else process.env.FIRESTORE_EMULATOR_HOST=saved;await Promise.all([deleteApp(app),deleteApp(wrong)])}});

test('Admin G2/G3 static dependency graph不載Web Auth/Firestore、browser或runtime',async()=>{const g2=await readFile(new URL('../js/core/firebase-record-sync-v2-genesis-seed-readback-admin-adapter.js',import.meta.url),'utf8'),g3=await readFile(new URL('../js/core/firebase-record-sync-v2-genesis-authority-admin-adapter.js',import.meta.url),'utf8'),combined=g2+'\n'+g3;for(const forbidden of ["from 'firebase/firestore'",'firebase/auth','firebase-auth-and-cloud-sync','genesis-seed-readback-adapter.js','cloud-active-record','browser','page-controller','activation-cutover-intent','trusted-deployment-evidence'])assert.equal(combined.includes(forbidden),false,forbidden);assert.match(g2,/firebase-admin\/firestore/);assert.match(g3,/firebase-admin\/firestore/);assert.match(g3,/genesis-seed-readback-admin-adapter\.js/);assert.match(g2,/identity-index-adapter\.js/);assert.match(g2,/all-batches-capability\.js/);assert.equal((g2.match(/tx\.set\(/g)??[]).length,2);assert.equal((g3.match(/tx\.set\(/g)??[]).length,1)});
