import test from 'node:test';
import assert from 'node:assert/strict';
import {createStagingV2RulesAttestation,stagingV2RulesetHash} from '../js/core/firebase-staging-v2-rules-attestation.js';

const projectId='danbridge-d8877-staging',source='rules_version = "2";\nservice cloud.firestore { match /databases/{database}/documents { match /{document=**} { allow read: if false; } } }\n';
const ruleset=content=>({name:'ruleset-1',createTime:'2026-08-31T00:00:00Z',source:[{name:'firestore.rules',content}]});
const context=(step,hash=stagingV2RulesetHash(source))=>({manifest:{projectId,rulesetHash:hash},phase:'STAGING_RULES_ATTESTATION',step,priorStepCapabilities:{},phaseStepCapabilities:{}});
function fixture(active=source){let current=active,releases=0;const value=createStagingV2RulesAttestation({expectedProjectId:projectId,source,getFirestoreRuleset:async()=>ruleset(current),releaseFirestoreRulesetFromSource:async next=>{releases++;current=next;return ruleset(next)}});return{value,releases:()=>releases,current:()=>current}}

test('active rules exact hash時只讀preflight/readback，不建立新ruleset',async()=>{const f=fixture(),preflight=await f.value.preflight();assert.equal(preflight.matches,true);assert.equal(preflight.writeCount,0);const result=await f.value.rulesReadbackAttestation(context('STAGING_RULES_READBACK_ATTESTATION'));assert.equal(result.readCount,1);assert.equal(result.writeCount,0);assert.equal(result.capability.activeRulesetHash,stagingV2RulesetHash(source));assert.equal(f.releases(),0)});
test('active rules不同時只允許一次staging release，之後fresh readback必須exact',async()=>{const f=fixture('rules_version = "2";\n');assert.equal((await f.value.preflight()).matches,false);const result=await f.value.rulesDeployAndAttest(context('STAGING_RULES_DEPLOY_AND_ATTEST'));assert.equal(result.readCount,2);assert.equal(result.writeCount,1);assert.equal(f.releases(),1);assert.equal(f.current(),source);await assert.rejects(()=>f.value.rulesDeployAndAttest(context('STAGING_RULES_DEPLOY_AND_ATTEST')),/not required/)});
test('錯專案、錯manifest hash、錯phase與多檔ruleset全部fail closed',async()=>{assert.throws(()=>createStagingV2RulesAttestation({expectedProjectId:'production',source,getFirestoreRuleset:async()=>ruleset(source),releaseFirestoreRulesetFromSource:async()=>{}}),/blocked/);const f=fixture();await assert.rejects(()=>f.value.rulesReadbackAttestation(context('STAGING_RULES_READBACK_ATTESTATION','f'.repeat(64))),/blocked/);await assert.rejects(()=>f.value.rulesReadbackAttestation({...context('STAGING_RULES_READBACK_ATTESTATION'),phase:'READINESS'}),/blocked/);const multi=createStagingV2RulesAttestation({expectedProjectId:projectId,source,getFirestoreRuleset:async()=>({source:[{name:'firestore.rules',content:source},{name:'extra',content:'x'}]}),releaseFirestoreRulesetFromSource:async()=>{}});await assert.rejects(()=>multi.preflight(),/blocked/)});
