import test from 'node:test';
import assert from 'node:assert/strict';
import {createFirebaseRecordSyncConflictBackupAdapter} from '../js/core/firebase-record-sync-conflict-backup-adapter.js';

function fake({active=true}={}){const store=new Map(),events=[];store.set('stagingRecordSyncControls/danbridge',{schema:'danbridge-record-sync-control-v1',environment:'staging',companyId:'danbridge',state:'active',activationEpoch:'epoch-12345678',writeTakeover:true});store.set('stagingRecordSyncSafetyControls/danbridge',{schema:'danbridge-record-sync-safety-control-v1',environment:'staging',companyId:'danbridge',activationEpoch:'epoch-12345678',state:active?'active':'paused',readAllowed:true,writeAllowed:active});return{store,events,async runTransaction(callback){const writes=[],transaction={get:async path=>{events.push(`get:${path}`);const data=store.get(path);return{exists:()=>data!==undefined,data:()=>structuredClone(data)}},set:(path,data)=>{events.push(`set:${path}`);writes.push([path,structuredClone(data)])}};const result=await callback(transaction);for(const write of writes)store.set(...write);return result}}}
const adapter=(source,overrides={})=>createFirebaseRecordSyncConflictBackupAdapter({runTransaction:source.runTransaction,serverTimestamp:()=>({server:true}),actor:{uid:'owner-1',email:'OWNER@EXAMPLE.COM'},environment:'staging',role:'owner',...overrides});
const context={activationEpoch:'epoch-12345678',deviceId:'device-123',baseHash:'record-v1:'+'a'.repeat(64),targetHash:'record-v1:'+'b'.repeat(64)};
const conflicts=()=>[{path:'lessons.lesson-1.room',local:'A',remote:'B'},{path:'students.student-1.name',local:'L',remote:'R'}];

test('衝突內容先原子保存到獨立 staging 不可變命名空間',async()=>{const source=fake(),result=await adapter(source).persist(conflicts(),context);assert.equal(result.writes,1);assert.equal(result.duplicates,0);assert.equal(result.conflictCount,2);assert.ok(result.paths[0].startsWith('stagingRecordSyncConflictBackups/danbridge/epochs/epoch-12345678/'));const saved=source.store.get(result.paths[0]);assert.equal(saved.createdByEmail,'owner@example.com');assert.deepEqual(JSON.parse(saved.payload),conflicts())});
test('相同衝突重送只辨識 duplicate，不覆寫內容',async()=>{const source=fake(),first=await adapter(source).persist(conflicts(),context),before=structuredClone(source.store.get(first.paths[0])),second=await adapter(source).persist(conflicts(),context);assert.equal(second.writes,0);assert.equal(second.duplicates,1);assert.deepEqual(source.store.get(first.paths[0]),before)});
test('同一路徑既有內容不一致時 fail closed',async()=>{const source=fake(),first=await adapter(source).persist(conflicts(),context);source.store.get(first.paths[0]).payload='tampered';await assert.rejects(adapter(source).persist(conflicts(),context),/immutable 衝突/)});
test('未啟用、安全暫停、epoch 不符、非 Owner 或 production 全部零寫入',async()=>{for(const setup of [{source:fake({active:false})},{source:fake(),context:{...context,activationEpoch:'epoch-wrong'}},{source:fake(),adapter:{role:'teacher'}},{source:fake(),adapter:{environment:'production'}}]){const before=setup.source.store.size;await assert.rejects(adapter(setup.source,setup.adapter).persist(conflicts(),setup.context||context),/未啟用|安全暫停|只允許 staging Owner/);assert.equal(setup.source.store.size,before)}});
test('大型衝突會分片且每片可重組回完整 JSON',async()=>{const source=fake(),large=Array.from({length:20},(_,index)=>({path:`lessons.lesson-${index}.note`,local:'L'.repeat(200),remote:'R'.repeat(200)})),result=await adapter(source,{maxChars:1000}).persist(large,context),serialized=result.paths.map(path=>source.store.get(path).payload).join('');assert.ok(result.partCount>1);assert.deepEqual(JSON.parse(serialized),large)});
