import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,buildFullRecordShadowPlan} from '../js/core/cloud-full-record-shadow.js';
import {prepareActiveRecordSync} from '../js/core/cloud-active-record-sync.js';
import {createFirebaseActiveRecordOperationAdapter} from '../js/core/firebase-active-record-operation-adapter.js';

const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));
const db=()=>{const value=empty();value.lessons=[{id:'lesson-1',room:'A'},{id:'lesson-2',room:'A'}];return value};
function fake({environment='staging',active=true}={}){
 const store=new Map(),events=[];store.set(`${environment}RecordSyncControls/danbridge`,{schema:'danbridge-record-sync-control-v1',environment,companyId:'danbridge',state:'active',activationEpoch:'epoch-12345678',readTakeover:false,writeTakeover:active});store.set(`${environment}RecordSyncSafetyControls/danbridge`,{schema:'danbridge-record-sync-safety-control-v1',environment,companyId:'danbridge',activationEpoch:'epoch-12345678',state:active?'active':'paused',readAllowed:true,writeAllowed:active});
 return{store,events,seed(value){const documents={};for(const key of FULL_RECORD_COLLECTIONS)documents[key]=[];for(const operation of buildFullRecordShadowPlan(documents,value,{sourceHash:'seed',environment} ).operations)store.set(operation.path,structuredClone(operation.payload))},documents(){const result={};for(const key of FULL_RECORD_COLLECTIONS)result[key]=[];for(const [path,data] of store){const match=path.match(new RegExp(`^${environment}FullRecordShadows/danbridge/collections/([^/]+)/records/(.+)$`));if(match)result[match[1]].push({id:match[2],data:structuredClone(data)})}return result},async runTransaction(callback){const writes=[],transaction={get:async path=>{events.push(`get:${path}`);const data=store.get(path);return{exists:()=>data!==undefined,data:()=>structuredClone(data)}},set:(path,data)=>{events.push(`set:${path}`);writes.push([path,structuredClone(data)])}};const result=await callback(transaction);for(const row of writes)store.set(...row);return result}};
}
const adapter=(source,overrides={})=>createFirebaseActiveRecordOperationAdapter({runTransaction:source.runTransaction,serverTimestamp:()=>({server:true}),actor:{uid:'owner-1',email:'OWNER@EXAMPLE.COM'},environment:'staging',role:'owner',...overrides});
const operation=(source,mutate,overrides={})=>{const baseline=db(),local=structuredClone(baseline);mutate(local);return prepareActiveRecordSync({documentsByCollection:source.documents(),baselineDb:baseline,localDb:local,environment:'staging',deviceId:'device-a',activationEpoch:'epoch-12345678',...overrides}).operations[0]};

test('已啟用 Owner 只原子寫入目標文件與不可變完成憑證',async()=>{const source=fake();source.seed(db());const op=operation(source,value=>value.lessons[0].room='B'),result=await adapter(source).apply(op);assert.equal(result.kind,'update');assert.equal(result.revision,2);const saved=source.store.get(op.path),receipt=source.store.get(result.receiptPath);assert.equal(saved.room,undefined);assert.equal(saved.record.room,'B');assert.equal(saved.lastOperationId,op.operationId);assert.deepEqual(saved.updatedAt,{server:true});assert.equal(receipt.operationId,op.operationId);assert.equal(receipt.updatedByEmail,'owner@example.com')});
test('回應遺失後重送只讀取既有憑證且不增加 revision',async()=>{const source=fake();source.seed(db());const op=operation(source,value=>value.lessons[0].room='B'),first=await adapter(source).apply(op),revision=source.store.get(op.path).revision,second=await adapter(source).apply(op);assert.equal(first.write,true);assert.equal(second.kind,'duplicate');assert.equal(second.write,false);assert.equal(source.store.get(op.path).revision,revision)});
test('控制未啟用、epoch 不符、非 Owner 與錯誤環境全部零寫入',async()=>{for(const setup of [{source:fake({active:false})},{source:fake(),change:op=>({...op,activationEpoch:'wrong-epoch'})},{source:fake(),adapter:{role:'teacher'}},{source:fake(),adapter:{environment:'production'}}]){setup.source.seed(db());const op=operation(setup.source,value=>value.lessons[0].room='B'),before=[...setup.source.store].length;await assert.rejects(adapter(setup.source,setup.adapter).apply(setup.change?setup.change(op):op),/尚未原子啟用|只允許指定環境 Owner|identity/);assert.equal([...setup.source.store].length,before)}});
test('兩位 Owner 修改不同文件都可成功，同一文件只允許符合 revision 的一方',async()=>{const source=fake();source.seed(db());const first=operation(source,value=>value.lessons[0].room='Daniel',{deviceId:'daniel'}),second=operation(source,value=>value.lessons[1].room='Catherine',{deviceId:'catherine',startSequence:2});await adapter(source).apply(first);await adapter(source,{actor:{uid:'owner-2',email:'catherine@example.com'}}).apply(second);const stale=prepareActiveRecordSync({documentsByCollection:(()=>{const seeded=fake();seeded.seed(db());return seeded.documents()})(),baselineDb:db(),localDb:{...db(),lessons:db().lessons.map((row,index)=>index?row:{...row,room:'Stale'})},environment:'staging',deviceId:'stale',activationEpoch:'epoch-12345678'}).operations[0];await assert.rejects(adapter(source).apply(stale),/revision 衝突/);assert.equal(source.store.get(first.path).record.room,'Daniel');assert.equal(source.store.get(second.path).record.room,'Catherine')});
test('production 使用既有 production 逐筆 namespace 並完全隔離 staging',async()=>{const source=fake({environment:'production'});source.seed(db());const baseline=db(),local=structuredClone(baseline);local.lessons[0].room='P';const op=prepareActiveRecordSync({documentsByCollection:source.documents(),baselineDb:baseline,localDb:local,environment:'production',deviceId:'device-p',activationEpoch:'epoch-12345678'}).operations[0],result=await adapter(source,{environment:'production'}).apply(op);assert.ok(result.path.startsWith('productionFullRecordShadows/'));assert.ok(result.receiptPath.startsWith('productionRecordSyncOperationReceipts/'));assert.ok([...source.store.keys()].every(path=>!path.startsWith('staging')))});
