import test from 'node:test';
import assert from 'node:assert/strict';
import {recordDataHash} from '../js/core/cloud-record-data-hash.js';
import {buildProductionRecordRuntimeControl,assertProductionRecordRuntimeControl,buildProductionRecordRuntimeSafety,assertProductionRecordRuntimeSafety,advanceProductionRecordRuntimeSafety,PRODUCTION_RECORD_CONTROL_PATH,PRODUCTION_RECORD_SAFETY_PATH,productionRecordPath,productionRecordCollectionPath} from '../js/core/cloud-production-record-runtime.js';
import {createFirebaseProductionRecordOperationAdapter,createFirebaseProductionRecordBatchAdapter,createFirebaseProductionAccessMutationAdapter,createFirebaseProductionRecordStreamAdapter} from '../js/core/firebase-production-record-runtime-adapter.js';
import {buildFullRecordShadowPlan,FULL_RECORD_COLLECTIONS} from '../js/core/cloud-full-record-shadow.js';
import {prepareActiveRecordSync} from '../js/core/cloud-active-record-sync.js';

const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));
const target=()=>({...empty(),students:[{id:'student-1',name:'A'}]});
const activation=()=>{const db=target(),hash=recordDataHash(db),control=buildProductionRecordRuntimeControl({activationEpoch:'production-epoch-1',legacyVersionHash:'4fwqr7:1255035',recordDataHash:hash,sourceSha256:'a'.repeat(64),documentCount:1,activeCount:1,tombstoneCount:0,roleViewDigest:'b'.repeat(64),rollbackChannel:'rollback-pre-v2-20260901',activatedAt:'2026-09-01T04:00:00.000Z'}),safety=buildProductionRecordRuntimeSafety({control,updatedAt:'2026-09-01T04:00:00.000Z'});return{db,control,safety}};
const snapshot=value=>({exists:()=>value!==undefined,data:()=>structuredClone(value)});
const adminSnapshot=value=>({exists:value!==undefined,data:()=>structuredClone(value)});

test('production runtime 控制逐欄綁定、hash 防竄改且 safety 可暫停寫入',()=>{const {control,safety}=activation();assert.equal(assertProductionRecordRuntimeControl(control).readTakeover,true);assert.equal(assertProductionRecordRuntimeSafety(safety,{activationEpoch:control.activationEpoch}).writeAllowed,true);assert.throws(()=>assertProductionRecordRuntimeControl({...control,activeCount:2}),/activation hash|格式/);assert.throws(()=>assertProductionRecordRuntimeSafety({...safety,state:'paused',writeAllowed:true},{activationEpoch:control.activationEpoch}),/格式/)});

test('production operation 使用 Admin SDK snapshot 時仍只改一筆、原子推進權威 head、保留主文件且 receipt 使重送 exactly-once',async()=>{const {db,control,safety}=activation(),seed=buildFullRecordShadowPlan(Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]])),db,{environment:'production',sourceHash:'legacy'}).operations[0].payload,recordPath=productionRecordPath('students','student-1'),store=new Map([[PRODUCTION_RECORD_CONTROL_PATH,control],[PRODUCTION_RECORD_SAFETY_PATH,safety],[recordPath,{...seed,updatedAt:'before',updatedBy:'seed',updatedByEmail:'owner@example.com'}],['companies/danbridge/data/main',{sentinel:'unchanged'}]]),runTransaction=async callback=>{const writes=[];const result=await callback({get:async path=>adminSnapshot(store.get(path)),set:(path,value)=>writes.push([path,structuredClone(value)])});for(const [path,value] of writes)store.set(path,value);return result},adapter=createFirebaseProductionRecordOperationAdapter({runTransaction,serverTimestamp:()=> 'SERVER',actor:{uid:'owner-uid',email:'owner@example.com'},role:'owner'}),nextDb=target();nextDb.students[0].name='B';const operation=buildFullRecordShadowPlan({students:[{id:'student-1',data:store.get(recordPath)}]},nextDb,{environment:'production',sourceHash:'next'}).operations[0];Object.assign(operation,{schema:'danbridge-active-record-operation-v1',environment:'production',companyId:'danbridge',activationEpoch:control.activationEpoch,operationId:'device-1:1',deviceId:'device-1',collection:'students',recordId:'student-1',createdAt:'2026-09-01T04:01:00.000Z',baseRevision:1,nextRevision:2,baseHash:recordDataHash(db),targetHash:recordDataHash(nextDb),targetDocumentCount:1,targetActiveCount:1,targetTombstoneCount:0,baselineRecord:{},localRecord:{}});const first=await adapter.apply(operation),second=await adapter.apply(operation),savedSafety=assertProductionRecordRuntimeSafety(store.get(PRODUCTION_RECORD_SAFETY_PATH),{activationEpoch:control.activationEpoch});assert.equal(first.write,true);assert.equal(second.kind,'duplicate');assert.equal(store.get(recordPath).record.name,'B');assert.equal(store.get(recordPath).revision,2);assert.equal(savedSafety.recordDataHash,recordDataHash(nextDb));assert.equal(savedSafety.recordRevision,1);assert.equal(savedSafety.lastOperationId,operation.operationId);assert.equal('lastOperationId'in store.get(recordPath),false);assert.deepEqual(store.get('companies/danbridge/data/main'),{sentinel:'unchanged'})});

test('production 高風險批次先預覽再一次提交，多筆資料與 head 同一交易完成',async()=>{const {db,control,safety}=activation(),documents=productionDocuments(db),studentPath=productionRecordPath('students','student-1'),store=new Map([[PRODUCTION_RECORD_CONTROL_PATH,control],[PRODUCTION_RECORD_SAFETY_PATH,safety],[studentPath,documents.students[0].data]]),runTransaction=async callback=>{const writes=[],deletes=[];const result=await callback({get:async path=>snapshot(store.get(path)),set:(path,value)=>writes.push([path,structuredClone(value)]),delete:path=>deletes.push(path)});deletes.forEach(path=>store.delete(path));for(const [path,value]of writes)store.set(path,value);return result},adapter=createFirebaseProductionRecordBatchAdapter({runTransaction,serverTimestamp:()=>'SERVER',actor:{uid:'owner-uid',email:'owner@example.com'},role:'owner',now:()=>Date.parse('2026-09-01T04:03:00.000Z')}),nextDb=target();nextDb.students[0].name='B';nextDb.teachers.push({id:'teacher-1',name:'Teacher'});const plan=prepareActiveRecordSync({documentsByCollection:documents,baselineDb:db,localDb:nextDb,environment:'production',deviceId:'device-batch',activationEpoch:control.activationEpoch,createdAt:'2026-09-01T04:03:00.000Z'}),preview=await adapter.preview({activationEpoch:control.activationEpoch,reason:'restore',operations:plan.operations},'preview-request-1');assert.equal(preview.operationCount,2);assert.equal(store.get(studentPath).record.name,'A');const committed=await adapter.apply({activationEpoch:control.activationEpoch,reason:'restore',previewId:preview.previewId,operations:plan.operations},'batch-request-1'),savedSafety=assertProductionRecordRuntimeSafety(store.get(PRODUCTION_RECORD_SAFETY_PATH),{activationEpoch:control.activationEpoch});assert.equal(committed.operationCount,2);assert.equal(store.get(studentPath).record.name,'B');assert.equal(store.get(productionRecordPath('teachers','teacher-1')).record.name,'Teacher');assert.equal(savedSafety.recordDataHash,plan.targetHash);assert.equal(savedSafety.recordRevision,2);await assert.rejects(()=>adapter.apply({activationEpoch:control.activationEpoch,reason:'restore',previewId:preview.previewId,operations:plan.operations},'batch-request-2'),/部分套用|預覽/)});

test('production 權限 mutation 驗證 revision、稽核並可 exactly-once 重送',async()=>{const store=new Map(),runTransaction=async callback=>{const writes=[],deletes=[];const result=await callback({get:async path=>snapshot(store.get(path)),set:(path,value)=>writes.push([path,structuredClone(value)]),delete:path=>deletes.push(path)});deletes.forEach(path=>store.delete(path));for(const [path,value]of writes)store.set(path,value);return result},adapter=createFirebaseProductionAccessMutationAdapter({runTransaction,serverTimestamp:()=>'SERVER',deleteField:()=>({__delete:true}),actor:{uid:'owner-uid',email:'owner@example.com'},role:'owner'}),mutation={action:'upsert',email:'teacher@example.com',expectedRevision:0,payload:{displayName:'Teacher',role:'teacher',active:true,teacherId:'teacher-1'},detail:{action:'teacher-access-created',changedFields:['role','teacherId'],release:'20.26.134'}},first=await adapter.mutate(mutation,'access-request-1'),duplicate=await adapter.mutate(mutation,'access-request-1');assert.equal(first.revision,1);assert.equal(duplicate.kind,'duplicate-access');assert.equal(store.get('companyAccess/teacher@example.com').accessRevision,1);assert.equal(store.get('companyAccess/teacher@example.com').companyId,'danbridge');await assert.rejects(()=>adapter.mutate({...mutation,payload:{...mutation.payload,active:false}},'access-request-2'),/revision/)});

test('production 權限主文件、登入鏡像與稽核同一交易，角色切換會清掉舊範圍',async()=>{
 const store=new Map([['users/user-1',{email:'teacher@example.com',companyId:'danbridge',role:'branch_manager',active:true,branchIds:['old'],branchNames:['舊校區'],readOnly:true,profileNote:'keep'}]]),transactions=[];
 const runTransaction=async callback=>{const writes=[],deletes=[];const result=await callback({get:async path=>snapshot(store.get(path)),set:(path,value,options={merge:false})=>writes.push([path,structuredClone(value),options]),delete:path=>deletes.push(path)});deletes.forEach(path=>store.delete(path));for(const [path,value,options]of writes){if(options.merge){const next={...structuredClone(store.get(path)||{})};for(const [key,item]of Object.entries(value)){if(item?.__delete===true)delete next[key];else next[key]=item}store.set(path,next)}else store.set(path,value)}transactions.push({writes:writes.map(([path])=>path),deletes:[...deletes]});return result};
 const adapter=createFirebaseProductionAccessMutationAdapter({runTransaction,serverTimestamp:()=>'SERVER',deleteField:()=>({__delete:true}),actor:{uid:'owner-uid',email:'owner@example.com'},role:'owner'}),upsert={action:'upsert',email:'teacher@example.com',expectedRevision:0,userPaths:['users/user-1'],payload:{role:'teacher',active:true,teacherId:'teacher-1',teacherName:'Teacher'},detail:{action:'teacher-access-updated',release:'20.26.134'}};
 await adapter.mutate(upsert,'access-mirror-upsert-1');
 assert.equal(transactions.length,1);assert.ok(transactions[0].writes.includes('companyAccess/teacher@example.com'));assert.ok(transactions[0].writes.includes('users/user-1'));assert.ok(transactions[0].writes.includes('companyAudit/danbridge-access-mirror-upsert-1'));assert.ok(transactions[0].writes.includes('companies/danbridge/productionAccessMutationReceipts/access-mirror-upsert-1'));
 assert.equal(store.get('users/user-1').role,'teacher');assert.equal(store.get('users/user-1').profileNote,'keep');assert.equal('branchIds'in store.get('users/user-1'),false);assert.equal('readOnly'in store.get('users/user-1'),false);
 await adapter.mutate({action:'delete',email:'teacher@example.com',expectedRevision:1,userPaths:['users/user-1'],detail:{action:'teacher-access-deleted',release:'20.26.134'}},'access-mirror-delete-1');
 assert.equal(store.has('companyAccess/teacher@example.com'),false);assert.equal(store.get('users/user-1').active,false);assert.equal(store.get('users/user-1').role,'revoked');assert.equal(transactions.length,2);
});

function streamHarness(){
 const documentListeners=new Map(),collectionListeners=new Map(),states=[],applies=[];
 const adapter=createFirebaseProductionRecordStreamAdapter({
  subscribeDocument:(path,next,error)=>{documentListeners.set(path,{next,error});return()=>documentListeners.delete(path)},
  subscribeCollection:(path,next,error)=>{collectionListeners.set(path,{next,error});return()=>collectionListeners.delete(path)},
  onApply:async value=>applies.push(value),
  onState:value=>states.push(value)
 });
 const emitDocument=(path,data,{fromCache=false,hasPendingWrites=false}={})=>documentListeners.get(path).next({exists:data!==null,data,fromCache,hasPendingWrites});
 const emitCollection=(collection,documents,changes=documents.map(row=>({type:'added',...row})),{fromCache=false,hasPendingWrites=false}={})=>collectionListeners.get(productionRecordCollectionPath(collection)).next({fromCache,hasPendingWrites,documents,changes});
 const settle=async()=>{for(let index=0;index<8;index++)await new Promise(resolve=>setImmediate(resolve))};
 return{adapter,documentListeners,collectionListeners,states,applies,emitDocument,emitCollection,settle};
}

function productionDocuments(db=target()){
 const operations=buildFullRecordShadowPlan(empty(),db,{environment:'production',sourceHash:'legacy'}).operations,documents=empty();
 for(const operation of operations)documents[operation.payload.collection].push({id:operation.payload.recordId,data:operation.payload});
 return documents;
}

test('production stream 即使 safety 先抵達，仍須全 16 集合精確讀回才 ready',async()=>{
 const {db,control,safety}=activation(),app=streamHarness(),documents=productionDocuments(db);app.adapter.start();
 app.emitDocument(PRODUCTION_RECORD_SAFETY_PATH,safety);app.emitDocument(PRODUCTION_RECORD_CONTROL_PATH,control);
 for(const collection of FULL_RECORD_COLLECTIONS)app.emitCollection(collection,documents[collection]);
 await app.settle();assert.equal(app.adapter.diagnostics().state,'ready');assert.equal(app.adapter.diagnostics().initialVerified,true);assert.equal(app.applies.length,1);assert.equal(app.applies[0].hash,control.recordDataHash);assert.equal(app.applies[0].writeAllowed,true);
 app.emitDocument(PRODUCTION_RECORD_CONTROL_PATH,control);await app.settle();assert.equal(app.adapter.diagnostics().state,'ready');assert.equal(app.applies.length,1);
});

test('production stream 原子啟用時 control 與 safety 回呼順序不同不會產生假性 blocked',async()=>{
 const {db,control,safety}=activation(),app=streamHarness(),documents=productionDocuments(db);app.adapter.start();
 app.emitDocument(PRODUCTION_RECORD_SAFETY_PATH,null);app.emitDocument(PRODUCTION_RECORD_CONTROL_PATH,control);app.emitDocument(PRODUCTION_RECORD_SAFETY_PATH,safety);
 for(const collection of FULL_RECORD_COLLECTIONS)app.emitCollection(collection,documents[collection]);
 await app.settle();assert.equal(app.adapter.diagnostics().state,'ready');assert.equal(app.adapter.diagnostics().blocked,false);assert.equal(app.adapter.diagnostics().initialVerified,true);
});

test('production 舊 safety 不再被日常 runtime 接受，立即 fail closed',async()=>{
 const {control,safety}=activation(),app=streamHarness(),legacySafety={schema:'danbridge-production-record-runtime-safety-v1',environment:'production',companyId:'danbridge',activationEpoch:control.activationEpoch,state:'active',revision:1,lastEventHash:control.activationHash,readAllowed:true,writeAllowed:true,updatedAt:'2026-09-01T04:00:00.000Z'};app.adapter.start();app.emitDocument(PRODUCTION_RECORD_SAFETY_PATH,legacySafety);app.emitDocument(PRODUCTION_RECORD_CONTROL_PATH,control);await app.settle();assert.equal(app.adapter.diagnostics().state,'blocked');assert.equal(app.adapter.diagnostics().blocked,true);assert.equal(app.collectionListeners.size,0);assert.equal(app.applies.length,0);app.emitDocument(PRODUCTION_RECORD_SAFETY_PATH,safety);await app.settle();assert.equal(app.adapter.diagnostics().state,'blocked');assert.equal(app.applies.length,0);
});

test('production 寫入後 safety 與 record 任一先抵達都會收斂，重新載入仍以新 head ready',async()=>{
 const {db,control,safety}=activation(),documents=productionDocuments(db),nextDb=target();nextDb.students[0].name='B';const payload=buildFullRecordShadowPlan(documents,nextDb,{environment:'production',sourceHash:'next'}).operations[0].payload,operation={activationEpoch:control.activationEpoch,operationId:'device-1:2',createdAt:'2026-09-01T04:02:00.000Z',baseHash:recordDataHash(db),targetHash:recordDataHash(nextDb),targetDocumentCount:1,targetActiveCount:1,targetTombstoneCount:0},nextSafety=advanceProductionRecordRuntimeSafety(safety,{operation}),nextDocuments=structuredClone(documents);nextDocuments.students[0].data=payload;
 const active=streamHarness();active.adapter.start();active.emitDocument(PRODUCTION_RECORD_CONTROL_PATH,control);active.emitDocument(PRODUCTION_RECORD_SAFETY_PATH,safety);for(const collection of FULL_RECORD_COLLECTIONS)active.emitCollection(collection,documents[collection]);await active.settle();active.emitDocument(PRODUCTION_RECORD_SAFETY_PATH,nextSafety);await active.settle();assert.equal(active.adapter.diagnostics().state,'loading');assert.equal(active.adapter.diagnostics().blocked,false);active.emitCollection('students',nextDocuments.students,[{type:'modified',...nextDocuments.students[0]}]);await active.settle();assert.equal(active.adapter.diagnostics().state,'ready');assert.equal(active.applies.at(-1).hash,nextSafety.recordDataHash);
 const reloaded=streamHarness();reloaded.adapter.start();reloaded.emitDocument(PRODUCTION_RECORD_CONTROL_PATH,control);reloaded.emitDocument(PRODUCTION_RECORD_SAFETY_PATH,nextSafety);for(const collection of FULL_RECORD_COLLECTIONS)reloaded.emitCollection(collection,nextDocuments[collection]);await reloaded.settle();assert.equal(reloaded.adapter.diagnostics().state,'ready');assert.equal(reloaded.adapter.diagnostics().initialVerified,true);assert.equal(reloaded.applies[0].hash,nextSafety.recordDataHash);
});

test('production stream 對 activation 變造、實體刪除與 revision 倒退一律 fail closed',async()=>{
 for(const fault of ['control','removed','revision']){
  const {db,control,safety}=activation(),app=streamHarness(),documents=productionDocuments(db);app.adapter.start();app.emitDocument(PRODUCTION_RECORD_CONTROL_PATH,control);app.emitDocument(PRODUCTION_RECORD_SAFETY_PATH,safety);for(const collection of FULL_RECORD_COLLECTIONS)app.emitCollection(collection,documents[collection]);await app.settle();
  if(fault==='control')app.emitDocument(PRODUCTION_RECORD_CONTROL_PATH,{...control,rollbackChannel:'changed'});
  else if(fault==='removed')app.emitCollection('students',documents.students,[{type:'removed',id:'student-1',data:documents.students[0].data}]);
  else app.emitCollection('students',documents.students,[{type:'modified',id:'student-1',data:{...documents.students[0].data,revision:0}}]);
  await app.settle();assert.equal(app.adapter.diagnostics().state,'blocked',fault);assert.equal(app.adapter.diagnostics().blocked,true,fault);
 }
});

test('production stream 不採信快取 control，伺服器確認缺少時阻擋且絕不回退舊主資料',async()=>{const app=streamHarness();app.adapter.start();app.emitDocument(PRODUCTION_RECORD_CONTROL_PATH,null,{fromCache:true});await app.settle();assert.equal(app.adapter.diagnostics().state,'checking');assert.equal(app.adapter.diagnostics().blocked,false);assert.equal(app.collectionListeners.size,0);app.emitDocument(PRODUCTION_RECORD_CONTROL_PATH,null);await app.settle();assert.equal(app.adapter.diagnostics().state,'blocked');assert.equal(app.adapter.diagnostics().blocked,true);assert.equal(app.collectionListeners.size,0);assert.equal(app.applies.length,0)});

test('production stream 快取中的舊 control、safety 與逐筆資料皆不具權威性',async()=>{const {db,control,safety}=activation(),app=streamHarness(),documents=productionDocuments(db);app.adapter.start();app.emitDocument(PRODUCTION_RECORD_CONTROL_PATH,control,{fromCache:true});app.emitDocument(PRODUCTION_RECORD_SAFETY_PATH,safety,{fromCache:true});await app.settle();assert.equal(app.collectionListeners.size,0);assert.equal(app.adapter.diagnostics().freshControlVerified,false);assert.equal(app.adapter.diagnostics().freshSafetyVerified,false);app.emitDocument(PRODUCTION_RECORD_CONTROL_PATH,control);app.emitDocument(PRODUCTION_RECORD_SAFETY_PATH,safety);for(const collection of FULL_RECORD_COLLECTIONS)app.emitCollection(collection,documents[collection],undefined,{fromCache:true});await app.settle();assert.equal(app.applies.length,0);for(const collection of FULL_RECORD_COLLECTIONS)app.emitCollection(collection,documents[collection]);await app.settle();assert.equal(app.adapter.diagnostics().state,'ready');assert.equal(app.adapter.diagnostics().freshControlVerified,true);assert.equal(app.adapter.diagnostics().freshSafetyVerified,true);assert.equal(app.applies.length,1)});
