import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS} from '../js/core/cloud-full-record-shadow.js';
import {buildRoleViewChunks} from '../js/core/role-view-chunks.js';
import {createPublishedSchedulerReceiptReader,PUBLISHED_SCHEDULER_RESPONSE_SCHEMA} from '../js/core/published-scheduler-receipt.js';
const identity={kind:'scheduler',email:'aa0966626336@gmail.com',teacherId:'aa',branchIds:[]};
function make(n){const db={...Object.fromEntries(FULL_RECORD_COLLECTIONS.map(c=>[c,[]])),lessons:[{id:'l1',start:n===1?'08:00':'09:00'}]},built=buildRoleViewChunks(db,{identity,sourceRevision:n,sourceHash:'record-v1:'+String(n).repeat(64),stableRecords:true}),response={schema:PUBLISHED_SCHEDULER_RESPONSE_SCHEMA,requestId:'receipt-request-'+n,state:'committed',sourceRecordRevision:n,sourceHash:built.manifest.sourceHash,roleManifest:built.manifest,operationCount:2,notificationCount:3};return{db,built,response,head:{roleChunkManifest:built.manifest,sourceRecordRevision:n,sourceRecordHash:built.manifest.sourceHash}}}
test('receipt resolves complete current view and old retry reauthorizes latest instead of old parts',async()=>{const a=make(1),b=make(2);let head=b.head,reads=0;const reader=createPublishedSchedulerReceiptReader({identity,isActive:()=>true,readCurrentHead:async()=>{reads++;return head},readPart:async id=>b.built.chunks.find(p=>p.id===id)});const first=await reader.resolve(a.response);assert.deepEqual(first.schedulerDb,b.db);assert.equal(first.requestId,a.response.requestId);assert.equal(first.sourceRecordRevision,2);const again=await reader.resolve(a.response);assert.deepEqual(again,first);assert.equal(reads,5);reader.invalidate();await assert.rejects(reader.resolve(b.response),/revoked/)});
test('bad receipt, mismatched commit fence and missing pieces never acknowledge the queue',async()=>{const a=make(1),reader=createPublishedSchedulerReceiptReader({identity,isActive:()=>true,readCurrentHead:async()=>a.head,readPart:async()=>null});for(const field of [{state:'pending'},{operationCount:181},{notificationCount:-1},{requestId:'bad'}, {sourceHash:'record-v1:'+'2'.repeat(64)}])await assert.rejects(reader.resolve({...a.response,...field}));await assert.rejects(reader.resolve(a.response),/integrity/)});
