import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS} from '../js/core/cloud-full-record-shadow.js';
import {buildRoleViewChunks} from '../js/core/role-view-chunks.js';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';
import {createRoleViewTransportSession} from '../js/core/role-view-transport-session.js';
const identity={kind:'teacher',email:'teacher@example.test',teacherId:'t1',branchIds:[]};
const db=(count=4)=>({...Object.fromEntries(FULL_RECORD_COLLECTIONS.map(k=>[k,[]])),lessons:Array.from({length:count},(_,i)=>({id:'l'+i,title:'課程'+i,note:'中文🙂'.repeat(20)}))});
function build(revision=1,scope=identity,count=4){const built=buildRoleViewChunks(db(count),{identity:scope,sourceRevision:revision,sourceHash:'record-v1:'+String(revision%10).repeat(64),stableRecords:true});return{...built,head:{roleChunkManifest:built.manifest,sourceRecordRevision:revision,sourceRecordHash:built.manifest.sourceHash}}}
function harness(built,overrides={}){const applied=[],states=[],parts=new Map(built.chunks.map(p=>[p.id,p]));let head=built.head,enabled=true,reads=0;const session=createRoleViewTransportSession({identity:built.manifest.identity,readCurrentHead:async()=>{reads++;return head},readPart:async id=>parts.get(id),isActive:()=>enabled,apply:async(value,meta)=>applied.push({value,meta}),onState:value=>states.push(value),...overrides});return{session,applied,states,parts,setHead:value=>head=value,revoke:()=>enabled=false,get reads(){return reads}}}
for(const limit of [1,6,12,16])test(`part concurrency ${limit} is bounded and assembles the exact snapshot`,async()=>{const a=build(1,identity,80);let active=0,peak=0;const h=harness(a,{maxConcurrentReads:limit,readPart:async id=>{peak=Math.max(peak,++active);await new Promise(r=>setImmediate(r));active--;return h.parts.get(id)}});await h.session.receive(a.head);assert.equal(peak,Math.min(limit,a.chunks.length));assert.equal(active,0);const expected=db(80);expected.lessons.sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0);assert.deepEqual(h.applied[0].value,expected)});
for(const limit of [0,17,-1,1.5,Infinity])test(`invalid concurrency ${limit} rejected`,()=>assert.throws(()=>harness(build(),{maxConcurrentReads:limit}),/concurrency/));
test('exact batch gets bound fanout and keep full integrity checks and cache reauthorization',async()=>{
 const a=build(1,identity,400);let active=0,peak=0,requests=0;
 const h=harness(a,{readPart:async()=>assert.fail('single reads not expected'),readParts:async ids=>{assert.ok(ids.length<=16);requests++;peak=Math.max(peak,++active);await new Promise(resolve=>setImmediate(resolve));active--;return ids.map(id=>h.parts.get(id))}});
 assert.equal((await h.session.receive(a.head)).state,'applied');assert.equal(h.applied[0].value.lessons.length,400);assert.ok(peak<=4);assert.equal(active,0);assert.equal(requests,Math.ceil(a.chunks.length/16));
 const previous=requests;assert.equal((await h.session.receive(a.head)).state,'unchanged');assert.equal(requests,previous);assert.equal(h.reads,4);
});
for(const fault of ['partial','corrupt','revoke','invalidate'])test(`batch ${fault} never applies a partial or unauthorized snapshot`,async()=>{
 const a=build(1,identity,80);const h=harness(a,{readParts:async ids=>{const rows=ids.map(id=>h.parts.get(id));if(fault==='partial')rows.pop();if(fault==='corrupt')rows[0]={...rows[0],payload:'[]'};if(fault==='revoke')h.revoke();if(fault==='invalidate')h.session.invalidate();return rows}});
 if(['revoke','invalidate'].includes(fault))assert.equal((await h.session.receive(a.head)).state,'superseded');else await assert.rejects(h.session.receive(a.head));
 assert.equal(h.applied.length,0);assert.equal(h.session.diagnostics().cacheBytes,0);
});
for(const role of ['teacher','scheduler','branch_manager'])test(`${role}: full fenced snapshot; same data cache still reauthorizes twice`,async()=>{const scope={...identity,kind:role,...(role==='branch_manager'?{branchIds:['art_museum']}:{})},a=build(1,scope),h=harness(a);assert.equal((await h.session.receive(a.head)).state,'applied');assert.deepEqual(h.applied[0].value,db());assert.equal(h.reads,2);await h.session.receive(a.head);assert.equal(h.reads,4);assert.equal(h.session.diagnostics().revision,1)});
test('ordinary legacy data remains legacy with zero extra network reads',async()=>{const a=build(),h=harness(a);assert.deepEqual(await h.session.receive({db:db()}),{state:'legacy'});assert.equal(h.reads,0);assert.equal(h.applied.length,0)});
for(const invalid of ['scope','digest','index','path','source','counts','missing'])test(`reject ${invalid} before requesting a single part`,async()=>{const a=build(),head=structuredClone(a.head),m=head.roleChunkManifest;if(invalid==='scope')m.identity.email='other@example.test';if(invalid==='digest')m.digest='a'.repeat(64);if(invalid==='index')m.chunkIds.push(m.chunkIds[0]);if(invalid==='path')m.chunkIds[0]='../secret';if(invalid==='source')head.sourceRecordHash='record-v1:'+'a'.repeat(64);if(invalid==='counts')m.counts.lessons=-1;if(invalid==='missing')head.roleChunkManifest=null;if(!['digest','missing'].includes(invalid)){const{digest,...body}=m;m.digest=sha256Canonical(body)}let reads=0;const h=harness(a,{readPart:async()=>{reads++;assert.fail('must reject first')}});await assert.rejects(h.session.receive(head));assert.equal(reads,0);assert.equal(h.applied.length,0)});
test('missing/corrupted part cannot fall back to db embedded beside manifest',async()=>{const a=build(),h=harness(a,{readPart:async()=>null});await assert.rejects(h.session.receive({...a.head,db:db()}));assert.equal(h.applied.length,0);await assert.rejects(h.session.receive({db:db()}),/downgrade/)});
test('pending old generation cannot replace new legacy or new chunk snapshot',async()=>{const a=build(1),b=build(2);let release,hold=true;const gate=new Promise(r=>release=r),h=harness(a,{readPart:async id=>{if(hold)await gate;return h.parts.get(id)}});for(const p of b.chunks)h.parts.set(p.id,p);const pending=h.session.receive(a.head);await new Promise(r=>setImmediate(r));hold=false;h.setHead(b.head);await h.session.receive(b.head);release();assert.equal((await pending).state,'superseded');assert.deepEqual(h.applied.map(x=>x.meta.sourceRecordRevision),[2]);await assert.rejects(h.session.receive({db:db()}),/downgrade/)});
for(const action of ['invalidate','revoke'])test(`${action} during read prevents applying or retaining a foreign account cache`,async()=>{const a=build();let release;const gate=new Promise(r=>release=r),h=harness(a,{readPart:async id=>{await gate;return h.parts.get(id)}}),pending=h.session.receive(a.head);await new Promise(r=>setImmediate(r));if(action==='invalidate')h.session.invalidate();else h.revoke();release();assert.equal((await pending).state,'superseded');assert.equal(h.applied.length,0);assert.equal(h.session.diagnostics().cacheBytes,0)});
test('head changes during loading: retry latest, never mix generations',async()=>{const a=build(1),b=build(2);let n=0;const h=harness(a,{readCurrentHead:async()=>++n===1?a.head:b.head});for(const p of b.chunks)h.parts.set(p.id,p);await h.session.receive(a.head);assert.deepEqual(h.applied.map(x=>x.meta.sourceRecordRevision),[2])});
test('same revision conflict and backwards head cannot apply',async()=>{const a=build(2),h=harness(a);await h.session.receive(a.head);h.setHead(build(1).head);await assert.rejects(h.session.receive(a.head),/backwards/);const bad=structuredClone(a.head),m=bad.roleChunkManifest;m.counts.students=1;const{digest,...body}=m;m.digest=sha256Canonical(body);h.setHead(bad);await assert.rejects(h.session.receive(bad),/Conflicting/);assert.equal(h.applied.length,1)});
test('same generation can retry after offline and UI apply failure; ready only after apply',async()=>{const a=build();let offline=true,failApply=true;const h=harness(a,{readPart:async id=>{if(offline)throw Error('offline');return h.parts.get(id)},apply:async(value,meta)=>{if(failApply)throw Error('UI apply failed');h.applied.push({value,meta})}});await assert.rejects(h.session.receive(a.head),/offline/);offline=false;await assert.rejects(h.session.receive(a.head),/UI apply/);assert.equal(h.session.diagnostics().revision,-1);failApply=false;await h.session.receive(a.head);assert.equal(h.session.diagnostics().revision,1)});
test('bounded cache evicts without changing complete snapshot',async()=>{const a=build(1,identity,40),h=harness(a,{maxCacheBytes:1000});await h.session.receive(a.head);assert.ok(h.session.diagnostics().cacheBytes<=1000);assert.equal(h.applied[0].value.lessons.length,40);h.session.invalidate();assert.equal(h.session.diagnostics().cacheCount,0)});
test('late older announcement must not cancel newer in-flight snapshot',async()=>{const a=build(1),b=build(2);let release;const gate=new Promise(r=>release=r),h=harness(b,{readPart:async id=>{await gate;return h.parts.get(id)}});const pending=h.session.receive(b.head);await new Promise(r=>setImmediate(r));assert.equal((await h.session.receive(a.head)).state,'superseded');release();assert.equal((await pending).state,'applied');assert.deepEqual(h.applied.map(x=>x.meta.sourceRecordRevision),[2])});
test('malformed announcement cancels an older in-flight application',async()=>{const a=build();let release;const gate=new Promise(r=>release=r),h=harness(a,{readPart:async id=>{await gate;return h.parts.get(id)}});const pending=h.session.receive(a.head);await new Promise(r=>setImmediate(r));await assert.rejects(h.session.receive({roleChunkManifest:null}));release();assert.equal((await pending).state,'superseded');assert.equal(h.applied.length,0)});
test('aggregate decoded snapshot memory limit rejects before assembly',async()=>{const a=build(1,identity,40),h=harness(a,{maxSnapshotBytes:1000});await assert.rejects(h.session.receive(a.head),/memory budget/);assert.equal(h.applied.length,0);assert.equal(h.session.diagnostics().cacheBytes,0)});
test('duplicate server announcement reauthorizes but does not parse and render again',async()=>{const a=build(1,identity,40);let parts=0;const h=harness(a,{readPart:async id=>{parts++;return h.parts.get(id)}});await h.session.receive(a.head);const before=parts;for(let i=0;i<20;i++)assert.equal((await h.session.receive(a.head)).state,'unchanged');assert.equal(h.applied.length,1);assert.equal(parts,before);assert.equal(h.reads,42)});
test('same authority can advance report visibility without accepting stale publication or a different source hash',async()=>{
 const a=build(),h=harness(a);await h.session.receive(a.head);
 const next=buildRoleViewChunks(db(5),{identity,sourceRevision:1,sourceHash:a.manifest.sourceHash,publicationRevision:1,stableRecords:true});
 const head={...a.head,roleChunkManifest:next.manifest};for(const p of next.chunks)h.parts.set(p.id,p);h.setHead(head);
 assert.equal((await h.session.receive(head)).state,'applied');assert.equal(h.applied.at(-1).value.lessons.length,5);
 assert.equal((await h.session.receive(a.head)).state,'superseded');
 const wrong=buildRoleViewChunks(db(5),{identity,sourceRevision:1,sourceHash:'record-v1:'+'a'.repeat(64),publicationRevision:2,stableRecords:true});
 await assert.rejects(h.session.receive({...head,sourceRecordHash:wrong.manifest.sourceHash,roleChunkManifest:wrong.manifest}),/Conflicting role authority/);
 assert.equal(h.applied.length,2);
});
