import test from 'node:test';
import assert from 'node:assert/strict';
import {FULL_RECORD_COLLECTIONS,buildFullRecordShadowPlan,rebuildFullRecordShadowDb} from '../js/core/cloud-full-record-shadow.js';
import {prepareActiveRecordSync} from '../js/core/cloud-active-record-sync.js';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';
import {createStagingV2ActiveRecordOperationSender,normalizeStagingV2FirestoreValue,stagingV2H0GenesisBaselineDocuments} from '../js/core/staging-v2-active-record-browser-bridge.js';

const activationEpoch='activation-v2-browser-12345',deviceId='device-v2-browser-12345',uid='owner-v2-browser-12345',email='owner.v2@example.com',createdAt='2026-08-30T13:00:00.000000001Z',hex=value=>String(value).repeat(64);
const empty=()=>Object.fromEntries(FULL_RECORD_COLLECTIONS.map(key=>[key,[]]));
const db=()=>({...empty(),lessons:[{id:'lesson-v2-browser-12345',room:'A'}]});
function documents(value){const rows=empty(),plan=buildFullRecordShadowPlan(rows,value,{sourceHash:'seed',environment:'staging'});for(const operation of plan.operations){const [,collection,id]=operation.path.match(/collections\/([^/]+)\/records\/(.+)$/);rows[collection].push({id,data:structuredClone(operation.payload)})}return rows}
function operation(mutator){const baseline=db(),local=structuredClone(baseline);mutator(local);return prepareActiveRecordSync({documentsByCollection:documents(baseline),baselineDb:baseline,localDb:local,environment:'staging',deviceId,activationEpoch,startSequence:1,createdAt}).operations[0]}

test('永久日誌操作在排入前保存精確 V2 baseline/local envelope 與固定 createdAt',()=>{const row=operation(value=>value.lessons[0].room='B');assert.equal(row.createdAt,createdAt);assert.equal(row.baselineRecord.revision,1);assert.equal(row.baselineRecord.record.room,'A');assert.equal(row.localRecord.revision,1);assert.equal(row.localRecord.record.room,'B');assert.equal(row.baseRevision,1);assert.equal(row.nextRevision,2);assert.match(row.baselineRecord.recordHash,/^record-item-v1:[a-f0-9]{64}$/);assert.match(row.localRecord.recordHash,/^record-item-v1:[a-f0-9]{64}$/)});

test('H0 legacy shadow只保留內容並固定轉成sealed Genesis revision 1，create仍從0開始',()=>{const legacy=documents(db());legacy.lessons[0].data.revision=17;const normalized=stagingV2H0GenesisBaselineDocuments(legacy),rebuilt=rebuildFullRecordShadowDb(normalized,{environment:'staging'}).db,local=structuredClone(rebuilt);local.lessons[0].room='B';local.lessons.push({id:'lesson-v2-browser-new',room:'N'});const plan=prepareActiveRecordSync({documentsByCollection:normalized,baselineDb:rebuilt,localDb:local,environment:'staging',deviceId,activationEpoch,startSequence:1,createdAt});assert.equal(normalized.lessons[0].data.revision,1);assert.equal(legacy.lessons[0].data.revision,17);assert.equal(plan.operationCount,2);const updated=plan.operations.find(row=>row.recordId==='lesson-v2-browser-12345'),created=plan.operations.find(row=>row.recordId==='lesson-v2-browser-new');assert.deepEqual([updated.type,updated.baseRevision,updated.nextRevision],['update',1,2]);assert.deepEqual([created.type,created.baseRevision,created.nextRevision],['create',0,1]);assert.ok(Object.isFrozen(normalized));assert.ok(Object.isFrozen(normalized.lessons[0].data));});

test('H0 normalizer拒絕缺集合、錯路徑identity、accessor與無效changes序號',()=>{const missing=documents(db());delete missing.branches;assert.throws(()=>stagingV2H0GenesisBaselineDocuments(missing),/fields invalid/);const wrong=documents(db());wrong.lessons[0].data.recordId='other';assert.throws(()=>stagingV2H0GenesisBaselineDocuments(wrong),/identity invalid/);const hostile=documents(db());Object.defineProperty(hostile.lessons[0],'data',{enumerable:true,get(){throw new Error('getter executed')}});assert.throws(()=>stagingV2H0GenesisBaselineDocuments(hostile),/invalid field/);const changes=documents({...empty(),changes:[{id:'not-used',kind:'edit'}]});changes.changes[0].data.recordIndex=3;assert.throws(()=>stagingV2H0GenesisBaselineDocuments(changes),/changes/);});

test('V2 operation sender只送一筆已保存 envelope，created/replayed轉成現有 worker receipt',async()=>{const row=operation(value=>value.lessons[0].room='B'),sent=[];let transactionState='created';const sender=createStagingV2ActiveRecordOperationSender({browserClient:{save:async payload=>{sent.push(structuredClone(payload));return{transactionState,activationEpoch,resultHeadHash:hex('a'),commitHash:hex('b'),saveId:row.operationId,operationCount:1,persistedAt:'2026-08-30T13:00:01.000Z'}}},getActor:()=>({uid,email})}),created=await sender.apply(row);assert.equal(created.kind,'update');assert.equal(created.write,true);assert.equal(created.revision,2);assert.equal(sent[0].save.createdAt,createdAt);assert.deepEqual(sent[0].baselineRecords,[row.baselineRecord]);assert.deepEqual(sent[0].localRecords,[row.localRecord]);transactionState='replayed';const replayed=await sender.apply(row);assert.deepEqual({kind:replayed.kind,write:replayed.write,revision:replayed.revision},{kind:'duplicate',write:false,revision:2})});

test('changes必須走獨立 immutable append；錯 actor、tamper envelope與不固定時間均 fail closed',async()=>{const rows=empty(),local=empty();local.changes=[{id:'audit-v2-browser-12345',kind:'edit'}];const change=prepareActiveRecordSync({documentsByCollection:rows,baselineDb:empty(),localDb:local,environment:'staging',deviceId,activationEpoch,createdAt}).operations[0],client={save:async()=>{throw new Error('must not send')}};await assert.rejects(()=>createStagingV2ActiveRecordOperationSender({browserClient:client,getActor:()=>({uid,email})}).apply(change),/journal operation invalid/);const row=operation(value=>value.lessons[0].room='B');await assert.rejects(()=>createStagingV2ActiveRecordOperationSender({browserClient:client,getActor:()=>({uid:'bad',email})}).apply(row),/actor invalid/);await assert.rejects(()=>createStagingV2ActiveRecordOperationSender({browserClient:client,getActor:()=>({uid,email})}).apply({...row,localRecord:{...row.localRecord,revision:99}}),/envelope mismatch|revision/);assert.throws(()=>prepareActiveRecordSync({documentsByCollection:documents(db()),baselineDb:db(),localDb:db(),environment:'staging',deviceId,activationEpoch,createdAt:'not-a-time'}),/設定無效/)});

test('Firestore Timestamp保留9位nanoseconds；accessor與custom prototype不會被讀取',()=>{class BrowserTimestamp{constructor(seconds,nanoseconds){this.seconds=seconds;this.nanoseconds=nanoseconds}toDate(){return new Date(this.seconds*1000)}}const value={persistedAt:new BrowserTimestamp(1788187238,726000000),nested:[1,{ok:true}]},normalized=normalizeStagingV2FirestoreValue(value);assert.deepEqual(normalized,{persistedAt:'2026-08-31T14:40:38.726000000Z',nested:[1,{ok:true}]});assert.equal(sha256Canonical({persistedAt:normalized.persistedAt,persistedBy:'service-account:danbridge-staging-v2',persistedByEmail:'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com'}),'a20838b7348f0afb9d656ca91dc666e02fcf5eb90d8638e2a5ff564d5f28e141');let calls=0;const hostile={};Object.defineProperty(hostile,'secret',{enumerable:true,get(){calls++;return'no'}});assert.throws(()=>normalizeStagingV2FirestoreValue(hostile),/invalid field/);assert.equal(calls,0);assert.throws(()=>normalizeStagingV2FirestoreValue(Object.assign(Object.create({}),{a:1})),/invalid object/)});
