import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {STAGING_V2_AUTHORITY_SAVE_APP_ID,STAGING_V2_AUTHORITY_SAVE_ORIGINS,STAGING_V2_AUTHORITY_SAVE_PROJECT_ID,STAGING_V2_AUTHORITY_SAVE_RESPONSE_SCHEMA} from '../js/core/staging-v2-authority-save-http-gateway.js';
import {STAGING_V2_AUTHORITY_SAVE_PATH,createStagingV2AuthoritySaveBrowserClient} from '../js/core/staging-v2-authority-save-browser-client.js';

const origin=STAGING_V2_AUTHORITY_SAVE_ORIGINS[0],uid='owner-staging-12345',email='owner.staging@example.com',saveId='save-staging-v2-12345',hex=value=>String(value).repeat(64),user={uid,email,emailVerified:true};
const payload=()=>({save:{saveId,deviceId:'device-staging-12345',actorUid:uid,actorEmail:email,createdAt:'2026-08-30T12:00:00.000Z'},changedKeys:[],baselineRecords:[],localRecords:[]});
const receipt=()=>({schema:STAGING_V2_AUTHORITY_SAVE_RESPONSE_SCHEMA,state:'complete-confirmed',transactionState:'created',projectId:STAGING_V2_AUTHORITY_SAVE_PROJECT_ID,activationEpoch:'activation-epoch-12345',resultHeadHash:hex('a'),commitHash:hex('b'),saveId,operationCount:1,persistedAt:'2026-08-30T12:00:01.000Z',writeCount:4});
function setup(overrides={}){let current=user,lastFetch=null;const cfg={projectId:STAGING_V2_AUTHORITY_SAVE_PROJECT_ID,appId:STAGING_V2_AUTHORITY_SAVE_APP_ID,origin,getCurrentUser:()=>current,getIdToken:async()=> 'id-token-12345',getLimitedUseAppCheckToken:async()=> 'app-check-token-12345',fetch:async(url,options)=>{lastFetch={url,options};return{status:200,text:async()=>JSON.stringify(receipt())}},timeoutMs:5000,...overrides},client=createStagingV2AuthoritySaveBrowserClient(cfg);return{client,lastFetch:()=>lastFetch,setCurrent:value=>{current=value}}}

test('browser client固定 staging same-origin endpoint、短效兩 token 與 no-store/omit',async()=>{const fixture=setup(),result=await fixture.client.save(payload()),sent=fixture.lastFetch();assert.equal(fixture.client.endpoint,origin+STAGING_V2_AUTHORITY_SAVE_PATH);assert.equal(result.saveId,saveId);assert.equal(sent.url,origin+STAGING_V2_AUTHORITY_SAVE_PATH);assert.equal(sent.options.method,'POST');assert.equal(sent.options.cache,'no-store');assert.equal(sent.options.credentials,'omit');assert.equal(sent.options.redirect,'error');assert.equal(sent.options.referrerPolicy,'no-referrer');assert.equal(sent.options.headers.authorization,'Bearer id-token-12345');assert.equal(sent.options.headers['x-firebase-appcheck'],'app-check-token-12345');assert.equal(sent.options.headers['x-danbridge-request-id'],saveId);const body=JSON.parse(sent.options.body);assert.equal(body.projectId,STAGING_V2_AUTHORITY_SAVE_PROJECT_ID);assert.equal(body.requestId,saveId)});

test('登入身分在取 token 前後或 response 前改變會 fail closed',async()=>{let current=user;const client=createStagingV2AuthoritySaveBrowserClient({projectId:STAGING_V2_AUTHORITY_SAVE_PROJECT_ID,appId:STAGING_V2_AUTHORITY_SAVE_APP_ID,origin,getCurrentUser:()=>current,getIdToken:async()=>{current={uid:'other-owner-12345',email:'other@example.com',emailVerified:true};return'id-token-12345'},getLimitedUseAppCheckToken:async()=>'app-check-token-12345',fetch:async()=>{throw new Error('must not fetch')},timeoutMs:5000});await assert.rejects(()=>client.save(payload()),/identity changed/)});

test('payload actor、production origin、server blocked 與 oversized response 都拒絕',async()=>{const wrong=payload();wrong.save.actorUid='other-owner-12345';await assert.rejects(()=>setup().client.save(wrong),/actor mismatch/);assert.throws(()=>createStagingV2AuthoritySaveBrowserClient({projectId:STAGING_V2_AUTHORITY_SAVE_PROJECT_ID,appId:STAGING_V2_AUTHORITY_SAVE_APP_ID,origin:'https://danbridge-d8877.web.app',getCurrentUser:()=>user,getIdToken:async()=>'',getLimitedUseAppCheckToken:async()=>'',fetch:async()=>{},timeoutMs:5000}),/config invalid/);const blocked=setup({fetch:async()=>({status:403,text:async()=>JSON.stringify({code:'OWNER_REQUIRED'})})});await assert.rejects(()=>blocked.client.save(payload()),/OWNER_REQUIRED/);const huge=setup({fetch:async()=>({status:200,text:async()=>'x'.repeat(70*1024)})});await assert.rejects(()=>huge.client.save(payload()),/too large/)});

test('browser client不依賴 firebase-admin、Firestore direct write 或 production',async()=>{const source=await readFile(new URL('../js/core/staging-v2-authority-save-browser-client.js',import.meta.url),'utf8');for(const forbidden of ['firebase-admin','firebase/firestore','runTransaction','setDoc','danbridge-d8877.web.app'])assert.equal(source.includes(forbidden),false,forbidden);assert.match(source,/getLimitedUseAppCheckToken/);assert.match(source,/credentials:'omit'/);assert.match(source,/cache:'no-store'/)});

test('App Check完成後頁面接上固定 staging client，Hosting 仍只 rewrite 精確 Function path',async()=>{const [runtime,html,firebaseRaw]=await Promise.all([readFile(new URL('../js/core/firebase-auth-and-cloud-sync.module.js',import.meta.url),'utf8'),readFile(new URL('../index.html',import.meta.url),'utf8'),readFile(new URL('../firebase.json',import.meta.url),'utf8')]);assert.equal(runtime.includes('staging-v2-authority-save-browser-client'),true);assert.equal(runtime.includes('getLimitedUseToken(stagingV2AppCheck)'),true);assert.equal(runtime.includes("DANBRIDGE_ENVIRONMENT==='staging'?initializeAppCheck"),true);assert.equal(html.includes(STAGING_V2_AUTHORITY_SAVE_PATH),false);const firebase=JSON.parse(firebaseRaw),rewrite=firebase.hosting.rewrites.find(row=>row.source===STAGING_V2_AUTHORITY_SAVE_PATH);assert.deepEqual(rewrite,{source:STAGING_V2_AUTHORITY_SAVE_PATH,function:{functionId:'stagingV2AuthoritySave',region:'asia-east1'}})});
