import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';

const require=createRequire(import.meta.url);
test('Gen2 function entry固定 Node22、region、service account、public transport與精確 Hosting rewrite',async()=>{const exported=require('../functions/index.cjs'),endpoint=exported.stagingV2AuthoritySave?.__endpoint,[pkg,firebase]=await Promise.all([readFile(new URL('../package.json',import.meta.url),'utf8').then(JSON.parse),readFile(new URL('../firebase.json',import.meta.url),'utf8').then(JSON.parse)]);assert.ok(endpoint);assert.equal(endpoint.platform,'gcfv2');assert.deepEqual(endpoint.region,['asia-east1']);assert.equal(endpoint.serviceAccountEmail,'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com');assert.deepEqual(endpoint.httpsTrigger.invoker,['public']);assert.equal(endpoint.maxInstances,10);assert.equal(endpoint.concurrency,8);assert.equal(pkg.main,'functions/index.cjs');assert.equal(pkg.engines.node,'22');assert.equal(pkg.dependencies.firebase,'12.17.1');assert.equal(Object.hasOwn(pkg.devDependencies,'firebase'),false);assert.equal(pkg.dependencies['firebase-functions'],'7.3.2');assert.equal(pkg.dependencies['firebase-admin'],'14.2.0');assert.equal(firebase.functions.source,'.');assert.equal(firebase.functions.runtime,'nodejs22');assert.deepEqual(firebase.hosting.rewrites,[{source:'/api/staging-v2/authority-save',function:{functionId:'stagingV2AuthoritySave',region:'asia-east1'}}])});

test('Gen2 function entry的runtime/save blocker只記錄錯誤名稱與訊息，不輸出stack或憑證',async()=>{const source=await readFile(new URL('../functions/index.cjs',import.meta.url),'utf8');assert.match(source,/STAGING_V2_RUNTIME_BLOCKED/);assert.match(source,/STAGING_V2_SAVE_BLOCKED/);assert.equal(source.match(/JSON\.stringify\(\{name,message\}\)/g)?.length,2);assert.doesNotMatch(source,/error\.stack|GOOGLE_APPLICATION_CREDENTIALS.*console|access[_-]?token.*console|authorization.*console|payload.*console/i)});

test('Gen2 server authority adapter不載入瀏覽器版Firebase dependency graph',async()=>{const [authority,paths]=await Promise.all([readFile(new URL('../js/core/firebase-active-record-authority-save-v2-adapter.js',import.meta.url),'utf8'),readFile(new URL('../js/core/firebase-record-sync-v2-genesis-paths.js',import.meta.url),'utf8')]);assert.match(authority,/from '\.\/firebase-record-sync-v2-genesis-paths\.js'/);assert.doesNotMatch(authority,/firebase-record-sync-v2-genesis-seed-batch-adapter/);assert.doesNotMatch(paths,/from ['"]firebase(?:\/|['"])/);assert.match(paths,/RECORD_SYNC_V2_GENESIS_BATCH_RECORD_PATH/)});

test('Gen2 authority router把H0送到H1＋完整baseline，H1 response-loss先補齊baseline才允許Hn',async()=>{const source=await readFile(new URL('../js/core/firebase-active-record-authority-save-chain-v2-adapter.js',import.meta.url),'utf8');assert.match(source,/createFirebaseRecordSyncV2PostCutoverCloudRecoveryV2Binder/);assert.match(source,/createFirebaseActiveRecordAuthoritySaveV2CloudRuntimeBinder/);assert.match(source,/createFirebaseActiveRecordV2H1BaselineCloudRuntime/);assert.match(source,/schema==='danbridge-active-record-v2-structural-head0-v2'&&revision===0/);assert.match(source,/const completion=await h1\.execute\(await recovery\.recover\(\),requestValue\);await baseline\.execute\(completion\);return completion/);assert.match(source,/schema===ACTIVE_RECORD_AUTHORITY_V2_HEAD_SCHEMA&&revision===1/);assert.match(source,/const completion=await h1\.recover\(\);await baseline\.execute\(completion\)/);assert.match(source,/Number\.isSafeInteger\(revision\)&&revision>1/)});

test('Gen2 H1 binder保留固定Cloud boundary內的durable recovery入口',async()=>{const source=await readFile(new URL('../js/core/firebase-active-record-authority-save-v2-adapter.js',import.meta.url),'utf8');assert.match(source,/createFirebaseActiveRecordAuthoritySaveV2CloudRuntimeBinder/);assert.match(source,/recover:\(\)=>bound\.recover\(\)/)});

test('H1 baseline inventory把Firestore hash路徑順序還原成Genesis canonical批次順序後才核對receipt',async()=>{const source=await readFile(new URL('../js/core/firebase-active-record-v2-h1-baseline-cloud-runtime.js',import.meta.url),'utf8');assert.match(source,/collectionOrder=new Map\(FULL_RECORD_COLLECTIONS/);assert.match(source,/\.sort\(compareGenesis\),verified=verifyReceipt/);assert.match(source,/collection==='changes'&&left\.recordIndex!==right\.recordIndex/)});

test('H1 baseline inventory固定有界並行讀取Genesis batches避免單次Function逾時',async()=>{const source=await readFile(new URL('../js/core/firebase-active-record-v2-h1-baseline-cloud-runtime.js',import.meta.url),'utf8');assert.match(source,/INVENTORY_CONCURRENCY=8/);assert.match(source,/batches=await bounded\(pending/);assert.match(source,/Math\.min\(INVENTORY_CONCURRENCY/)});
