import test from 'node:test';
import assert from 'node:assert/strict';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';
import {createStagingV2ActivationSupervisor,STAGING_V2_SUPERVISOR_PHASES} from '../js/core/staging-v2-activation-supervisor.js';
import {buildStagingV2PostAtomicRecoveryEvidence,STAGING_V2_POST_ATOMIC_RECOVERY_STATUS} from '../js/core/staging-v2-post-atomic-recovery-evidence.js';

const hex=value=>String(value).repeat(64);
const runMetadata={runId:'33405051938',runAttempt:1,headSha:'e3dc345a5ae74f9759f4766eae776724df3720dc',headBranch:'main',event:'workflow_dispatch',status:'completed',conclusion:'failure',repository:'Danbridge777/danbridge-scheduler-v11',workflowPath:'.github/workflows/staging-v2-atomic.yml'};
const runKey='gh_33405051938_1_e3dc345a5ae7';
function manifest(){const body={schema:'danbridge-staging-v2-activation-supervisor-manifest-v1',runId:runKey,requestHash:hex('1'),environment:'staging',companyId:'danbridge',projectId:'danbridge-d8877-staging',serviceAccountEmail:'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com',rulesetHash:hex('2'),runtimePolicyHash:hex('3'),runtimeAdapterHash:hex('4'),clientWiringHash:hex('5'),firestoreRulesDeployAllowed:false,hostingDeployAllowed:false,productionAllowed:false,timeMachineAllowed:false,atomicActivationAllowed:true};return{...body,manifestHash:sha256Canonical(body)}}
function phaseResult(phase){return{schema:'danbridge-staging-v2-supervisor-phase-result-v1',phase,status:'complete',receiptHash:sha256Canonical({phase}),readCount:phase==='POST_CUTOVER_RECOVERY'?36:0,writeCount:phase==='ATOMIC_ACTIVATION'?4:0,firestoreRulesDeployed:false,hostingDeployed:false,productionTouched:false,timeMachineTouched:false,capability:{phase}}}
async function blockedRows(){const rows=[],actions=Object.fromEntries(STAGING_V2_SUPERVISOR_PHASES.map(phase=>[phase,async()=>phaseResult(phase)]));actions.H1_SAVE=async()=>{throw new Error('separate H1 input required')};actions.ROLLBACK=async()=>phaseResult('ROLLBACK');const journal={append:async row=>rows.push(structuredClone(row)),readAll:async()=>structuredClone(rows)},supervisor=createStagingV2ActivationSupervisor({rawManifest:manifest(),actions,journal});await assert.rejects(()=>supervisor.run(),/terminal blocked/);return rows}
function recovery(){return{state:'complete-confirmed',transactionState:'recovered',scope:'native-admin-ci-fixed-twelve-document-read-only-post-cutover-recovery-capability-for-first-daily-only',environment:'staging',companyId:'danbridge',projectId:'danbridge-d8877-staging',sourceV1ActivationEpoch:'source-v1-epoch',sourceFreezeId:'source-freeze-id',targetV2Epoch:'target-v2-epoch',seedId:'v2-genesis:'+hex('6'),identityIndexRootHash:hex('7'),identityIndexRootAuditHash:hex('8'),identityIndexRootPersistedAt:'2026-08-31T14:00:00.000000001Z',authorityRootHash:hex('9'),candidateControlHash:hex('a'),candidateHeadHash:hex('b'),candidatePairAuditHash:hex('c'),activationIntentHash:hex('d'),activationIntentAuditHash:hex('e'),deploymentAttestationHash:hex('f'),deploymentAttestationAuditHash:hex('1'),deploymentEvidenceHash:hex('2'),deploymentEvidenceAuditHash:hex('3'),rulesetHash:hex('4'),runtimePolicyHash:hex('5'),orderedGateSetHash:hex('6'),candidatePolicyHash:hex('7'),activeHeadHash:hex('8'),activeControlHash:hex('9'),activationReceiptHash:hex('a'),atomicAuditHash:hex('b'),fenceHash:hex('c'),persistedAt:'2026-08-31T14:01:00.000000001Z',writeCount:0}}

test('failed workflow 的 atomic+recovery durable poststate 轉成唯讀續接 receipt',async()=>{const rows=await blockedRows(),result=buildStagingV2PostAtomicRecoveryEvidence({runMetadata,rows,recovery:recovery()});assert.equal(result.status,STAGING_V2_POST_ATOMIC_RECOVERY_STATUS);assert.equal(result.atomicWriteCount,4);assert.equal(result.firstDailySaveRequired,true);assert.equal(result.dataWrite,false);assert.equal(result.productionTouched,false);assert.match(result.receiptHash,/^[a-f0-9]{64}$/)});

test('journal 非精確 terminal shape、成功 run 或 recovery write 都 fail closed',async()=>{const rows=await blockedRows();assert.throws(()=>buildStagingV2PostAtomicRecoveryEvidence({runMetadata:{...runMetadata,conclusion:'success'},rows,recovery:recovery()}),/GitHub run blocked/);assert.throws(()=>buildStagingV2PostAtomicRecoveryEvidence({runMetadata,rows:rows.slice(0,-1),recovery:recovery()}),/terminal shape blocked/);assert.throws(()=>buildStagingV2PostAtomicRecoveryEvidence({runMetadata,rows,recovery:{...recovery(),writeCount:1}}),/completion blocked/)});
