import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';

const require=createRequire(import.meta.url);
test('Gen2 function entry固定 Node22、region、service account、public transport與精確 Hosting rewrite',async()=>{const exported=require('../functions/index.cjs'),endpoint=exported.stagingV2AuthoritySave?.__endpoint,[pkg,firebase]=await Promise.all([readFile(new URL('../package.json',import.meta.url),'utf8').then(JSON.parse),readFile(new URL('../firebase.json',import.meta.url),'utf8').then(JSON.parse)]);assert.ok(endpoint);assert.equal(endpoint.platform,'gcfv2');assert.deepEqual(endpoint.region,['asia-east1']);assert.equal(endpoint.serviceAccountEmail,'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com');assert.deepEqual(endpoint.httpsTrigger.invoker,['public']);assert.equal(endpoint.minInstances,1);assert.equal(endpoint.maxInstances,10);assert.equal(endpoint.concurrency,8);assert.equal(pkg.main,'functions/index.cjs');assert.equal(pkg.engines.node,'22');assert.equal(pkg.dependencies.firebase,'12.17.1');assert.equal(Object.hasOwn(pkg.devDependencies,'firebase'),false);assert.equal(pkg.dependencies['firebase-functions'],'7.3.2');assert.equal(pkg.dependencies['firebase-admin'],'14.2.0');assert.equal(firebase.functions.source,'.');assert.equal(firebase.functions.runtime,'nodejs22');assert.deepEqual(firebase.hosting.rewrites,[{source:'/api/staging-v2/authority-save',function:{functionId:'stagingV2AuthoritySave',region:'asia-east1'}}])});

test('staging V2 衝突備份固定為 App Check callable 且沿用隔離 service account',async()=>{const endpoint=require('../functions/index.cjs').stagingV2ConflictBackup?.__endpoint,source=await readFile(new URL('../functions/index.cjs',import.meta.url),'utf8');assert.ok(endpoint);assert.equal(endpoint.platform,'gcfv2');assert.deepEqual(endpoint.region,['asia-east1']);assert.equal(endpoint.serviceAccountEmail,'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com');assert.match(source,/exports\.stagingV2ConflictBackup=onCall\(\{[^}]*enforceAppCheck:true,consumeAppCheckToken:true/)});

test('staging 通知確認固定走受 App Check 保護的後端且只能確認本人通知',async()=>{const exported=require('../functions/index.cjs'),endpoint=exported.stagingAcknowledgeScheduleNotification?.__endpoint,source=await readFile(new URL('../functions/index.cjs',import.meta.url),'utf8'),client=await readFile(new URL('../js/core/firebase-auth-and-cloud-sync.module.js',import.meta.url),'utf8');assert.ok(endpoint);assert.equal(endpoint.platform,'gcfv2');assert.deepEqual(endpoint.region,['asia-east1']);assert.equal(endpoint.serviceAccountEmail,'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com');assert.equal(endpoint.minInstances,1);assert.match(source,/exports\.stagingAcknowledgeScheduleNotification=onCall\(\{[^}]*enforceAppCheck:true,consumeAppCheckToken:true/);assert.match(source,/assertProductionNotificationRecipient\(snapshot\.data\(\),actor\)/);assert.match(client,/stagingAcknowledgeScheduleNotification/);assert.match(client,/for\(let offset=0;offset<ids\.length;offset\+=20\)/);assert.match(client,/notificationIds:ids\.slice\(offset,offset\+20\)/)});

test('staging 排課固定走 App Check 後端與 V2 authority，前端不直寫舊 scheduleRequests',async()=>{const exported=require('../functions/index.cjs'),endpoint=exported.stagingSchedulerOperation?.__endpoint,source=await readFile(new URL('../functions/index.cjs',import.meta.url),'utf8'),client=await readFile(new URL('../js/core/firebase-auth-and-cloud-sync.module.js',import.meta.url),'utf8');assert.ok(endpoint);assert.equal(endpoint.platform,'gcfv2');assert.deepEqual(endpoint.region,['asia-east1']);assert.equal(endpoint.serviceAccountEmail,'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com');assert.equal(endpoint.minInstances,1);assert.match(source,/exports\.stagingSchedulerOperation=onCall\(\{[^}]*enforceAppCheck:true,consumeAppCheckToken:true/);assert.match(source,/executeStagingAuthorityPayload/);assert.match(client,/stagingSchedulerOperationCall/);assert.match(client,/createFirebaseCallableHttpClient/);assert.doesNotMatch(client,/httpsCallable\(stagingFunctions,'stagingSchedulerOperation'/);assert.doesNotMatch(client,/httpsCallable\(productionFunctions,'productionSchedulerOperation'/);assert.match(client,/DANBRIDGE_ENVIRONMENT==='staging'\?stagingSchedulerOperationCall:productionSchedulerOperationCall/)});

test('staging 排課 30 堂不再重切 8 堂或逐筆送 audit',async()=>{const [runtime,client]=await Promise.all([readFile(new URL('../functions/staging-scheduler-runtime.cjs',import.meta.url),'utf8'),readFile(new URL('../js/core/firebase-auth-and-cloud-sync.module.js',import.meta.url),'utf8')]);assert.match(runtime,/records\.length>90\|\|audits\.length>30\|\|plan\.operations\.length>120/);assert.match(runtime,/sender\.applyBatch\(plan\.operations\)/);assert.doesNotMatch(runtime,/for\(const audit of audits\)/);assert.match(client,/maxChangesPerRequest:30/);assert.doesNotMatch(client,/maxChangesPerRequest:DANBRIDGE_ENVIRONMENT==='staging'\?8:30/)});

test('staging V2 正式頁面不再載入 V1 衝突備份或 operation fallback',async()=>{const source=await readFile(new URL('../js/core/firebase-auth-and-cloud-sync.module.js',import.meta.url),'utf8');assert.doesNotMatch(source,/from '\.\/firebase-record-sync-conflict-backup-adapter\.js/);assert.match(source,/stagingV2ConflictBackup/);assert.match(source,/legacy fallback forbidden/)});

test('Gen2 function entry的runtime/save blocker只記錄錯誤名稱與訊息，不輸出stack或憑證',async()=>{const source=await readFile(new URL('../functions/index.cjs',import.meta.url),'utf8');assert.match(source,/STAGING_V2_RUNTIME_BLOCKED/);assert.match(source,/STAGING_V2_SAVE_BLOCKED/);assert.equal(source.match(/JSON\.stringify\(\{name,message\}\)/g)?.length,2);assert.doesNotMatch(source,/error\.stack|GOOGLE_APPLICATION_CREDENTIALS.*console|access[_-]?token.*console|authorization.*console|payload.*console/i)});

test('Gen2 authority endpoint將混合批次中的changes送往單次 immutable audit batch，並保留固定runtime scope',async()=>{const source=await readFile(new URL('../functions/index.cjs',import.meta.url),'utf8');assert.match(source,/createFirebaseStagingV2AuditAppendCloudRuntimeBinder/);assert.match(source,/function executeStagingAuthorityPayload/);assert.match(source,/key\?\.collection==='changes'\?auditIndexes:recordIndexes/);assert.match(source,/auditBinder\.executeBatch\(auditPayloads\)/);assert.match(source,/recordBinder\.execute\(recordPayload,trustedHashes\)/);assert.match(source,/reportingBinder=Object\.freeze\(\{scope:recordBinder\.scope,/);assert.doesNotMatch(source,/for\(const index of auditIndexes\)/);assert.doesNotMatch(source,/scope:recordBinder\.scope\s*\+\s*['"]\+['"]\s*\+\s*auditBinder\.scope/)});

test('staging authority endpoint 在回傳完成前只做一次角色檢視、課程索引與通知讀回',async()=>{const source=await readFile(new URL('../functions/index.cjs',import.meta.url),'utf8');assert.match(source,/createStagingDerivedDeliveryRuntime/);assert.match(source,/const completion=publicCompletion\(recordCompletion,auditCompletion\),derived=await derivedDelivery\.deliver\(payload,completion,trustedHashes\)/);assert.doesNotMatch(source,/derivedDelivery\.deliver\(recordPayload/);assert.doesNotMatch(source,/derivedDelivery\.deliver\(auditPayload/)});

test('staging 排課沿用同一後端計畫已核對的前後 record hash、快照、永久柵欄與即時 head',async()=>{const scheduler=await readFile(new URL('../functions/staging-scheduler-runtime.cjs',import.meta.url),'utf8'),entry=await readFile(new URL('../functions/index.cjs',import.meta.url),'utf8'),derived=await readFile(new URL('../functions/staging-derived-delivery-runtime.cjs',import.meta.url),'utf8'),adapter=await readFile(new URL('../js/core/firebase-active-record-authority-save-chain-v2-adapter.js',import.meta.url),'utf8');assert.match(scheduler,/changedCollections:\['lessons','students','makeups','changes'\]/);assert.match(scheduler,/trustedHashes=Object\.freeze\(\{sourceHash:plan\.targetHash,previousSourceHash:sourceHash,sourceDb:target\.db,previousDb:source\.db,authorityFence:fence,authorityHead:liveHead\}\)/);assert.match(scheduler,/executeAuthorityPayload\(payload,trustedHashes\)/);assert.match(entry,/recordBinder\.execute\(recordPayload,trustedHashes\)/);assert.match(entry,/derivedDelivery\.deliver\(payload,completion,trustedHashes\)/);assert.match(derived,/trustedDbPair=lessonOnly&&trustedHashPair/);assert.match(derived,/sourceDb=trustedSourceDb;previousDb=trustedPreviousDb;sourceHash=trustedSourceHash/);assert.match(adapter,/trustedBootstrap:hasTrustedBootstrap/);assert.match(adapter,/verifyDurablePrewrite\(fence,head\)/);assert.match(adapter,/hasTrustedBootstrap\?TRUSTED_TRANSACTION_SNAPSHOT_ONLY:null/);assert.match(adapter,/assertActiveRecordAuthoritySaveChainV2Integrity/);assert.match(adapter,/fresh durable bundle does not match committed transaction/);assert.doesNotMatch(adapter,/freshPlan=plan\(req,fresh\)/)});

test('staging 與 production 登入後不再啟動舊 scheduleRequests 消費者',async()=>{const client=await readFile(new URL('../js/core/firebase-auth-and-cloud-sync.module.js',import.meta.url),'utf8');assert.match(client,/if\(!\['staging','production'\]\.includes\(DANBRIDGE_ENVIRONMENT\)\)subscribeSchedulerRequests\(\)/)});

test('staging 排課熱路徑沿用內部已驗證快照且角色增量以單次 getAll 讀取',async()=>{const scheduler=await readFile(new URL('../functions/staging-scheduler-runtime.cjs',import.meta.url),'utf8'),entry=await readFile(new URL('../functions/index.cjs',import.meta.url),'utf8'),derived=await readFile(new URL('../functions/staging-derived-delivery-runtime.cjs',import.meta.url),'utf8'),role=await readFile(new URL('../js/core/firebase-role-record-view-adapter.js',import.meta.url),'utf8');assert.match(entry,/getCachedAuthoritySnapshot:\(\)=>derivedDelivery\.peek\(\)/);assert.match(entry,/memory:'2GiB',cpu:2/);assert.match(derived,/snapshot=\(\)=>cache\?clone\(cache\):null,peek=\(\)=>cache/);assert.match(derived,/readDocuments=async paths=>\(await firestore\.getAll/);assert.match(scheduler,/source=cached\.sourceModel/);assert.match(scheduler,/verifiedRemote:\{\.\.\.source,hash:sourceHash\},compactResult:true/);assert.match(role,/transaction\.getAll\(controlPath,\.\.\.paths\)/);assert.match(role,/typeof readDocuments==='function'/)});

test('staging 排課先固定 request 身分再寫權威資料，成功後不再多等一次回條寫入',async()=>{const scheduler=await readFile(new URL('../functions/staging-scheduler-runtime.cjs',import.meta.url),'utf8');assert.match(scheduler,/danbridge-staging-scheduler-reservation-v1/);assert.match(scheduler,/reservationPromise=receiptRef\.create\(reservation\)/);assert.match(scheduler,/const reservationError=await reservationPromise;if\(reservationError\)throw reservationError;/);assert.match(scheduler,/STAGING_SCHEDULER_COMPLETE/);assert.doesNotMatch(scheduler,/const value=\{fingerprint,uid:caller\.uid,email:caller\.email,response/);assert.doesNotMatch(scheduler,/await receiptRef\.create\(value\)/)});

test('staging authority 對不可變 Genesis 基準做有界批次與逐筆驗證快取，且 Cloud 外層明確暴露預熱方法；可變 head、ledger、receipt 與 daily record 仍三次讀回',async()=>{const source=await readFile(new URL('../js/core/firebase-active-record-authority-save-chain-v2-adapter.js',import.meta.url),'utf8');assert.match(source,/MAX_VERIFIED_GENESIS_BASELINES=32/);assert.match(source,/MAX_VERIFIED_GENESIS_RECORDS=8192/);assert.match(source,/verifiedGenesisRecordCache/);assert.match(source,/warmBaselines:rawKeys=>chain\.warmBaselines\(rawKeys\)/);assert.match(source,/sealed Genesis root changed after verification/);assert.match(source,/verifiedBaselineCacheHit/);assert.match(source,/readSnapshot:\(\)=>buildSnapshot/);assert.match(source,/runTransaction/);assert.match(source,/fresh=snapshot\(await cfg\.readSnapshot/)});
test('staging 新提交的 fresh read 只讀新 head 與本次 bundle，仍完整驗證 30 筆 record、receipt 與 Genesis',async()=>{const source=await readFile(new URL('../js/core/firebase-active-record-authority-save-chain-v2-adapter.js',import.meta.url),'utf8');assert.match(source,/requestFreshBase=\[RECORD_SYNC_V1_PERMANENT_FENCE_V2_PATH,headPath,requestLedger,\.\.\.requestRecords,\.\.\.requestReceipts,indexRoot\]/);assert.match(source,/freshRequestOnly=result\.transactionState==='created'/);assert.match(source,/requestCurrentOnly&&!requestIsCurrent/);assert.match(source,/readSetSize:basePaths\.length\+genesis\.derivedReadCount/);assert.match(source,/minimumFreshReadSetSize=req\.keys\.length\*2\+4/);assert.match(source,/totalReadCount:initialReadCount\+transactionReadCount\+freshReadCount/)});

test('staging 日常逐筆預取下一枚 limited-use App Check token 且每筆只取用一次',async()=>{const source=await readFile(new URL('../js/core/firebase-auth-and-cloud-sync.module.js',import.meta.url),'utf8');assert.match(source,/function warmStagingV2LimitedUseToken\(\)/);assert.match(source,/function takeStagingV2LimitedUseToken\(\)/);assert.match(source,/getLimitedUseAppCheckToken:takeStagingV2LimitedUseToken/);assert.match(source,/stagingV2LimitedUseTokenSlot=null/);assert.match(source,/Date\.now\(\)-slot\.createdAt>120000/);assert.match(source,/now-stagingV2LimitedUseTokenStartedAt<=90000/);assert.match(source,/function warmStagingV2TokenForScheduleIntent\(event\)/);assert.match(source,/addEventListener\('pointerdown',warmStagingV2TokenForScheduleIntent,\{capture:true,passive:true\}\)/);assert.match(source,/target\.closest\('#calendar,#lessonModal,#batchModal,#smartSchedulerModal'\)/)});
test('staging 通知確認使用獨立 limited-use token 與明確 callable Auth 傳輸',async()=>{const source=await readFile(new URL('../js/core/firebase-auth-and-cloud-sync.module.js',import.meta.url),'utf8');assert.match(source,/functionName:'stagingAcknowledgeScheduleNotification'/);assert.match(source,/getLimitedUseAppCheckToken:takeStagingNotificationLimitedUseToken/);assert.match(source,/async function takeStagingNotificationLimitedUseToken\(\)/);assert.doesNotMatch(source,/httpsCallable\(stagingFunctions,'stagingAcknowledgeScheduleNotification'/);assert.match(source,/functionName:'productionAcknowledgeScheduleNotification'/);assert.match(source,/getLimitedUseAppCheckToken:takeProductionNotificationLimitedUseToken/);assert.doesNotMatch(source,/httpsCallable\(productionFunctions,'productionAcknowledgeScheduleNotification'/)});

test('staging常駐實例接受Cloud Functions或Cloud Run的精確專案鍵並以onInit阻擋至完整資料及常用基準預熱完成，雙鍵衝突或production皆不初始化staging',async()=>{const source=await readFile(new URL('../functions/index.cjs',import.meta.url),'utf8');assert.match(source,/require\('firebase-functions\/v2\/core'\)/);assert.match(source,/function shouldEagerWarmStagingService\(service\)/);assert.match(source,/process\.env\.GCLOUD_PROJECT/);assert.match(source,/process\.env\.GOOGLE_CLOUD_PROJECT/);assert.match(source,/\(!gcloudProject\|\|gcloudProject===PROJECT_ID\)&&\(!googleProject\|\|googleProject===PROJECT_ID\)/);assert.match(source,/await derivedDelivery\.warm\(\)[\s\S]*recordBinder\.warmBaselines/);assert.match(source,/STAGING_V2_BASELINE_WARM/);assert.match(source,/onInit\(async\(\)=>\{/);assert.match(source,/shouldEagerWarmStagingService\('stagingv2authoritysave'\)[\s\S]*await runtime\(\)[\s\S]*state:'complete'/);assert.match(source,/shouldEagerWarmStagingService\('stagingscheduleroperation'\)[\s\S]*await stagingSchedulerRuntime\(\)[\s\S]*state:'complete'/);assert.doesNotMatch(source,/void (?:runtime|stagingSchedulerRuntime)\(\)/);assert.doesNotMatch(source,/shouldEagerWarmStagingService\(['"]production/)});

test('Gen2 server authority adapter不載入瀏覽器版Firebase dependency graph',async()=>{const [authority,paths]=await Promise.all([readFile(new URL('../js/core/firebase-active-record-authority-save-v2-adapter.js',import.meta.url),'utf8'),readFile(new URL('../js/core/firebase-record-sync-v2-genesis-paths.js',import.meta.url),'utf8')]);assert.match(authority,/from '\.\/firebase-record-sync-v2-genesis-paths\.js'/);assert.doesNotMatch(authority,/firebase-record-sync-v2-genesis-seed-batch-adapter/);assert.doesNotMatch(paths,/from ['"]firebase(?:\/|['"])/);assert.match(paths,/RECORD_SYNC_V2_GENESIS_BATCH_RECORD_PATH/)});

test('Gen2 authority router把H0送到H1＋完整baseline，H1 response-loss先補齊baseline才允許Hn',async()=>{const source=await readFile(new URL('../js/core/firebase-active-record-authority-save-chain-v2-adapter.js',import.meta.url),'utf8');assert.match(source,/createFirebaseRecordSyncV2PostCutoverCloudRecoveryV2Binder/);assert.match(source,/createFirebaseActiveRecordAuthoritySaveV2CloudRuntimeBinder/);assert.match(source,/createFirebaseActiveRecordV2H1BaselineCloudRuntime/);assert.match(source,/schema==='danbridge-active-record-v2-structural-head0-v2'&&revision===0/);assert.match(source,/const completion=await h1\.execute\(await recovery\.recover\(\),requestValue\);await baseline\.execute\(completion\);return completion/);assert.match(source,/schema===ACTIVE_RECORD_AUTHORITY_V2_HEAD_SCHEMA&&revision===1/);assert.match(source,/const completion=await h1\.recover\(\);await baseline\.execute\(completion\)/);assert.match(source,/Number\.isSafeInteger\(revision\)&&revision>1/)});

test('Gen2 H1 binder保留固定Cloud boundary內的durable recovery入口',async()=>{const source=await readFile(new URL('../js/core/firebase-active-record-authority-save-v2-adapter.js',import.meta.url),'utf8');assert.match(source,/createFirebaseActiveRecordAuthoritySaveV2CloudRuntimeBinder/);assert.match(source,/recover:\(\)=>bound\.recover\(\)/)});

test('H1 baseline inventory把Firestore hash路徑順序還原成Genesis canonical批次順序後才核對receipt',async()=>{const source=await readFile(new URL('../js/core/firebase-active-record-v2-h1-baseline-cloud-runtime.js',import.meta.url),'utf8');assert.match(source,/collectionOrder=new Map\(FULL_RECORD_COLLECTIONS/);assert.match(source,/\.sort\(compareGenesis\),verified=verifyReceipt/);assert.match(source,/collection==='changes'&&left\.recordIndex!==right\.recordIndex/)});

test('H1 baseline inventory固定有界並行讀取Genesis batches避免單次Function逾時',async()=>{const source=await readFile(new URL('../js/core/firebase-active-record-v2-h1-baseline-cloud-runtime.js',import.meta.url),'utf8');assert.match(source,/INVENTORY_CONCURRENCY=8/);assert.match(source,/batches=await bounded\(pending/);assert.match(source,/Math\.min\(INVENTORY_CONCURRENCY/)});
