import test from 'node:test';
import assert from 'node:assert/strict';
import {Buffer} from 'node:buffer';
import {createStagingV2AuthoritySaveCloudRuntime,STAGING_V2_AUTHORITY_SAVE_CLOUD_RUNTIME_SCOPE} from '../js/core/staging-v2-authority-save-cloud-runtime.js';
import {STAGING_V2_AUTHORITY_SAVE_APP_ID,STAGING_V2_AUTHORITY_SAVE_PROJECT_ID} from '../js/core/staging-v2-authority-save-http-gateway.js';

const now=Date.parse('2026-08-30T12:00:00Z'),uid='owner-runtime-12345',email='a0965487920@gmail.com',requestId='save-runtime-12345';
const payload=()=>({save:{saveId:requestId,deviceId:'device-runtime-12345',actorUid:uid,actorEmail:email,createdAt:'2026-08-30T12:00:00.000000001Z'},changedKeys:[{collection:'lessons',recordId:'lesson-runtime-12345'}],baselineRecords:[],localRecords:[]});
const completion=()=>({state:'complete-confirmed',transactionState:'created',projectId:STAGING_V2_AUTHORITY_SAVE_PROJECT_ID,activationEpoch:'activation-runtime-12345',resultHeadHash:'a'.repeat(64),commitHash:'b'.repeat(64),saveId:requestId,operationCount:1,persistedAt:'2026-08-30T12:00:01.000000001Z',writeCount:4});
const claims=()=>({aud:STAGING_V2_AUTHORITY_SAVE_PROJECT_ID,iss:`https://securetoken.google.com/${STAGING_V2_AUTHORITY_SAVE_PROJECT_ID}`,sub:uid,user_id:uid,email,email_verified:true,auth_time:Math.floor(now/1000)-60,exp:Math.floor(now/1000)+3600});
const appToken=()=>({appId:STAGING_V2_AUTHORITY_SAVE_APP_ID,alreadyConsumed:false,token:{app_id:STAGING_V2_AUTHORITY_SAVE_APP_ID,sub:STAGING_V2_AUTHORITY_SAVE_APP_ID,iss:'https://firebaseappcheck.googleapis.com/883029466360',aud:['883029466360',STAGING_V2_AUTHORITY_SAVE_PROJECT_ID],iat:Math.floor(now/1000)-10,exp:Math.floor(now/1000)+3600}});
function response(){const value={statusCode:0,headers:{},body:''};return{value,set(key,val){value.headers[key]=val;return this},status(code){value.statusCode=code;return this},send(body){value.body=body;return this}}}
function setup(overrides={}){let writes=0;const runtime=createStagingV2AuthoritySaveCloudRuntime({verifyIdToken:async()=>claims(),verifyAppCheckToken:async()=>appToken(),readCompanyAccess:async()=>null,executeAuthoritySave:async()=>{writes++;return completion()},now:()=>now,...overrides});return{runtime,writes:()=>writes}}
function request(body=payload()){const rawBody=Buffer.from(JSON.stringify({schema:'danbridge-staging-v2-authority-save-request-v1',projectId:STAGING_V2_AUTHORITY_SAVE_PROJECT_ID,requestId,payload:body}));return{method:'POST',headers:{origin:'https://danbridge-d8877-staging.web.app',authorization:'Bearer id-token-12345','x-firebase-appcheck':'app-check-token-12345','x-danbridge-request-id':requestId,'content-type':'application/json','content-length':String(rawBody.length)},rawBody}}

test('Gen2 raw HTTP adapter以 ID token、limited-use App Check 與 primary Owner 完成最小 receipt',async()=>{const value=setup(),res=response();await value.runtime.handle(request(),res);assert.equal(value.runtime.scope,STAGING_V2_AUTHORITY_SAVE_CLOUD_RUNTIME_SCOPE);assert.equal(res.value.statusCode,200);assert.equal(JSON.parse(res.value.body).saveId,requestId);assert.equal(value.writes(),1)});
test('非 primary owner只接受精確 companyAccess owner；非 raw body與陣列 header零寫入',async()=>{const otherPayload=payload();otherPayload.save.actorEmail='secondary.owner@example.com';const otherClaims={...claims(),email:'secondary.owner@example.com'},allowed=setup({verifyIdToken:async()=>otherClaims,readCompanyAccess:async()=>({active:true,companyId:'danbridge',role:'owner'})}),allowedRes=response();await allowed.runtime.handle(request(otherPayload),allowedRes);assert.equal(allowedRes.value.statusCode,200);const blocked=setup({verifyIdToken:async()=>otherClaims,readCompanyAccess:async()=>({active:true,companyId:'danbridge',role:'teacher'})}),blockedRes=response();await blocked.runtime.handle(request(otherPayload),blockedRes);assert.equal(blockedRes.value.statusCode,403);assert.equal(blocked.writes(),0);const malformed=request();malformed.rawBody=JSON.stringify({});malformed.headers.authorization=['one','two'];const malformedRes=response();await setup().runtime.handle(malformed,malformedRes);assert.equal(malformedRes.value.statusCode,400)});
