import test from 'node:test';
import assert from 'node:assert/strict';
import {sha256Canonical} from '../js/core/cloud-immutable-migration-backup.js';
import {createStagingV2ActivationSupervisor,STAGING_V2_SUPERVISOR_PHASES} from '../js/core/staging-v2-activation-supervisor.js';
import {createStagingV2ManualSupervisorActions} from '../js/core/staging-v2-manual-supervisor-actions.js';

const hash=value=>sha256Canonical({value});
const manifest=(atomicActivationAllowed=true)=>{const body={schema:'danbridge-staging-v2-activation-supervisor-manifest-v1',runId:'manual_run_12345',requestHash:hash('request'),environment:'staging',companyId:'danbridge',projectId:'danbridge-d8877-staging',serviceAccountEmail:'danbridge-staging-v2@danbridge-d8877-staging.iam.gserviceaccount.com',rulesetHash:hash('rules'),runtimePolicyHash:hash('policy'),runtimeAdapterHash:hash('adapter'),clientWiringHash:hash('client'),firestoreRulesDeployAllowed:true,hostingDeployAllowed:false,productionAllowed:false,timeMachineAllowed:false,atomicActivationAllowed};return{...body,manifestHash:sha256Canonical(body)}};
function result(phase){return{capability:Object.freeze({schema:'real-'+phase.toLowerCase(),phase}),receiptHash:hash(phase),readCount:1,writeCount:phase==='READINESS'||phase==='PRE_ATOMIC_GATE'||phase==='FINAL_READBACK'?0:1,firestoreRulesDeployed:phase==='STAGING_RULES_ATTESTATION'}}
function fixture(atomic=true){const order=[],seen=[],executors=Object.fromEntries(STAGING_V2_SUPERVISOR_PHASES.map(phase=>[phase,async context=>{order.push(phase);seen.push(context.priorCapabilities);return result(phase)}])),rollback=async context=>{order.push('ROLLBACK');seen.push(context.priorCapabilities);return{...result('ROLLBACK'),writeCount:0,firestoreRulesDeployed:false}},actions=createStagingV2ManualSupervisorActions({executors,rollback}),rows=[],journal={append:async row=>rows.push(structuredClone(row)),readAll:async()=>structuredClone(rows)},supervisor=createStagingV2ActivationSupervisor({rawManifest:manifest(atomic),actions,journal});return{order,seen,executors,actions,rows,supervisor}}

test('真實 executor 只按固定 phase chain 收到累積的原 capability，完成H1 baseline後才final',async()=>{const value=fixture(),done=await value.supervisor.run();assert.equal(done.status,'COMPLETE');assert.deepEqual(value.order,STAGING_V2_SUPERVISOR_PHASES);for(let index=0;index<value.seen.length;index++)assert.deepEqual(Object.keys(value.seen[index]),STAGING_V2_SUPERVISOR_PHASES.slice(0,index));assert.ok(value.order.indexOf('H1_SAVE')<value.order.indexOf('H1_BASELINE_SNAPSHOT'));assert.ok(value.order.indexOf('H1_BASELINE_SNAPSHOT')<value.order.indexOf('FINAL_READBACK'))});

test('chain capability clone/manual/跳步皆無法餵給下一 phase',async()=>{const value=fixture(),start=Object.freeze({schema:'danbridge-staging-v2-supervisor-start-capability-v1'}),first=await value.actions.READINESS({manifest:manifest(),phase:'READINESS',capability:start});await assert.rejects(()=>value.actions.BASELINE_ATTESTATION({manifest:manifest(),phase:'BASELINE_ATTESTATION',capability:structuredClone(first.capability)}),/cloned|foreign|order/);await assert.rejects(()=>value.actions.HARD_PAUSE({manifest:manifest(),phase:'HARD_PAUSE',capability:first.capability}),/order/);await assert.rejects(()=>value.actions.READINESS({manifest:manifest(),phase:'WRONG',capability:start}),/phase mismatch/)});

test('atomic前失敗把精確累積 capability 交給cleanup-only rollback；rollback寫入或Rules部署拒絕',async()=>{const value=fixture(false);value.executors.GENESIS_AUTHORITY=async()=>{throw new Error('injected')};const rebuilt=createStagingV2ManualSupervisorActions({executors:value.executors,rollback:async context=>{assert.ok(context.priorCapabilities.GENESIS_IDENTITY_INDEX);return{...result('ROLLBACK'),writeCount:0,firestoreRulesDeployed:false}}}),rows=[],supervisor=createStagingV2ActivationSupervisor({rawManifest:manifest(false),actions:rebuilt,journal:{append:async row=>rows.push(structuredClone(row)),readAll:async()=>structuredClone(rows)}});await assert.rejects(()=>supervisor.run(),/rollback confirmed/);const unsafe=fixture(false);unsafe.executors.READINESS=async()=>{throw new Error('fail')};const bad=createStagingV2ManualSupervisorActions({executors:unsafe.executors,rollback:async()=>({...result('ROLLBACK'),writeCount:1,firestoreRulesDeployed:false})}),badRows=[],badSupervisor=createStagingV2ActivationSupervisor({rawManifest:manifest(false),actions:bad,journal:{append:async row=>badRows.push(structuredClone(row)),readAll:async()=>structuredClone(badRows)}});await assert.rejects(()=>badSupervisor.run(),/cleanup-only|rollback/)});
