import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeTeacherLeaveInput,normalizeTeacherLeaveActor,assertTeacherLeaveScope,buildTeacherLeaveRecord,teacherLeaveRequestFingerprint} from '../js/core/teacher-leave-policy.js';

const owner=normalizeTeacherLeaveActor({uid:'owner-uid-1',email:'owner@example.com',companyId:'danbridge',role:'owner',active:true});
const scheduler=normalizeTeacherLeaveActor({uid:'scheduler-uid-1',email:'aa@example.com',companyId:'danbridge',role:'teacher',teacherId:'teacher-aa',canManageSchedule:true,active:true});
const teacher=normalizeTeacherLeaveActor({uid:'teacher-uid-1',email:'teacher@example.com',companyId:'danbridge',role:'teacher',teacherId:'teacher-1',active:true});
const input={teacherId:'teacher-1',leaveType:'sick',date:'2026-09-02',start:'09:30',end:'11:00',note:'看診'};

test('請假時數由開始與結束時間精確計算',()=>assert.deepEqual({...normalizeTeacherLeaveInput(input)},{...input,durationMinutes:90,hours:1.5}));
test('拒絕跨日、零時數、未知類別與不存在的日期',()=>{for(const row of [{...input,end:'09:30'},{...input,end:'08:00'},{...input,leaveType:'other'},{...input,date:'bad'},{...input,date:'2026-02-31'}])assert.throws(()=>normalizeTeacherLeaveInput(row))});
test('Owner 與排課專員可操作任一老師；老師只能操作自己',()=>{assert.equal(assertTeacherLeaveScope(owner,{...input,teacherId:'teacher-2'}).teacherId,'teacher-2');assert.equal(assertTeacherLeaveScope(scheduler,{...input,teacherId:'teacher-2'}).teacherId,'teacher-2');assert.throws(()=>assertTeacherLeaveScope(teacher,{...input,teacherId:'teacher-2'}));assert.equal(assertTeacherLeaveScope(teacher,input).teacherId,'teacher-1')});
test('新增、更新與取消均使用 revision 且取消保留原資料',()=>{const created=buildTeacherLeaveRecord({request:{action:'create',operationId:'operation-0001',leaveId:'leave-0001',expectedRevision:0,input},actor:owner,teacherName:'張毅',nowIso:'2026-09-01T00:00:00.000Z'});assert.equal(created.revision,1);assert.equal(created.status,'active');const updated=buildTeacherLeaveRecord({request:{action:'update',operationId:'operation-0002',leaveId:'leave-0001',expectedRevision:1,input:{...input,end:'12:00'}},actor:scheduler,current:created,teacherName:'張毅',nowIso:'2026-09-01T01:00:00.000Z'});assert.equal(updated.hours,2.5);assert.equal(updated.revision,2);const cancelled=buildTeacherLeaveRecord({request:{action:'cancel',operationId:'operation-0003',leaveId:'leave-0001',expectedRevision:2},actor:teacher,current:updated,teacherName:'張毅',nowIso:'2026-09-01T02:00:00.000Z'});assert.equal(cancelled.status,'cancelled');assert.equal(cancelled.hours,2.5);assert.equal(cancelled.revision,3)});
test('相同請求產生穩定指紋，不同內容不可冒充重播',()=>{const request={action:'create',operationId:'operation-0001',leaveId:'leave-0001',expectedRevision:0,input};assert.equal(teacherLeaveRequestFingerprint(request),teacherLeaveRequestFingerprint(structuredClone(request)));assert.notEqual(teacherLeaveRequestFingerprint(request),teacherLeaveRequestFingerprint({...request,input:{...input,note:'different'}}))});
