import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeTeacherLeaveInput,normalizeTeacherLeaveActor,assertTeacherLeaveScope,buildTeacherLeaveRecord,teacherLeaveRequestFingerprint,teacherRecordFromAuthorityEnvelope} from '../js/core/teacher-leave-policy.js';

const owner=normalizeTeacherLeaveActor({uid:'owner-uid-1',email:'owner@example.com',companyId:'danbridge',role:'owner',active:true});
const scheduler=normalizeTeacherLeaveActor({uid:'scheduler-uid-1',email:'aa@example.com',companyId:'danbridge',role:'teacher',teacherId:'teacher-aa',canManageSchedule:true,active:true});
const teacher=normalizeTeacherLeaveActor({uid:'teacher-uid-1',email:'teacher@example.com',companyId:'danbridge',role:'teacher',teacherId:'teacher-1',active:true});
const teacherAuthority={id:'teacher-1',name:'張毅',employmentStartDate:'2024-01-01',standardDailyHours:8};
const input={teacherId:'teacher-1',leaveType:'sick',date:'2026-09-02',start:'09:30',end:'11:00',note:'看診'};

test('偽造立即核准旗標仍不能讓老師或排課專員自行核准',()=>{
 for(const actor of [teacher,scheduler]){
  const record=buildTeacherLeaveRecord({request:{action:'create',operationId:'operation-forged-now',leaveId:'leave-forged-now',expectedRevision:0,approveImmediately:true,input},actor,teacher:teacherAuthority,nowIso:'2026-09-01T00:00:00.000Z'});
  assert.equal(record.status,'pending');
 }
});

test('請假時數與天數由時間及老師標準每日工時精確計算',()=>{const normalized=normalizeTeacherLeaveInput(input);assert.equal(normalized.durationMinutes,90);assert.equal(normalized.hours,1.5);const record=buildTeacherLeaveRecord({request:{action:'create',operationId:'operation-0001',leaveId:'leave-0001',expectedRevision:0,input},actor:owner,teacher:teacherAuthority,nowIso:'2026-09-01T00:00:00.000Z'});assert.equal(record.days,0.188)});
test('接受法定十種假別；喪假必須指定親屬關係',()=>{for(const leaveType of ['annual','personal','sick','hospitalSick','marriage','familyCare','menstrual','occupational','official'])assert.equal(normalizeTeacherLeaveInput({...input,leaveType}).leaveType,leaveType);assert.throws(()=>normalizeTeacherLeaveInput({...input,leaveType:'bereavement'}),/親屬/);assert.equal(normalizeTeacherLeaveInput({...input,leaveType:'bereavement',bereavementRelationship:'close8'}).bereavementRelationship,'close8')});
test('拒絕跨日、零時數、未知類別與不存在的日期',()=>{for(const row of [{...input,end:'09:30'},{...input,end:'08:00'},{...input,leaveType:'other'},{...input,date:'bad'},{...input,date:'2026-02-31'}])assert.throws(()=>normalizeTeacherLeaveInput(row))});
test('Owner 與排課專員可送任一老師；老師只能送自己',()=>{assert.equal(assertTeacherLeaveScope(owner,{...input,teacherId:'teacher-2'}).teacherId,'teacher-2');assert.equal(assertTeacherLeaveScope(scheduler,{...input,teacherId:'teacher-2'}).teacherId,'teacher-2');assert.throws(()=>assertTeacherLeaveScope(teacher,{...input,teacherId:'teacher-2'}));assert.equal(assertTeacherLeaveScope(teacher,input).teacherId,'teacher-1')});
test('正式教師權威文件只接受 record envelope 且精確核對身分',()=>{const envelope={recordId:'teacher-1',deleted:false,record:{id:'teacher-1',name:'張毅'}};assert.equal(teacherRecordFromAuthorityEnvelope(envelope,'teacher-1').name,'張毅');assert.throws(()=>teacherRecordFromAuthorityEnvelope({...envelope,record:null,data:envelope.record},'teacher-1'),/找不到有效老師資料/);assert.throws(()=>teacherRecordFromAuthorityEnvelope({...envelope,deleted:true},'teacher-1'),/找不到有效老師資料/);assert.throws(()=>teacherRecordFromAuthorityEnvelope(envelope,'teacher-2'),/找不到有效老師資料/)});
test('申請待審，只有 Owner 可核准；核准後非 Owner 不可變更',()=>{const created=buildTeacherLeaveRecord({request:{action:'create',operationId:'operation-0001',leaveId:'leave-0001',expectedRevision:0,input},actor:teacher,teacher:teacherAuthority,nowIso:'2026-09-01T00:00:00.000Z'});assert.equal(created.status,'pending');assert.throws(()=>buildTeacherLeaveRecord({request:{action:'approve',operationId:'operation-0002',leaveId:'leave-0001',expectedRevision:1},actor:scheduler,current:created,teacher:teacherAuthority,nowIso:'2026-09-01T01:00:00.000Z'}),/Owner/);const approved=buildTeacherLeaveRecord({request:{action:'approve',operationId:'operation-0003',leaveId:'leave-0001',expectedRevision:1},actor:owner,current:created,teacher:teacherAuthority,nowIso:'2026-09-01T01:00:00.000Z'});assert.equal(approved.status,'approved');assert.equal(approved.revision,2);assert.throws(()=>buildTeacherLeaveRecord({request:{action:'cancel',operationId:'operation-0004',leaveId:'leave-0001',expectedRevision:2},actor:scheduler,current:approved,teacher:teacherAuthority,nowIso:'2026-09-01T02:00:00.000Z'}),/Owner/)});
test('Owner 可立即核准，更新會重新待審，駁回保留理由',()=>{const approved=buildTeacherLeaveRecord({request:{action:'create',operationId:'operation-1001',leaveId:'leave-1001',expectedRevision:0,approveImmediately:true,input:{...input,leaveType:'annual'}},actor:owner,teacher:teacherAuthority,nowIso:'2026-09-01T00:00:00.000Z'});assert.equal(approved.status,'approved');assert.equal(approved.statutoryAllowanceDays,10);const cancelled=buildTeacherLeaveRecord({request:{action:'cancel',operationId:'operation-1002',leaveId:'leave-1001',expectedRevision:1},actor:owner,current:approved,teacher:teacherAuthority,nowIso:'2026-09-01T01:00:00.000Z'});assert.equal(cancelled.status,'cancelled');const pending=buildTeacherLeaveRecord({request:{action:'create',operationId:'operation-2001',leaveId:'leave-2001',expectedRevision:0,input},actor:scheduler,teacher:teacherAuthority,nowIso:'2026-09-01T00:00:00.000Z'});const rejected=buildTeacherLeaveRecord({request:{action:'reject',operationId:'operation-2002',leaveId:'leave-2001',expectedRevision:1,decisionNote:'證明不足'},actor:owner,current:pending,teacher:teacherAuthority,nowIso:'2026-09-01T02:00:00.000Z'});assert.equal(rejected.status,'rejected');assert.equal(rejected.decisionNote,'證明不足')});
test('相同請求產生穩定指紋，不同內容不可冒充重播',()=>{const request={action:'create',operationId:'operation-0001',leaveId:'leave-0001',expectedRevision:0,input};assert.equal(teacherLeaveRequestFingerprint(request),teacherLeaveRequestFingerprint(structuredClone(request)));assert.notEqual(teacherLeaveRequestFingerprint(request),teacherLeaveRequestFingerprint({...request,input:{...input,note:'different'}}))});
