/**
 * Danbridge Scheduler V15.4 — Students CRM module
 *
 * Extracted from application-and-business-features.js without changing behavior.
 * This is a classic script so existing inline onclick handlers remain compatible.
 */

function studentDefaults(x={}){return {...x,status:x.status||'active',school:x.school||'',grade:x.grade||'',level:x.level||'',preferredTeacherId:x.preferredTeacherId||'',parentLine:x.parentLine||'',parentEmail:x.parentEmail||'',materials:x.materials||'',availability:x.availability||'',scores:x.scores||'',archivedAt:x.archivedAt||'',archivedReason:x.archivedReason||'',archivedBy:x.archivedBy||''}}
function isArchivedRecord(x){return !!String(x?.archivedAt||'').trim()}
function archivalActorLabel(){const ctx=window.DanbridgeAccess?.getContext?.()||{};return String(document.body.dataset.cloudDisplayName||ctx.email||'Owner').trim()||'Owner'}

function saveStudent(){const id=$('studentId').value||uid(),old=db.students.find(x=>String(x.id)===String(id)),o=studentDefaults({...old,id,name:$('studentName').value.trim(),status:$('studentStatus').value,school:$('studentSchool').value.trim(),grade:$('studentGrade').value.trim(),level:$('studentLevel').value.trim(),preferredTeacherId:$('studentPreferredTeacher').value,parent:$('parentName').value.trim(),contact:$('parentContact').value.trim(),parentLine:$('parentLine').value.trim(),parentEmail:$('parentEmail').value.trim(),homeAddress:$('studentHomeAddress').value.trim(),courseType:$('studentCourseType').value,billing:$('studentBilling').value,rate:+$('studentRate').value||0,materials:$('studentMaterials').value.trim(),availability:$('studentAvailability').value.trim(),scores:$('studentScores').value.trim(),note:$('studentNote').value});
if(!o.name)return alert('請輸入學生姓名');
snapshot();
const i=db.students.findIndex(x=>x.id===id);i>=0?db.students[i]=o:db.students.push(o);
const wasEdit=i>=0;clearStudentForm();
saveDB();toast(wasEdit?'學生 CRM 已更新':'學生已新增')}

function editStudent(id){const x=studentDefaults(db.students.find(s=>String(s.id)===String(id)));
if(!x?.id)return alert('找不到這位學生，請重新整理後再試');switchTab('students');$('studentId').value=x.id;$('studentName').value=x.name||'';$('studentStatus').value=x.status;$('studentSchool').value=x.school;$('studentGrade').value=x.grade;$('studentLevel').value=x.level;$('studentPreferredTeacher').value=x.preferredTeacherId;$('parentName').value=x.parent||'';$('parentContact').value=x.contact||'';$('parentLine').value=x.parentLine;$('parentEmail').value=x.parentEmail;$('studentHomeAddress').value=x.homeAddress||'';$('studentCourseType').value=x.courseType||'1對1';$('studentBilling').value=x.billing||'hour';$('studentRate').value=x.rate??'';$('studentMaterials').value=x.materials;$('studentAvailability').value=x.availability;$('studentScores').value=x.scores;$('studentNote').value=x.note||'';
const box=$('studentEditIndicator');
if(box){box.textContent='正在編輯：'+(x.name||'未命名學生');box.style.display='block'}$('studentName').focus();$('students').scrollIntoView({behavior:'smooth',block:'start'});toast('已載入 '+(x.name||'學生')+' 的 CRM')}

function clearStudentForm(){['studentId','studentName','studentSchool','studentGrade','studentLevel','parentName','parentContact','parentLine','parentEmail','studentHomeAddress','studentRate','studentMaterials','studentAvailability','studentScores','studentNote'].forEach(id=>{if($(id))$(id).value=''});$('studentStatus').value='active';$('studentPreferredTeacher').value='';$('studentCourseType').value='1對1';$('studentBilling').value='hour';
const box=$('studentEditIndicator');
if(box){box.textContent='';box.style.display='none'}}

function archiveStudent(id){if((window.currentCloudRole?.()||window.DanbridgeAccess?.getContext?.().role)!=='owner')return alert('只有 Owner 可以封存學生。');const s=db.students.find(x=>String(x.id)===String(id));if(!s||isArchivedRecord(s))return;const reason=prompt(`請輸入封存「${s.name||'學生'}」的原因：`,'離班');if(reason===null)return;if(!reason.trim())return alert('請輸入封存原因');if(!confirm(`確定封存「${s.name||'學生'}」？\n\n封存後不再出現在新增課程與智慧排課選項；歷史課程、收款與月結仍會完整保留。`))return;snapshot();Object.assign(s,{archivedAt:new Date().toISOString(),archivedReason:reason.trim(),archivedBy:archivalActorLabel(),status:'inactive'});clearStudentForm();saveDB();toast('學生已封存，歷史資料仍保留')}
function restoreStudent(id){if((window.currentCloudRole?.()||window.DanbridgeAccess?.getContext?.().role)!=='owner')return alert('只有 Owner 可以恢復學生。');const s=db.students.find(x=>String(x.id)===String(id));if(!s||!isArchivedRecord(s))return;if(!confirm(`確定恢復「${s.name||'學生'}」？\n恢復後會重新出現在排課選項。`))return;snapshot();Object.assign(s,{archivedAt:'',archivedReason:'',archivedBy:'',status:'active',restoredAt:new Date().toISOString(),restoredBy:archivalActorLabel()});saveDB();toast('學生已恢復')}

function studentHistoryStats(id){const ls=db.lessons.filter(l=>l.studentId===id),completed=ls.filter(l=>l.status==='已上課'||l.status==='補課').length,absent=ls.filter(l=>['學生請假','老師請假','取消','停課'].includes(l.status)).length,unpaid=ls.filter(l=>l.paymentStatus==='unpaid'&&timetableRevenueCharge(l)>0).length;return{total:ls.length,completed,absent,unpaid,last:[...ls].sort((a,b)=>(b.date+b.start).localeCompare(a.date+a.start))[0]}}

function ensureStudentTeacherFilter(){const search=$('crmSearch'),toolbar=search?.closest('.toolbar');if(!search||!toolbar)return null;let select=$('crmTeacherFilter');if(!select){const field=document.createElement('div');field.className='crm-teacher-filter-field';field.innerHTML='<label for="crmTeacherFilter">篩選老師</label><select id="crmTeacherFilter" onchange="renderStudents()"><option value="">全部老師</option></select>';toolbar.append(field);select=$('crmTeacherFilter')}const old=select.value,allowedIds=new Set((db.teachers||[]).map(t=>String(t.id)));select.innerHTML='<option value="">全部老師</option>'+(db.teachers||[]).map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('');select.value=allowedIds.has(String(old))?old:'';return select}
function ensureStudentArchiveFilter(){const search=$('crmSearch'),toolbar=search?.closest('.toolbar');if(!search||!toolbar)return null;let select=$('crmArchiveFilter');if(!select){const field=document.createElement('div');field.className='crm-teacher-filter-field';field.innerHTML='<label for="crmArchiveFilter">資料狀態</label><select id="crmArchiveFilter" onchange="renderStudents()"><option value="active">使用中</option><option value="archived">已封存</option><option value="all">全部</option></select>';toolbar.append(field);select=$('crmArchiveFilter')}return select}

function studentTeacherIds(s){const ids=new Set();(db.lessons||[]).filter(l=>!l.isDraft&&String(l.studentId)===String(s.id)).forEach(l=>lessonTeacherIds(l).forEach(id=>ids.add(String(id))));return ids}
function studentMatchesCrmFilters(s,q='',teacherId=''){const text=[s.name,s.parent,s.contact,s.parentLine,s.parentEmail,s.school,s.grade,s.level,s.materials].join(' ').toLowerCase();return(!teacherId||studentTeacherIds(s).has(String(teacherId)))&&(!q||text.includes(q))}

function renderStudents(){const q=($('crmSearch')?.value||'').trim().toLowerCase(),teacherId=ensureStudentTeacherFilter()?.value||'',archiveMode=ensureStudentArchiveFilter()?.value||'active';
const rows=db.students.map(studentDefaults).filter(s=>(archiveMode==='all'||(archiveMode==='archived')===isArchivedRecord(s))&&studentMatchesCrmFilters(s,q,teacherId));$('studentRows').innerHTML=rows.map(s=>{const h=studentHistoryStats(s.id),t=teacher(s.preferredTeacherId),archived=isArchivedRecord(s);return`<tr${archived?' class="is-archived"':''}><td><b>${esc(s.name)}</b><div class="crm-badges"><span class="crm-badge">${archived?'已封存':s.status==='active'?'在讀':s.status==='trial'?'試讀':s.status==='paused'?'暫停':'離班'}</span>${s.grade?`<span class="crm-badge">${esc(s.grade)}</span>`:''}</div>${archived?`<div class="small">${esc(s.archivedReason||'未填原因')}｜${esc(s.archivedBy||'Owner')}｜${new Date(s.archivedAt).toLocaleDateString('zh-TW')}</div>`:''}</td><td>${esc(s.parent)}<br><span class="small">${esc(s.contact||s.parentLine||s.parentEmail||'—')}</span></td><td>${esc(s.school||'—')}<br><span class="small">${esc(s.level||'未設定程度')}${t?.name?'｜'+esc(t.name):''}</span></td><td>${esc(s.courseType)}<br><span class="small">${s.billing==='hour'?'每小時':s.billing==='lesson'?'每堂':'月費'} ${money(s.rate)}</span></td><td><b>${h.total}</b> 堂｜請假 ${h.absent}<br><span class="small ${h.unpaid?'status-unpaid':''}">未繳 ${h.unpaid} 堂${h.last?'｜最近 '+h.last.date:''}</span></td><td class="crm-actions"><button type="button" class="btn" onclick="editStudent('${s.id}')">檢視／編輯</button>${archived?'':`<button type="button" class="btn ok" onclick="openSmartScheduler('${s.id}')">排課</button>`}<button type="button" class="btn" onclick="showStudentHistory('${s.id}')">歷程</button>${archived?`<button type="button" class="btn ok" onclick="restoreStudent('${s.id}')">恢復</button>`:`<button type="button" class="btn danger" onclick="archiveStudent('${s.id}')">封存</button>`}</td></tr>`}).join('')||'<tr><td colspan="6" class="small">沒有符合條件的學生。</td></tr>'}

function showStudentHistory(id){const s=studentDefaults(db.students.find(x=>x.id===id)||{}),ls=db.lessons.filter(l=>l.studentId===id).sort((a,b)=>(b.date+b.start).localeCompare(a.date+a.start));
const lines=ls.slice(0,30).map(l=>`${l.date} ${l.start}–${l.end}｜${lessonTeacherNames(l)}｜${l.title||'課程'}｜${l.status}｜${l.paymentStatus==='paid'?'已繳':'未繳'}`).join('\n');alert(`【${s.name||'學生'} CRM 歷程】\n學校／年級：${s.school||'—'} ${s.grade||''}\n程度：${s.level||'—'}\n教材：${s.materials||'—'}\n考試紀錄：${s.scores||'—'}\n\n最近課程（最多30筆）\n${lines||'尚無課程紀錄'}`)}
