/* Teacher leave records: production callable writes, role-scoped live reads. */
(function(){
 'use strict';
 const $=id=>document.getElementById(id),html=value=>String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
 const labels={personal:'事假',sick:'病假',bereavement:'喪假'};let records=[],loadError='';
 const context=()=>window.DanbridgeAccess?.getContext?.()||{},monthNow=()=>new Date().toISOString().slice(0,7),today=()=>{const d=new Date(),offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,10)};
 const roleCanManageAll=()=>context().role==='owner'||(context().role==='teacher'&&context().canManageSchedule===true);
 const recordCanEdit=record=>roleCanManageAll()||(context().role==='teacher'&&String(record.teacherId)===String(context().teacherId));
 const duration=()=>{const start=$('teacherLeaveStart')?.value||'',end=$('teacherLeaveEnd')?.value||'';if(!/^\d\d:\d\d$/.test(start)||!/^\d\d:\d\d$/.test(end))return 0;const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);return eh*60+em-sh*60-sm};
 function renderHours(){const target=$('teacherLeaveHoursPreview'),minutes=duration();if(!target)return;target.classList.toggle('is-invalid',minutes<=0);target.textContent=minutes>0?`共 ${Number((minutes/60).toFixed(2))} 小時`:'結束時間必須晚於開始時間'}
 function teacherOptions(){return(db?.teachers||[]).filter(teacher=>!teacher.archivedAt||records.some(record=>String(record.teacherId)===String(teacher.id)))}
 function syncSelectors(){const own=String(context().teacherId||''),all=roleCanManageAll(),options=teacherOptions(),select=$('teacherLeaveTeacher'),filter=$('teacherLeaveFilterTeacher'),selected=select?.value||own,filtered=filter?.value||'';if(select){select.innerHTML=options.map(teacher=>`<option value="${html(teacher.id)}">${html(teacher.name||teacher.displayName||teacher.id)}</option>`).join('');select.value=all?selected:own;if(!select.value&&options[0])select.value=options[0].id;select.disabled=!all}if(filter){filter.innerHTML=(all?'<option value="">全部老師</option>':'')+options.map(teacher=>`<option value="${html(teacher.id)}">${html(teacher.name||teacher.displayName||teacher.id)}</option>`).join('');filter.value=all?filtered:own;if(!filter.value&&!all)filter.value=own;filter.disabled=!all}}
 function setStatus(message,state=''){const node=$('teacherLeaveFormStatus');if(node){node.textContent=message;node.dataset.state=state}}
 function clearTeacherLeaveForm(){const own=String(context().teacherId||'');if($('teacherLeaveId'))$('teacherLeaveId').value='';if($('teacherLeaveRevision'))$('teacherLeaveRevision').value='0';if($('teacherLeaveType'))$('teacherLeaveType').value='personal';if($('teacherLeaveDate'))$('teacherLeaveDate').value=today();if($('teacherLeaveStart'))$('teacherLeaveStart').value='09:00';if($('teacherLeaveEnd'))$('teacherLeaveEnd').value='10:00';if($('teacherLeaveNote'))$('teacherLeaveNote').value='';syncSelectors();if(!roleCanManageAll()&&$('teacherLeaveTeacher'))$('teacherLeaveTeacher').value=own;if($('teacherLeaveSaveBtn'))$('teacherLeaveSaveBtn').textContent='儲存請假';setStatus('');renderHours()}
 async function saveTeacherLeave(){const button=$('teacherLeaveSaveBtn'),leaveId=$('teacherLeaveId')?.value||'',revision=Number($('teacherLeaveRevision')?.value||0),minutes=duration();if(minutes<=0)return setStatus('結束時間必須晚於開始時間。','error');const teacherId=$('teacherLeaveTeacher')?.value||'';if(!teacherId)return setStatus('請選擇老師。','error');const payload={action:leaveId?'update':'create',leaveId:leaveId||undefined,expectedRevision:revision,input:{teacherId,leaveType:$('teacherLeaveType')?.value||'',date:$('teacherLeaveDate')?.value||'',start:$('teacherLeaveStart')?.value||'',end:$('teacherLeaveEnd')?.value||'',note:$('teacherLeaveNote')?.value||''}};try{button.disabled=true;setStatus('正在由受保護後端驗證並同步…','pending');await window.__danbridgeSaveTeacherLeave(payload);clearTeacherLeaveForm();setStatus('已安全同步，三種角色畫面會即時更新。','ok');window.toast?.(leaveId?'請假紀錄已更新':'請假紀錄已新增')}catch(error){console.error(error);setStatus(error?.message||'請假同步失敗','error')}finally{button.disabled=false}}
 function editTeacherLeave(id){const record=records.find(row=>String(row.id||row.leaveId)===String(id));if(!record||!recordCanEdit(record)||record.status==='cancelled')return;window.switchTab?.('teacherLeave');syncSelectors();$('teacherLeaveId').value=record.leaveId||record.id;$('teacherLeaveRevision').value=record.revision||0;$('teacherLeaveTeacher').value=record.teacherId;$('teacherLeaveType').value=record.leaveType;$('teacherLeaveDate').value=record.date;$('teacherLeaveStart').value=record.start;$('teacherLeaveEnd').value=record.end;$('teacherLeaveNote').value=record.note||'';$('teacherLeaveSaveBtn').textContent='更新請假';renderHours();$('teacherLeaveDate').focus()}
 async function cancelTeacherLeave(id){const record=records.find(row=>String(row.id||row.leaveId)===String(id));if(!record||!recordCanEdit(record)||record.status==='cancelled')return;if(!confirm(`確定取消 ${record.teacherName||'老師'} ${record.date} ${record.start}–${record.end} 的${labels[record.leaveType]||'請假'}？\n\n紀錄不會刪除，會保留為「已取消」供日後稽核。`))return;try{setStatus('正在取消並保留稽核紀錄…','pending');await window.__danbridgeCancelTeacherLeave({leaveId:record.leaveId||record.id,expectedRevision:Number(record.revision)||0});setStatus('已取消；歷史紀錄已保留。','ok');window.toast?.('請假紀錄已取消')}catch(error){console.error(error);setStatus(error?.message||'取消失敗','error')}}
 function renderTeacherLeaves(){if(!$('teacherLeaveRows'))return;syncSelectors();if(!$('teacherLeaveMonth').value)$('teacherLeaveMonth').value=monthNow();const month=$('teacherLeaveMonth').value,teacherId=$('teacherLeaveFilterTeacher').value,status=$('teacherLeaveStatus').value||'active',rows=records.filter(row=>(!month||String(row.date||'').startsWith(month))&&(!teacherId||String(row.teacherId)===String(teacherId))&&(status==='all'||row.status===status)),active=rows.filter(row=>row.status!=='cancelled'),typeHours=type=>active.filter(row=>row.leaveType===type).reduce((sum,row)=>sum+Number(row.hours||0),0),total=active.reduce((sum,row)=>sum+Number(row.hours||0),0);$('teacherLeaveSummary').innerHTML=[['有效紀錄',active.length],['總時數',`${total.toFixed(2)} 小時`],['事假／病假',`${typeHours('personal').toFixed(2)}／${typeHours('sick').toFixed(2)}`],['喪假',`${typeHours('bereavement').toFixed(2)} 小時`]].map(([label,value])=>`<div><span>${label}</span><b>${value}</b></div>`).join('');$('teacherLeaveRows').innerHTML=loadError?`<tr><td colspan="8" class="small">讀取失敗：${html(loadError)}</td></tr>`:(rows.length?rows.map(row=>{const canEdit=recordCanEdit(row)&&row.status!=='cancelled';return`<tr><td><b>${html(row.teacherName||row.teacherId)}</b></td><td>${html(row.date)}</td><td>${html(row.start)}–${html(row.end)}</td><td>${html(labels[row.leaveType]||row.leaveType)}</td><td>${html(row.hours)} 小時</td><td>${html(row.note||'—')}</td><td><span class="teacher-leave-status ${row.status==='cancelled'?'cancelled':''}">${row.status==='cancelled'?'已取消':'有效'}</span><br><span class="small">v${html(row.revision||1)}</span></td><td class="row-actions">${canEdit?`<button class="btn" onclick="editTeacherLeave('${html(row.leaveId||row.id)}')">編輯</button><button class="btn danger" onclick="cancelTeacherLeave('${html(row.leaveId||row.id)}')">取消</button>`:'<span class="small">僅供查閱</span>'}</td></tr>`}).join(''):'<tr><td colspan="8" class="small">這個範圍目前沒有請假紀錄。</td></tr>')}
 function viewTeacherLeaves(teacherId){window.switchTab?.('teacherLeave');setTimeout(()=>{if($('teacherLeaveFilterTeacher'))$('teacherLeaveFilterTeacher').value=String(teacherId||'');renderTeacherLeaves()},0)}
 function teacherLeaveProfileSummary(teacherId){const month=monthNow(),active=records.filter(row=>row.status!=='cancelled'&&String(row.teacherId)===String(teacherId)&&String(row.date||'').startsWith(month)),hours=active.reduce((sum,row)=>sum+Number(row.hours||0),0);return active.length?`本月 ${active.length} 筆／${hours.toFixed(2)} 小時`:'本月無請假'}
 window.__danbridgeSetTeacherLeaves=rows=>{records=Array.isArray(rows)?rows:[];loadError='';renderTeacherLeaves();window.renderTeachers?.()};window.__danbridgeSetTeacherLeaveError=message=>{loadError=message;renderTeacherLeaves()};window.renderTeacherLeaves=renderTeacherLeaves;window.clearTeacherLeaveForm=clearTeacherLeaveForm;window.saveTeacherLeave=saveTeacherLeave;window.editTeacherLeave=editTeacherLeave;window.cancelTeacherLeave=cancelTeacherLeave;window.viewTeacherLeaves=viewTeacherLeaves;window.teacherLeaveProfileSummary=teacherLeaveProfileSummary;
 document.addEventListener('input',event=>{if(['teacherLeaveStart','teacherLeaveEnd'].includes(event.target?.id))renderHours()});document.addEventListener('DOMContentLoaded',clearTeacherLeaveForm);
})();
