/* Teacher leave center: statutory balances, Owner approval and schedule impact. */
(function(){
 'use strict';
 const $=id=>document.getElementById(id),html=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
 const entitlement=window.DanbridgeTeacherLeaveEntitlement||{},rules=entitlement.STATUTORY_LEAVE_RULES||{};
 const labels=Object.fromEntries(Object.entries(rules).map(([key,value])=>[key,value.label]));
 const statusLabels={pending:'待審核',approved:'已核准',active:'已核准',rejected:'已駁回',cancelled:'已取消'};
 let records=[],loadError='';
 const context=()=>window.DanbridgeAccess?.getContext?.()||{},isOwner=()=>context().role==='owner',monthNow=()=>localToday().slice(0,7);
 function localToday(){const d=new Date(),offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,10)}
 const roleCanManageAll=()=>isOwner()||(context().role==='teacher'&&context().canManageSchedule===true);
 const isApproved=record=>entitlement.isApproved?.(record)??['approved','active'].includes(record?.status);
 const teacherById=id=>(db?.teachers||[]).find(row=>String(row.id)===String(id));
 const recordCanEdit=record=>!isApproved(record)&&record.status!=='cancelled'&&(roleCanManageAll()||(context().role==='teacher'&&String(record.teacherId)===String(context().teacherId)));
 const recordCanCancel=record=>record.status!=='cancelled'&&(isOwner()||(!isApproved(record)&&recordCanEdit(record)));
 function duration(){const start=$('teacherLeaveStart')?.value||'',end=$('teacherLeaveEnd')?.value||'';if(!/^\d\d:\d\d$/.test(start)||!/^\d\d:\d\d$/.test(end))return 0;const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);return eh*60+em-sh*60-sm}
 function selectedDraft(){return{teacherId:$('teacherLeaveTeacher')?.value||'',leaveType:$('teacherLeaveType')?.value||'',date:$('teacherLeaveDate')?.value||'',start:$('teacherLeaveStart')?.value||'',end:$('teacherLeaveEnd')?.value||'',note:$('teacherLeaveNote')?.value||'',bereavementRelationship:$('teacherLeaveBereavementRelationship')?.value||''}}
 function impacts(record){return entitlement.impactedLessonsForLeave?.(record,db)||[]}
 function number(value){const n=Number(value)||0;return Number.isInteger(n)?String(n):n.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')}
 function setStatus(message,state=''){const node=$('teacherLeaveFormStatus');if(node){node.textContent=message;node.dataset.state=state}}
 function teacherOptions(){return(db?.teachers||[]).filter(teacher=>!teacher.archivedAt||records.some(record=>String(record.teacherId)===String(teacher.id)))}
 function optionsMarkup(options){return options.map(teacher=>`<option value="${html(teacher.id)}">${html(teacher.name||teacher.displayName||teacher.id)}</option>`).join('')}
 function syncSelectors(){
  const own=String(context().teacherId||''),all=roleCanManageAll(),options=teacherOptions(),form=$('teacherLeaveTeacher'),filter=$('teacherLeaveFilterTeacher'),balance=$('teacherLeaveBalanceTeacher'),formValue=form?.value||own,filterValue=filter?.value||'',balanceValue=balance?.value||formValue||own;
  if(form){form.innerHTML=optionsMarkup(options);form.value=all?formValue:own;if(!form.value&&options[0])form.value=options[0].id;form.disabled=!all}
  if(filter){filter.innerHTML=(all?'<option value="">全部老師</option>':'')+optionsMarkup(options);filter.value=all?filterValue:own;if(!filter.value&&!all)filter.value=own;filter.disabled=!all}
  if(balance){balance.innerHTML=optionsMarkup(options);balance.value=all?balanceValue:own;if(!balance.value&&options[0])balance.value=options[0].id;balance.disabled=!all}
 }
 function renderTeacherLeavePreview(){
  const minutes=duration(),draft=selectedDraft(),teacher=teacherById(draft.teacherId),days=minutes>0?minutes/60/(entitlement.teacherDailyHours?.(teacher)||8):0,hoursNode=$('teacherLeaveHoursPreview');
  if(hoursNode){hoursNode.classList.toggle('is-invalid',minutes<=0);hoursNode.textContent=minutes>0?`共 ${number(minutes/60)} 小時／${number(days)} 天`:'結束時間必須晚於開始時間'}
  const bereavement=$('teacherLeaveBereavementWrap');if(bereavement)bereavement.hidden=draft.leaveType!=='bereavement';
  const rule=rules[draft.leaveType]||{},quota=entitlement.quotaDays?.(draft.leaveType,{teacher,record:draft,asOfDate:draft.date}),ruleNode=$('teacherLeaveRulePreview');
  if(ruleNode)ruleNode.innerHTML=`<b>${html(rule.label||'請假')}</b><span>${quota===null?'依實際需要':`法定額度 ${number(quota)} 天`}｜${html(rule.period||'')}｜${html(rule.paid||'')}</span>`;
  const affected=impacts(draft),impactNode=$('teacherLeaveImpactPreview');
  if(impactNode)impactNode.innerHTML=affected.length?`<b>當天受影響 ${affected.length} 堂／${number(affected.reduce((sum,row)=>sum+row.overlapHours,0))} 小時</b>${affected.map(row=>`<span>${html(row.start)}–${html(row.end)}　${html(row.studentNames.join('、'))}</span>`).join('')}`:'<b>當天沒有重疊課程</b><span>核准後仍會保留這次請假紀錄。</span>';
 }
 function clearTeacherLeaveForm(){
  const own=String(context().teacherId||'');if($('teacherLeaveId'))$('teacherLeaveId').value='';if($('teacherLeaveRevision'))$('teacherLeaveRevision').value='0';if($('teacherLeaveType'))$('teacherLeaveType').value='annual';if($('teacherLeaveDate'))$('teacherLeaveDate').value=localToday();if($('teacherLeaveStart'))$('teacherLeaveStart').value='09:00';if($('teacherLeaveEnd'))$('teacherLeaveEnd').value='17:00';if($('teacherLeaveNote'))$('teacherLeaveNote').value='';if($('teacherLeaveBereavementRelationship'))$('teacherLeaveBereavementRelationship').value='close8';syncSelectors();if(!roleCanManageAll()&&$('teacherLeaveTeacher'))$('teacherLeaveTeacher').value=own;if($('teacherLeaveSaveBtn'))$('teacherLeaveSaveBtn').textContent='送出申請';if($('teacherLeaveApproveImmediately'))$('teacherLeaveApproveImmediately').checked=isOwner();if($('teacherLeaveOwnerApproveWrap'))$('teacherLeaveOwnerApproveWrap').hidden=!isOwner();setStatus('');renderTeacherLeavePreview()
 }
 async function operate(payload,success){try{setStatus('正在由受保護後端驗證並同步…','pending');await window.__danbridgeSaveTeacherLeave(payload);setStatus(success,'ok');window.toast?.(success)}catch(error){console.error(error);setStatus(error?.message||'請假同步失敗','error');throw error}}
 async function saveTeacherLeave(){
  const button=$('teacherLeaveSaveBtn'),leaveId=$('teacherLeaveId')?.value||'',minutes=duration(),input=selectedDraft();if(minutes<=0)return setStatus('結束時間必須晚於開始時間。','error');if(!input.teacherId)return setStatus('請選擇老師。','error');
  const payload={action:leaveId?'update':'create',leaveId:leaveId||undefined,expectedRevision:Number($('teacherLeaveRevision')?.value||0),approveImmediately:isOwner()&&$('teacherLeaveApproveImmediately')?.checked===true,input};
  try{button.disabled=true;await operate(payload,payload.approveImmediately?'已登記並核准請假。':'請假申請已送出，等待 Owner 核准。');clearTeacherLeaveForm()}catch{}finally{button.disabled=false}
 }
 function editTeacherLeave(id){const record=records.find(row=>String(row.id||row.leaveId)===String(id));if(!record||!recordCanEdit(record))return;window.switchTab?.('teacherLeave');syncSelectors();$('teacherLeaveId').value=record.leaveId||record.id;$('teacherLeaveRevision').value=record.revision||0;$('teacherLeaveTeacher').value=record.teacherId;$('teacherLeaveType').value=record.leaveType;$('teacherLeaveDate').value=record.date;$('teacherLeaveStart').value=record.start;$('teacherLeaveEnd').value=record.end;$('teacherLeaveNote').value=record.note||'';if($('teacherLeaveBereavementRelationship'))$('teacherLeaveBereavementRelationship').value=record.bereavementRelationship||'close8';$('teacherLeaveSaveBtn').textContent='更新申請';renderTeacherLeavePreview();$('teacherLeaveDate').focus()}
 async function decideTeacherLeave(id,action){const record=records.find(row=>String(row.id||row.leaveId)===String(id));if(!record||record.status!=='pending'||!isOwner())return;let decisionNote='';if(action==='reject'){decisionNote=prompt(`駁回 ${record.teacherName||'老師'} ${record.date} 的理由：`,'資料需要補充')??'';if(!decisionNote.trim())return}try{await operate({action,leaveId:record.leaveId||record.id,expectedRevision:Number(record.revision)||0,decisionNote},action==='approve'?'請假已核准並扣除額度。':'請假已駁回。')}catch{}}
 async function cancelTeacherLeave(id){const record=records.find(row=>String(row.id||row.leaveId)===String(id));if(!record||!recordCanCancel(record))return;if(!confirm(`確定取消 ${record.teacherName||'老師'} ${record.date} ${record.start}–${record.end} 的${labels[record.leaveType]||'請假'}？\n\n紀錄不會刪除，會保留供稽核。`))return;try{await operate({action:'cancel',leaveId:record.leaveId||record.id,expectedRevision:Number(record.revision)||0},'請假已取消，歷史紀錄已保留。')}catch{}}
 function renderQuota(){
  const grid=$('teacherLeaveQuotaGrid');if(!grid)return;const year=Number($('teacherLeaveYear')?.value)||new Date().getFullYear(),teacher=teacherById($('teacherLeaveBalanceTeacher')?.value);if(!teacher){grid.innerHTML='<div class="small">請先選擇老師。</div>';return}
  const types=['annual','personal','sick','hospitalSick','marriage','familyCare','menstrual','bereavement','occupational','official'];
  grid.innerHTML=types.map(type=>{const balance=entitlement.leaveBalance?.({records,teacher,type,year,asOfDate:`${year}-12-31`})||{},rule=rules[type]||{},value=type==='bereavement'?'8／6／3':balance.total===null?'依實際需要':`${number(balance.remaining)}/${number(balance.total)}`,used=type==='bereavement'?'依親屬關係逐次計算':`已核准使用 ${number(balance.used)} 天`;return`<article class="teacher-leave-quota"><span>${html(rule.label||type)}</span><strong>${html(value)}</strong><small>${html(used)}｜${html(rule.paid||'')}</small></article>`}).join('');
  const notice=$('teacherLeaveEmploymentNotice');if(notice)notice.textContent=teacher.employmentStartDate?`到職日 ${teacher.employmentStartDate}；特休依年資自動計算。標準每日工時 ${entitlement.teacherDailyHours?.(teacher)||8} 小時。`:'尚未設定到職日，因此特休顯示 0 天；請先到老師資料補上到職日。';
 }
 function impactMarkup(record){const affected=impacts(record);return affected.length?`<b>${affected.length} 堂／${number(affected.reduce((sum,row)=>sum+row.overlapHours,0))} 小時</b><br><span class="small">${html([...new Set(affected.flatMap(row=>row.studentNames))].join('、'))}</span>`:'<span class="small">沒有重疊課程</span>'}
 function renderPending(){const node=$('teacherLeavePendingQueue');if(!node)return;const pending=records.filter(row=>row.status==='pending').sort((a,b)=>String(a.date).localeCompare(String(b.date)));node.innerHTML=pending.length?pending.map(row=>`<article class="teacher-leave-pending-item"><div><b>${html(row.teacherName||row.teacherId)}</b><span>${html(row.date)}　${html(row.start)}–${html(row.end)}　${html(labels[row.leaveType]||row.leaveType)}</span><small>${impactMarkup(row)}</small></div>${isOwner()?`<div class="row-actions"><button class="btn ok" onclick="approveTeacherLeave('${html(row.leaveId||row.id)}')">核准</button><button class="btn danger" onclick="rejectTeacherLeave('${html(row.leaveId||row.id)}')">駁回</button></div>`:'<span class="teacher-leave-status pending">等待 Owner</span>'}</article>`).join(''):'<div class="teacher-leave-empty">目前沒有待審核申請</div>'}
 function renderDashboard(){const stats=entitlement.leaveDashboardStats?.({records,db,today:localToday()})||{pending:0,today:0,affectedLessons:0};if($('teacherLeaveDashboardPending'))$('teacherLeaveDashboardPending').textContent=stats.pending;if($('teacherLeaveDashboardToday'))$('teacherLeaveDashboardToday').textContent=stats.today;if($('teacherLeaveDashboardText'))$('teacherLeaveDashboardText').textContent=stats.pending?`${stats.pending} 筆等待核准；今日 ${stats.today} 位老師請假`:`沒有待審；今日 ${stats.today} 位老師請假、影響 ${stats.affectedLessons} 堂`}
 function renderTeacherLeaves(){
  if(!$('teacherLeaveRows'))return;syncSelectors();if(!$('teacherLeaveMonth').value)$('teacherLeaveMonth').value=monthNow();if(!$('teacherLeaveYear').value)$('teacherLeaveYear').value=new Date().getFullYear();const month=$('teacherLeaveMonth').value,teacherId=$('teacherLeaveFilterTeacher').value,status=$('teacherLeaveStatus').value||'all',rows=records.filter(row=>(!month||String(row.date||'').startsWith(month))&&(!teacherId||String(row.teacherId)===String(teacherId))&&(status==='all'||(status==='approved'?isApproved(row):row.status===status))).sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(a.start).localeCompare(String(b.start))),approved=rows.filter(isApproved),pending=rows.filter(row=>row.status==='pending'),hours=approved.reduce((sum,row)=>sum+Number(row.hours||0),0),affected=approved.flatMap(impacts);
  $('teacherLeaveSummary').innerHTML=[['已核准',approved.length],['待審核',pending.length],['核准時數',`${number(hours)} 小時`],['影響課程',`${affected.length} 堂`]].map(([label,value])=>`<div><span>${label}</span><b>${value}</b></div>`).join('');
  $('teacherLeaveRows').innerHTML=loadError?`<tr><td colspan="6" class="small">讀取失敗：${html(loadError)}</td></tr>`:(rows.length?rows.map(row=>{const canEdit=recordCanEdit(row),canCancel=recordCanCancel(row),statusKey=isApproved(row)?'approved':row.status;return`<tr><td><b>${html(row.teacherName||row.teacherId)}</b><br>${html(row.date)}<br><span class="small">${html(row.start)}–${html(row.end)}</span></td><td>${html(labels[row.leaveType]||row.leaveType)}<br><b>${html(number(row.hours))} 小時／${html(number(entitlement.recordDays?.(row,teacherById(row.teacherId))||row.days||0))} 天</b></td><td>${impactMarkup(row)}</td><td>${html(row.note||'—')}${row.decisionNote?`<br><span class="small">決定：${html(row.decisionNote)}</span>`:''}</td><td><span class="teacher-leave-status ${html(statusKey)}">${html(statusLabels[row.status]||row.status)}</span><br><span class="small">v${html(row.revision||1)}</span></td><td class="row-actions">${canEdit?`<button class="btn" onclick="editTeacherLeave('${html(row.leaveId||row.id)}')">編輯</button>`:''}${row.status==='pending'&&isOwner()?`<button class="btn ok" onclick="approveTeacherLeave('${html(row.leaveId||row.id)}')">核准</button><button class="btn danger" onclick="rejectTeacherLeave('${html(row.leaveId||row.id)}')">駁回</button>`:''}${canCancel?`<button class="btn danger" onclick="cancelTeacherLeave('${html(row.leaveId||row.id)}')">取消</button>`:''}${!canEdit&&!canCancel&&!(row.status==='pending'&&isOwner())?'<span class="small">僅供查閱</span>':''}</td></tr>`}).join(''):'<tr><td colspan="6" class="small">這個範圍目前沒有請假紀錄。</td></tr>');renderQuota();renderPending();renderDashboard();renderTeacherLeavePreview()
 }
 function viewTeacherLeaves(teacherId){window.switchTab?.('teacherLeave');setTimeout(()=>{if($('teacherLeaveFilterTeacher'))$('teacherLeaveFilterTeacher').value=String(teacherId||'');if($('teacherLeaveBalanceTeacher'))$('teacherLeaveBalanceTeacher').value=String(teacherId||'');renderTeacherLeaves()},0)}
 function teacherLeaveProfileSummary(teacherId){const month=monthNow(),approved=records.filter(row=>isApproved(row)&&String(row.teacherId)===String(teacherId)&&String(row.date||'').startsWith(month)),hours=approved.reduce((sum,row)=>sum+Number(row.hours||0),0),pending=records.filter(row=>row.status==='pending'&&String(row.teacherId)===String(teacherId)).length;return approved.length||pending?`本月核准 ${approved.length} 筆／${number(hours)} 小時${pending?`；待審 ${pending} 筆`:''}`:'本月無請假'}
 window.__danbridgeGetTeacherLeaves=()=>records.map(row=>({...row}));window.__danbridgeSetTeacherLeaves=rows=>{records=Array.isArray(rows)?rows:[];loadError='';renderTeacherLeaves();window.renderTeachers?.();window.renderFinance?.();window.renderSettlement?.()};window.__danbridgeSetTeacherLeaveError=message=>{loadError=message;renderTeacherLeaves()};window.renderTeacherLeaves=renderTeacherLeaves;window.renderTeacherLeavePreview=renderTeacherLeavePreview;window.renderTeacherLeaveDashboard=renderDashboard;window.clearTeacherLeaveForm=clearTeacherLeaveForm;window.saveTeacherLeave=saveTeacherLeave;window.editTeacherLeave=editTeacherLeave;window.approveTeacherLeave=id=>decideTeacherLeave(id,'approve');window.rejectTeacherLeave=id=>decideTeacherLeave(id,'reject');window.cancelTeacherLeave=cancelTeacherLeave;window.viewTeacherLeaves=viewTeacherLeaves;window.teacherLeaveProfileSummary=teacherLeaveProfileSummary;
 document.addEventListener('input',event=>{if(['teacherLeaveStart','teacherLeaveEnd'].includes(event.target?.id))renderTeacherLeavePreview()});document.addEventListener('DOMContentLoaded',clearTeacherLeaveForm);
})();
