import {build} from 'esbuild';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve,dirname} from 'node:path';

const root=fileURLToPath(new URL('../',import.meta.url));
const output=resolve(root,'js/generated/record-plan.worker.js');
// Bundle only the pure planner. No Firebase/Auth/storage capability is added.
// Reproducible bytes are checked before tests/deploy; sources remain editable.
export async function buildRecordPlanWorker({check=false}={}){
 const result=await build({absWorkingDir:root,entryPoints:['js/core/cloud-record-plan.worker.js'],outfile:output,bundle:true,platform:'browser',format:'esm',target:['safari16','chrome110'],write:false,metafile:true,minify:false,legalComments:'inline',banner:{js:'// Generated by tools/build_record_plan_worker.mjs; do not edit.'}});
 if(result.outputFiles.length!==1||Object.values(result.metafile.outputs).some(row=>row.imports.length))throw Error('Planner must be exactly one self-contained script');
 if(Object.keys(result.metafile.inputs).some(path=>!path.startsWith('js/core/')||/firebase|auth-and|browser-operation|operation-journal/.test(path)))throw Error('Planner bundle contains a non-pure dependency');
 const bytes=result.outputFiles[0].contents;
 if(check){if(!Buffer.from(bytes).equals(await readFile(output)))throw Error('Record planner bundle is stale; run npm run build:record-plan')}
 else{await mkdir(dirname(output),{recursive:true});await writeFile(output,bytes)}
 return{bytes:bytes.length,modules:Object.keys(result.metafile.inputs).length};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(JSON.stringify(await buildRecordPlanWorker({check:process.argv.includes('--check')})));
